 
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_ACTIVITY_INSTANCE_ID_USERS' AND object_id = OBJECT_ID('[SGW_BPM_ACTIVITY_INST_USERS]'))
 BEGIN
    CREATE NONCLUSTERED INDEX IX_ACTIVITY_INSTANCE_ID_USERS
    ON [dbo].[SGW_BPM_ACTIVITY_INST_USERS] ([ACTIVITY_INSTANCE_ID])
    INCLUDE ([USER_SERIAL_ID])
 END
ELSE
  BEGIN
  PRINT 'IX_ACTIVITY_INSTANCE_ID_USERS IS already EXISTS'
END 
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_PROCESS_INSTANCE_ACTIVITY_ID_INSTANCE' AND object_id = OBJECT_ID('[[SGW_BPM_ACTIVITY_INSTANCE]]'))
 BEGIN
  CREATE NONCLUSTERED INDEX IX_PROCESS_INSTANCE_ACTIVITY_ID_INSTANCE
  ON [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([PROCESS_INSTANCE_ID],[ACTIVITY_ID])
  INCLUDE ([CHECKED_OUT_USER],[REFERENCE_ID],[STATUS_ID],[STATUS_VALUE],[SUSPENSION_START_DATE],[SUSPENSION_MINUTES],[SUSPENSION_END_DATE],[RETURN_FROM_AUDIT_IND],[RESUME_ACTION_ID],[RESUME_ACTION_VALUE],[SUSPENSION_REASON_ID],[SUSPENSION_REASON_VALUE],[COMMENTS],[DUE_DATE],[START_DATE],[END_DATE],[INITIATOR_INSTANCE_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ],[CHECKED_OUT_DATE],[ASSIGNED_BY],[SLA_MINUTES],[SLA_HOURS],[SLA_DAYS],[ACTION_CONTROL],[REJECTION_REASON_ID],[REJECTION_REASON_VALUE],[LAUNCH_DATE])
 END
ELSE
 BEGIN
 PRINT 'IX_PROCESS_INSTANCE_ACTIVITY_ID_INSTANCE IS already EXISTS'
 END 
GO


