
CREATE TABLE SGW_BPM_CASE_CONFIG_TRACING(
	[CASE_CONFIG_TRACING_ID] [int] IDENTITY(1,1) NOT NULL,
	[CASE_FILE] VARCHAR(4000) NULL,
	[BPM_TRACING_FLAG] VARCHAR(1) NOT NULL,	
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT]  NULL,
 CONSTRAINT [PK_SGW_BPM_CASE_CONFIG_TRACING] PRIMARY KEY CLUSTERED 
(
	[CASE_CONFIG_TRACING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

