--------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Created By	:	Siddharth Sabadra
--Created On	:	26th April 2021
--Description	:	Changing the column ID of SGW_BPM_ACTIVITY_INST_USERS to bigint and setting to Identity using temporary table SGW_BPM_ACTIVITY_INST_USERS_TEMP 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGW_BPM_ACTIVITY_INST_USERS_TEMP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_INSTANCE_ID] [int] NOT NULL,
	[USER_SERIAL_ID] [int] NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGW_BPM_ACTIVITY_INST_USERS_TEMP]  WITH NOCHECK ADD  CONSTRAINT [FK_SGW_BPM_ACTIVITY_INST_USERS_SGW_BPM_ACTIVITY_INSTANCE] FOREIGN KEY([ACTIVITY_INSTANCE_ID])
REFERENCES [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID])
GO

ALTER TABLE [dbo].[SGW_BPM_ACTIVITY_INST_USERS_TEMP] CHECK CONSTRAINT [FK_SGW_BPM_ACTIVITY_INST_USERS_SGW_BPM_ACTIVITY_INSTANCE]
GO

SET IDENTITY_INSERT SGW_BPM_ACTIVITY_INST_USERS_TEMP ON

INSERT INTO SGW_BPM_ACTIVITY_INST_USERS_TEMP(ID,ACTIVITY_INSTANCE_ID,USER_SERIAL_ID,USER_ID)
SELECT ID,ACTIVITY_INSTANCE_ID,USER_SERIAL_ID,USER_ID FROM SGW_BPM_ACTIVITY_INST_USERS
GO

SET IDENTITY_INSERT SGW_BPM_ACTIVITY_INST_USERS_TEMP OFF

DROP TABLE SGW_BPM_ACTIVITY_INST_USERS

EXEC sp_rename 'SGW_BPM_ACTIVITY_INST_USERS_TEMP', 'SGW_BPM_ACTIVITY_INST_USERS'
