IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.COLUMNS
  WHERE
    TABLE_NAME = 'SGS_ACT_LOG_APP' AND COLUMN_NAME = 'BLOCK_IP')
BEGIN
  ALTER TABLE SGS_ACT_LOG_APP
    ADD BLOCK_IP varchar(2000) NULL
END;
