CREATE TABLE [dbo].[SGW_BPM_ACTV_CHKL_GROUP](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_ID] [int] NOT NULL,
	[GROUP_NAME] [varchar](max) NOT NULL,
	[MIN_REQ_FIELDS] [int] NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


