IF NOT EXISTS (select 1 from SGW_BPM_PROCESS where NAME = 'GlobalProcess')
BEGIN
SET IDENTITY_INSERT SGW_BPM_PROCESS ON;
INSERT INTO SGW_BPM_PROCESS(PROCESS_ID,BPM_PROCESS_ID,CASE_ID,NAME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ
,PRIORITY,TYPE_ID,TYPE_VALUE,STATUS_ID,STATUS_VALUE)
VALUES(0,'',0,'GlobalProcess','System',getdate(),'System',GETDATE(),0,'',2003,'NONE','','');
SET IDENTITY_INSERT SGW_BPM_PROCESS OFF;
END
ELSE IF EXISTS (select 1 from SGW_BPM_PROCESS where NAME = 'GlobalProcess')
BEGIN
UPDATE SGW_BPM_PROCESS SET TYPE_ID = 2003, TYPE_VALUE = 'NONE' WHERE NAME = 'GlobalProcess'
END
