IF NOT EXISTS(SELECT 1 FROM SGS_CODE WITH(NOLOCK) WHERE CODE_ID = 2031)
BEGIN
INSERT INTO DBO.SGS_CODE (CODE_ID, DESCRIPTION, DATA1_CAPTION, DATA1_TYPE, DATA2_CAPTION, DATA2_TYPE, DATA3_CAPTION, DATA3_TYPE, FIRST_LOOKUP_ITEM, FIRST_MAINTENANCE_ITEM, COMMENTS, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031, 'Activity Type', NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO