CREATE TABLE [dbo].[SGW_BPM_CASE_PARAMETER] (
    [CASE_PARAMETER_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [CASE_ID]             INT          NULL,
    [PARAMETER_NAME]      VARCHAR (50) NOT NULL,
    [PARAMETER_DATA_TYPE] VARCHAR (50) NULL,
    [CREATED_BY]          VARCHAR (50) NOT NULL,
    [CREATED_DATE]        DATETIME     NOT NULL,
    [MODIFIED_BY]         VARCHAR (50) NOT NULL,
    [MODIFIED_DATE]       DATETIME     NOT NULL,
    [UPDATE_SEQ]          INT          NULL,
    CONSTRAINT [PK_SGW_BPM_CASE_PARAMETER_CASE_PARAMETER_ID] PRIMARY KEY CLUSTERED ([CASE_PARAMETER_ID] ASC)
);

