-- ================================================
-- Template generated from Template Explorer using:
-- Create Trigger (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- See additional Create Trigger templates for more
-- examples of different Trigger statements.
--
-- This block of comments will not be included in
-- the definition of the function.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE TRIGGER InsertIntoBpmRequest 
   ON  SGW_WORKFLOW_REQUEST 
   INSTEAD OF INSERT
AS 
DECLARE
@ORG_ID INT,
@ORG_CODE VARCHAR(50),
@FILENET_DOCUMENT_TYPE VARCHAR(50),
@IMAGE_DOC_CATEGORY VARCHAR(50),
@ADDITIONAL_INFO VARCHAR(MAX),
@CONTACT_TICKET_ID INT,
@REQUEST_ID INT,
@CREATED_BY VARCHAR(100),
@CREATED_DATE DATETIME,
@MODIFIED_BY  VARCHAR(100),
@MODIFIED_DATE DATETIME,
@UPDATE_SEQ INT,
@ADDITIONAL_PARAMETER1 varchar(50)
BEGIN
	set @ORG_ID = NULL;
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SELECT 
	@ORG_CODE = ORG_CODE, 
	@FILENET_DOCUMENT_TYPE= FILENET_DOCUMENT_TYPE,
	@IMAGE_DOC_CATEGORY = IMAGE_DOC_CATEGORY,
	@CONTACT_TICKET_ID = CONTACT_TICKET_ID,
	@CREATED_DATE = CREATED_DATE,
	@MODIFIED_BY = MODIFIED_BY,
	@MODIFIED_DATE = MODIFIED_DATE,
	@UPDATE_SEQ = UPDATE_SEQ,
	@ADDITIONAL_PARAMETER1 = ADDITIONAL_PARAMETER1
	 FROM inserted;
	IF (@ORG_CODE is not null)
	BEGIN
		SELECT @ORG_ID = ORG_ID FROM sgt_organization WHERE ORG_CODE = @ORG_CODE;
	END
	SET @ADDITIONAL_INFO = '{"FILENET_DOCUMENT_TYPE":"' + ISNULL(@FILENET_DOCUMENT_TYPE,'') + '","IMAGE_DOC_CATEGORY":"' + ISNULL(@IMAGE_DOC_CATEGORY,'') + '"}';
    INSERT INTO SGW_BPM_REQUEST(DOC_TYPE,PROCESS_ID,REFERENCE_ID,PERSON_ID,ORG_ID,STATUS_ID,STATUS_VALUE,SOURCE_ID,SOURCE_VALUE,ADDITIONAL_INFO,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	SELECT DOCUMENT_CODE,0,REFERENCE_ID,PERSON_ID,@ORG_ID,7026,STATUS_VALUE,2021,'INDX',@ADDITIONAL_INFO,@CREATED_BY,@CREATED_DATE,@MODIFIED_BY,@MODIFIED_DATE,@UPDATE_SEQ FROM INSERTED
	SET @REQUEST_ID = SCOPE_IDENTITY();
	if (@CONTACT_TICKET_ID IS NOT NULL)
	BEGIN
		INSERT INTO SGW_BPM_REQUEST_PARAMETER(REQUEST_ID,PARAMETER_NAME,PARAMETER_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
		VALUES(@REQUEST_ID,'contact_ticket_id',CAST(@CONTACT_TICKET_ID AS varchar),@CREATED_BY,@CREATED_DATE,@MODIFIED_BY,@MODIFIED_DATE,@UPDATE_SEQ);
	END
	if (@ADDITIONAL_PARAMETER1 IS NOT NULL)
	BEGIN
		INSERT INTO SGW_BPM_REQUEST_PARAMETER(REQUEST_ID,PARAMETER_NAME,PARAMETER_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
		VALUES(@REQUEST_ID,'additional_parameter1',@ADDITIONAL_PARAMETER1,@CREATED_BY,@CREATED_DATE,@MODIFIED_BY,@MODIFIED_DATE,@UPDATE_SEQ);
	END
END
GO
