IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'MIGRATION_STATUS_VALUE'  AND OBJECT_ID = OBJECT_ID(N'SGW_PROCESS_INSTANCE'))
BEGIN
ALTER TABLE [dbo].[SGW_PROCESS_INSTANCE]
ADD MIGRATION_STATUS_VALUE VARCHAR(4);
PRINT 'COLUMN NAME: MIGRATION_STATUS_VALUE ALTERED SUCCESSFULLY'
END
ELSE
BEGIN
  PRINT 'COLUMN NAME: MIGRATION_STATUS_VALUE ALREADY EXISTS IN THE TABLE SGW_PROCESS_INSTANCE'
END
GO


IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IX_SGW_PROCESS_INSTANCE_MIGRATION_STATUS_VALUE' AND object_id = OBJECT_ID('SGW_PROCESS_INSTANCE'))
BEGIN
CREATE NONCLUSTERED INDEX IX_SGW_PROCESS_INSTANCE_MIGRATION_STATUS_VALUE
ON SGW_PROCESS_INSTANCE (MIGRATION_STATUS_VALUE);
Print('Non Clustred index IX_SGW_PROCESS_INSTANCE_MIGRATION_STATUS_VALUE added sucessfully on SGW_PROCESS_INSTANCE')
END
ELSE
BEGIN
Print('IX_SGW_PROCESS_INSTANCE_MIGRATION_STATUS_VALUE Already Exists')
END
Go
