CREATE TABLE [dbo].[SGW_BPM_ESCALATION_MESSAGE] (
    [ESCALATION_MESSAGE_ID]  INT           IDENTITY (1, 1) NOT NULL,
    [ESCALATION_INSTANCE_ID] INT           NOT NULL,
    [ESCALATION_TYPE_ID]     INT           NOT NULL,
    [ESCALATION_TYPE_VALUE]  VARCHAR (4)   NOT NULL,
    [ESCALATION_MESSAGE]     VARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_SGW_BPM_ESCALATION_MESSAGE] PRIMARY KEY CLUSTERED ([ESCALATION_MESSAGE_ID] ASC)
);

