CREATE TABLE [dbo].[SGW_BPM_ESCALATION_RECIPIENT] (
    [ESCALATION_RECIPIENT_ID]         INT         IDENTITY (1, 1) NOT NULL,
    [ESCALATION_ID]                   INT         NOT NULL,
    [ESCALTION_RECPNT_TYPE_ID]    INT         NOT NULL,
    [ESCALTION_RECPNT_TYPE_VALUE] VARCHAR (4) NOT NULL,
    [CREATED_BY]          VARCHAR (50)  NOT NULL DEFAULT 'BPM Service',
    [CREATED_DATE]        DATETIME      NOT NULL DEFAULT GetDate(),
    [MODIFIED_BY]         VARCHAR (50)  NOT NULL DEFAULT 'BPM Service',
    [MODIFIED_DATE]       DATETIME      NOT NULL DEFAULT GetDate(),
    [UPDATE_SEQ]          INT           NULL DEFAULT 0,
    CONSTRAINT [PK_SGW_BPM_ESCALATION_RECIPIENT_ESCALATION_RECIPIENT_ID] PRIMARY KEY CLUSTERED ([ESCALATION_RECIPIENT_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_ESCALATION_RECIPIENT_ESCALATION_RECIPIENT_ID_SGW_BPM_ESCALATION_ESCALATION_ID] FOREIGN KEY ([ESCALATION_ID]) REFERENCES [dbo].[SGW_BPM_ESCALATION] ([ESCALATION_ID]) ON DELETE CASCADE
);


