CREATE TABLE [dbo].[SGW_BPM_PROCESS_EVENT_XR] (
    [BPM_PROCESS_EVENT_XR_ID] INT          IDENTITY (1, 1) NOT NULL,
    [EVENT_ID]                INT          NOT NULL,
    [PROCESS_ID]              INT          NOT NULL,
    [ACTION_ID]               INT          NOT NULL,
    [ACTION_VALUE]            VARCHAR (4)  NULL,
    [CREATED_BY]              VARCHAR (50) NOT NULL,
    [CREATED_DATE]            DATETIME     NOT NULL,
    [MODIFIED_BY]             VARCHAR (50) NOT NULL,
    [MODIFIED_DATE]           DATETIME     NOT NULL,
    [UPDATE_SEQ]              INT          NULL,
    [EVENT_REASON_ID]         INT          NULL,
    [ACTIVITY_ID]             INT          DEFAULT (NULL) NULL,
    CONSTRAINT [PK_SGW_BPM_PROCESS_EVENT_XR_PROCESS_EVENT_XR_ID] PRIMARY KEY CLUSTERED ([BPM_PROCESS_EVENT_XR_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_PROCESS_EVENT_XR_ACTIVITY_ID_SGW_BPM_ACTIVIY_ACTIVITY_ID] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[SGW_BPM_ACTIVITY] ([ACTIVITY_ID]),
    CONSTRAINT [FK_SGW_BPM_PROCESS_EVENT_XR_EVENT_ID_SGW_BPM_EVENT_EVENT_ID] FOREIGN KEY ([EVENT_ID]) REFERENCES [dbo].[SGW_BPM_EVENT] ([BPM_EVENT_ID]),
    CONSTRAINT [FK_SGW_BPM_PROCESS_EVENT_XR_PROCESS_ID_SGW_BPM_PROCESS_PROCESS_ID] FOREIGN KEY ([PROCESS_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS] ([PROCESS_ID])
);

