CREATE TABLE [dbo].[SGW_BPM_PROCESS_INSTANCE] (
    [PROCESS_INSTANCE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [CASE_INSTANCE_ID]    INT          NOT NULL,
    [PROCESS_ID]          INT          NOT NULL,
    [END_DATE]            DATETIME     NULL,
    [STATUS_ID]           INT          NOT NULL,
    [STATUS_VALUE]        VARCHAR (4)  NULL,
    [CREATED_BY]          VARCHAR (50) NOT NULL,
    [CREATED_DATE]        DATETIME     NOT NULL,
    [MODIFIED_BY]         VARCHAR (50) NOT NULL,
    [MODIFIED_DATE]       DATETIME     NOT NULL,
    [UPDATE_SEQ]          INT          NULL,
    [DUE_DATE]            DATETIME     NULL,
	[SLA_MINUTES]		  INT			NULL,
	[SLA_HOURS]			  INT			NULL,
	[SLA_DAYS]			  INT			NULL,
	[NOTIFICATION_MESSAGE] VARCHAR(100) NULL,    
    CONSTRAINT [PK_SGW_BPM_PROCESS_INSTANCE_PROCESS_INSTANCE_ID] PRIMARY KEY CLUSTERED ([PROCESS_INSTANCE_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_PROCESS_INSTANCE_PROCESS_ID_SGW_BPM_PROCESS_PROCESS_ID] FOREIGN KEY ([PROCESS_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS] ([PROCESS_ID])
);

