--001_UserDefindedatatype_F.W

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ACCTNO')
BEGIN
CREATE TYPE [dbo].[UDT_ACCTNO]
    FROM VARCHAR (17) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ADDRESS')
BEGIN
CREATE TYPE [dbo].[UDT_ADDRESS]
FROM VARCHAR (60) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ADDRESS_LINE')
BEGIN
CREATE TYPE [dbo].[UDT_ADDRESS_LINE]
    FROM VARCHAR (60) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_AGE')
BEGIN
CREATE TYPE [dbo].[UDT_AGE]
 FROM NUMERIC (3) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_AMT')
BEGIN
 CREATE TYPE [dbo].[UDT_AMT]
    FROM NUMERIC (11, 2) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_BIGINT')
BEGIN
CREATE TYPE [dbo].[UDT_BIGINT]
    FROM BIGINT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_BIN_MAX_VALUE')
BEGIN
CREATE TYPE [dbo].[UDT_BIN_MAX_VALUE]
    FROM VARBINARY (MAX) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_CITY')
BEGIN
CREATE TYPE [dbo].[UDT_CITY]
    FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_CODE')
BEGIN
CREATE TYPE [dbo].[UDT_CODE]
    FROM VARCHAR (10) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_CODE_ID')
BEGIN
CREATE TYPE [dbo].[UDT_CODE_ID]
    FROM INT NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_CODE_VALUE')
BEGIN
CREATE TYPE [dbo].[UDT_CODE_VALUE]
    FROM VARCHAR (4) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_COL_VALUE')
BEGIN
CREATE TYPE [dbo].[UDT_COL_VALUE]
    FROM VARCHAR (1000) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_COMMENTS')
BEGIN
CREATE TYPE [dbo].[UDT_COMMENTS]
    FROM VARCHAR (2000) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_CREATEDBY')
BEGIN
CREATE TYPE [dbo].[UDT_CREATEDBY]
    FROM VARCHAR (50) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DATA')
BEGIN
CREATE TYPE [dbo].[UDT_DATA]
    FROM VARCHAR (20) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DATA40')
BEGIN
CREATE TYPE [dbo].[UDT_DATA40]
FROM VARCHAR (40) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DATA50')
BEGIN
CREATE TYPE [dbo].[UDT_DATA50]
FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DATE')
BEGIN
CREATE TYPE [dbo].[UDT_DATE]
    FROM DATE NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DATETIME')
BEGIN
CREATE TYPE [dbo].[UDT_DATETIME]
FROM DATETIME NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DAYS')
BEGIN
CREATE TYPE [dbo].[UDT_DAYS]
FROM NUMERIC (5, 2) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DBOBJ')
BEGIN
CREATE TYPE [dbo].[UDT_DBOBJ]
    FROM VARCHAR (128) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DESC')
BEGIN
CREATE TYPE [dbo].[UDT_DESC]
    FROM VARCHAR (100) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_DESCRIPTION')
BEGIN
CREATE TYPE [dbo].[UDT_DESCRIPTION]
    FROM VARCHAR (255) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_EMAIL')
BEGIN
CREATE TYPE [dbo].[UDT_EMAIL]
    FROM VARCHAR (70) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ENCRYPTEDVAL')
BEGIN
CREATE TYPE [dbo].[UDT_ENCRYPTEDVAL]
    FROM VARCHAR (256) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FACTOR')
BEGIN
CREATE TYPE [dbo].[UDT_FACTOR]
    FROM NUMERIC (12, 9) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FAX')
BEGIN
CREATE TYPE [dbo].[UDT_FAX]
    FROM VARCHAR (15) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FEDERAL_ID')
BEGIN
CREATE TYPE [dbo].[UDT_FEDERAL_ID]
    FROM VARCHAR (9) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FILE')
BEGIN
CREATE TYPE [dbo].[UDT_FILE]
    FROM VARBINARY (MAX) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FILE_LOCATION')
BEGIN
CREATE TYPE [dbo].[UDT_FILE_LOCATION]
    FROM VARCHAR (200) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FILE_MAX')
BEGIN
CREATE TYPE [dbo].[UDT_FILE_MAX]
    FROM VARCHAR (MAX) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FILE_NAME')
BEGIN
CREATE TYPE [dbo].[UDT_FILE_NAME]
    FROM VARCHAR (100) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FLAG')
BEGIN
CREATE TYPE [dbo].[UDT_FLAG]
    FROM VARCHAR (1) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FOREIGN_POSTAL_CODE')
BEGIN
CREATE TYPE [dbo].[UDT_FOREIGN_POSTAL_CODE]
    FROM VARCHAR (12) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_FY_YEAR')
BEGIN
CREATE TYPE [dbo].[UDT_FY_YEAR]
FROM NUMERIC (4) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_HOURS')
BEGIN
CREATE TYPE [dbo].[UDT_HOURS]
    FROM DECIMAL (7, 2) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ID')
BEGIN
CREATE TYPE [dbo].[UDT_ID]
 FROM INT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_IDENTITY')
BEGIN
 CREATE TYPE [dbo].[UDT_IDENTITY]
    FROM INT NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_IMAGE')
BEGIN
CREATE TYPE [dbo].[UDT_IMAGE]
    FROM IMAGE NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_IND')
BEGIN
CREATE TYPE [dbo].[UDT_IND]
    FROM VARCHAR (1) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_INT')
BEGIN
CREATE TYPE [dbo].[UDT_INT]
    FROM INT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_KEY')
BEGIN
CREATE TYPE [dbo].[UDT_KEY]
    FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_LONGDESC')
BEGIN
CREATE TYPE [dbo].[UDT_LONGDESC]
    FROM VARCHAR (500) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_LONGNAME')
BEGIN
CREATE TYPE [dbo].[UDT_LONGNAME]
    FROM VARCHAR (1000) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_MAILNAME')
BEGIN
CREATE TYPE [dbo].[UDT_MAILNAME]
    FROM VARCHAR (100) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_MAX_VALUE')
BEGIN
CREATE TYPE [dbo].[UDT_MAX_VALUE]
    FROM VARCHAR (MAX) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_MODIFIEDBY')
BEGIN
CREATE TYPE [dbo].[UDT_MODIFIEDBY]
    FROM VARCHAR (50) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_MONTHS')
BEGIN
CREATE TYPE [dbo].[UDT_MONTHS]
    FROM NUMERIC (5, 2) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_NAME')
BEGIN
CREATE TYPE [dbo].[UDT_NAME]
    FROM VARCHAR (100) NULL;

GRANT REFERENCES
ON TYPE::[dbo].[UDT_NAME] TO PUBLIC;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_NOTES')
BEGIN
CREATE TYPE [dbo].[UDT_NOTES]
    FROM VARCHAR (2000) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_NOTES_MAX')
BEGIN
CREATE TYPE [dbo].[UDT_NOTES_MAX]
    FROM VARCHAR (5300) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_NULL_DATETIME')
BEGIN
CREATE TYPE [dbo].[UDT_NULL_DATETIME]
    FROM DATETIME NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ORGNAME')
BEGIN
CREATE TYPE [dbo].[UDT_ORGNAME]
    FROM VARCHAR (75) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PASSWD')
BEGIN
CREATE TYPE [dbo].[UDT_PASSWD]
    FROM VARCHAR (20) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PERC')
BEGIN
CREATE TYPE [dbo].[UDT_PERC]
    FROM NUMERIC (7, 4) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PERCENT')
BEGIN
CREATE TYPE [dbo].[UDT_PERCENT]
    FROM NUMERIC (7, 4) NULL;

GRANT REFERENCES
    ON TYPE::[dbo].[UDT_PERCENT] TO PUBLIC;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PHONE')
BEGIN
CREATE TYPE [dbo].[UDT_PHONE]
FROM BIGINT NULL;

GRANT REFERENCES
    ON TYPE::[dbo].[UDT_PHONE] TO PUBLIC;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PIN')
BEGIN
CREATE TYPE [dbo].[UDT_PIN]
FROM VARCHAR (256) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_POSTAL_CODE')
BEGIN
CREATE TYPE [dbo].[UDT_POSTAL_CODE]
    FROM VARCHAR (12) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_PROVINCE')
BEGIN
CREATE TYPE [dbo].[UDT_PROVINCE]
FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_RATE_PERC')
BEGIN
CREATE TYPE [dbo].[UDT_RATE_PERC]
FROM NUMERIC (7, 4) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_RECORD_DATA')
BEGIN
CREATE TYPE [dbo].[UDT_RECORD_DATA]
    FROM VARCHAR (899) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_REF_NBR')
BEGIN
CREATE TYPE [dbo].[UDT_REF_NBR]
    FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ROUTINGNO')
BEGIN
CREATE TYPE [dbo].[UDT_ROUTINGNO]
    FROM VARCHAR (20) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SERVICE')
BEGIN
CREATE TYPE [dbo].[UDT_SERVICE]
    FROM NUMERIC (18, 15) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SERVICE_TOTAL')
BEGIN
CREATE TYPE [dbo].[UDT_SERVICE_TOTAL]
    FROM NUMERIC (18, 15) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SHORTDESC')
BEGIN
CREATE TYPE [dbo].[UDT_SHORTDESC]
    FROM VARCHAR (30) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SHORTNAME')
BEGIN
CREATE TYPE [dbo].[UDT_SHORTNAME]
    FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SINT')
BEGIN
CREATE TYPE [dbo].[UDT_SINT]
    FROM SMALLINT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SMALLINT')
BEGIN
CREATE TYPE [dbo].[UDT_SMALLINT]
    FROM SMALLINT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SSN')
BEGIN
CREATE TYPE [dbo].[UDT_SSN]
    FROM VARCHAR (9) NULL;

GRANT REFERENCES
    ON TYPE::[dbo].[UDT_SSN] TO PUBLIC;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_STATE')
BEGIN
CREATE TYPE [dbo].[UDT_STATE]
   FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_SUBMITEDBY')
BEGIN
CREATE TYPE [dbo].[UDT_SUBMITEDBY]
 FROM VARCHAR (50) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_TEXT')
BEGIN
 CREATE TYPE [dbo].[UDT_TEXT]
    FROM VARCHAR (256) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_TIME')
BEGIN
CREATE TYPE [dbo].[UDT_TIME]
    FROM NUMERIC (4, 2) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_UC_PATH_ID')
BEGIN
CREATE TYPE [dbo].[UDT_UC_PATH_ID]
    FROM VARCHAR (10) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_UNIQUE_IDENTIFIER')
BEGIN
CREATE TYPE [dbo].[UDT_UNIQUE_IDENTIFIER]
    FROM UNIQUEIDENTIFIER NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_UPDSEQ')
BEGIN
CREATE TYPE [dbo].[UDT_UPDSEQ]
    FROM INT NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_URL')
BEGIN
CREATE TYPE [dbo].[UDT_URL]
    FROM VARCHAR (200) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_USERID')
BEGIN
CREATE TYPE [dbo].[UDT_USERID]
FROM VARCHAR (20) NOT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_YEAR')
BEGIN
CREATE TYPE [dbo].[UDT_YEAR]
 FROM INT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_YEARS')
BEGIN
 CREATE TYPE [dbo].[UDT_YEARS]
 FROM NUMERIC (5, 2) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ZIP_CODE')
BEGIN
 CREATE TYPE [dbo].[UDT_ZIP_CODE]
 FROM VARCHAR (5) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ZIP4')
BEGIN
CREATE TYPE [dbo].[UDT_ZIP4]
 FROM INT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ZIP4_CODE')
BEGIN
CREATE TYPE [dbo].[UDT_ZIP4_CODE]
FROM VARCHAR (4) NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ZIP5')
BEGIN
CREATE TYPE [dbo].[UDT_ZIP5]
FROM INT NULL;
END

IF NOT EXISTS( SELECT * FROM sys.types where name ='UDT_ZIP5_CODE')
BEGIN
CREATE TYPE [dbo].[UDT_ZIP5_CODE]
FROM VARCHAR (5) NULL;
END
