CREATE TABLE [dbo].[SGW_BPM_ACTIVITY_INST_USERS] (
    [ID]                   INT          IDENTITY (1, 1) NOT NULL,
    [ACTIVITY_INSTANCE_ID] INT          NOT NULL,
    [USER_SERIAL_ID]       INT          NOT NULL,
    [USER_ID]              VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SGW_BPM_ACTIVITY_INST_USERS_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SGW_BPM_ACTIVITY_INST_USERS_ACTIVITY_INSTANCE_ID_SGW_BPM_ACTIVITY_INSTANCE_ACTIVITY_INSTANCE_ID] FOREIGN KEY ([ACTIVITY_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID])
);

