CREATE TABLE [dbo].[SGW_BPM_PRCS_ESC_INSTANCE] (
    [PROCESS_ESCALATION_INSTANCE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [PROCESS_ESCALATION_ID]          INT          NOT NULL,
    [PROCESS_INSTANCE_ID]            INT          NOT NULL,
    [ESCALATION_DATE_TIME]           DATETIME     NOT NULL,
    [STATUS_ID]                      INT          NOT NULL,
    [STATUS_VALUE]                   VARCHAR (4)  NOT NULL,
    [CREATED_BY]                     VARCHAR (50) NOT NULL,
    [CREATED_DATE]                   DATETIME     NOT NULL,
    [MODIFIED_BY]                    VARCHAR (50) NOT NULL,
    [MODIFIED_DATE]                  DATETIME     NOT NULL,
    [UPDATE_SEQ]                     INT          NULL,
    [PROCESSING_FLAG]                VARCHAR (1)  DEFAULT ('N') NULL,
    CONSTRAINT [PK_SGW_BPM_PRCS_ESC_INSTANCE] PRIMARY KEY CLUSTERED ([PROCESS_ESCALATION_INSTANCE_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_PRCS_ESC_INSTANCE_PROCESS_ESCALATION_ID_SGW_BPM_PROCESS_ESCALATION_PROCESS_ESCALATION_ID] FOREIGN KEY ([PROCESS_ESCALATION_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS_ESCALATION] ([PROCESS_ESCALATION_ID]),
    CONSTRAINT [FK_SGW_BPM_PRCS_ESC_INSTANCE_PROCESS_INSTANCE_ID_SGW_BPM_PROCESS_INSTANCE_PROCESS_INSTANCE_ID] FOREIGN KEY ([PROCESS_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS_INSTANCE] ([PROCESS_INSTANCE_ID])
);



