CREATE TABLE [dbo].[SGW_BPM_REQUEST_ACTION]
(
	[REQUEST_ACTION_ID] [dbo].[UDT_IDENTITY] IDENTITY (1, 1) NOT NULL, 
    [REQUEST_ID] [dbo].[UDT_INT] NULL, 
    [CASE_INSTANCE_ID] [dbo].[UDT_INT] NULL, 
    [PROCESS_INSTANCE_ID] [dbo].[UDT_INT] NULL, 
    [ACTIVITY_INSTANCE_ID] [dbo].[UDT_INT] NULL, 
    [TYPE] [dbo].[UDT_DESC] NULL, 
    CONSTRAINT [PK_SGW_BPM_REQUEST_ACTION] PRIMARY KEY CLUSTERED ([REQUEST_ACTION_ID])	
)

