
CREATE TABLE SGW_BPM_TRACE_INST_ACTN_DTL(
	[TRACE_INST_ACTN_DTL_ID] [INT] IDENTITY(1,1) NOT NULL,		
	[START_TIME] [DATETIME] NOT NULL,
	[REFERENCE_TYPE] [VARCHAR](100)  NULL,
	[REFERENCE_ID] [BIGINT]  NULL,
	[PROCESS_INSTANCE_ID] [INT]  NULL,
	[RESPONSE_MESSAGE_VALUE] [INT]  NULL,	
	[TRANSACTION_ID] [uniqueidentifier] null,
	[SUB_TRANSACTION_ID] int,
	[END_TIME] [DATETIME]  NULL,	
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT] NULL,
 CONSTRAINT [PK_SGW_BPM_TRACE_INST_ACTN_DTL] PRIMARY KEY CLUSTERED 
(
	[TRACE_INST_ACTN_DTL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


