
CREATE TABLE [dbo].[SGW_BPM_TRACE_INST_QUERY](
	[BPM_TRACE_INST_QUERY_ID] [int] IDENTITY(1,1) NOT NULL,	
	[QUERY_ID] [varchar](100) NULL,
	[QUERY_TEXT] [varchar](8000) NOT NULL,
	[RESULT] [varchar](500) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime]  NULL,
	[STEP_NAME] [varchar](100) NULL,
	[PARAMETER_DETAILS] [varchar](8000) NULL,
	[TRANSACTION_ID] [uniqueidentifier] null,
	[SUB_TRANSACTION_ID] int,
	[TOTAL_TIME_IN_MS] [int] NULL,	
 CONSTRAINT [PK_SGW_BPM_TRACE_INST_QUERY] PRIMARY KEY CLUSTERED 
(
	[BPM_TRACE_INST_QUERY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] 
