CREATE TABLE [dbo].[SGW_BPM_USERS_ESC_MESSAGE] (
    [USERS_ESC_MESSAGE_ID] INT         IDENTITY (1, 1) NOT NULL,
    [ESCALATION_MESSAGE_ID]       INT         NOT NULL,
    [USER_SERIAL_ID]              INT         NOT NULL,
    [MARK_AS_READ]                VARCHAR (1) NOT NULL,
    CONSTRAINT [PK_SGW_BPM_USERS_ESC_MESSAGE] PRIMARY KEY CLUSTERED ([USERS_ESC_MESSAGE_ID] ASC)
);

