
CREATE TABLE SGW_BPM_TRACING(
	[BPM_TRACING_ID] [int] IDENTITY(1,1) NOT NULL,
	[BPM_TRACING_FLAG] VARCHAR(1) NOT NULL,
	[BPM_QUERY_TRACING_FLAG] VARCHAR(1) NULL,
	[BPM_QUERY_LIMIT] [INT] NOT NULL ,
	[BPM_QUERY_LIMIT_ALERT] [VARCHAR](100) NOT NULL, 
	[BPM_QUERY_HIGH_LIMIT] [INT] NOT NULL,	
	[BPM_QUERY_HIGH_LIMIT_ALERT] [VARCHAR](100) NOT NULL,	
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT]  NULL,
 CONSTRAINT [PK_SGW_BPM_TRACING] PRIMARY KEY CLUSTERED 
(
	[BPM_TRACING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

