DECLARE @MESSAGE_ID AS INT
DECLARE @MESSAGE_KEY AS VARCHAR(200)
DECLARE @DISPLAY_MESSAGE AS VARCHAR(MAX)
DECLARE @SEVERITY_ID AS INT
DECLARE @SEVERITY_VALUE AS VARCHAR(50)
DECLARE @CATEGORY_ID AS INT
DECLARE @CATEGORY_VALUE AS VARCHAR(50)
DECLARE @CATEGORY_NAME AS VARCHAR(50)
DECLARE @CREATED_BY AS VARCHAR(200)
DECLARE @CREATED_DATE AS DATETIME
DECLARE @UPDATE_SEQ AS INT
DECLARE @PRINT_MESSAGE_FLAG AS BIT
DECLARE @UPDATE_MESSAGE_FLAG AS BIT
DECLARE @PRINT_MESSAGE AS VARCHAR(100)
DECLARE @INSERT_MESSAGE AS VARCHAR(100)
DECLARE @UPDATE_MESSAGE AS VARCHAR(100)
DECLARE @EXISTS_MESSAGE AS VARCHAR(100)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--========================================================================================================================================================================
SET @PRINT_MESSAGE_FLAG = 1   -- Flag to Print or Do not print Message after execution
SET @UPDATE_MESSAGE_FLAG = 1  -- Flag to Update the existing message
--========================================================================================================================================================================
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET @PRINT_MESSAGE = 'MESSAGE {MESSAGE_TYPE} - MESSAGE_ID: {MESSAGE_ID} DISPLAY_MESSAGE: "{DISPLAY_MESSAGE}".'
SET @INSERT_MESSAGE = REPLACE(@PRINT_MESSAGE, '{MESSAGE_TYPE}', 'INSERTED')
SET @UPDATE_MESSAGE = REPLACE(@PRINT_MESSAGE, '{MESSAGE_TYPE}', 'UPDATED')
SET @EXISTS_MESSAGE = REPLACE(@PRINT_MESSAGE, '{MESSAGE_TYPE}', 'ALREADY EXISTS')
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET @CREATED_BY = 'FRAMEWORK'
SET @SEVERITY_ID = 16
SET @CATEGORY_ID = 256
SET @CREATED_DATE = GETDATE()
SET @UPDATE_SEQ = 0
SET @CATEGORY_NAME = 'FWK'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET @CATEGORY_VALUE = 'OTM'
SET @SEVERITY_VALUE = 'I'
SET @MESSAGE_ID = 50030
SET @DISPLAY_MESSAGE = 'Error Occured.'

IF NOT EXISTS (SELECT 1 FROM SGS_FWK_MESSAGES WHERE MESSAGE_ID = @MESSAGE_ID OR DISPLAY_MESSAGE LIKE @DISPLAY_MESSAGE)
BEGIN
	INSERT INTO SGS_FWK_MESSAGES
	(MESSAGE_ID,  MESSAGE_KEY,   DISPLAY_MESSAGE,  SEVERITY_ID,  SEVERITY_VALUE,  CATEGORY_NAME,  CATEGORY_ID,  CATEGORY_VALUE,  CREATED_BY,  CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	VALUES
	(@MESSAGE_ID, @MESSAGE_KEY, @DISPLAY_MESSAGE, @SEVERITY_ID, @SEVERITY_VALUE, @CATEGORY_NAME, @CATEGORY_ID, @CATEGORY_VALUE, @CREATED_BY, @CREATED_DATE, @CREATED_BY, @CREATED_DATE, @UPDATE_SEQ)

	IF @PRINT_MESSAGE_FLAG = 1
	BEGIN
		PRINT REPLACE(REPLACE(@INSERT_MESSAGE, '{MESSAGE_ID}', CONVERT(VARCHAR, @MESSAGE_ID)), '{DISPLAY_MESSAGE}', CONVERT(VARCHAR(MAX), @DISPLAY_MESSAGE))
	END
END
ELSE
BEGIN
	IF @UPDATE_MESSAGE_FLAG = 1
	BEGIN
		UPDATE SGS_FWK_MESSAGES
		SET
			MESSAGE_KEY = @MESSAGE_KEY,
			DISPLAY_MESSAGE = @DISPLAY_MESSAGE,
			SEVERITY_ID = @SEVERITY_ID,
			SEVERITY_VALUE = @SEVERITY_VALUE,
			CATEGORY_NAME = @CATEGORY_NAME,
			CATEGORY_ID = @CATEGORY_ID,
			CATEGORY_VALUE = @CATEGORY_VALUE,
			MODIFIED_BY = @CREATED_BY,
			MODIFIED_DATE = @CREATED_DATE,
			UPDATE_SEQ = UPDATE_SEQ + 1
		WHERE MESSAGE_ID = @MESSAGE_ID

		IF @PRINT_MESSAGE_FLAG = 1
		BEGIN
			PRINT REPLACE(REPLACE(@UPDATE_MESSAGE, '{MESSAGE_ID}', CONVERT(VARCHAR, @MESSAGE_ID)), '{DISPLAY_MESSAGE}', CONVERT(VARCHAR(MAX), @DISPLAY_MESSAGE))
		END
	END
	ELSE IF @PRINT_MESSAGE_FLAG = 1
	BEGIN
		PRINT REPLACE(REPLACE(@EXISTS_MESSAGE, '{MESSAGE_ID}', CONVERT(VARCHAR, @MESSAGE_ID)), '{DISPLAY_MESSAGE}', CONVERT(VARCHAR(MAX), @DISPLAY_MESSAGE))
	END
END