ALTER TABLE SGS_SESSION_STORE
ADD UPDATE_SEQ INT NOT NULL DEFAULT(0);

ALTER TABLE SGS_ACT_LOG
ADD REFRESH_DB_CACHE DATETIME NULL;

ALTER TABLE SGS_ACT_LOG
ADD REFRESH_SYSTEM_SETTINGS_CACHE DATETIME NULL;

ALTER TABLE SGS_ACT_LOG
ADD REFRESH_DB_CONNECTION DATETIME NULL;

ALTER TABLE SGS_ACT_LOG
ADD REFRESH_WEB_CACHE DATETIME NULL;

ALTER TABLE SGS_ACT_LOG
ADD RUN_GC DATETIME NULL;

ALTER TABLE SGS_ACT_LOG
ADD CLEAR_DB_POOL DATETIME NULL;

ALTER TABLE SGS_DATABASE_CONNECTIONS
DROP COLUMN SUPPORTS_ALWAYS_ON_FLAG; 


