/*----------------------------------------Iserting new Member Types into SGS_CODE_VALUE Table-----------------------------*/
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DCT1') INSERT INTO SGS_CODE_VALUE VALUES (320,'DCT1','DC 2025 Temporary 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC01') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC01','DC 2025 Reg 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC02') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC02','DC 2025 Reg 2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC03') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC03','DC 2025 Reg 3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC04') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC04','DC 2025 Reg 4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC05') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC05','DC 2025 Reg 5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC06') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC06','DC 2025 Reg 6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC07') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC07','DC 2025 Reg 7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC08') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC08','DC 2025 Reg 8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC09') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC09','DC 2025 Reg 9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC10') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC10','DC 2025 Reg 10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC11') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC11','DC 2025 Reg 11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC12') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC12','DC 2025 Reg 12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC13') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC13','DC 2025 Reg 13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC14') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC14','DC 2025 Reg 14',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC15') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC15','DC 2025 Reg 15',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC16') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC16','DC 2025 Reg 16',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC17') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC17','DC 2025 Reg 17',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC18') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC18','DC 2025 Reg 18',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC19') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC19','DC 2025 Reg 19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC20') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC20','DC 2025 Reg 20',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC21') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC21','DC 2025 Reg 21',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC22') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC22','DC 2025 Reg 22',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC23') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC23','DC 2025 Reg 23',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC24') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC24','DC 2025 Reg 24',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC25') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC25','DC 2025 Reg 25',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC26') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC26','DC 2025 Reg 26',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC27') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC27','DC 2025 Reg 27',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC28') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC28','DC 2025 Reg 28',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC29') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC29','DC 2025 Reg 29',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 320 AND CODE_VALUE='DC30') INSERT INTO SGS_CODE_VALUE VALUES (320,'DC30','DC 2025 Reg 30',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR 25920', GETDATE(),'PIR 25920', GETDATE(),0) 
GO


/*----------------------------------------Iserting data into SGT_PLAN_MEMBER_TYPE_CROSSREF Table-----------------------------*/
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'TEMP',320,'DCT1') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC01')
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC01') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC02') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC03') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC04') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC05') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC06') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC07') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC08') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC09') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC10') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC11') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC12') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC13') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC14') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC15') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC16') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC17') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC18') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC19') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC20') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC21') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC22') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC23') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC24') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC25') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC26') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC27') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC28') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC29') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEO' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEO',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='STAP' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'STAP',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='SEO' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'SEO',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='USS' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'USS',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSAP' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSAP',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NSEM' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NSEM',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='NCLS' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'NCLS',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='LEGI' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'LEGI',313,'PERM',320,'DC30') 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_MEMBER_TYPE_CROSSREF] WHERE PLAN_ID = 30 AND JOB_CLASS_VALUE ='CLAS' AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF VALUES (30,314,'CLAS',313,'PERM',320,'DC30') 
GO


/*----------------------------------------Iserting data into SGT_PLAN_RETIREMENT_RATE Table-----------------------------*/
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC01') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC01',NULL,2,2,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC02') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC02',NULL,3,1,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC03') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC03',NULL,3.5,0.5,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC04') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC04',NULL,4,NULL,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,NULL,2,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC05') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC05',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC06') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC06',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC07') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC07',1,NULL,3,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC08') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC08',1,NULL,3,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC09') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC09',NULL,4,NULL,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC10') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC10',NULL,0.5,3.5,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC11') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC11',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC12') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC12',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC13') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC13',2.26,NULL,1.74,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC14') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC14',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC15') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC15',3.19,NULL,0.81,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC16') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC16',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC17') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC17',NULL,3,1,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC18') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC18',3,NULL,1,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC19') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC19',2.26,NULL,1.74,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC20') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC20',2.5,NULL,1.5,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC21') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC21',4,NULL,NULL,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC22') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC22',3.12,NULL,0.88,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC23') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC23',2,NULL,2,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC24') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC24',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC25') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC25',NULL,NULL,4,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC26') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC26',NULL,1,3,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC27') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC27',0.5,NULL,3.5,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC28') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC28',NULL,1.43,2.57,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC29') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC29',NULL,0.26,3.74,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,NULL,3,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DC30') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DC30',2.26,NULL,1.74,0,5.26,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,2,NULL,NULL,3,NULL,3,0) 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE PLAN_ID = 30 AND MEMBER_TYPE_VALUE ='DCT1') INSERT INTO SGT_PLAN_RETIREMENT_RATE VALUES (30,'1/1/2025',320,'DCT1',NULL,9.26,NULL,NULL,NULL,NULL,'PIR25920',GETDATE(),'PIR25920',GETDATE(),0,NULL,2,NULL,NULL,6,0,0) 
GO

