/*Schema_Changes_PIR_19701*/
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_ORG_PLAN'
                 AND COLUMN_NAME = 'DAY_OF_MONTH') 
	ALTER TABLE SGT_ORG_PLAN 
	ADD DAY_OF_MONTH INT NULL
GO

/*Data_Changes_PIR_19701*/
UPDATE SGT_ORG_PLAN SET DAY_OF_MONTH = 1 WHERE PLAN_ID IN (8, 19) AND REPORT_FREQUENCY_ID = 405 AND REPORT_FREQUENCY_VALUE = 'MONT'

/*UPDATE SGT_ORG_PLAN SET DAY_OF_MONTH = 9 WHERE PLAN_ID IN (8, 19) AND REPORT_FREQUENCY_ID = 405 AND REPORT_FREQUENCY_VALUE = 'MONT' AND ORG_ID IN (267, 351)*/

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10404)
	INSERT [SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], 
							[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (10404,N'Day of Month must be entered.', 16, N'E', NULL, NULL, N'PIR 19701', GETDATE(), N'PIR 19701', GETDATE(), 0)
GO

/*Data_Change_PIR_17400*/
UPDATE SGS_SECURITY SET SECURITY_VALUE = 4 WHERE RESOURCE_ID = 2020 AND SECURITY_VALUE = 3

/*Data_Changes_PIR_16208*/
IF NOT EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=5014 AND CODE_VALUE='DFME')
	INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(5014,'DFME',	'Different member',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 16208',	GETDATE(),	'PIR 16208',	GETDATE(),	0)
GO
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10402)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10402,'Please enter the member id to whom the amount need to be refunded.',16,'E',NULL,NULL,'PIR 16208',GETDATE(),'PIR 16208',GETDATE(),0)
GO

/*Data_Changes_PIR_18127*/
IF NOT EXISTS (SELECT 1 FROM SGS_COR_TEMPLATES WHERE TEMPLATE_NAME ='PUR-8314')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] (TEMPLATE_NAME,TEMPLATE_DESC,TEMPLATE_GROUP_ID,TEMPLATE_GROUP_VALUE,ACTIVE_FLAG,DESTINATION_ID,DESTINATION_VALUE,ASSOCIATED_FORMS
,FILTER_OBJECT_ID,FILTER_OBJECT_FIELD,FILTER_OBJECT_VALUE,CONTACT_ROLE_ID,CONTACT_ROLE_VALUE,BATCH_FLAG,ONLINE_FLAG,AUTO_PRINT_FLAG,PRINTER_NAME_ID
,PRINTER_NAME_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,IMAGE_DOC_CATEGORY_ID,IMAGE_DOC_CATEGORY_VALUE,FILENET_DOCUMENT_TYPE_ID,FILENET_DOCUMENT_TYPE_VALUE,DOCUMENT_CODE)
VALUES
('PUR-8314','Service Purchase Payment Installments Termination',19,'MMBR','Y',601,'IMG','wfmServicePurchaseHeaderMaintenance;',NULL,NULL,NULL,515,NULL,'N','Y','N',44,NULL,'PIR 18127',GETDATE(),'PIR 18127',GETDATE(),0,603,'MEMB',604,'CORR','1518')
GO

/*Data_Changes_PIR_21668*/
IF EXISTS (SELECT 1 FROM SGS_BATCH_SCHEDULE WHERE STEP_NAME='No HDV Dependent Report' AND BATCH_SCHEDULE_ID=107)
	UPDATE SGS_BATCH_SCHEDULE SET STEP_NAME ='Insurance Discrepancies Report' WHERE BATCH_SCHEDULE_ID=107
GO

/*DataChange_PIR19046*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10403)
BEGIN
INSERT INTO SGS_MESSAGES([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10403,'Unused Sick Leave has been entered on the last terminated employment.',16,'E',NULL,NULL,'PIR19046	',getdate(),'PIR19046',GETDATE(),0)
END
GO 

/*DataChange_PIR21591*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10401)
BEGIN
INSERT INTO SGS_MESSAGES([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10401,'Pay Period End Date should be greater than or equal to Pay Period Start Date.',16,'E',NULL,NULL,'PIR21591',getdate(),'PIR21591',GETDATE(),0)
END
GO 

/*Data_Change_FW_PIR_17537*/
/********************Purpose: Allowing ASCII characters in comments******************************
*********************Created By: Dinesh********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT 1 FROM SGS_SYSTEM_SETTINGS WHERE SETTING_NAME = 'AllowNonASCIIChars')
INSERT INTO dbo.SGS_SYSTEM_SETTINGS (SETTING_NAME, SETTING_TYPE, SETTING_VALUE, ENCRYPTED_FLAG)
VALUES ('AllowNonASCIIChars','bool','True',NULL)
GO 

/*DataChange_FW_Upgrade_PIR_22998_08162020*/
IF NOT EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 52 AND CODE_VALUE = 'DLSN')
INSERT INTO [dbo].[SGS_CODE_VALUE]
           ([CODE_ID]
           ,[CODE_VALUE]
           ,[DESCRIPTION]
           ,[DATA1]
           ,[DATA2]
           ,[DATA3]
           ,[COMMENTS]
           ,[START_DATE]
           ,[END_DATE]
           ,[CODE_VALUE_ORDER]
           ,[LEGACY_CODE_ID]
           ,[CREATED_BY]
           ,[CREATED_DATE]
           ,[MODIFIED_BY]
           ,[MODIFIED_DATE]
           ,[UPDATE_SEQ])
     VALUES
           (52
           ,'DLSN'
           ,'No Of Days To Retain Session Store'
           ,'14'
           ,null
           ,null
           ,null
           ,null
           ,null
           ,null
           ,null
           ,'F/W_UPGRADE_PIR_22998'
           ,GETDATE()
           ,'F/W_UPGRADE_PIR_22998'
           ,GETDATE()
           ,0)
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_BATCH_SCHEDULE] WHERE BATCH_SCHEDULE_ID = 151)
INSERT [dbo].[SGS_BATCH_SCHEDULE] ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS], [FREQUENCY_IN_MONTHS], 
			[NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG], [REQUIRES_TRANSACTION_FLAG], [EMAIL_NOTIFICATION], [ORDER_NO], [CUTOFF_START], 
			[CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (151, 620, N'Process Delete Session Store', NULL,NULL,1, CAST(N'2020-09-16 00:00:00.000' AS DateTime), NULL, N'Y', N'N', NULL, NULL, NULL, NULL, N'F/W_UPGRADE_PIR_22998', getdate(), N'F/W_UPGRADE_PIR_22998', getdate(), 0)
GO

/*DataChange_PIR_21591*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10405) 
BEGIN
INSERT INTO SGS_MESSAGES([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10405,'Pay Period End Month for Bonuses should be greater than Pay Period Date',16,'E',NULL,NULL,'PIR21591',getdate(),'PIR21591',GETDATE(),0)
END
GO 

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10406) 
BEGIN
INSERT INTO SGS_MESSAGES([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10406,'End Month for Bonus/Retro Pay should be greater than Reporting Month',16,'E',NULL,NULL,'PIR21591',getdate(),'PIR21591',GETDATE(),0)
END
GO 

/*Schema_Data_Changes_PIR 22932*/
/********************Purpose: PIR 22932******************************
*********************Created By: Vidya********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7019) 
BEGIN
INSERT INTO SGS_CODE (CODE_ID,DESCRIPTION,DATA1_CAPTION,DATA1_TYPE,DATA2_CAPTION,DATA2_TYPE,DATA3_CAPTION,DATA3_TYPE,FIRST_LOOKUP_ITEM,FIRST_MAINTENANCE_ITEM,COMMENTS,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(7019,'COBRA Letter Status',NULL,NULL,NULL,NULL,NULL,NULL,'All',NULL,NULL,NULL,'PIR 22932',GETDATE(),'PIR 22932',GETDATE(),0)
END
GO 

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7019 AND CODE_VALUE='LNS') 
BEGIN
INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(7019,'LNS','Letter Not Sent',NULL,NULL,NULL,NULL,NULL,NULL,	NULL,NULL,'PIR 22932',GETDATE(),'PIR 22932',GETDATE(),0)
END
GO 

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7019 AND CODE_VALUE='LSN') 
BEGIN
INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(7019,'LSN','Letter Sent',NULL,NULL,NULL,NULL,NULL,NULL,	NULL,NULL,'PIR 22932',GETDATE(),'PIR 22932',GETDATE(),0)
END
GO 

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'SGT_PERSON_EMPLOYMENT_DETAIL' AND [COLUMN_NAME] = 'COBRA_LETTER_STATUS_ID')
BEGIN
ALTER TABLE SGT_PERSON_EMPLOYMENT_DETAIL
ADD COBRA_LETTER_STATUS_ID INT NOT NULL DEFAULT (7019)
END
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'SGT_PERSON_EMPLOYMENT_DETAIL' AND [COLUMN_NAME] = 'COBRA_LETTER_STATUS_VALUE')
BEGIN
ALTER TABLE SGT_PERSON_EMPLOYMENT_DETAIL
ADD COBRA_LETTER_STATUS_VALUE VARCHAR(4) NULL
END
GO

