--------------Created By: Sarvesh
--------------Purpose   : PIR 26256

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'ENR-5063')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
[IMAGE_DOC_CATEGORY_ID],[IMAGE_DOC_CATEGORY_VALUE],[FILENET_DOCUMENT_TYPE_ID],[FILENET_DOCUMENT_TYPE_VALUE],[DOCUMENT_CODE],[BATCH_PRINT_FLAG]) 
VALUES ( 'ENR-5063', 'Retirement Annual Contribution Limit', '19', 'MMBR', 'Y', '601', NULL, 
'wfmEmployerPayrollDetailMaintenance;', NULL, NULL, NULL, 
'515',NULL, 'N', 'Y', 'N', '44', NULL, 'PIR 26256', getdate(), 'PIR 26256', getdate(), '0',603,'MEMB',604,'FORM',Null,Null)
GO




--------------Created By: Vidya
--------------Purpose   : PIR 26544
IF EXISTS (SELECT 1 FROM [DBO].[SGS_CODE] WHERE CODE_ID=7003)
BEGIN
UPDATE SGS_CODE SET DESCRIPTION = 'All Plan Benefit Tier', DATA1_CAPTION ='Effective Start Date', DATA1_TYPE='date', DATA2_CAPTION = 'PlanID', DATA2_TYPE='int' WHERE CODE_ID=7003
END
GO
-- PLAN ID 26
IF EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE CODE_ID=7003 AND CODE_VALUE='11BT' AND DESCRIPTION <> 'Tier 1 BCI')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DESCRIPTION='Tier 1 BCI', DATA1='01/01/1900', DATA2 =26, MODIFIED_BY='PIR 26544', MODIFIED_DATE=GETDATE() WHERE CODE_ID=7003 AND CODE_VALUE='11BT'
END
GO
IF EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE CODE_ID=7003 AND CODE_VALUE='23BT' AND DESCRIPTION <> 'Tier 2 BCI 2023')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DESCRIPTION = 'Tier 2 BCI 2023', DATA1 ='08/01/2023', DATA2 = 26, MODIFIED_BY='PIR 26544', MODIFIED_DATE=GETDATE() WHERE CODE_ID=7003 AND CODE_VALUE='23BT'
END
GO
-- PLAN ID 1
IF EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE CODE_ID=7003 AND CODE_VALUE='97MT' AND DESCRIPTION <> 'Tier 1 Main')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DESCRIPTION = 'Tier 1 Main', DATA1='01/01/1900', DATA2=1, MODIFIED_BY='PIR 26544', MODIFIED_DATE=GETDATE()  WHERE CODE_ID=7003 AND CODE_VALUE='97MT'
END
GO
IF EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE CODE_ID=7003 AND CODE_VALUE='16MT' AND DESCRIPTION <> 'Tier 2 Main 2016')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DESCRIPTION = 'Tier 2 Main 2016', DATA1='01/01/2016', DATA2=1, MODIFIED_BY='PIR 26544', MODIFIED_DATE=GETDATE()  WHERE CODE_ID=7003 AND CODE_VALUE='16MT'
END
GO
-- PLAN ID 27
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20MT' AND DATA2 = 27)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20MT', 'Tier 3 Main 2020', '01/01/2020', 27, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO
-- PLAN ID 2
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97PS' AND DATA2 = 2)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97PS', 'Tier 1 PS', '01/01/1900', 2, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20PS' AND DATA2 = 2)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20PS', 'Tier 2 PS 2020', '01/01/2020', 2, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

--PLAN ID 20
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97PT' AND DATA2 = 20)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97PT', 'Tier 1 PS', '01/01/1900', 20, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20PT' AND DATA2 = 20)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20PT', 'Tier 2 PS 2020', '01/01/2020', 20, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

--PLAN ID 29
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97ST' AND DATA2 = 29)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97ST', 'Tier 1 PS', '01/01/1900', 29, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20ST' AND DATA2 = 29)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20ST', 'Tier 2 PS 2020', '01/01/2020', 29, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

--PLAN ID 3
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97NG' AND DATA2 = 3)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97NG', 'Tier 1 PS', '01/01/1900', 3, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20NG' AND DATA2 = 3)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20NG', 'Tier 2 PS 2020', '01/01/2020', 3, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

--PLAN ID DC
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97DC' AND DATA2 = 7 )
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97DC', 'Tier 1 DC', '01/01/1900', 7, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

--PLAN ID DC2020
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='97DC' AND DATA2 = 28)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '97DC', 'Tier 1 DC', '01/01/1900', 28, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='20DC' AND DATA2 = 28)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '20DC', 'Tier 2 DC 2020', '01/01/2020', 28, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

-- UPDATE EXISTING ENTRY [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 27
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 11 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '20MT')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '20MT' WHERE BENEFIT_PROVISION_ID = 11
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 2
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '97PS' AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '97PS' WHERE BENEFIT_PROVISION_ID = 2 AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND BENEFIT_TIER_VALUE = '20PS' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'2020-01-01 00:00:00.000',	1904,	'RETR',	2309,	'SRSM',	2310,	'FAPM',	0.005000,	2315,	'HIAV',	36,	180,	'Y',	2311,	'MASA',	NULL,	'Y',	2312,	'MASA',	NULL,	5.00,	7003,	'20PS')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND BENEFIT_TIER_VALUE = '20PS' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'2020-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PS')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND BENEFIT_TIER_VALUE = '20PS' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'2020-01-01 00:00:00.000',	1904,	'DETH',	2309,	'SRSM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PS')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND BENEFIT_TIER_VALUE = '20PS' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'2020-01-01 00:00:00.000',	1904,	'DISA',	2309,	'SERM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PS')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 2 AND BENEFIT_TIER_VALUE = '20PS' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'2020-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'20PS')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 20
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97PT' AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '97PT' WHERE BENEFIT_PROVISION_ID = 8 AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND BENEFIT_TIER_VALUE = '20PT' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'2020-01-01 00:00:00.000',	1904,	'RETR',	2309,	'SRSM',	2310,	'FAPM',	0.005000,	2315,	'HIAV',	36,	180,	'Y',	2311,	'MASA',	NULL,	'Y',	2312,	'MASA',	NULL,	5.00,	7003,	'20PT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND BENEFIT_TIER_VALUE = '20PT' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'2020-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND BENEFIT_TIER_VALUE = '20PT' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'2020-01-01 00:00:00.000',	1904,	'DETH',	2309,	'SRSM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND BENEFIT_TIER_VALUE = '20PT' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'2020-01-01 00:00:00.000',	1904,	'DISA',	2309,	'SERM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20PT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 8 AND BENEFIT_TIER_VALUE = '20PT' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'2020-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'20PT')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 29
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '97ST' AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '97ST' WHERE BENEFIT_PROVISION_ID = 13 AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND BENEFIT_TIER_VALUE = '20ST' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'2020-01-01 00:00:00.000',	1904,	'RETR',	2309,	'SRSM',	2310,	'FAPM',	0.005000,	2315,	'HIAV',	36,	180,	'Y',	2311,	'MASA',	NULL,	'Y',	2312,	'MASA',	NULL,	5.00,	7003,	'20ST')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND BENEFIT_TIER_VALUE = '20ST' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'2020-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20ST')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND BENEFIT_TIER_VALUE = '20ST' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'2020-01-01 00:00:00.000',	1904,	'DETH',	2309,	'SRSM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20ST')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND BENEFIT_TIER_VALUE = '20ST' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'2020-01-01 00:00:00.000',	1904,	'DISA',	2309,	'SERM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20ST')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 13 AND BENEFIT_TIER_VALUE = '20ST' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'2020-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'20ST')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 3
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97NG' AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '97NG' WHERE BENEFIT_PROVISION_ID = 3 AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND BENEFIT_TIER_VALUE = '20NG' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'2020-01-01 00:00:00.000',	1904,	'RETR',	2309,	'SRSM',	2310,	'FAPM',	0.005000,	2315,	'HIAV',	36,	180,	'Y',	2311,	'MASA',	NULL,	'Y',	2312,	'MASA',	NULL,	5.00,	7003,	'20NG')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND BENEFIT_TIER_VALUE = '20NG' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'2020-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20NG')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND BENEFIT_TIER_VALUE = '20NG' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'2020-01-01 00:00:00.000',	1904,	'DETH',	2309,	'SRSM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20NG')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND BENEFIT_TIER_VALUE = '20NG' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'2020-01-01 00:00:00.000',	1904,	'DISA',	2309,	'SERM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'20NG')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 3 AND BENEFIT_TIER_VALUE = '20NG' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'2020-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'20NG')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 7
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 7 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97DC' AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '97DC' WHERE BENEFIT_PROVISION_ID = 7 AND EFFECTIVE_DATE < '2020-01-01 00:00:00.000'
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 28
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '20DC' AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '20DC' WHERE BENEFIT_PROVISION_ID = 12 AND EFFECTIVE_DATE = '2020-01-01 00:00:00.000'
END
GO
--97DC
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND BENEFIT_TIER_VALUE = '97DC' AND EFFECTIVE_DATE = '1900-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'1900-01-01 00:00:00.000',	1904,	'RETR',	2309,	'OTHR',	2310,	'OTHR',	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	'OTHR',	NULL,	NULL,	2312,	'OTHR',	NULL,	0.00,	7003,	'97DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND BENEFIT_TIER_VALUE = '97DC' AND EFFECTIVE_DATE = '1900-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'1900-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'97DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND BENEFIT_TIER_VALUE = '97DC' AND EFFECTIVE_DATE = '1900-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'1900-01-01 00:00:00.000',	1904,	'DETH',	2309,	'OTHR',	2310,	NULL,	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'97DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND BENEFIT_TIER_VALUE = '97DC' AND EFFECTIVE_DATE = '1900-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'1900-01-01 00:00:00.000',	1904,	'DISA',	2309,	'OTHR',	2310,	'OTHR',	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	'OTHR',	NULL,	NULL,	2312,	'OTHR',	NULL,	0.00,	7003,	'97DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 12 AND BENEFIT_TIER_VALUE = '97DC' AND EFFECTIVE_DATE = '1900-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'1900-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'97DC')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 27
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 11 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '20MT' AND [EFFECTIVE_DATE] = '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '20MT' WHERE BENEFIT_PROVISION_ID = 11 AND [EFFECTIVE_DATE] = '01/01/2020'
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 2
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 2 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '97PS' AND [EFFECTIVE_DATE]  < '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '97PS' WHERE BENEFIT_PROVISION_ID = 2 AND [EFFECTIVE_DATE]  < '01/01/2020'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=2 AND [EFFECTIVE_DATE]='01/01/2020' AND [BENEFIT_TIER_VALUE]='20PS')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'01/01/2020', 1904, 'RETR', 1910, 'VEST', 50, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 2, NULL, 7003,	'20PS')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'01/01/2020', 1904, 'RETR', 1910, 'ERLY', 50, 36, NULL, 'N', 'Y', NULL, NULL, NULL, NULL, 12, NULL, 7003, '20PS')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'01/01/2020', 1904, 'RETR', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 17, NULL, 7003,	'20PS')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'01/01/2020', 1904, 'DETH', 1910, 'VEST', NULL, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 24, NULL, 7003,	'20PS')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(2,	'01/01/2020', 1904, 'DETH', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 39, NULL, 7003,	'20PS')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 20
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 8 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97PT' AND [EFFECTIVE_DATE]  < '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '97PT' WHERE BENEFIT_PROVISION_ID = 8 AND [EFFECTIVE_DATE]  < '01/01/2020'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=8 AND [EFFECTIVE_DATE]='01/01/2020'AND [BENEFIT_TIER_VALUE]='20PT')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'01/01/2020', 1904, 'RETR', 1910, 'VEST', 50, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 3, NULL, 7003,	'20PT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'01/01/2020', 1904, 'RETR', 1910, 'ERLY', 50, 36, NULL, 'N', 'Y', NULL, NULL, NULL, NULL, 11, NULL, 7003,	'20PT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'01/01/2020', 1904, 'RETR', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 22, NULL, 7003,	'20PT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'01/01/2020', 1904, 'DETH', 1910, 'VEST', NULL, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 25, NULL, 7003,	'20PT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(8,	'01/01/2020', 1904, 'DETH', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 44, NULL, 7003,	'20PT')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 29
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 13 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97ST' AND [EFFECTIVE_DATE]  < '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '97ST' WHERE BENEFIT_PROVISION_ID = 13 AND [EFFECTIVE_DATE]  < '01/01/2020'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=13 AND [EFFECTIVE_DATE]='01/01/2020'AND [BENEFIT_TIER_VALUE]='20ST')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'01/01/2020', 1904, 'RETR', 1910, 'VEST', 50, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 2, NULL, 7003,	'20ST')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'01/01/2020', 1904, 'RETR', 1910, 'ERLY', 50, 36, NULL, 'N', 'Y', NULL, NULL, NULL, NULL, 12, NULL, 7003,	'20ST')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'01/01/2020', 1904, 'RETR', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 17, NULL, 7003,	'20ST')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'01/01/2020', 1904, 'DETH', 1910, 'VEST', NULL, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 24, NULL, 7003,	'20ST')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(13,	'01/01/2020', 1904, 'DETH', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 39, NULL, 7003,	'20ST')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 3
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 3 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '97NG' AND [EFFECTIVE_DATE]  < '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '97NG' WHERE BENEFIT_PROVISION_ID = 3 AND [EFFECTIVE_DATE]  < '01/01/2020'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=3 AND [EFFECTIVE_DATE]='01/01/2020'AND [BENEFIT_TIER_VALUE]='20NG')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'01/01/2020', 1904, 'RETR', 1910, 'VEST', 50, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 4, NULL, 7003,	'20NG')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'01/01/2020', 1904, 'RETR', 1910, 'ERLY', 50, 36, NULL, 'N', 'Y', NULL, NULL, NULL, NULL, 14, NULL, 7003,	'20NG')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'01/01/2020', 1904, 'RETR', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 18, NULL, 7003,	'20NG')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'01/01/2020', 1904, 'DETH', 1910, 'VEST', NULL, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 26, NULL, 7003,	'20NG')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(3,	'01/01/2020', 1904, 'DETH', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 40, NULL, 7003,	'20NG')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 7
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 7 AND ISNULL(BENEFIT_TIER_VALUE, '') <> '97DC' AND [EFFECTIVE_DATE]  < '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '97DC' WHERE BENEFIT_PROVISION_ID = 7 AND [EFFECTIVE_DATE]  < '01/01/2020'
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 28
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID = 12 AND ISNULL(BENEFIT_TIER_VALUE,'') <> '20DC' AND [EFFECTIVE_DATE]  = '01/01/2020')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = '20DC' WHERE BENEFIT_PROVISION_ID = 12 AND [EFFECTIVE_DATE]  = '01/01/2020'
END
GO
--97DC
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=12 AND [EFFECTIVE_DATE] < '01/01/2020'AND [BENEFIT_TIER_VALUE]='97DC')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'01/01/1900', 1904, 'RETR', 1910, 'VEST', 55, 36, 85, 'Y', NULL, NULL, 'Y', NULL, NULL, 1, NULL, 7003,	'97DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'01/01/1900', 1904, 'RETR', 1910, 'ERLY', 55, NULL, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, 13, NULL, 7003,	'97DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'01/01/1900', 1904, 'RETR', 1910, 'NRML', 65, 36, 85, NULL, NULL, NULL, 'Y', NULL, NULL, 16, NULL, 7003,	'97DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'01/01/1900', 1904, 'DETH', 1910, 'VEST', NULL, 36, NULL, 'Y', NULL, NULL, 'Y', NULL, NULL, 23, NULL, 7003,	'97DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(12,	'01/01/1900', 1904, 'DETH', 1910, 'NRML', 65, 36, 85, 'N', 'Y', NULL, 'Y', NULL, NULL, 38, NULL, 7003,	'97DC')
END
GO
------------------------------------------------------------------------------------------------
-- Script to update benefit tier value

DROP TABLE IF EXISTS TEMP_PERSON_ACCOUNT_DETAILS

IF OBJECT_ID(N'dbo.TEMP_PERSON_ACCOUNT_DETAILS', N'U') IS NULL
BEGIN
	CREATE TABLE TEMP_PERSON_ACCOUNT_DETAILS(
	 [PERSON_DETAILS_ID] [INT] IDENTITY(1,1) NOT NULL,
	 [PERSON_ID] [INT] NULL,
	 [PLAN_ID] INT NULL,
	 [PERSON_ACCOUNT_ID] INT NULL,
	 [BENEFIT_TIER_VALUE] VARCHAR(8) NULL,
	 [IS_RECORD_PROCESSED] CHAR(1) NULL,
	) ON [PRIMARY]
END

INSERT INTO TEMP_PERSON_ACCOUNT_DETAILS ([PERSON_ID], [PLAN_ID], [PERSON_ACCOUNT_ID], [IS_RECORD_PROCESSED])
(SELECT  PA.PERSON_ID, PA.PLAN_ID, PA.PERSON_ACCOUNT_ID, 'N' FROM SGT_PERSON_ACCOUNT PA WITH(NOLOCK)
INNER JOIN SGT_PERSON_ACCOUNT_RETIREMENT PAR WITH(NOLOCK) ON PA.PERSON_ACCOUNT_ID = PAR.PERSON_ACCOUNT_ID
WHERE PA.PLAN_ID IN (2,20,27,3,29,7,28,1) AND (PA.PLAN_PARTICIPATION_STATUS_VALUE LIKE 'ENL%' OR PA.PLAN_PARTICIPATION_STATUS_VALUE LIKE 'SUS%')
AND ISNULL(BENEFIT_TIER_VALUE, '') = '')

BEGIN TRY
-------- Iterating one by one record from table --------------
DECLARE @RowCnt INT;
DECLARE @RowNum INT = 1;
DECLARE @PERSON_ID INT;
DECLARE @PLAN_ID INT;
DECLARE @PERSON_ACCOUNT_ID INT;
DECLARE @PIR VARCHAR(10) = 'PIR 26544'

BEGIN TRANSACTION

SELECT @RowCnt = COUNT(*) FROM TEMP_PERSON_ACCOUNT_DETAILS WITH(NOLOCK) WHERE ISNULL(IS_RECORD_PROCESSED,'N') <> 'Y';

DROP TABLE IF EXISTS #TEMPPERSONDETAILSNOTPROCESSED

SELECT [PERSON_DETAILS_ID], 
	   [PERSON_ID], 
	   [PLAN_ID],
	   [PERSON_ACCOUNT_ID]
INTO	#TEMPPERSONDETAILSNOTPROCESSED
FROM TEMP_PERSON_ACCOUNT_DETAILS WITH(NOLOCK) WHERE ISNULL(IS_RECORD_PROCESSED,'N') <> 'Y'
 
WHILE @RowNum <= @RowCnt
BEGIN

SELECT @PERSON_ID = [PERSON_ID], 
	  @PLAN_ID = [PLAN_ID],
	  @PERSON_ACCOUNT_ID = [PERSON_ACCOUNT_ID]
FROM 
(
    SELECT ROW_NUMBER() OVER (ORDER BY [PERSON_DETAILS_ID]) AS ROWNUM, *
    FROM #TEMPPERSONDETAILSNOTPROCESSED
) T2
WHERE ROWNUM = @RowNum

--SELECT @PERSON_ID= [PERSON_ID], @PLAN_ID = [PLAN_ID] FROM TEMP_PERSON_ACCOUNT_DETAILS WHERE PERSON_ACCOUNT_ID = @PERSON_ACCOUNT_ID

PRINT 'Processing for Person ID ' + CAST(@PERSON_ID AS VARCHAR(10)) + CAST(@PLAN_ID AS VARCHAR(10))

DECLARE @PLANSTARTDATE DATETIME
SELECT @PLANSTARTDATE = [START_DATE] FROM SGT_PERSON_ACCOUNT WITH(NOLOCK) WHERE PERSON_ACCOUNT_ID = @PERSON_ACCOUNT_ID

DECLARE @PRIORENROLLEDDATE DATETIME

SELECT @PRIORENROLLEDDATE = MIN(PARH.[START_DATE]) FROM SGT_PERSON_ACCOUNT_RETIREMENT_HISTORY PARH WITH(NOLOCK)
INNER JOIN SGT_PERSON_ACCOUNT PA WITH(NOLOCK) ON PA.PERSON_ACCOUNT_ID = PARH.PERSON_ACCOUNT_ID
WHERE PLAN_ID IN (1,27,2,20,3,26,29,5) AND PERSON_ID = @PERSON_ID AND PARH.PLAN_PARTICIPATION_STATUS_VALUE ='ENL1' 
AND PARH.[START_DATE] <> ISNULL(PARH.END_DATE, '99991231')


IF @PRIORENROLLEDDATE IS NULL OR @PRIORENROLLEDDATE > @PLANSTARTDATE
BEGIN
SET @PRIORENROLLEDDATE = @PLANSTARTDATE
END

IF @PRIORENROLLEDDATE IS NULL
BEGIN
SELECT @PRIORENROLLEDDATE = [START_DATE] FROM SGT_PERSON_ACCOUNT PARH WITH(NOLOCK) WHERE PERSON_ACCOUNT_ID = @PERSON_ACCOUNT_ID
END

DECLARE @BENEFITTIERVALUE VARCHAR(4) = NULL

IF @PLAN_ID = 27
BEGIN
SELECT TOP 1 @BENEFITTIERVALUE = CODE_VALUE FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID=7003 AND DATA2 = @PLAN_ID ORDER BY DATA1 DESC
END
ELSE 
BEGIN
SELECT TOP 1 @BENEFITTIERVALUE = CODE_VALUE FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID=7003 AND DATA1 <= @PRIORENROLLEDDATE AND DATA2 = @PLAN_ID ORDER BY DATA1 DESC
END

UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = @BENEFITTIERVALUE, MODIFIED_BY = @PIR, MODIFIED_DATE = GETDATE() WHERE PERSON_ACCOUNT_ID = @PERSON_ACCOUNT_ID
 
-- UPDATING TEMP TABLE FOR PA IDs
UPDATE TEMP_PERSON_ACCOUNT_DETAILS SET [IS_RECORD_PROCESSED] = 'Y', [BENEFIT_TIER_VALUE] = @BENEFITTIERVALUE  WHERE [PERSON_ACCOUNT_ID] = @PERSON_ACCOUNT_ID
SET @RowNum += 1
END
COMMIT

END TRY

BEGIN CATCH
IF @@TRANCOUNT > 0 
BEGIN
ROLLBACK TRANSACTION
SELECT ERROR_NUMBER() AS ErrorNumber;
SELECT ERROR_MESSAGE() AS ErrorMessage;
END
END CATCH

DROP TABLE IF EXISTS TEMP_PERSON_ACCOUNT_DETAILS



--------------Created By: sanket 
--------------Purpose   : PIR 26305
IF NOT EXISTS (SELECT * FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10508)
INSERT INTO [DBO].[SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],
[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10508,'Please update Contact status to Inactive with Affiliated Organizations first.',16,'E',NULL,NULL,'PIR 26305',GETDATE(),'PIR 26305',GETDATE(),0)
GO

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID = 10509)
INSERT INTO [DBO].[SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY],
[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
VALUES (10509,'Contact is Inactive. Update Contact status before activating with Affiliated Organizations.',16,'E',NULL,NULL,'PIR 26305',GETDATE(),'PIR 26305',GETDATE(),0)
GO