/********************Purpose: PIR 26896******************************
*********************Created By: Bharat ********************************/
IF NOT EXISTS (SELECT * FROM [dbo].SGS_BATCH_SCHEDULE WHERE BATCH_SCHEDULE_ID = 183)
	INSERT INTO [DBO].[SGS_BATCH_SCHEDULE] ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS],
			 [FREQUENCY_IN_MONTHS], [NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG],[REQUIRES_TRANSACTION_FLAG],[EMAIL_NOTIFICATION],
			 [ORDER_NO],[CUTOFF_START],[CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
	VALUES(183, 1042, 'Payment - Pull Check Update Batch', NULL,1,
			NULL,GETDATE(),NULL,'Y','N',NULL,
			NULL,NULL,NULL, 'PIR 26896', getdate(), 'PIR 26896', getdate(),	0)
--------------Created By: Sanket
--------------Purpose   : PIR 27084

IF NOT EXISTS (SELECT * FROM [dbo].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID] =10 and [ELIGIBILITY_TYPE_VALUE]='ERLY' and [SERVICE]=120 )
INSERT INTO [dbo].[SGT_BENEFIT_PROVISION_ELIGIBILITY] ([BENEFIT_PROVISION_ID],[EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE],  
[AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG],[CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG],[AGE_WHILE_EMPLOYED_FLAG],[GROUPING_LOGIC],[OTHER_LOGIC_FLAG],[ELIGIBILITY_GROUP_CODE],[MINIMUM_AGE]
,[BENEFIT_TIER_ID],[BENEFIT_TIER_VALUE])
VALUES (10,'2023-08-01', 1904, 'RETR', 1910, 'ERLY',50,120,Null,'N','Y',Null,Null,Null,Null, 12, Null, 7003, '23BT')