/********************Purpose: PIR 25920******************************
*********************Created By: Abhijeet Malwadkar********************************
********************Create tables  and columns  ********************************************/
/*---------------------------//----PIR 25920 DC 2025 Changes-----//-------------------------------------------*/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_WSS_PERSON_ACCOUNT_ENROLLMENT_REQUEST'))
BEGIN
    ALTER TABLE SGT_WSS_PERSON_ACCOUNT_ENROLLMENT_REQUEST
	ADD ADDL_EE_CONTRIBUTION_PERCENT INT NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT
	ADD ADDL_EE_CONTRIBUTION_PERCENT INT NULL 
END
GO
--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'IS_APPLY_EMPLOYER_MATCHING_CONTRIBUTION' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_DEFERRED_COMP_PROVIDER'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_DEFERRED_COMP_PROVIDER
	ADD IS_APPLY_EMPLOYER_MATCHING_CONTRIBUTION char(1) NULL 
END
GO
--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_PRETAX_ADDL' AND Object_ID = Object_ID(N'dbo.SGT_PLAN_RETIREMENT_RATE'))
BEGIN
    ALTER TABLE SGT_PLAN_RETIREMENT_RATE
	ADD EE_PRETAX_ADDL DECIMAL(13,4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_POST_TAX_ADDL' AND Object_ID = Object_ID(N'dbo.SGT_PLAN_RETIREMENT_RATE'))
BEGIN
    ALTER TABLE SGT_PLAN_RETIREMENT_RATE
	ADD EE_POST_TAX_ADDL DECIMAL(13,4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH' AND Object_ID = Object_ID(N'dbo.SGT_PLAN_RETIREMENT_RATE'))
BEGIN
    ALTER TABLE SGT_PLAN_RETIREMENT_RATE
	ADD ER_PRETAX_MATCH DECIMAL(13,4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADEC' AND Object_ID = Object_ID(N'dbo.SGT_PLAN_RETIREMENT_RATE'))
BEGIN
    ALTER TABLE SGT_PLAN_RETIREMENT_RATE
	ADD ADEC DECIMAL(13,4) NULL 
END
GO

--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TOTAL_ADEC_AMOUNT_REPORTED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_HEADER'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_HEADER
	ADD TOTAL_ADEC_AMOUNT_REPORTED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TOTAL_ADEC_AMOUNT_CALCULATED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_HEADER'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_HEADER
	ADD TOTAL_ADEC_AMOUNT_CALCULATED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TOTAL_ADEC_AMOUNT_ORIGINAL' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_HEADER'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_HEADER
	ADD TOTAL_ADEC_AMOUNT_ORIGINAL DECIMAL(11,2) NULL 
END
GO
--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_PRETAX_ADDL_ORIGINAL' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_PRETAX_ADDL_ORIGINAL DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_POST_TAX_ADDL_ORIGINAL' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_POST_TAX_ADDL_ORIGINAL DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH_ORIGINAL' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ER_PRETAX_MATCH_ORIGINAL DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADEC_ORIGINAL' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ADEC_ORIGINAL DECIMAL(11,2) NULL 
END
GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_PRETAX_ADDL_REPORTED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_PRETAX_ADDL_REPORTED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_POST_TAX_ADDL_REPORTED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_POST_TAX_ADDL_REPORTED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH_REPORTED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ER_PRETAX_MATCH_REPORTED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADEC_REPORTED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ADEC_REPORTED DECIMAL(11,2) NULL 
END
GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_PRETAX_ADDL_CALCULATED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_PRETAX_ADDL_CALCULATED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_POST_TAX_ADDL_CALCULATED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD EE_POST_TAX_ADDL_CALCULATED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH_CALCULATED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ER_PRETAX_MATCH_CALCULATED DECIMAL(11,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADEC_CALCULATED' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ADEC_CALCULATED DECIMAL(11,2) NULL 
END
GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ELIGIBLE_WAGES_DEFCOMP' AND Object_ID = Object_ID(N'dbo.SGT_EMPLOYER_PAYROLL_DETAIL'))
BEGIN
    ALTER TABLE SGT_EMPLOYER_PAYROLL_DETAIL
	ADD ELIGIBLE_WAGES_DEFCOMP DECIMAL(11,2) NULL 
END
GO


--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_PRETAX_ADDL_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
	ADD EE_PRETAX_ADDL_AMOUNT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EE_POST_TAX_ADDL_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
	ADD EE_POST_TAX_ADDL_AMOUNT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
	ADD ER_PRETAX_MATCH_AMOUNT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADEC_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_CONTRIBUTION
	ADD ADEC_AMOUNT DECIMAL(13,2) NULL 
END
GO

--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EMPLOYER_MATCH_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_DEFERRED_COMP_CONTRIBUTION'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_DEFERRED_COMP_CONTRIBUTION
	ADD EMPLOYER_MATCH_AMOUNT  DECIMAL(13,2) NULL 
END
GO

--------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ER_PRETAX_MATCH' AND Object_ID = Object_ID(N'dbo.SGT_PROVIDER_REPORT_DATA_DEFF_COMP'))
BEGIN
    ALTER TABLE SGT_PROVIDER_REPORT_DATA_DEFF_COMP
	ADD ER_PRETAX_MATCH DECIMAL(11,2) NULL 
END
GO
--------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT_RETIREMENT_HISTORY'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT_RETIREMENT_HISTORY
	ADD ADDL_EE_CONTRIBUTION_PERCENT INT NULL 
END
GO

-----------------------------------------------------------------------------------------------------------------------------------
--Added new column EMPLOYEE_EMPLOYER_MATCH in Enrollment Data, 

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EMPLOYEE_EMPLOYER_MATCH' AND Object_ID = Object_ID(N'dbo.SGT_ENROLLMENT_DATA'))
BEGIN
    ALTER TABLE [DBO].[SGT_ENROLLMENT_DATA]
	ADD EMPLOYEE_EMPLOYER_MATCH VARCHAR(50) NULL 
END
GO
--Added column ADDL_EE_CONTRIBUTION_PERCENT in SGT_PEOPLESOFT_PLAN_CROSS_REF

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_PEOPLESOFT_PLAN_CROSS_REF'))
BEGIN
    ALTER TABLE [DBO].[SGT_PEOPLESOFT_PLAN_CROSS_REF]
	ADD ADDL_EE_CONTRIBUTION_PERCENT INT NULL 
END
GO

/*---------------------------//----End Of PIR 25920 DC 2025 Changes--------------//-------------------------------------------*/
/********************Purpose: PIR 25920******************************
*********************Created By: Abhijeet Malwadkar********************************
********************Create tables  and columns  ********************************************/
/*---------------------------//----PIR 25920 DC 2025 Changes-----//-------------------------------------------*/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'CALCULATED_ACTUARIAL_VALUE' AND Object_ID = Object_ID(N'dbo.SGT_BENEFIT_REFUND_CALCULATION'))
BEGIN
    ALTER TABLE SGT_BENEFIT_REFUND_CALCULATION
	ADD CALCULATED_ACTUARIAL_VALUE  DECIMAL(13,2) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'DB_ACCOUNT_BALANCE' AND Object_ID = Object_ID(N'dbo.SGT_BENEFIT_REFUND_CALCULATION'))
BEGIN
    ALTER TABLE SGT_BENEFIT_REFUND_CALCULATION
	ADD DB_ACCOUNT_BALANCE  DECIMAL(13,2) NULL
END
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ACCRUED_BENEFIT_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_BENEFIT_REFUND_CALCULATION'))
BEGIN
    ALTER TABLE SGT_BENEFIT_REFUND_CALCULATION
	ADD ACCRUED_BENEFIT_AMOUNT  DECIMAL(13,2) NULL
END
GO

