/********************Purpose: PIR 25920******************************
*********************Created By: Abhijeet Malwadkar********************************/
/*---------------------------//----PIR 25920 DC 2025 Changes-----//-------------------------------------------*/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT_TEMP' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT
	ADD ADDL_EE_CONTRIBUTION_PERCENT_TEMP INT NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT_END_DATE' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT
	ADD ADDL_EE_CONTRIBUTION_PERCENT_END_DATE DATETIME NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT_TEMP_END_DATE' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_PERSON_ACCOUNT
	ADD ADDL_EE_CONTRIBUTION_PERCENT_TEMP_END_DATE DATETIME NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'ADDL_EE_CONTRIBUTION_PERCENT_TEMP' AND Object_ID = Object_ID(N'dbo.SGT_WSS_PERSON_ACCOUNT_ENROLLMENT_REQUEST'))
BEGIN
    ALTER TABLE SGT_WSS_PERSON_ACCOUNT_ENROLLMENT_REQUEST
	ADD ADDL_EE_CONTRIBUTION_PERCENT_TEMP INT NULL 
END
GO
/*---------------------------//----PIR 25920 DC 2025 Changes-----//-------------------------------------------*/

/********************Purpose: PIR  ******************************
*********************Created By: Vidya Fulsoundar********************************
*********************Comments: Death BPM-Automation *****************/ 
/*
	SGT_COR_DEATH_NOTIFICATION
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_DEATH_NOTIFICATION' AND [type] = 'U')
BEGIN
CREATE TABLE DBO.SGT_COR_DEATH_NOTIFICATION
(
	COR_DEATH_NOTIFICATION_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PERSON_ID INT,
	FIRST_NAME VARCHAR(3000),
	MIDDLE_NAME VARCHAR(3000),
	LAST_NAME VARCHAR(3000),
	IS_ACTIVE CHAR(1),
	IS_RETIREE CHAR(1),
	IS_RETIREMENT_PLAN CHAR(1),
	IS_INSURANCE_PLAN CHAR(1),
)
END
/*
	SGT_COR_RETIREMENT
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_RETIREMENT' AND [type] = 'U')
BEGIN

CREATE TABLE DBO.SGT_COR_RETIREMENT
(
	COR_RETIREMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PERSON_ACCOUNT_ID INT,	
	IS_VESTED CHAR(1),
	IS_DB_RETIREMENT CHAR(1),
	IS_DC_RETIREMENT CHAR(1),
)
END
/*
	SGT_COR_INSURANCE
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_INSURANCE' AND [type] = 'U')
BEGIN

CREATE TABLE DBO.SGT_COR_INSURANCE
(
	COR_INSURANCE_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PERSON_ACCOUNT_ID INT,	
	PERSON_DEPENDENT_ID INT,
)
END
/*
	SGT_COR_PAYEE_ACCOUNT
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_PAYEE_ACCOUNT' AND [type] = 'U')
BEGIN
CREATE TABLE DBO.SGT_COR_PAYEE_ACCOUNT
(
	COR_PAYEE_ACCOUNT_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PAYEE_ACCOUNT_ID INT,	
)
END
/*
	SGT_COR_BENE_DEP_TO
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_BENE_DEP_TO' AND [type] = 'U')
BEGIN
CREATE TABLE DBO.SGT_COR_BENE_DEP_TO
(
	COR_BENE_DEP_TO_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PERSON_ACCOUNT_ID INT,	
	DEPENDENT_TO CHAR(1),	
	BENEFICIARY_TO CHAR(1),
	PERSON_ACCOUNT_BENEFICIARY_ID INT,
	PERSON_ACCOUNT_DEPENDENT_ID INT,
	BENEFICIARY_ID INT,
	PERSON_DEPENDENT_ID INT,
	BENEFICIARY_RELATIONSHIP VARCHAR(200),
	DEPENDENT_RELATIONSHIP VARCHAR(200),
)
END
/*
	SGT_COR_BENE_DEP
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_COR_BENE_DEP' AND [type] = 'U')
BEGIN
CREATE TABLE DBO.SGT_COR_BENE_DEP
(
	COR_BENE_DEP_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEATH_NOTIFICATION_ID INT, 
	PERSON_ID INT,	
	ORG_ID INT,
	PERSON_DEPENDENT_ID INT,
	BENEFICIARY_ID INT,
	PERSON_ACCOUNT_ID INT,	
	BENEFICIARY_RELATIONSHIP VARCHAR(200),
	DEPENDENT_RELATIONSHIP VARCHAR(200),
	FAMILY_RELATIONSHIP VARCHAR(200),
	ACCOUNT_RELATIONSHIP VARCHAR(200),
)
END
/*
	SGT_CUSTOM_CORRESPONDENCE
*/
IF NOT EXISTS(SELECT 1 FROM sys.OBJECTS
          WHERE [Name] = N'SGT_CUSTOM_CORRESPONDENCE' AND [type] = 'U')
BEGIN
CREATE TABLE DBO.SGT_CUSTOM_CORRESPONDENCE
(
	COR_ID INT IDENTITY(1,1) PRIMARY KEY
)
END