/********************Purpose: PIR 26356/26428******************************
*********************Created By: Bharat Reddy********************************
*********************Comments: Update Auto_post flag for Flex New Hire change reason to Y************/

IF EXISTS (SELECT 1 FROM [DBO].[SGT_WSS_AUTO_POSTING_CROSS_REF] WHERE [PLAN_ID] = 18 AND [CHANGE_REASON_VALUE] = 'NEWH')
BEGIN
	UPDATE [DBO].[SGT_WSS_AUTO_POSTING_CROSS_REF] SET [AUTO_POST_FLAG] = 'Y' WHERE [PLAN_ID] = 18 AND [CHANGE_REASON_VALUE] = 'NEWH'
END
GO

/*********************Comments: Update Error message severity value from W to E************/

IF EXISTS (SELECT 1 FROM [DBO].[SGS_MESSAGES] WHERE [MESSAGE_ID] = 6665)
BEGIN
	UPDATE [DBO].[SGS_MESSAGES] SET [SEVERITY_VALUE] = 'E' WHERE [MESSAGE_ID] = 6665
END
GO

/*********************Comments: New acknowledgement text for Flex Intro Screen************/

IF NOT EXISTS (SELECT 1 FROM [DBO].SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'FLIN' AND DISPLAY_SEQUENCE = 1)
BEGIN
	INSERT INTO [DBO].[SGT_WSS_ACKNOWLEDGEMENT](EFFECTIVE_DATE, SCREEN_STEP_ID, SCREEN_STEP_VALUE, DISPLAY_SEQUENCE, ACKNOWLEDGEMENT_TEXT,
												SHOW_CHECK_BOX_FLAG, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	VALUES ('2025-04-01', 6000, 'FLIN', 1, 'If you previously participated in the NDPERS flexcomp (medical FSA, dependent care FSA, or premium conversion) in this calendar year, you are not eligible to participate for the remainder of this calendar year.',
			 'N', 'PIR 26356/26428', GETDATE(), 'PIR 26356/26428', GETDATE(),0)
END
GO

/********************Purpose: PIR 26948******************************
*********************Created By: Bharat Reddy********************************/

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 1)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Main Defined Benefit' WHERE PLAN_ID = 1
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 2)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Public Safety with Prior Service Defined Benefit' WHERE PLAN_ID = 2
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 3)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'National Guard Defined Benefit' WHERE PLAN_ID = 3
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 4)
BEGIN
update SGT_WELCOME_ORG_BENEFIT_PLAN set PLAN_NAME = 'Highway Patrol Defined Benefit' where PLAN_ID = 4
END
GO
IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 5)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Judges Defined Benefit' WHERE PLAN_ID = 5
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 6)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Job Service Defined Benefit' WHERE PLAN_ID = 6
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 7)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Defined Contribution' WHERE PLAN_ID = 7
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 8)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Other 457/403(b)' WHERE PLAN_ID = 8
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 9)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Medicare Part D' WHERE PLAN_ID = 9
END
GO
IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 12)
BEGIN
update SGT_WELCOME_ORG_BENEFIT_PLAN set PLAN_NAME = 'Health Insurance' where PLAN_ID = 12
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 13)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Life Insurance' WHERE PLAN_ID = 13
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 14)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Employee Assistance Program' WHERE PLAN_ID = 14
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 15)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Long Term Care Insurance' WHERE PLAN_ID = 15
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 16)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Dental Insurance' WHERE PLAN_ID = 16
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 17)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Vision Insurance' WHERE PLAN_ID = 17
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 18)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'FlexComp Plan' WHERE PLAN_ID = 18
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 19)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'NDPERS 457 Deferred Compensation' WHERE PLAN_ID = 19
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 20)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Public Safety without Prior Service Defined Benefit' WHERE PLAN_ID = 20
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 21)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Oasis' WHERE PLAN_ID = 21
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 22)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Health Maintenance Organization (HMO)' WHERE PLAN_ID = 22
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 23)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Job Service with Third Party Payor Defined Benefit' WHERE PLAN_ID = 23
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 24)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Prior Judges Defined Benefit' WHERE PLAN_ID = 24
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 25)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Prior Service  Defined Benefit' WHERE PLAN_ID = 25
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 26)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'BCI Law Enforcement Defined Benefit' WHERE PLAN_ID = 26
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 27)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Main 2020 Defined Benefit' WHERE PLAN_ID = 27
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 28)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Defined Contribution 2020' WHERE PLAN_ID = 28
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 29)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'State Public Safety Defined Benefit' WHERE PLAN_ID = 29
END
GO

IF EXISTS (SELECT 1 FROM dbo.[SGT_WELCOME_ORG_BENEFIT_PLAN] WHERE PLAN_ID = 30)
BEGIN
	UPDATE SGT_WELCOME_ORG_BENEFIT_PLAN SET PLAN_NAME = 'Defined Contribution 2025' WHERE PLAN_ID = 30
END
GO


/********************Purpose: PIR 18493******************************
*********************Created By: Sanket Chougale********************************/			
IF EXISTS (SELECT 1 FROM dbo.[SGT_WSS_ACKNOWLEDGEMENT] WHERE ACKNOWLEDGEMENT_ID = 154)
BEGIN
UPDATE SGT_WSS_ACKNOWLEDGEMENT SET ACKNOWLEDGEMENT_TEXT = 
'You will receive a packet from <b>{0}</b>that will include details on converting your life insurance to an individual policy or for portability of your existing term life insurance policy.'
WHERE ACKNOWLEDGEMENT_ID = 154
END
GO

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_MESSAGES] WHERE [MESSAGE_ID] =10529 )
INSERT INTO [dbo].[SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS],  
[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES (10529,'Record deleted successfully.', 16, 'I', null, null,'PIR 18493', getdate(), 'PIR 18493', getdate(), '0')
