--------------Created By: Surendra
--------------Purpose   : 1099R Issues
IF EXISTS (SELECT 1 FROM SGT_PAYMENT_ITEM_TYPE WHERE PAYMENT_ITEM_TYPE_ID in (24,26) and TAXABLE_ITEM_FLAG = 'N')
BEGIN
	UPDATE SGT_PAYMENT_ITEM_TYPE SET TAXABLE_ITEM_FLAG = 'Y' WHERE PAYMENT_ITEM_TYPE_ID IN (24,26)
END
GO


--------------Created By: Sarvesh
--------------PIR - 26456
IF NOT EXISTS (SELECT * FROM [dbo].[SGS_FILE] WHERE [FILE_ID] = 106 AND [DESCRIPTION] = 'Empower 457 Enrollment Outbound')
BEGIN
SET IDENTITY_INSERT[SGS_FILE] ON;
INSERT INTO [dbo].[SGS_FILE] ([FILE_ID],[DESCRIPTION], [DELIMITED_BY], [TRANSACTION_CODE_POS], [TRANSACTION_CODE_LENGTH], [TRANSACTION_CODE_VALUE],
 [HEADER_GROUP_POS], [HEADER_GROUP_LENGTH], [XML_LAYOUT_FILE], [INBOUND_MASK], [MAILBOX_PATH_CODE], [STAGING_PATH_CODE], [ERROR_PATH_CODE],	
 [PROCESS_PATH_CODE], [FILE_STATUS_ID], [FILE_STATUS_VALUE], [INBOUND_OUTBOUND_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE],
 [UPDATE_SEQ], [EMAIL_NOTIFICATION], [OTHER_PARAMETERS], [GROUP_PROCESS_FLAG]) 
VALUES (106,'Empower 457 Enrollment Outbound', NULL, NULL, NULL, 1, 0, 0, 'fleEmpower457EnrollmentOut', '*.*', 'PAOut', 'PAStaging', 'PAError', 'PAOutProc', 26, 'A', 'O','PIR 26456', getdate(), 'PIR 26456', getdate(), '0', NULL, NULL, 'N')
SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_FILE] WHERE [FILE_ID] = 107 AND [DESCRIPTION] = 'Empower DC Enrollment Outbound')
BEGIN
SET IDENTITY_INSERT[SGS_FILE] ON;
INSERT INTO [dbo].[SGS_FILE] ([FILE_ID],[DESCRIPTION], [DELIMITED_BY], [TRANSACTION_CODE_POS], [TRANSACTION_CODE_LENGTH], [TRANSACTION_CODE_VALUE],
 [HEADER_GROUP_POS], [HEADER_GROUP_LENGTH], [XML_LAYOUT_FILE], [INBOUND_MASK], [MAILBOX_PATH_CODE], [STAGING_PATH_CODE], [ERROR_PATH_CODE],	
 [PROCESS_PATH_CODE], [FILE_STATUS_ID], [FILE_STATUS_VALUE], [INBOUND_OUTBOUND_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE],
 [UPDATE_SEQ], [EMAIL_NOTIFICATION], [OTHER_PARAMETERS], [GROUP_PROCESS_FLAG]) 
VALUES (107,'Empower DC Enrollment Outbound', NULL, NULL, NULL, 1, 0, 0, 'fleEmpowerDCEnrollmentOut', '*.*', 'PAOut', 'PAStaging', 'PAError', 'PAOutProc', 26, 'A', 'O','PIR 26456', getdate(), 'PIR 26456', getdate(), '0', NULL, NULL, 'N')
SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO

IF NOT EXISTS (SELECT * FROM [dbo].SGS_BATCH_SCHEDULE WHERE [BATCH_SCHEDULE_ID]=165 AND STEP_NAME = 'Empower 457 Enrollment Outbound')
INSERT INTO [DBO].[SGS_BATCH_SCHEDULE] ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS], [FREQUENCY_IN_MONTHS], [NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG],[REQUIRES_TRANSACTION_FLAG],[EMAIL_NOTIFICATION],[ORDER_NO],[CUTOFF_START],[CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(165, 1021, 'Empower 457 Enrollment Outbound', NULL, NULL, NULL, '2024-01-06 00:00:00.000', NULL, 'Y', 'Y', NULL, NULL, NULL, NULL, 'PIR 26456', getdate(), 'PIR 26456', getdate(), 0)
GO

IF NOT EXISTS (SELECT * FROM [dbo].SGS_BATCH_SCHEDULE WHERE [BATCH_SCHEDULE_ID]=166 AND STEP_NAME = 'Empower DC Enrollment Outbound')
INSERT INTO [DBO].[SGS_BATCH_SCHEDULE] ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS], [FREQUENCY_IN_MONTHS], [NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG],[REQUIRES_TRANSACTION_FLAG],[EMAIL_NOTIFICATION],[ORDER_NO],[CUTOFF_START],[CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(166, 1022, 'Empower DC Enrollment Outbound', NULL,NULL,NULL,'2024-01-06 00:00:00.000',NULL,'Y','Y',NULL,NULL,NULL,NULL,	'PIR 26456',	getdate(),	'PIR 26456',	getdate(),	0)
GO


--------------Created By: Sanket Chougale
--------------Purpose   : PIR 26471
--------------Date      : 04/26/2024
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE [CODE_ID] = 52 AND CODE_VALUE = 'CPOR')
BEGIN
INSERT INTO [DBO].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER],
							[LEGACY_CODE_ID], [CREATED_BY],	[CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(52, 'CPOR', 'Companion Plan Organization', 'Empower', '8668164400', 'https://www.empower.com/', 'These values are used to update correspondence with the Companion Plan provider and phone number. No dashes allowed in the phone number.', NULL,
         NULL, NULL, NULL, 'PIR 26471', GETDATE(), 'PIR 26471', GETDATE(), 0 )
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE [CODE_ID] = 52 AND CODE_VALUE = 'DCOR')
BEGIN
INSERT INTO [DBO].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER],
							[LEGACY_CODE_ID], [CREATED_BY],	[CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(52, 'DCOR', 'Defined Contribution Organization', 'Empower', '8668164400', 'https://www.empower.com/', 'These values are used to update correspondence with the Defined Contribution provider and phone number. No dashes allowed in the phone number.', NULL,
         NULL, NULL, NULL, 'PIR 26471', GETDATE(), 'PIR 26471', GETDATE(), 0 )
END
GO
