/*
	TAX	REF CONFIGURATION
*/
IF EXISTS(SELECT * FROM sys.OBJECTS
          WHERE [Name] = N'SGT_TAX_REF_CONFIG' AND [type] = 'U')
BEGIN
DROP TABLE SGT_TAX_REF_CONFIG
END
CREATE TABLE SGT_TAX_REF_CONFIG
(
	TAX_REF_ID INT IDENTITY(1,1) PRIMARY KEY,
	TAX_IDENTIFIER_ID INT, 
	TAX_IDENTIFIER_VALUE VARCHAR(4),
	TAX_REF VARCHAR(4) NOT NULL,
	EFFECTIVE_DATE DATETIME,
	NO_OF_PERIODS INT,
	ONEG_AMT_SINGLE DECIMAL(13,2),
	ONEG_AMT_MARRIED DECIMAL(13,2),
	ONEG_AMT_HOHH DECIMAL(13,2),
	DEFAULT_ALLOWANCE_AMT DECIMAL(13,2),
	TOTAL_AMT_SINGLE DECIMAL(13,2),
	TOTAL_AMT_MARRIED DECIMAL(13,2),
	CHILD_AGE INT,
	CHILD_AGE_BY_AMT DECIMAL(13,2),
	OTHER_DEPD_AMT DECIMAL(13,2),
	THREE_FIRST_LINE VARCHAR(100),
	THREE_SECOND_LINE VARCHAR(100),
	THREE_THIRD_LINE VARCHAR(100)
)


/*
	REFUND FEDERAL TAX SCHEMA CHANGES - REFUND, RMD, PLSO, ROLLOVER
*/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'IS_RMD' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_FLAT_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_FLAT_TAX_RATE
	ADD IS_RMD CHAR(1) NULL 
END

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'MIN_TAX_PERCENTAGE' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_FLAT_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_FLAT_TAX_RATE
	ADD MIN_TAX_PERCENTAGE DECIMAL(13,2) NULL 
END

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'MAX_TAX_PERCENTAGE' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_FLAT_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_FLAT_TAX_RATE
	ADD MAX_TAX_PERCENTAGE DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TAX_REF' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_FLAT_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_FLAT_TAX_RATE
	ADD TAX_REF VARCHAR(4) NULL 
END
GO
/*
	SGT_FED_STATE_TAX_RATE
*/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_ID' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_TAX_RATE
	ADD FILING_STATUS_ID INT NULL
END
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_VALUE' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_TAX_RATE
	ADD FILING_STATUS_VALUE VARCHAR(4) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TAX_REF' AND Object_ID = Object_ID(N'dbo.SGT_FED_STATE_TAX_RATE'))
BEGIN
    ALTER TABLE SGT_FED_STATE_TAX_RATE
	ADD TAX_REF VARCHAR(4) NULL 
END
GO

/*
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING SCHEMA CHANGES
*/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'REFUND_FED_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD REFUND_FED_PERCENT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'REFUND_STATE_AMT' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD REFUND_STATE_AMT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TAX_REF' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD TAX_REF VARCHAR(4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_ID' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD FILING_STATUS_ID INT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_VALUE' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD FILING_STATUS_VALUE VARCHAR(4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_i' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD TWO_b_i DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_ii' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD TWO_b_ii DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_iii' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD TWO_b_iii DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_1' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD THREE_1 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_2' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD THREE_2 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_3' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD THREE_3 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_TOTAL' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD THREE_TOTAL DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_a' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD FOUR_a DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_b' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD FOUR_b DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_c' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD FOUR_c DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'NO_FED_WITHHOLDING' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD NO_FED_WITHHOLDING CHAR(1) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'STATE_FLAT_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING
	ADD STATE_FLAT_AMOUNT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns 
          WHERE [Name] = N'STATE_TAX_FLAT_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_PAYMENT_HISTORY_HEADER'))
BEGIN
    ALTER TABLE SGT_PAYMENT_HISTORY_HEADER
	ADD STATE_TAX_FLAT_AMOUNT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FED_FILING_STATUS_ID' AND Object_ID = Object_ID(N'dbo.SGT_PAYMENT_HISTORY_HEADER'))
BEGIN
    ALTER TABLE SGT_PAYMENT_HISTORY_HEADER
	ADD FED_FILING_STATUS_ID INT NULL
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FED_FILING_STATUS_VALUE' AND Object_ID = Object_ID(N'dbo.SGT_PAYMENT_HISTORY_HEADER'))
BEGIN
    ALTER TABLE SGT_PAYMENT_HISTORY_HEADER
	ADD FED_FILING_STATUS_VALUE VARCHAR(4) NULL
END
GO



