/********************Purpose: Adhoc - ACH Pull and New Hire Automation******************************
*********************Created By: Nikhil********************************
*********************Comments: *****************/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_MEMBER_RECORD_REQUEST' AND COLUMN_NAME = 'BPM_INITIATED')
BEGIN
ALTER TABLE SGT_WSS_MEMBER_RECORD_REQUEST
ADD BPM_INITIATED VARCHAR(1) DEFAULT 'N'
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_PERSON_EMPLOYMENT_DETAIL' AND COLUMN_NAME IN ('RETR_STATUS', 'EAP_STATUS', 'LIFE_STATUS'))
BEGIN
ALTER TABLE SGT_WSS_PERSON_EMPLOYMENT_DETAIL
ADD RETR_STATUS VARCHAR(1) DEFAULT 'N', EAP_STATUS VARCHAR(1) DEFAULT 'N', LIFE_STATUS VARCHAR(1) DEFAULT 'N'
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_MEMBER_RECORD_REQUEST' AND COLUMN_NAME = 'LAST_MONTH_ON_EMPLOYER_BILLING')
BEGIN
EXEC SP_RENAME 'SGT_WSS_MEMBER_RECORD_REQUEST.LAST_MONTH_ON_EMPLOYER_BILLING', 'FIRST_MONTH_FOR_RETIREMENT_CONTRIBUTION', 'COLUMN'
END
GO
