/********************Purpose: PIR 25920******************************
*********************Created By: Abhijeet Malwadkar********************************
********************Create tables  and columns  ********************************************/
/*---------------------------//----PIR 25920 DC 2025 Changes-----//-------------------------------------------*/


/*----------------------------------------Iserting data into SGT_BENEFIT_PROVISION Table-----------------------------*/

IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_PROVISION PL WHERE SHORT_DECRIPTION = 'Defined Contribution 2025')
BEGIN
	INSERT INTO SGT_BENEFIT_PROVISION VALUES('Defined Contribution 2025',	'Provision for Defined Contribution 2025 Benefit')
END
GO
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE [CODE_ID] = 251 AND CODE_VALUE = 'HB')
BEGIN
INSERT INTO [DBO].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER],
							[LEGACY_CODE_ID], [CREATED_BY],	[CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(251, 'HB', 'HB 1040 DC 2025', NULL, NULL, NULL, NULL, NULL,
         NULL, NULL, NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0 )
END
GO

/*----------------------------------------Iserting data into SGT_PLAN Table-----------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_PLAN PL WHERE PLAN_CODE = 'DC25')
BEGIN
	SELECT * INTO #TEMP_PLAN FROM SGT_PLAN WHERE PLAN_ID = 28
	--Update Main 2020
	UPDATE #TEMP_PLAN SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, 
	PLAN_CODE = 'DC25', PLAN_NAME ='Defined Contribution 2025',RETIREMENT_TYPE_VALUE = 'HB',ACTUARY_NAME = 'Defined Contribution 2025',ALLOW_INTEREST_POSTING = 1,ALLOW_PEP_CALCULATION = 1
		
	UPDATE #TEMP_PLAN SET BENEFIT_PROVISION_ID = (SELECT BENEFIT_PROVISION_ID FROM SGT_BENEFIT_PROVISION PL WHERE SHORT_DECRIPTION = 'Defined Contribution 2025')

	ALTER TABLE #TEMP_PLAN DROP COLUMN PLAN_ID

	INSERT INTO SGT_PLAN SELECT * FROM #TEMP_PLAN
	UPDATE SGT_PLAN SET SORT_ORDER = 1, ALLOW_INTEREST_POSTING = 0 , ALLOW_PEP_CALCULATION = 0 WHERE PLAN_CODE = 'DC25'
END
GO
IF EXISTS(SELECT 1 FROM SGT_PLAN PL WHERE PLAN_CODE = 'DC25' AND (ISNULL(ALLOW_INTEREST_POSTING,0) <> 0 OR ISNULL(ALLOW_PEP_CALCULATION,0) <> 0))
BEGIN
	UPDATE SGT_PLAN SET SORT_ORDER = 1, ALLOW_INTEREST_POSTING = 0 , ALLOW_PEP_CALCULATION = 0 WHERE PLAN_CODE = 'DC25'
END 
GO

IF EXISTS(SELECT 1 FROM SGT_PLAN PL WHERE PLAN_CODE = 'DC25' AND RETIREMENT_TYPE_VALUE!='HB')
BEGIN
	UPDATE SGT_PLAN SET RETIREMENT_TYPE_VALUE = 'HB' WHERE PLAN_CODE = 'DC25' AND RETIREMENT_TYPE_VALUE!='HB'
END
GO
/*-----------------------------------Iserting data into SGT_ACCOUNT_REFERENCE-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_ACCOUNT_REFERENCE T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN
	SELECT * INTO #TEMP_ACCOUNT_REFERENCE FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 28
	--SELECT PL.PLAN_ID, T.*
	
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	FROM #TEMP_ACCOUNT_REFERENCE T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_ACCOUNT_REFERENCE DROP COLUMN ACCOUNT_REFERENCE_ID
	INSERT INTO SGT_ACCOUNT_REFERENCE SELECT * FROM #TEMP_ACCOUNT_REFERENCE 
END
GO
/*-----------------------------------Iserting data into SGT_ORG_CONTACT-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_ORG_CONTACT T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25' )
BEGIN 
	--SELECT OP.* INTO #TEMP_ORG_CONTACT FROM SGT_ORG_CONTACT OP JOIN SGT_ORGANIZATION O ON OP.ORG_ID = O.ORG_ID AND O.ORG_CODE = '012500' WHERE PLAN_ID = 2
	SELECT * INTO #TEMP_ORG_CONTACT FROM SGT_ORG_CONTACT WHERE PLAN_ID = 27 AND STATUS_VALUE != 'INCV'
	
	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	FROM #TEMP_ORG_CONTACT T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_ORG_CONTACT DROP COLUMN ORG_CONTACT_ID

	INSERT INTO SGT_ORG_CONTACT SELECT * FROM #TEMP_ORG_CONTACT 
END
GO
/*-----------------------------------Iserting data into SGT_ORG_PLAN-----------------------------------------------*/

IF NOT EXISTS(SELECT 1 FROM SGT_ORG_PLAN T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25' )
BEGIN 	 
	--SELECT OP.* INTO #TEMP_ORG_PLAN FROM SGT_ORG_PLAN OP JOIN SGT_ORGANIZATION O ON OP.ORG_ID = O.ORG_ID AND O.ORG_CODE = '012500' WHERE PLAN_ID = 2
	IF OBJECT_ID('tempdb..#TEMP_ORG_PLAN') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_ORG_PLAN
	END
	SELECT * INTO #TEMP_ORG_PLAN FROM SGT_ORG_PLAN (NOLOCK) WHERE PLAN_ID = 27 AND PARTICIPATION_END_DATE IS NULL

	--SELECT PL.PLAN_ID, T.*	
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID,
	PARTICIPATION_START_DATE = '2025-01-01 00:00:00.000'
	FROM #TEMP_ORG_PLAN T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_ORG_PLAN DROP COLUMN ORG_PLAN_ID

	INSERT INTO SGT_ORG_PLAN SELECT * FROM #TEMP_ORG_PLAN 
END
GO
IF NOT EXISTS(SELECT 1 FROM SGT_ORG_PLAN where PLAN_ID = 30 and Org_id = 2413)
BEGIN
	INSERT INTO SGT_ORG_PLAN 
	VALUES(2413,30,'2025-01-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
END
GO

--Iserting data into ORG_PLAN_PROVIDER
IF NOT EXISTS(SELECT 1 FROM SGT_ORG_PLAN_PROVIDER T JOIN SGT_ORG_PLAN OP ON OP.ORG_PLAN_ID = T.ORG_PLAN_ID JOIN SGT_PLAN PL ON OP.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 
	INSERT INTO SGT_ORG_PLAN_PROVIDER
	SELECT  ORG_PLAN_ID,2413,407,'ACTV','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0 FROM SGT_ORG_PLAN WHERE PLAN_ID = 30 
END
GO


/*-----------------------------------Iserting data into SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 	
	IF OBJECT_ID('tempdb..#TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF
	END
	SELECT * INTO #TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF FROM SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF WHERE PLAN_ID = 28

	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	FROM #TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF DROP COLUMN SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF_ID

	INSERT INTO SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF SELECT * FROM #TEMP_PEOPLESOFT_PLAN_ORG_CROSS_REF 
END
GO
/*-----------------------------------Iserting data into SGT_PLAN_EMP_CATEGORY_CROSSREF-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_PLAN_EMP_CATEGORY_CROSSREF T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 	
	IF OBJECT_ID('tempdb..#TEMP_PLAN_EMP_CATEGORY_CROSSREF') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_PLAN_EMP_CATEGORY_CROSSREF
	END
	SELECT * INTO #TEMP_PLAN_EMP_CATEGORY_CROSSREF FROM SGT_PLAN_EMP_CATEGORY_CROSSREF WHERE PLAN_ID = 1

	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	FROM #TEMP_PLAN_EMP_CATEGORY_CROSSREF T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_PLAN_EMP_CATEGORY_CROSSREF DROP COLUMN PLAN_EMP_CATEGORY_ID

	INSERT INTO SGT_PLAN_EMP_CATEGORY_CROSSREF SELECT * FROM #TEMP_PLAN_EMP_CATEGORY_CROSSREF 
END
GO
/*-----------------------------------Iserting data into SGT_PLAN_JOB_CLASS_CROSSREF-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_PLAN_JOB_CLASS_CROSSREF T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 	
	IF OBJECT_ID('tempdb..#TEMP_PLAN_JOB_CLASS_CROSSREF') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_PLAN_JOB_CLASS_CROSSREF
	END
	SELECT * INTO #TEMP_PLAN_JOB_CLASS_CROSSREF FROM SGT_PLAN_JOB_CLASS_CROSSREF WHERE PLAN_ID = 27 --AND JOB_CLASS_VALUE ='PEAO'
	AND JOB_CLASS_VALUE NOT IN ('NGSF','CTTF','DPTF','SUPR','PEAO','CTCT','DPIC','','')

	INSERT INTO #TEMP_PLAN_JOB_CLASS_CROSSREF SELECT PLAN_ID,JOB_TYPE_ID,JOB_TYPE_VALUE,JOB_CLASS_ID,JOB_CLASS_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
		DC_TRANSFER_ELIGIBLE FROM SGT_PLAN_JOB_CLASS_CROSSREF WHERE PLAN_ID = 27 and JOB_TYPE_VALUE = 'TEMP' AND JOB_CLASS_VALUE NOT IN ('CTTF','DPTF')
	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	,DC_TRANSFER_ELIGIBLE='N'
	FROM #TEMP_PLAN_JOB_CLASS_CROSSREF T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_PLAN_JOB_CLASS_CROSSREF DROP COLUMN PLAN_JOBCLASS_ID

	INSERT INTO SGT_PLAN_JOB_CLASS_CROSSREF SELECT * FROM #TEMP_PLAN_JOB_CLASS_CROSSREF 
END
GO
/*-----------------------------------Iserting data into SGT_SERVICE_CREDIT_PLAN_FORMULA_REF-----------------------------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_SERVICE_CREDIT_PLAN_FORMULA_REF T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 	
	IF OBJECT_ID('tempdb..#TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF
	END
	SELECT * INTO #TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF FROM SGT_SERVICE_CREDIT_PLAN_FORMULA_REF WHERE PLAN_ID = 28

	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET CREATED_BY = 'PIR 25920', MODIFIED_BY = 'PIR 25920', CREATED_DATE = GETDATE(), MODIFIED_DATE = GETDATE(), UPDATE_SEQ = 0, PLAN_ID = PL.PLAN_ID
	FROM #TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'

	ALTER TABLE #TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF DROP COLUMN SERVICE_CREDIT_PLAN_FORMULA_REF_ID

	INSERT INTO SGT_SERVICE_CREDIT_PLAN_FORMULA_REF SELECT * FROM #TEMP_SERVICE_CREDIT_PLAN_FORMULA_REF 
END
GO
/*-----------2-----------------------------Iserting data into SGS_CODE_VALUE Table        DATA1-----------------------------*/
IF NOT EXISTS(SELECT 1 FROM	SGS_CODE_VALUE CV  JOIN	SGT_PLAN PL ON PL.PLAN_CODE = 'DC25' WHERE CV.DATA1 = CONVERT(varchar(20), 30))
BEGIN
	INSERT  INTO SGS_CODE_VALUE 
	SELECT CV.CODE_ID, 'DC'+ CV.CODE_VALUE AS CODE_VALUE, REPLACE(CV.DESCRIPTION, 'DC2020', 'DC2025'), PLAN_ID AS DATA1, CV.DATA2, CV.DATA3
	, REPLACE(CV.COMMENTS,'DC','DC 2025'), CV.START_DATE, CV.END_DATE, CV.CODE_VALUE_ORDER, CV.LEGACY_CODE_ID
	, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0
	FROM	SGS_CODE CD JOIN SGS_CODE_VALUE CV ON CD.CODE_ID = CV.CODE_ID 
	JOIN	SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'
	WHERE	DATA1_CAPTION LIKE '%PLAN%'  AND CV.DATA1 = '28'
	ORDER BY CD.CODE_ID
END	
GO
/*---------------3-------------------------Iserting data into SGT_WSS_AUTO_POSTING_CROSS_REF Table-----------------------------*/
IF NOT EXISTS(SELECT 1 FROM SGT_WSS_AUTO_POSTING_CROSS_REF T JOIN SGT_PLAN PL ON T.PLAN_ID = PL.PLAN_ID WHERE PL.PLAN_CODE = 'DC25')
BEGIN 
	IF OBJECT_ID('tempdb..#TEMP_WSS_AUTO_POSTING_CROSS_REF') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_WSS_AUTO_POSTING_CROSS_REF
	END
	SELECT * INTO #TEMP_WSS_AUTO_POSTING_CROSS_REF FROM SGT_WSS_AUTO_POSTING_CROSS_REF WHERE PLAN_ID = 28

	--SELECT PL.PLAN_ID, T.*
	UPDATE T SET  PLAN_ID = PL.PLAN_ID, AUTO_POSTING_CROSS_REF_ID = (select max(AUTO_POSTING_CROSS_REF_ID) from SGT_WSS_AUTO_POSTING_CROSS_REF) + ROW_NUMBRE
	FROM #TEMP_WSS_AUTO_POSTING_CROSS_REF T JOIN SGT_PLAN PL ON PL.PLAN_CODE = 'DC25'
	JOIN (select ROW_NUMBER() OVER (ORDER BY AUTO_POSTING_CROSS_REF_ID) ROW_NUMBRE, AUTO_POSTING_CROSS_REF_ID FROM #TEMP_WSS_AUTO_POSTING_CROSS_REF) R 
	ON R.AUTO_POSTING_CROSS_REF_ID = T.AUTO_POSTING_CROSS_REF_ID
	
	--select * from #TEMP_WSS_AUTO_POSTING_CROSS_REF
	INSERT INTO SGT_WSS_AUTO_POSTING_CROSS_REF SELECT * FROM #TEMP_WSS_AUTO_POSTING_CROSS_REF 
	--SELECT * FROM SGT_WSS_AUTO_POSTING_CROSS_REF WHERE PLAN_ID = 30
END
GO


--DC25 Code Value updates 

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 332 AND CODE_VALUE='ADEC')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(332,'ADEC','Matching Contribution Election start date equals the reporting month the change is effective',null,null,null,null,null,null,null
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1302 AND CODE_VALUE='ADEC')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(1302,'ADEC','ADEC',null,null,null,null,null,null,null
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1302 AND CODE_VALUE='AEPT')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(1302,'AEPT','Additional Employee Post Tax',null,null,null,null,null,null,null
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1302 AND CODE_VALUE='AEPR')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(1302,'AEPR','Additional Employee Pre Tax',null,null,null,null,null,null,null
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1302 AND CODE_VALUE='EPTM')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(1302,'EPTM','Employer Pre Tax Match',null,null,null,null,null,null,null
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO





IF NOT EXISTS (SELECT 1 FROM [SGT_ITEM_TYPE_SOURCE_TYPE_CROSSREF] WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE ='REMI')
	INSERT INTO [SGT_ITEM_TYPE_SOURCE_TYPE_CROSSREF](ITEM_TYPE_ID,ITEM_TYPE_VALUE,SOURCE_TYPE_ID,SOURCE_TYPE_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
     VALUES(1302,'ADEC',1304,'REMI','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_REMIT_TYPE_BANK_ACCT_CROSSREF WHERE REMITTANCE_TYPE_VALUE = 'ADEC' AND BANK_ACCOUNT_VALUE ='RETR')
	INSERT INTO SGT_REMIT_TYPE_BANK_ACCT_CROSSREF (REMITTANCE_TYPE_ID,REMITTANCE_TYPE_VALUE,BANK_ACCOUNT_ID,BANK_ACCOUNT_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
     VALUES(1302,'ADEC',1201,'RETR','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'AEPR' AND TRANSACTION_TYPE_VALUE = 'ITLV')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,	1302,'AEPR',NULL,NULL,NULL,NULL,1303,'ITLV',1309,NULL,1304,'EMPR',1,26,54,'Employer Pre Tax Additional','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'AEPT' AND TRANSACTION_TYPE_VALUE = 'ITLV')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,	1302,'AEPT',NULL,NULL,NULL,NULL,1303,'ITLV',1309,NULL,1304,'EMPR',1,26,54,'Employer Post Tax Additional','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ITLV' AND PLAN_ID = 19)
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(19,1300,481,1301,3001,	1302,'EPTM',NULL,NULL,NULL,NULL,1303,'ITLV',1309,NULL,1304,'EMPR',1,10,53,'Employer Match','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ITLV' AND PLAN_ID = 30)
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,	1302,'EPTM',NULL,NULL,NULL,NULL,1303,'ITLV',1309,NULL,1304,'EMPR',1,26,53,'Employer Match','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ITLV' AND PLAN_ID = 30 AND (DEBIT_ACCOUNT_ID != 26 OR CREDIT_ACCOUNT_ID != 53))
 UPDATE  SGT_ACCOUNT_REFERENCE SET DEBIT_ACCOUNT_ID	= 26, CREDIT_ACCOUNT_ID = 53  where ITEM_TYPE_VALUE = 'EPTM' AND PLAN_ID = 30
GO
IF EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ITLV' AND PLAN_ID = 19 AND (DEBIT_ACCOUNT_ID != 10 OR CREDIT_ACCOUNT_ID != 53))
 UPDATE  SGT_ACCOUNT_REFERENCE SET DEBIT_ACCOUNT_ID	= 10, CREDIT_ACCOUNT_ID = 53  where ITEM_TYPE_VALUE = 'EPTM' AND PLAN_ID = 19
GO

IF NOT EXISTS (SELECT 1 FROM SGT_CHART_OF_ACCOUNT WHERE GL_ACCOUNT_NUMBER = 448012)
	INSERT INTO SGT_CHART_OF_ACCOUNT VALUES(448012,1306,'REVE','Employee Contributions-Current Year','2023-01-01','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'ITLV')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,483,1301,1001,	1302,'ADEC',NULL,NULL,NULL,NULL,1303,'ITLV',1309,NULL,1304,'EMPR',1,26,256,'ADEC Fund Transfer','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
 IF EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR'  AND TRANSACTION_TYPE_VALUE = 'ITLV' AND (DEBIT_ACCOUNT_ID != 26 OR CREDIT_ACCOUNT_ID != 256))
 UPDATE  SGT_ACCOUNT_REFERENCE SET DEBIT_ACCOUNT_ID = 26,CREDIT_ACCOUNT_ID = 256  where ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR'
GO
 IF EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'ITLV' AND (DEPT_VALUE != 1001))
 UPDATE  SGT_ACCOUNT_REFERENCE SET DEPT_VALUE = 1001 where ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR'
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE='REMI' AND TRANSACTION_TYPE_VALUE='TRAN')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,483,1301,1001,	1302,'ADEC',NULL,NULL,NULL,NULL,1303,'TRAN',1309,'APPL',1304,'REMI',1,26,25,'Fund Allocation','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE='REMI' AND TRANSACTION_TYPE_VALUE='STAT' )
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,483,1301,1001,	1302,'ADEC',NULL,NULL,NULL,NULL,1303,'STAT',1309,'APPL',1304,'REMI',1,26,25,'Fund Allocation','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

-- Reverse GL Entries

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'AEPR' AND TRANSACTION_TYPE_VALUE = 'ALLO')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,NULL,NULL,1302,'AEPR',1302,'CNTR',1303,'ALLO',1309,NULL,1304,'EMPR',1,54,26,'Employer Pre Tax Additional Payable ER','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'AEPT' AND TRANSACTION_TYPE_VALUE = 'ALLO')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,NULL,NULL,1302,'AEPT',1302,'CNTR',1303,'ALLO',1309,NULL,1304,'EMPR',1,54,26,'Employer Post Tax Additional Payable ER','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ALLO' AND PLAN_ID = 19)
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(19,1300,481,1301,3001,NULL,NULL,	1302,'EPTM',1302,'CNTR',1303,'ALLO',1309,NULL,1304,'EMPR',1,53,10,'Employer Match Payable ER','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF EXISTS (SELECT * FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ALLO' AND PLAN_ID = 19 AND (DEBIT_ACCOUNT_ID != 53 OR CREDIT_ACCOUNT_ID != 10))
 UPDATE  SGT_ACCOUNT_REFERENCE SET DEBIT_ACCOUNT_ID	= 53, CREDIT_ACCOUNT_ID = 10  where FROM_ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ALLO' AND PLAN_ID = 19
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'EPTM' AND TRANSACTION_TYPE_VALUE = 'ALLO' AND PLAN_ID = 30)
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,480,1301,1101,	NULL,NULL,1302,'EPTM',1302,'CNTR',1303,'ALLO',1309,NULL,1304,'EMPR',1,53,26,'Employer Match Payable ER','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE FROM_ITEM_TYPE_VALUE = 'ADEC' AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'ALLO')
	INSERT INTO SGT_ACCOUNT_REFERENCE VALUES(30,1300,483,1301,1001,	NULL,NULL,1302,'ADEC',1302,'CNTR',1303,'ALLO',1309,NULL,1304,'EMPR',1,256,26,'ADEC Fund Transfer Payable ER','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
--------------Created By: 	
--------------Purpose   : PIR 25920 
--------------Date      : 26 June 2023
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10512)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10512,	'Employer Match for this PERSLink ID does not match with reported amount for this period.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10513)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10513,	'Contributions and Wages must not be blank for Deferred Compensation.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10514)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10514,	'You should only change the additional contribution election within {0} days of an employment start date.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10515)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10515,'Employer match already applied to Retirement.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10516)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10516,'An election has already been made.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10517)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10517,'Please select a percentage before continuing.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10518)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10518,'Please select all acknowledgements listed.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10519)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10519,'Your Defined Contribution retirement plan enrollment has been processed.  You have {0} days from your date of hire to make your additional contribution election.', 16, 'I', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
 
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10520)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10520,'Additional EE Contribution should be blank for the initial plan period.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go 

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10521)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10521,'Before changing this provider''s amount to 0, apply the ER Match to another provider.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10522)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10522,'Enter a valid Employer Match.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
--ACKNOWLEDGEMENT 
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 6000 AND CODE_VALUE='ADCI')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(6000,'ADCI','Additional Contribution Election Info',NULL,NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'ADCI' )
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'ADCI',1,'I understand I have the option to contribute up to {0}% of my gross wages to the Defined Contribution Plan, and my employer will match my contribution. I understand that if I do not elect an additional contribution within my first 30 days of employment, <u>I will not have a future option to contribute up to an additional {1}% in the Defined Contribution Plan later.</u>  I acknowledge that this one-time 30-day election is an <u><b><b style="color:red;font-size:18px;">irrevocable,</b></b> lifetime election</u> for as long as I participate in this plan, and the amount cannot be changed, unless I become a temporary or part-time employee in the future.', 'N', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END
GO
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 6000 AND CODE_VALUE='PACA')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(6000,'PACA','Additional Contribution Election Acknowledgement',NULL,NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'PACA' )
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'PACA',1,'I, <b>{0}</b>, acknowledge that under the NDCC 54-52.6 I am responsible for directing the investments in the Defined Contribution Retirement Plan. I will be solely responsible for the investment results of my account. NDPERS and its governing board will not be liable for any election or investment decision I make or any default investment made as a result of my failure to timely make an investment election.' , 'N', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END
--Temp
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 6000 AND CODE_VALUE='TACA')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(6000,'TACA','Temporary Additional Contribution Election Acknowledgement',NULL,NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 1)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',1,'I am electing to participate in the NDPERS Defined Contribution Plan.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 2)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',2,'Temporary – I am filling a position limited in duration which is not regularly funded, working 40 hours per week with a participating governmental unit. <br/>Part-Time – I am a regularly funded employee and working less than twenty (20) hours per week, and my employment may or may not be limited in duration.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 3)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',3,'I understand that I can only elect to participate in the NDPERS as a temporary/part-time employee within the <u><b>first six months</b></u> of employment or <u><b>within six months</b></u> of a change in status from permanent/full time to temporary/part-time.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 4)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',4,'I understand that upon electing to participate in the NDPERS Defined Contribution Plan as a temporary/part-time employee, I will be obligated to contribute monthly contributions to the plan and do not have access to these funds for any reason while I am employed with the state of North Dakota or a political subdivision.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 5)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',5,'I acknowledge that I am not permitted to make pre-tax contributions.  Instead, my contributions will be made on an after-tax basis and that the monthly after-tax contribution I am obligated to pay is {0}%  of my gross monthly salary.  <br/>I am allowed to make a one-time <u>irrevocable</u>, lifetime additional contribution election in the plan in the plan within 180 days of hire. This will remain in effect for as long as I participate in this plan.  This <u>irrevocable</u> contribution must be submitted to my payroll office no later than the 6th working day of the month for the previous month’s salary.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 6)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',6,'I understand that as a temporary or part-time employee my election above must remain in effect for the duration of my temporary or part-time employment.  I understand that if I become a permanent employee, my additional Defined Contribution Plan contributions cannot exceed an additional 3%.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 7)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',7,'I understand that NDPERS will forward retirement contributions to the Defined Contribution Plan vendor where it will be invested according to the asset allocation that I have selected.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 8)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',8,'I understand that if I miss a payment of my retirement contribution to NDPERS for any reason other than an approved Leave of Absence, I will have thirty (30) days to bring my account up to date. Failure to do so will result in termination of my eligibility to participate as a temporary/ part-time employee.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 9)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',9,'I understand that if I terminate my employment and take a refund of my retirement monies, I will not be allowed to participate in NDPERS through future employment as a temporary/part-time employee.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 10)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',10,'I acknowledge that I cannot participate as both a temporary employee and a permanent employee. In the event that my employment qualifies me for participation as a full-time, permanent employee, I must participate as such. Any additional temporary or part-time employment less than 20 hours outside of the permanent eligible position must be excluded.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TACA' AND DISPLAY_SEQUENCE = 11)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TACA',11,'I understand that by electing to participate in the Defined Contribution Plan, my enrollment is <u><b>effective as of the date of my employee signature</b></u> and my participation as a temporary/part-time employee is only prospective from this date.', 'Y', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 6000 AND CODE_VALUE='TATP')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(6000,'TATP','Temporary Agreement To Participate ',NULL,NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_WSS_ACKNOWLEDGEMENT WHERE SCREEN_STEP_VALUE = 'TATP' AND DISPLAY_SEQUENCE = 1)
BEGIN
	INSERT INTO SGT_WSS_ACKNOWLEDGEMENT (EFFECTIVE_DATE,SCREEN_STEP_ID,SCREEN_STEP_VALUE,DISPLAY_SEQUENCE,ACKNOWLEDGEMENT_TEXT,SHOW_CHECK_BOX_FLAG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
	VALUES('01/01/2025',6000,'TATP',1,'IF YOU ELECT TO PARTICIPATE: I understand the statements listed in Part B and certify that I am eligible under NDCC 54-52.6-02.6 to participate in the NDPERS Defined Contribution Plan. I elect to begin participating in the plan.  I have provided a copy of this form to my employer for payroll deduction and have completed a Designation of Beneficiary SFN 2560.', 'N', 'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
END


/*---------------3-------------------------Iserting data into correspondance Table-----------------------------*/

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'ENR-5305')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
IMAGE_DOC_CATEGORY_ID,IMAGE_DOC_CATEGORY_VALUE,FILENET_DOCUMENT_TYPE_ID,FILENET_DOCUMENT_TYPE_VALUE,DOCUMENT_CODE) 
VALUES ( 'ENR-5305', 'Defined Contribution Retirement Program Election SFN 52170', '19', 'MMBR', 'Y', '601', 'IMG', 
'wfmPensionPlanMaintenance;', NULL, NULL, NULL, 
'515',NULL, 'Y', 'Y', 'N', '44', NULL,  'PIR 25920', getdate(), 'PIR 25920', getdate(), '0',
603,'MEMB',604,'FORM','62523')
GO

IF EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'ENR-5305' AND AUTO_PRINT_FLAG = 'Y')
	UPDATE SGS_COR_TEMPLATES SET AUTO_PRINT_FLAG = 'N' WHERE TEMPLATE_NAME = 'ENR-5305'
GO
IF EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'ENR-5305' AND DOCUMENT_CODE IS NULL)
	UPDATE SGS_COR_TEMPLATES SET DOCUMENT_CODE = '62523' WHERE TEMPLATE_NAME = 'ENR-5305'
GO

-----------------------------------------Provision Tables

--PLAN ID DC2025
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='25DC' AND DATA2 = 30)
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '25DC', 'Tier 3 DC 2025', '01/01/2025', 30, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26544', GETDATE(), 'PIR 26544', GETDATE(), 0)
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] TABLE FOR PLAN ID 30
--25DC
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 14 AND BENEFIT_TIER_VALUE = '25DC' AND EFFECTIVE_DATE = '2025-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'2025-01-01 00:00:00.000',	1904,	'RETR',	2309,	'OTHR',	2310,	'OTHR',	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	'OTHR',	NULL,	NULL,	2312,	'OTHR',	NULL,	0.00,	7003,	'25DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 14 AND BENEFIT_TIER_VALUE = '25DC' AND EFFECTIVE_DATE = '2025-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'2025-01-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'25DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 14 AND BENEFIT_TIER_VALUE = '25DC' AND EFFECTIVE_DATE = '2025-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'2025-01-01 00:00:00.000',	1904,	'DETH',	2309,	'OTHR',	2310,	NULL,	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'25DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 14 AND BENEFIT_TIER_VALUE = '25DC' AND EFFECTIVE_DATE = '2025-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DISA')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'2025-01-01 00:00:00.000',	1904,	'DISA',	2309,	'OTHR',	2310,	'OTHR',	NULL,	2315,	'OTHR',	NULL,	NULL,	NULL,	2311,	'OTHR',	NULL,	NULL,	2312,	'OTHR',	NULL,	0.00,	7003,	'25DC')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 14 AND BENEFIT_TIER_VALUE = '25DC' AND EFFECTIVE_DATE = '2025-01-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'PSTD')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'2025-01-01 00:00:00.000',	1904,	'PSTD',	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	0.00,	7003,	'25DC')
END
GO

-- UPDATE [SGT_BENEFIT_PROVISION_ELIGIBILITY] TABLE FOR PLAN ID 30

--25DC
IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=14 AND [EFFECTIVE_DATE]='01/01/2025'AND [BENEFIT_TIER_VALUE]='25DC')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'01/01/2025', 1904, 'RETR', 1910, 'VEST', 50, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 4, NULL, 7003,	'25DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'01/01/2025', 1904, 'RETR', 1910, 'ERLY', 50, 36, NULL, 'N', 'Y', NULL, NULL, NULL, NULL, 14, NULL, 7003,	'25DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'01/01/2025', 1904, 'RETR', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 18, NULL, 7003,	'25DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'01/01/2025', 1904, 'DETH', 1910, 'VEST', 55, 36, 85, 'Y', NULL, NULL, 'N', NULL, NULL, 26, NULL, 7003,	'25DC')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(14,	'01/01/2025', 1904, 'DETH', 1910, 'NRML', 55, 36, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 40, NULL, 7003,	'25DC')
END
GO

-------------------------------------------------------------------------------------
--Insert PS entiers for DC25

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 2025 Tier - Mandatory Rates Only')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 2025 Tier - Mandatory Rates Only',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'DC25','State Defined Contribution Plan - 2025 Tier - Mandatory Rates Only','7A','Defined Contribution Plan','DC25M','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,0)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 2025 Tier - 1% Election')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 2025 Tier - 1% Election',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'DC25 1%','State Defined Contribution Plan - 2025 Tier - 1% Election','7A','Defined Contribution Plan','DC251','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,1)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 2025 Tier - 2% Election')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 2025 Tier - 2% Election',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'DC25 2%','State Defined Contribution Plan - 2025 Tier - 2% Election','7A','Defined Contribution Plan','DC252','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,2)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 2025 Tier - 3% Election')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 2025 Tier - 3% Election',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'DC25 3%','State Defined Contribution Plan - 2025 Tier - 3% Election','7A','Defined Contribution Plan','DC253','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,3)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - Temp Mandatory Only')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - Temp Mandatory Only',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,'TP25','State Defined Contribution Plan - Temp Mandatory Only','7A','Defined Contribution Plan','TP25M','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,0)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 1% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 1% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 1%','State Defined Contribution Plan - 1% Election Temp','7A','Defined Contribution Plan','TP251','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,1)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 2% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 2% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 2%','State Defined Contribution Plan - 2% Election Temp','7A','Defined Contribution Plan','TP252','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,2)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 3% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 3% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 3%','State Defined Contribution Plan - 3% Election Temp','7A','Defined Contribution Plan','TP253','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,3)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 4% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 4% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 4%','State Defined Contribution Plan - 4% Election Temp','7A','Defined Contribution Plan','TP254','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,4)

END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 5% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 5% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 5%','State Defined Contribution Plan - 5% Election Temp','7A','Defined Contribution Plan','TP255','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,5)

END
GO


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 30 AND DESCRIPTION = 'State Defined Contribution Plan - 6% Election Temp')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (30,'State Defined Contribution Plan - 6% Election Temp',NULL,NULL,'TEMP',NULL,NULL,NULL,NULL,'N',NULL,'TP25 6%','State Defined Contribution Plan - 6% Election Temp','7A','Defined Contribution Plan','TP256','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,6)
END
GO


--------------------------------------------------------------------------------------------------------------

--Insert PS entries for Deferred Comp


IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 19 AND DESCRIPTION = '457 Employer Match 1%')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (19,'457 Employer Match 1%',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'Match 1%','457 Employer Match 1%','4P','457 Plan','MATCH1','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,2)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 19 AND DESCRIPTION = '457 Employer Match 2%')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (19,'457 Employer Match 2%',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'Match 2%','457 Employer Match 2%','4P','457 Plan','MATCH2','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,1)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID = 19 AND DESCRIPTION = '457 Employer Match 3%')
BEGIN 
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF
     VALUES (19,'457 Employer Match 3%',NULL,NULL,'PERM',NULL,NULL,NULL,NULL,'N',NULL,'Match 3%','457 Employer Match 3%','4P','457 Plan','MATCH3','N','Y','Y','Y','Y','N','PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0,NULL,'N','N','N',NULL,NULL,0)
END
GO


/*---------------------------//----End Of PIR 25920 DC 2025 Changes--------------//-------------------------------------------*/



--------------Created By: sanket 
--------------Purpose   : PIR 26694
IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'PER-0359')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
[IMAGE_DOC_CATEGORY_ID],[IMAGE_DOC_CATEGORY_VALUE],[FILENET_DOCUMENT_TYPE_ID],[FILENET_DOCUMENT_TYPE_VALUE],[DOCUMENT_CODE],[BATCH_PRINT_FLAG]) 
VALUES ( 'PER-0359', 'Refund or Rollover of Member Account (PER-0359)', '19', 'MMBR', 'Y', '601', NULL, 
'wfmPensionPlanMaintenance;', NULL, NULL, NULL, 
'515',NULL, 'N', 'Y', 'N', '44', NULL, 'PIR 26694', getdate(), 'PIR 26694', getdate(), '0',603,'MEMB',604,'CORR',1529,'N')
GO

--------------Created By: Sarvesh 
--------------Purpose   : PIR 26738

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'SFN-62522')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
[IMAGE_DOC_CATEGORY_ID],[IMAGE_DOC_CATEGORY_VALUE],[FILENET_DOCUMENT_TYPE_ID],[FILENET_DOCUMENT_TYPE_VALUE],[DOCUMENT_CODE],[BATCH_PRINT_FLAG]) 
VALUES ('SFN-62522', 'SFN 62522 - DEFINED CONTRIBUTION RETIREMENT PLAN ENROLLMENT', '19', 'MMBR', 'Y', '601', NULL, 'wfmPensionPlanMaintenance;', NULL, NULL, NULL, 
'515',NULL, 'N', 'Y', 'N', '44', NULL, 'PIR 26738', getdate(), 'PIR 26738', getdate(), '0',603,'MEMB',604,'FORM',Null,Null)
GO

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'SFN-62523')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
[IMAGE_DOC_CATEGORY_ID],[IMAGE_DOC_CATEGORY_VALUE],[FILENET_DOCUMENT_TYPE_ID],[FILENET_DOCUMENT_TYPE_VALUE],[DOCUMENT_CODE],[BATCH_PRINT_FLAG]) 
VALUES ('SFN-62523', 'SFN 62523 - DEFINED CONTRIBUTION RETIREMENT PLAN SPECIAL ELECTION', '19', 'MMBR', 'Y', '601', NULL, 'wfmPensionPlanMaintenance;', NULL, NULL, NULL, 
'515',NULL, 'N', 'Y', 'N', '44', NULL, 'PIR 26738', getdate(), 'PIR 26738', getdate(), '0',603,'MEMB',604,'FORM',Null,Null)
GO
--------------Created By: sanket 
--------------Purpose   : PIR 26847

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGW_ACTIVITY] WHERE ACTIVITY_ID = 355)
INSERT INTO [dbo].[SGW_ACTIVITY] ([ACTIVITY_ID], [PROCESS_ID], [NAME], [DISPLAY_NAME], [STANDARD_TIME_IN_MINUTES], [ROLE_ID], [SUPERVISOR_ROLE_ID], [SORT_ORDER], [IS_DELETED_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(355, 259, 'Review Eligibility for DC Transfer', 'Review Eligibility for DC Transfer', 300, 179,	148,	1,	NULL,	'PIR 26847',	getdate(),	'PIR 26847',	getdate(),	0)
GO

IF EXISTS (SELECT 1 FROM [dbo].[SGW_ACTIVITY] WHERE ACTIVITY_ID = 85)
BEGIN
UPDATE [DBO].[SGW_ACTIVITY] SET [Name] = 'Review Enrollment for DC Transfer' , [Display_Name] = 'Review Enrollment for DC Transfer'
,MODIFIED_BY = 'PIR 26847',MODIFIED_DATE = GETDATE()  
WHERE [ACTIVITY_ID] = 85
END


/*********************Comments: New FileNet Events*****************/
IF NOT EXISTS(SELECT 1 FROM [DBO].[SGT_DOCUMENT] WHERE DOCUMENT_CODE = 62523 AND DOCUMENT_NAME = 'DEFINED CONTRIBUTION RETIREMENT PLAN SPECIAL ELECTION')
BEGIN
	INSERT INTO [DBO].[SGT_DOCUMENT] (DOCUMENT_CODE,DOCUMENT_NAME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
										IGNORE_PROCESS_FLAG, WSS, FILENET_DOCUMENT_TYPE)
		VALUES (62523,'DEFINED CONTRIBUTION RETIREMENT PLAN SPECIAL ELECTION','PIR 26847',GETDATE(),'PIR 26847',GETDATE(),0,'Y',NULL,NULL)
END
GO

IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_EVENT] WHERE BPM_EVENT_ID = 618 AND EVENT_DESC = 'DEFINED CONTRIBUTION RETIREMENT PLAN SPECIAL ELECTION')
BEGIN
	SET IDENTITY_INSERT[SGW_BPM_EVENT] ON;
	INSERT INTO [DBO].[SGW_BPM_EVENT] (BPM_EVENT_ID,EVENT_DESC,EVENT_TYPE_ID,EVENT_TYPE_VALUE,RCPT_EMAIL_ID,RCPT_FAX_NU,DOC_TYPE,SCREEN_ID,PRIORITY_DOCUMENT_IND,ECM_SECURITY_TEMPLATE_ID,ECM_SUBSCRIPTION_FLAG
           ,STATUS_ID, STATUS_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ, DOCUMENT_CATEGORY, ORG_ID_REQUIRED_IND, PERSON_ID_REQUIRED_IND, DOC_CLASS)
		VALUES (618,'DEFINED CONTRIBUTION RETIREMENT PLAN SPECIAL ELECTION',2010,'DOC',NULL,NULL,62523,NULL,NULL,NULL,'',2009,'ACTV','PIR 26847',GETDATE(),'PIR 26847',GETDATE(),0, NULL, NULL, NULL, NULL)
	SET IDENTITY_INSERT[SGW_BPM_EVENT] OFF;
END
GO

IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_PROCESS_EVENT_XR] WHERE EVENT_ID = 32 AND PROCESS_ID = (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC))
BEGIN
	INSERT INTO [DBO].[SGW_BPM_PROCESS_EVENT_XR] (EVENT_ID,PROCESS_ID,ACTION_ID,ACTION_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
						EVENT_REASON_ID, ACTIVITY_ID)
		VALUES (32, (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC), 2005, 'INRE', 'PIR 26847',GETDATE(),'PIR 26847',GETDATE(),0, NULL, NULL)
END
GO

IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_PROCESS_EVENT_XR] WHERE EVENT_ID = 585 AND PROCESS_ID = (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC))
BEGIN
	INSERT INTO [DBO].[SGW_BPM_PROCESS_EVENT_XR] (EVENT_ID,PROCESS_ID,ACTION_ID,ACTION_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
						EVENT_REASON_ID, ACTIVITY_ID)
		VALUES (585, (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC), 2005, 'INRE', 'PIR 26847',GETDATE(),'PIR 26847',GETDATE(),0, NULL, NULL)
END
GO

IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_PROCESS_EVENT_XR] WHERE EVENT_ID = 618 AND PROCESS_ID = (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC))
BEGIN
	INSERT INTO [DBO].[SGW_BPM_PROCESS_EVENT_XR] (EVENT_ID,PROCESS_ID,ACTION_ID,ACTION_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
						EVENT_REASON_ID, ACTIVITY_ID)
		VALUES (618, (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDBtoDCTransfer.bpmn%' ORDER BY 1 DESC), 2005, 'INRE', 'PIR 26847',GETDATE(),'PIR 26847',GETDATE(),0, NULL, NULL)
END
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10523)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10523,'No eligible wages are posted for December.', 16, 'W', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
IF EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10523 AND SEVERITY_VALUE = 'E')
BEGIN
	UPDATE SGS_MESSAGES SET SEVERITY_VALUE = 'W' WHERE MESSAGE_ID = 10523
END
Go
IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10524)
BEGIN
	INSERT INTO SGS_MESSAGES VALUES(10524,'Please review Calculated Actuarial Value and DB Account Balance.', 16, 'E', NULL,	NULL, 'PIR 25920', GETDATE(), 'PIR 25920', GETDATE(), 0)
END
Go
/********************Purpose: PIR 25920******************************
*********************Created By: Abhijeet Malwadkar********************************
********************Benefit option values********************************************/
IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 2216 AND CODE_VALUE='SPEL')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(2216,'SPEL','DB to DC Transfer – Special Election',NULL,'RFND',NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO


IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 2201 AND CODE_VALUE='SPEL')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(2201,'SPEL','DB to DC Transfer – Special Election',NULL,'RFND',NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO


IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 350 AND CODE_VALUE='SPEL')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(350,'SPEL','DB to DC Transfer – Special Election','CUDT',NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO


IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 2504  AND CODE_VALUE='VNPT')
INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(2504 ,'VNPT','VNPT',NULL,NULL,NULL,NULL,NULL,NULL,NULL
           ,NULL,'PIR 25920',GETDATE(),'PIR 25920',GETDATE(),0)
GO


/********************Purpose: PIR 26260******************************
*********************Created By: Bharat********************************
********************Update role and update code_value 304********************************************/

IF EXISTS (SELECT 1 FROM SGT_BPM_ACTIVITY_ROLE_XR  WHERE ACTIVITY_ID = 1012 AND ROLE_ID != 146)
BEGIN
	UPDATE SGT_BPM_ACTIVITY_ROLE_XR SET ROLE_ID = 146 WHERE ACTIVITY_ID = 1012
END
GO

IF EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 304 AND CODE_VALUE = 'CONS')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA1 = 'N' WHERE CODE_ID = 304 AND CODE_VALUE = 'CONS'
END
GO

IF EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 304 AND  CODE_VALUE = 'GRDN')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA1 = 'N' WHERE CODE_ID = 304 AND  CODE_VALUE = 'GRDN'
END
GO