--------------Created By: Sarvesh
--------------Purpose   : PIR 26536
IF EXISTS (SELECT 1 FROM [DBO].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'APP-7009')
BEGIN
UPDATE [SGS_COR_TEMPLATES] SET [ASSOCIATED_FORMS] = 'wfmPersonOverviewMaintenance;' WHERE [TEMPLATE_NAME] = 'APP-7009' and [TEMPLATE_ID] = 192 
END
GO

--------------Created By: Sarvesh
--------------Purpose   : PIR 26489
IF EXISTS (SELECT 1 FROM [DBO].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'PER-0053')
BEGIN
UPDATE SGS_COR_TEMPLATES SET ASSOCIATED_FORMS = 'wfmPersonMaintenance;' WHERE TEMPLATE_NAME = 'PER-0053' and TEMPLATE_ID = 127 
END
GO


--------------Created By: Vidya
--------------Purpose   : PIR 26282

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='11BT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '11BT', '2011 Tier', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26282', GETDATE(), 'PIR 26282', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7003 AND [CODE_VALUE]='23BT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7003, '23BT', '2023 Tier', '08/01/2023', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 26282', GETDATE(), 'PIR 26282', GETDATE(), 0)
END
GO

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID] = 10 AND [EFFECTIVE_DATE] < '08/01/2023' AND ISNULL([BENEFIT_TIER_VALUE],'') <> '11BT')
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET [BENEFIT_TIER_VALUE] = '11BT' WHERE [BENEFIT_PROVISION_ID] = 10 AND [EFFECTIVE_DATE] < '08/01/2023'
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]=10 AND [EFFECTIVE_DATE]='08/01/2023'AND [BENEFIT_TIER_VALUE]='23BT')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'08/01/2023', 1904, 'RETR', 1910, 'VEST', 55, 120, 85, 'Y', NULL, NULL, 'Y', NULL, NULL, 2, NULL, 7003,	'23BT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'08/01/2023', 1904, 'DETH', 1910, 'VEST', 55, 120, 85, 'Y', NULL, NULL, 'Y', NULL, NULL, 24, NULL, 7003,	'23BT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'08/01/2023', 1904, 'RETR', 1910, 'NRML', 55, 120, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 17, NULL, 7003,	'23BT')

INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'08/01/2023', 1904, 'DETH', 1910, 'NRML', 55, 120, 85, 'N', 'Y', NULL, NULL, NULL, NULL, 39, NULL, 7003,	'23BT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 10 AND BENEFIT_TIER_VALUE = '23BT' AND EFFECTIVE_DATE = '2023-08-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'2023-08-01 00:00:00.000',	1904,	'RETR',	2309,	'SRSM',	2310,	'FAPM',	0.005000,	2315,	'HIAV',	36,	180,	'Y',	2311,	'MASA',	NULL,	'Y',	2312,	'MASA',	NULL,	5.00,	7003,	'23BT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 10 AND BENEFIT_TIER_VALUE = '23BT' AND EFFECTIVE_DATE = '2023-08-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] IS NULL)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'2023-08-01 00:00:00.000',	1904,	NULL,	2309,	NULL,	2310,	NULL,	NULL,	2315,	NULL,	NULL,	NULL,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'23BT')
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID = 10 AND BENEFIT_TIER_VALUE = '23BT' AND EFFECTIVE_DATE = '2023-08-01 00:00:00.000' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'DETH')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_BENEFIT_TYPE ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES(10,	'2023-08-01 00:00:00.000',	1904,	'DETH',	2309,	'SRSM',	2310,	NULL,	NULL,	2315,	'HIAV',	36,	180,	NULL,	2311,	NULL,	NULL,	NULL,	2312,	NULL,	NULL,	5.00,	7003,	'23BT')
END
GO

--------------Created By: Vidya
--------------Purpose   : PIR 26317 

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE BENEFIT_PROVISION_ID  NOT IN (1,10))
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = NULL WHERE BENEFIT_PROVISION_ID  NOT IN (1,10)
END
GO

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ID  NOT IN (1,10))
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] SET BENEFIT_TIER_VALUE = NULL WHERE BENEFIT_PROVISION_ID  NOT IN (1,10)
END
GO


IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (1,5,45,57,62)
AND ISNULL(AGE,0) <> 55)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE = 55 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (1,5,45,57,62)
END
GO

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (1,5,45,62)
AND ISNULL(AGE_PLUS_SERVICE,0) <> 85)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_PLUS_SERVICE = 85 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (1,5,45,62)
END 
GO

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (57)
AND ISNULL(AGE_PLUS_SERVICE,0) <> 90)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_PLUS_SERVICE = 90 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (57)
END
GO

IF NOT EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE [BENEFIT_PROVISION_ID]= 1 AND [EFFECTIVE_DATE]= '8/1/2015' AND [BENEFIT_TIER_VALUE]= '16MT' AND [ELIGIBILITY_TYPE_VALUE] = 'VEST' AND [BENEFIT_ACCOUNT_TYPE_VALUE] = 'RETR')
BEGIN
INSERT INTO [dbo].[SGT_BENEFIT_PROVISION_ELIGIBILITY] ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], [COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
VALUES (1, '8/1/2015', 1904, 'RETR', 1910, 'VEST', 55, NULL, 90, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, 7003, '16MT')
END

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE ELIGIBILITY_TYPE_VALUE='VEST' AND BENEFIT_PROVISION_ID IN (2,8,10,3,4,13) AND AGE_WHILE_EMPLOYED_FLAG <> 'N')
BEGIN
UPDATE  SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_WHILE_EMPLOYED_FLAG='N' WHERE ELIGIBILITY_TYPE_VALUE='VEST' AND BENEFIT_PROVISION_ID  IN (2,8,10,3,4,13)
END
GO
-- BENEFIT TIER VALUE SET NULL WHERE PLAN ID <> 1

IF EXISTS (SELECT 1 FROM [DBO].[SGT_PERSON_ACCOUNT_RETIREMENT] WHERE PERSON_ACCOUNT_ID IN (SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT WHERE PLAN_ID NOT IN (1)))
BEGIN
UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = NULL, MODIFIED_BY ='PIR 26282', MODIFIED_DATE=GETDATE() 
WHERE PERSON_ACCOUNT_ID IN (SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT WHERE PLAN_ID NOT IN (1))
END
GO

-- PLAN_ID 1 SET BENEFIT TIER VALUE WHERE TIER VALUE IS NULL
UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = '97MT', MODIFIED_BY ='PIR 26282', MODIFIED_DATE=GETDATE() 
WHERE  BENEFIT_TIER_VALUE IS NULL AND PERSON_ACCOUNT_ID IN (
SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT SPA WHERE PLAN_ID=1 AND SPA.START_DATE < '01/01/2016' 
AND PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') 
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM SGT_PERSON_ACCOUNT PA WITH(NOLOCK)
INNER JOIN SGT_PLAN SP WITH(NOLOCK) ON PA.PLAN_ID = SP.PLAN_ID AND SP.BENEFIT_TYPE_VALUE ='RETR'
WHERE PA.PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') AND PA.PLAN_ID <> 1)) 

UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = '16MT', MODIFIED_BY ='PIR 26282', MODIFIED_DATE=GETDATE() 
WHERE  BENEFIT_TIER_VALUE IS NULL AND PERSON_ACCOUNT_ID IN (
SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT SPA WHERE PLAN_ID=1 AND SPA.START_DATE >= '01/01/2016' 
AND PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') 
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM SGT_PERSON_ACCOUNT PA WITH(NOLOCK)
INNER JOIN SGT_PLAN SP WITH(NOLOCK) ON PA.PLAN_ID = SP.PLAN_ID AND SP.BENEFIT_TYPE_VALUE ='RETR'
WHERE PA.PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') AND PA.PLAN_ID <> 1)) 


-- PLAN_ID 26 SET BENEFIT TIER VALUE WHERE TIER VALUE IS NULL
UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = '11BT', MODIFIED_BY ='PIR 26282', MODIFIED_DATE=GETDATE() 
WHERE  BENEFIT_TIER_VALUE IS NULL AND PERSON_ACCOUNT_ID IN (
SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT SPA WHERE PLAN_ID=26 AND SPA.START_DATE < '08/01/2023'
AND PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') 
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM SGT_PERSON_ACCOUNT PA WITH(NOLOCK)
INNER JOIN SGT_PLAN SP WITH(NOLOCK) ON PA.PLAN_ID = SP.PLAN_ID AND SP.BENEFIT_TYPE_VALUE ='RETR'
WHERE PA.PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') AND PA.PLAN_ID <> 26)) 

UPDATE SGT_PERSON_ACCOUNT_RETIREMENT SET BENEFIT_TIER_VALUE = '23BT', MODIFIED_BY ='PIR 26282', MODIFIED_DATE=GETDATE() 
WHERE  BENEFIT_TIER_VALUE IS NULL AND PERSON_ACCOUNT_ID IN (
SELECT PERSON_ACCOUNT_ID FROM SGT_PERSON_ACCOUNT SPA WHERE PLAN_ID=26 AND SPA.START_DATE >= '08/01/2023'
AND PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') 
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM SGT_PERSON_ACCOUNT PA WITH(NOLOCK)
INNER JOIN SGT_PLAN SP WITH(NOLOCK) ON PA.PLAN_ID = SP.PLAN_ID AND SP.BENEFIT_TYPE_VALUE ='RETR'
WHERE PA.PLAN_PARTICIPATION_STATUS_VALUE IN ('ENL1', 'SUS2') AND PA.PLAN_ID <> 26)) 


IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE [BENEFIT_PROVISION_ID] = 10 AND [EFFECTIVE_DATE] < '08/01/2023' AND ISNULL([BENEFIT_TIER_VALUE],'') <> '11BT')
BEGIN
UPDATE [DBO].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] SET BENEFIT_TIER_VALUE = '11BT' WHERE BENEFIT_PROVISION_ID = 10 AND [EFFECTIVE_DATE] < '08/01/2023' AND ISNULL([BENEFIT_TIER_VALUE],'') <> '11BT'
END
GO

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (2,4,7,3,50,67)
AND ISNULL(AGE,0) <> 50)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE = 50 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (2,4,7,3,50,67)
END

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (29,2,31,4,30,3,53,50,73,72,70,67)
AND ISNULL(AGE_PLUS_SERVICE,0) <> 85 )
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_PLUS_SERVICE = 85 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (29,2,31,4,30,3,53,50,73,72,70,67)
END

IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (34,7)
AND ISNULL(AGE_PLUS_SERVICE,0) <> 80)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_PLUS_SERVICE = 80 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (34,7)
END
-- main2020 
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (61)
AND ISNULL(AGE_PLUS_SERVICE,0) <> 90 )
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET AGE_PLUS_SERVICE = 90 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (61)
END

-- 36
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (69,71,66,64,61,58,44,27,49,47,37,20,19,36,35,18,55)
AND ISNULL([SERVICE],0) <> 36)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET [SERVICE] = 36 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (69,71,66,64,61,58,44,27,49,47,37,20,19,36,35,18,55)
END

-- 120
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (21,38)
AND ISNULL([SERVICE],0) <> 120)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET [SERVICE] = 120 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (21,38)
END

--60
IF EXISTS (SELECT 1 FROM [DBO].[SGT_BENEFIT_PROVISION_ELIGIBILITY] WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (22,39)
AND ISNULL([SERVICE],0) <> 60)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_ELIGIBILITY SET [SERVICE] = 60 WHERE BENEFIT_PROVISION_ELIGIBILITY_ID IN (22,39)
END

--------------Created By: Sarvesh
--------------Purpose   : PIR 26536
IF EXISTS (SELECT 1 FROM [DBO].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'APP-7009')
BEGIN
UPDATE [SGS_COR_TEMPLATES] SET [ASSOCIATED_FORMS] = 'wfmPersonMaintenance;wfmRetirementApplicationMaintenance;' WHERE [TEMPLATE_NAME] = 'APP-7009' and [TEMPLATE_ID] = 192 
END
GO