/********************Purpose: PIR 26688******************************
*********************Created By: Bharat Reddy********************************/

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 2324 AND CODE_VALUE='IN121')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(2324,'IN121','Interest Effective from 01/01/2025','01/01/2025',6.5,30,null,null,null,1
           ,NULL,'PIR 26688',GETDATE(),'PIR 26688',GETDATE(),0)
GO

/********************Purpose: PIR 26939******************************
*********************Created By: Sanket Chougale********************************/
IF NOT EXISTS(SELECT 1 FROM [DBO].[SGT_DOCUMENT] WHERE DOCUMENT_CODE = 62522 AND DOCUMENT_NAME = 'SFN 62522 - DEFINED CONTRIBUTION RETIREMENT PLAN ENROLLMENT')
BEGIN
	INSERT INTO [DBO].[SGT_DOCUMENT] (DOCUMENT_CODE,DOCUMENT_NAME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
										IGNORE_PROCESS_FLAG, WSS, FILENET_DOCUMENT_TYPE)
		VALUES (62522,'SFN 62522 - DEFINED CONTRIBUTION RETIREMENT PLAN ENROLLMENT','PIR 26939',GETDATE(),'PIR 26939',GETDATE(),0,'Y',NULL,NULL)
END
GO

IF NOT EXISTS (SELECT * FROM [dbo].[SGW_PROCESS] WHERE PROCESS_ID = 383)
INSERT INTO [DBO].[SGW_PROCESS] ([PROCESS_ID], [DESCRIPTION], [NAME], [PRIORITY], [TYPE_ID], [TYPE_VALUE], [STATUS_ID], [STATUS_VALUE], [USE_NEW_MAP_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(383,'Process DC Enrollment',	'nfmProcessDCEnrollment',	0,	5004,	'PERS',	5003,	'ACT',	NULL,	'PIR 26939',	getdate(),	'PIR 26939',	getdate(),	0)
GO
 
IF NOT EXISTS (SELECT * FROM [dbo].[SGW_BPM_PROCESS_ID_DESC] WHERE PROCESS_ID = 383)
INSERT INTO [DBO].[SGW_BPM_PROCESS_ID_DESC] ([PROCESS_ID], [DESCRIPTION])
VALUES(383, 'Process DC Enrollment')
GO
 
IF NOT EXISTS (SELECT * FROM [dbo].[SGW_ACTIVITY] WHERE ACTIVITY_ID = 356)
INSERT INTO [DBO].[SGW_ACTIVITY] ([ACTIVITY_ID], [PROCESS_ID], [NAME], [DISPLAY_NAME], [STANDARD_TIME_IN_MINUTES], [ROLE_ID], [SUPERVISOR_ROLE_ID], [SORT_ORDER], [IS_DELETED_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(356, 383, 'Enter DC Additional Contribution', 'Enter DC Additional Contribution',	300, 143,	148,	1,	NULL,	'PIR 26939',	getdate(),	'PIR 18493',	getdate(),	0)
GO
 
IF NOT EXISTS (SELECT * FROM [dbo].[SGW_ACTIVITY] WHERE ACTIVITY_ID = 357)
INSERT INTO [DBO].[SGW_ACTIVITY] ([ACTIVITY_ID], [PROCESS_ID], [NAME], [DISPLAY_NAME], [STANDARD_TIME_IN_MINUTES], [ROLE_ID], [SUPERVISOR_ROLE_ID], [SORT_ORDER], [IS_DELETED_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(357, 383, 'Audit DC Additional Contribution', 'Audit DC Additional Contribution',	300, 142,	148,	1,	NULL,	'PIR 26939',	getdate(),	'PIR 18493',	getdate(),	0)
GO



IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_EVENT] WHERE BPM_EVENT_ID = 619 AND EVENT_DESC = 'SFN 62522 - DEFINED CONTRIBUTION RETIREMENT PLAN ENROLLMENT')
BEGIN
	SET IDENTITY_INSERT[SGW_BPM_EVENT] ON;
	INSERT INTO [DBO].[SGW_BPM_EVENT] (BPM_EVENT_ID,EVENT_DESC,EVENT_TYPE_ID,EVENT_TYPE_VALUE,RCPT_EMAIL_ID,RCPT_FAX_NU,DOC_TYPE,SCREEN_ID,PRIORITY_DOCUMENT_IND,ECM_SECURITY_TEMPLATE_ID,ECM_SUBSCRIPTION_FLAG
           ,STATUS_ID, STATUS_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ, DOCUMENT_CATEGORY, ORG_ID_REQUIRED_IND, PERSON_ID_REQUIRED_IND, DOC_CLASS)
		VALUES (619,'SFN 62522 - DEFINED CONTRIBUTION RETIREMENT PLAN ENROLLMENT',2010,'DOC',NULL,NULL,62522,NULL,NULL,NULL,'',2009,'ACTV','PIR 26939',GETDATE(),'PIR 26939',GETDATE(),0, NULL, NULL, NULL, NULL)
	SET IDENTITY_INSERT[SGW_BPM_EVENT] OFF;
END
GO

IF NOT EXISTS(SELECT 1 FROM [DBO].[SGW_BPM_PROCESS_EVENT_XR] WHERE EVENT_ID = 619 AND PROCESS_ID = (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDCEnrollment.bpmn%' ORDER BY 1 DESC))
BEGIN
	INSERT INTO [DBO].[SGW_BPM_PROCESS_EVENT_XR] (EVENT_ID,PROCESS_ID,ACTION_ID,ACTION_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
						EVENT_REASON_ID, ACTIVITY_ID)
		VALUES (619, (SELECT TOP 1 P.PROCESS_ID FROM SGW_BPM_CASE C INNER JOIN SGW_BPM_PROCESS P ON C.CASE_ID = P.CASE_ID WHERE CASE_FILE LIKE '%sbpProcessDCEnrollment.bpmn%' ORDER BY 1 DESC), 2005, 'INRE', 'PIR 26939',GETDATE(),'PIR 26939',GETDATE(),0, NULL, NULL)
END
GO



/********************Purpose: PIR 26652******************************
*********************Created By: Sarvesh Ghante***********************
****************************Video link Queries*************************/

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE] WHERE CODE_ID = 7004 and ISNULL(DATA3_CAPTION,'') <> 'PLAN_ID' AND ISNULL(DATA3_TYPE,'') <> 'int')
BEGIN
	UPDATE [DBO].[SGS_CODE] 
	SET  DATA3_CAPTION = 'PLAN_ID', DATA3_TYPE = 'int', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_ID = 7004
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE  [CODE_ID] = 7004 and [CODE_VALUE] = 'PIGL' AND ISNULL(DATA3,'') <> '13')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '13', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17840
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE  [CODE_ID] = 7004 and [CODE_VALUE] = 'PEAP' AND ISNULL(DATA3,'') <> '14')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '14', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17841
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIDL' AND ISNULL(DATA3,'') <> '16')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '16', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17842
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIDC' AND ISNULL(DATA3,'') <> '19')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '19', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17843
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIFC' AND ISNULL(DATA3,'') <> '18')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '18', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17844
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIVP' AND ISNULL(DATA3,'') <> '17')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '17', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17846
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIGH' AND ISNULL(DATA3,'') <> '12')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '12', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17847
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIDB' AND DESCRIPTION <> 'NDPERS - Main Plan' AND ISNULL(DATA3,'') <> '1')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET    DESCRIPTION = 'NDPERS - Main Plan', DATA2 = 'NDPERS - Defined Benefit.mp4', DATA3 = '1', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17848
END
GO

IF EXISTS(SELECT 1 FROM [DBO].[SGS_CODE_VALUE] WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PDCP' AND ISNULL(DATA3,'') <> '7')
BEGIN
	UPDATE [DBO].[SGS_CODE_VALUE] 
	SET  DATA3 = '7', MODIFIED_DATE = GETDATE(), MODIFIED_BY = 'PIR 26955' 
	WHERE CODE_SERIAL_ID = 17849
END
GO


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PPSS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004, 'PPSS', 'NDPERS - Public Safety With Prior Service Plan', './MSSVideos/','NDPERS - Defined Benefit.mp4', '2', NULL, NULL, NULL, NULL, NULL, 'PIR 26955', GETDATE(), 'PIR 26955', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PING')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PING','NDPERS - National Guard Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','3',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIHP')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PIHP','NDPERS - Highway Patrol Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','4',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIJD')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PIJD','NDPERS - Judges Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','5',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIJS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PIJS','NDPERS - Job Service Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','6',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PSWS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PSWS','NDPERS - Public Safety Without Prior Service Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','20',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PBLE')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PBLE','NDPERS - BCI Law Enforcement Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','26',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIMA')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PIMA','NDPERS - Main 2020 Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','27',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PSPS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PSPS','NDPERS - State Public Safety Plan','./MSSVideos/','NDPERS - Defined Benefit.mp4','29',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PIOT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PIOT','NDPERS - Other 457/403(b) Plan','./MSSVideos/','NDPERS - Deferred Comp.mp4','8',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PDC20')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PDC20','NDPERS - Defined Contribution 2020 Plan','./MSSVideos/','NDPERS - Defined Contribution.mp4','28',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7004 and [CODE_VALUE] = 'PDC25')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7004,'PDC25','NDPERS - Defined Contribution 2025 Plan','./MSSVideos/','NDPERS - Defined Contribution.mp4','30',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

/****************************PDF link Queries*************************/

IF NOT EXISTS(SELECT 1 FROM SGS_CODE WHERE [CODE_ID] = 7036)
BEGIN
INSERT INTO SGS_CODE (CODE_ID, DESCRIPTION	,DATA1_CAPTION,	DATA1_TYPE,	DATA2_CAPTION,	DATA2_TYPE,	DATA3_CAPTION,	DATA3_TYPE,	FIRST_LOOKUP_ITEM,	FIRST_MAINTENANCE_ITEM,	COMMENTS,	LEGACY_CODE_ID,	CREATED_BY,	CREATED_DATE,	MODIFIED_BY,	MODIFIED_DATE,	UPDATE_SEQ)
VALUES(7036, 'MSS - PDF Links',	'PDF PATH',	'str', 	'PDF NAME', 'str', 'PLAN_ID',	'int',	'All',	NULL,	NULL,	NULL, 'PIR 26955',	GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIDB')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIDB','NDPERS - Main Plan','MSSHelpFiles\','1.pdf','1',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PPSS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PPSS','NDPERS - Public Safety With Prior Service Plan','MSSHelpFiles\','1.pdf','2',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PING')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PING','NDPERS - National Guard Plan','MSSHelpFiles\','1.pdf','3',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIHP')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIHP','NDPERS - Highway Patrol Plan','MSSHelpFiles\','1.pdf','4',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIJD')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIJD','NDPERS - Judges Plan','MSSHelpFiles\','1.pdf','5',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIJS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIJS','NDPERS - Job Service Plan','MSSHelpFiles\','1.pdf','6',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PDCP')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PDCP','NDPERS - Defined Contribution Plan','MSSHelpFiles\','7.pdf','7',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIOT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIOT','NDPERS - Other 457/403(b) Plan','MSSHelpFiles\','19.pdf','8',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIGH')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIGH','NDPERS - Health Plan','MSSHelpFiles\','12.pdf','12',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIGL')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIGL','NDPERS - Life Plan','MSSHelpFiles\','13.pdf','13',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PEAP')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PEAP','NDPERS - EAP Plan','MSSHelpFiles\','14.pdf','14',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIDL')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIDL','NDPERS - Dental Plan','MSSHelpFiles\','16.pdf','16',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIVP')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIVP','NDPERS - Vision Plan','MSSHelpFiles\','17.pdf','17',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIFC')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIFC','NDPERS - FlexComp Plan','MSSHelpFiles\','18.pdf','18',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIDC')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIDC','NDPERS - Deferred Comp Plan','MSSHelpFiles\','19.pdf','19',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PSWS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PSWS','NDPERS - Public Safety Without Prior Service Plan','MSSHelpFiles\','1.pdf','20',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PBLE')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PBLE','NDPERS - BCI Law Enforcement Plan','MSSHelpFiles\','1.pdf','26',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PIMA')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PIMA','NDPERS - Main 2020 Plan','MSSHelpFiles\','1.pdf','27',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PDC20')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PDC20','NDPERS - Defined Contribution 2020 Plan','MSSHelpFiles\','7.pdf','28',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PSPS')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PSPS','NDPERS - State Public Safety Plan','MSSHelpFiles\','1.pdf','29',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PDC25')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PDC25','NDPERS - Defined Contribution 2025 Plan','MSSHelpFiles\','30.pdf','30',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PAEH')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PAEH','NDPERS - Annual Enrollment Health Plan','MSSHelpFiles\','ANNE_12.pdf','12',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PAEL')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PAEL','NDPERS - Annual Enrollment Life Plan','MSSHelpFiles\','ANNE_13.pdf','13',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PAED')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PAED','NDPERS - Annual Enrollment Denatl Plan','MSSHelpFiles\','ANNE_16.pdf','16',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PAEV')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PAEV','NDPERS - Annual Enrollment Vision Plan','MSSHelpFiles\','ANNE_17.pdf','17',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE [CODE_ID] = 7036 and [CODE_VALUE] = 'PAEF')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7036,'PAEF','NDPERS - Annual Enrollment Flex Plan','MSSHelpFiles\','ANNE_18.pdf','18',NULL,NULL,NULL,NULL,NULL,'PIR 26955',GETDATE(),'PIR 26955',GETDATE(),0)
END
