--------------Created By: Vidya Fulsoundar
--------------Purpose   : PIR 25685
IF NOT EXISTS (SELECT 1 FROM SGS_BATCH_SCHEDULE WHERE [BATCH_SCHEDULE_ID]=162)
INSERT INTO SGS_BATCH_SCHEDULE ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS], [FREQUENCY_IN_MONTHS], [NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG], [REQUIRES_TRANSACTION_FLAG], [EMAIL_NOTIFICATION], [ORDER_NO], [CUTOFF_START], [CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(162,	1018,	'Annual 1099R Payment File Batch',	NULL,	NULL,	1,	GETDATE(),	NULL,	'Y',	'N',	NULL,	NULL,	NULL,	NULL,	'PIR 25685',	GETDATE(),	'PIR 25685',	GETDATE(),	0)
GO


/********************Purpose: PIR 25712******************************
*********************Created By: Saylee P********************************
*********************Comments: *****************/


SET IDENTITY_INSERT [dbo].[SGT_LIFE_REF_CONFIG] ON 
GO
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 1 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) 
VALUES (1, CAST(N'2023-07-01T00:00:00.000' AS DateTime), 347, N'NREM', 408, N'SPML', CAST(50000.00 AS Decimal(13, 2)), CAST(300000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(0.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, CAST(25000.00 AS Decimal(13, 2)))
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 2 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(2, CAST(N'2023-07-01T00:00:00.000' AS DateTime), 347, N'REME', 408, N'SPML', CAST(50000.00 AS Decimal(13, 2)), CAST(300000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(0.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, CAST(25000.00 AS Decimal(13, 2)))
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 3 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(3, CAST(N'2023-07-01T00:00:00.000' AS DateTime), 347, N'NREM', 408, N'SPSL', CAST(0.00 AS Decimal(13, 2)), CAST(100000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(50.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, NULL)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 4 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(4, CAST(N'2023-07-01T00:00:00.000' AS DateTime), 347, N'REME', 408, N'SPSL', CAST(0.00 AS Decimal(13, 2)), CAST(100000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(50.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, NULL)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 5 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(5, CAST(N'2005-07-01T00:00:00.000' AS DateTime), 347, N'NREM', 408, N'SPML', CAST(50000.00 AS Decimal(13, 2)), CAST(200000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(0.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, CAST(25000.00 AS Decimal(13, 2)))
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 6 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(6, CAST(N'2005-07-01T00:00:00.000' AS DateTime), 347, N'REME', 408, N'SPML', CAST(50000.00 AS Decimal(13, 2)), CAST(200000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(0.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, CAST(25000.00 AS Decimal(13, 2)))
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 7 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(7, CAST(N'2005-07-01T00:00:00.000' AS DateTime), 347, N'NREM', 408, N'SPSL', CAST(0.00 AS Decimal(13, 2)), CAST(50000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(50.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, NULL)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGT_LIFE_REF_CONFIG] WHERE [LIFE_REF_CONFIG_ID] = 8 ) 
BEGIN
INSERT [dbo].[SGT_LIFE_REF_CONFIG] ([LIFE_REF_CONFIG_ID], [EFFECTIVE_DATE], [LIFE_INSURANCE_TYPE_ID], [LIFE_INSURANCE_TYPE_VALUE], [LEVEL_OF_COVERAGE_ID], [LEVEL_OF_COVERAGE_VALUE], [PRE_TAX_LIMIT], [GI_LIMIT], [INCREMENT], [COVERAGE_LIMIT_PERCENTAGE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [INCREMENT_LIMIT]) VALUES 
(8, CAST(N'2005-07-01T00:00:00.000' AS DateTime), 347, N'REME', 408, N'SPSL', CAST(0.00 AS Decimal(13, 2)), CAST(50000.00 AS Decimal(13, 2)), CAST(5000.00 AS Decimal(13, 2)), CAST(50.00 AS Decimal(13, 2)), N'PIR 25712', GETDATE(), N'PIR 25712', GETDATE(), 0, NULL)
END
GO


SET IDENTITY_INSERT [dbo].[SGT_LIFE_REF_CONFIG] OFF
GO


--------------------------------------------------


UPDATE SGS_CODE_VALUE SET DESCRIPTION = '$2,000' WHERE CODE_ID = 1027 AND CODE_VALUE = '2000'
UPDATE SGS_CODE_VALUE SET DESCRIPTION = '$5,000' WHERE CODE_ID = 1027 AND CODE_VALUE = '5000'
UPDATE SGS_CODE_VALUE SET DESCRIPTION = '$7,000' WHERE CODE_ID = 1027 AND CODE_VALUE = '7000'
UPDATE SGS_CODE_VALUE SET DESCRIPTION = '$10,000' WHERE CODE_ID = 1027 AND CODE_VALUE = '10000'


----------------------------------------------------------------------------------------------------------------------------------------------------------

/********************Purpose: PIR 24755 ******************************
*********************Created By: Sanket C ********************************
*********************Comments: *****************/

UPDATE SGS_COR_TEMPLATES SET ASSOCIATED_FORMS = 'wfmPaymentElectionAdjustmentMaintenance;wfmPremiumDetailLTDMaintenance;wfmHealthDentalVisonMaintenance;', MODIFIED_BY = 'PIR 24755', MODIFIED_DATE = GETDATE() WHERE TEMPLATE_ID = 500


