
/********************Purpose: PIR 23634******************************
*********************Created By: Saylee Pujari********************************
*********************Comments:Created new message ID for Disability Application *****************/

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10426)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10426,'Death benefits for disability recipients must be processed as Pre-Retirement Death.',16,'E',NULL,NULL,'PIR 23634',GETDATE(),'PIR 23634',GETDATE(),0)
GO
/********************Purpose: PIR 24305******************************
*********************Created By: Nurul Gondane********************************
*********************Comments:wfmServicePurchaseHeaderMaintenance – On Save click – new soft (suppressible) error  *****************/
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10427)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10427,'Member is TFFR dual – FAS override required.',16,'W',NULL,NULL,'PIR 24305',GETDATE(),'PIR 24305',GETDATE(),0)
GO
/********************Purpose: PIR 19100 ******************************
*********************Created By: Abhijeet Malwadkar********************************
*********************Comments:SFN-53405 also needs to generate from wfmPersonEmploymentMaintenance *****************/
IF EXISTS(SELECT * FROM SGS_COR_TEMPLATES WHERE TEMPLATE_NAME = 'SFN-53405'  AND ASSOCIATED_FORMS = 'WFMPENSIONPLANMAINTENANCE;')
BEGIN
	UPDATE SGS_COR_TEMPLATES SET ASSOCIATED_FORMS = 'WFMPENSIONPLANMAINTENANCE;WFMPERSONEMPLOYMENTMAINTENANCE;' WHERE TEMPLATE_NAME = 'SFN-53405'
END
/********************Purpose: PIR 24243******************************
*********************Created By: Vidya Fulsoundar********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT * FROM  [dbo].[SGS_CODE] WHERE CODE_ID=7025)
INSERT INTO [dbo].[SGS_CODE]
           ([CODE_ID] ,[DESCRIPTION],[DATA1_CAPTION],[DATA1_TYPE],[DATA2_CAPTION],[DATA2_TYPE],[DATA3_CAPTION],[DATA3_TYPE],[FIRST_LOOKUP_ITEM]
           ,[FIRST_MAINTENANCE_ITEM],[COMMENTS],[LEGACY_CODE_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (7025
           ,'401(a) Limit For Eligible Wages'
           ,'Effective Date',NULL,'Amount',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PIR-24243' ,GETDATE() ,'PIR-24243',GETDATE(),0)
GO

IF NOT EXISTS (SELECT * FROM  [dbo].[SGS_CODE_VALUE] WHERE CODE_ID=7025 AND [CODE_VALUE] = 'EWLT')
INSERT INTO [dbo].[SGS_CODE_VALUE]
           ([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3],[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER]
           ,[LEGACY_CODE_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (7025  ,'EWLT'    ,'401(a) Limit For Eligible Wages'   ,'1/1/2021'  ,'290000' ,NULL ,NULL  ,NULL  ,NULL   ,1   ,NULL ,'PIR-24243' ,GETDATE() ,'PIR-24243',GETDATE()   ,0)
GO

IF NOT EXISTS (SELECT * FROM  [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID=10425)
INSERT INTO [dbo].[SGS_MESSAGES]
           ([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (10425,'Final Average Salary cannot be calculated. 401(a) limit applies.  Please contact the Retirement Programs Manager at NDPERS.', 16 ,'E' ,NULL ,NULL ,'PIR-24243' ,GETDATE() ,'PIR-24243' ,GETDATE() ,0)
GO	

/********************************************************************************
************************ New resource for Annual DB Contribution Limit ****************************
*********************************************************************************/

BEGIN
DECLARE @cnt INT
BEGIN TRANSACTION Trans
SELECT @cnt = count(*) FROM SGS_RESOURCES  WHERE RESOURCE_ID=2060 AND RESOURCE_DESCRIPTION='Annual DB Contribution Limit'; 
   if @cnt = 0   
   Begin    
       INSERT INTO SGS_RESOURCES ([RESOURCE_ID],[RESOURCE_TYPE_ID],[RESOURCE_TYPE_VALUE],[RESOURCE_DESCRIPTION],[CREATED_BY],[CREATED_DATE]
       ,[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
  VALUES
           (2060,12,'U','Annual DB Contribution Limit','PIR 24243',GETDATE(),'PIR 24243',GETDATE(),0)
   END
   ELSE 
   PRINT 'RESOURCE_ID 2060 and RESOURCE_DESCRIPTION Show System Preferences is alredy exist in SGS_RESOURCES table';
 COMMIT TRANSACTION Trans
 END

 --------------------------------------------------------------------------------------------------------------
 /* Insert query to assign New Resources to all ROLES */
 ---------------------------------------------------------------------------------------------------------------
 
BEGIN TRANSACTION Trans2
IF NOT EXISTS(SELECT 1 FROM SGS_SECURITY WHERE RESOURCE_ID = 2060)
BEGIN
INSERT INTO SGS_SECURITY
SELECT ROL.ROLE_ID, RES.RESOURCE_ID, 11, 1, 'PIR 24243', GETDATE(), 'PIR 24243', GETDATE(), 0
  FROM SGS_ROLES ROL, SGS_RESOURCES RES
 WHERE NOT EXISTS (SELECT ROLE_ID 
                     FROM SGS_SECURITY SEC
                    WHERE ROL.ROLE_ID = SEC.ROLE_ID
                      AND RES.RESOURCE_ID = SEC.RESOURCE_ID) AND RES.RESOURCE_ID = 2060
END
COMMIT TRANSACTION Trans2

BEGIN TRANSACTION TRANS3
IF EXISTS(SELECT 1 FROM SGS_SECURITY WHERE RESOURCE_ID = 2060 AND SECURITY_VALUE = 0)
BEGIN
UPDATE SGS_SECURITY SET SECURITY_VALUE = 1 WHERE RESOURCE_ID = 2060 AND SECURITY_VALUE = 0
END
COMMIT TRANSACTION TRANS3


/********************************************************************************
****** Update Deposit_ Date with created_date for Old Deposite Record ***********
*********************************************************************************/
IF EXISTS(SELECT * FROM SGT_DEPOSIT where DEPOSIT_DATE IS NULL AND DEPOSIT_TAPE_ID IS NULL )
BEGIN
	UPDATE SGT_DEPOSIT SET DEPOSIT_DATE=CREATED_DATE WHERE DEPOSIT_TAPE_ID IS NULL
END

GO
UPDATE SGT_DEPOSIT 
SET DEPOSIT_DATE=DT.DEPOSIT_DATE
FROM SGT_DEPOSIT_TAPE DT
WHERE DT.DEPOSIT_TAPE_ID=SGT_DEPOSIT.DEPOSIT_TAPE_ID


/********************Purpose: PIR 24305******************************
*********************Created By: Nurul Gondane********************************
*********************Comments:wfmServicePurchaseHeaderMaintenance – On Save click – new soft (suppressible) error  *****************/
IF  EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10427)
	UPDATE SGS_MESSAGES SET SEVERITY_VALUE='E' WHERE MESSAGE_ID=10427
GO
/********************Purpose: PIR 24310******************************
*********************Created By: Surendra Reddy ********************************
*********************Comments:wfmServicePurchaseHeaderMaintenance – On Save click – new hard (suppressible) error  *****************/
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10428)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10428,'Current Employment Is Temporary.',16,'W',NULL,NULL,'PIR 24310',GETDATE(),'PIR 24310',GETDATE(),0)
GO

/********************Purpose: PIR 23999******************************
*********************Created By: Abhijeet Malwadkar********************************
*********************Comments: *****************/

IF EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 1206 AND ISNULL(DATA2_CAPTION,'') = '')
	UPDATE [SGS_CODE] SET DATA2_CAPTION = 'Manual payroll?', DATA2_TYPE = 'str' WHERE CODE_ID = 1206
GO
IF EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1206 AND CODE_VALUE='REG' AND ISNULL(DATA2,'') = '' )
	UPDATE [SGS_CODE_VALUE] SET DATA2 = 'Y' WHERE CODE_ID = 1206 AND CODE_VALUE='REG'
GO
IF EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1206 AND CODE_VALUE='ADJS' AND ISNULL(DATA2,'') = '')
	UPDATE [SGS_CODE_VALUE] SET DATA2 = 'Y' WHERE CODE_ID = 1206 AND CODE_VALUE='ADJS'
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 1206 AND CODE_VALUE='PEN')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(1206,'PEN','Penalty',3,'N',null,null,null,null,null
           ,NULL,'PIR 23999',GETDATE(),'PIR 23999',GETDATE(),0)
GO


SET IDENTITY_INSERT [dbo].[SGS_CODE_VALUE] ON
GO
	IF NOT EXISTS (SELECT * FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7023)
		INSERT dbo.SGS_CODE ([CODE_ID],[DESCRIPTION],[DATA1_CAPTION],[DATA1_TYPE],[DATA2_CAPTION],[DATA2_TYPE],[DATA3_CAPTION],[DATA3_TYPE],[FIRST_LOOKUP_ITEM],[FIRST_MAINTENANCE_ITEM],[COMMENTS],[LEGACY_CODE_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
		VALUES
		(7023,'Penalty header contribution calculation','Effective Date','date','Amount','int','Percentage','int',null,NULL,'Penalty Header contribution calculation',NULL,'PIR 23999',GETDATE(),'PIR 23999',GETDATE(),0)
	GO
SET IDENTITY_INSERT [dbo].[SGS_CODE_VALUE] OFF
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 7023 AND CODE_VALUE='PNLT')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(7023,'PNLT','Penalty header contribution calculation','07/01/2021','50','1',null,null,null,null
           ,NULL,'PIR 23999',GETDATE(),'PIR 23999',GETDATE(),0)
GO



IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10420)
	INSERT [SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], 
							[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (10420,N'Penalty header already exists.', 16, N'E', NULL, NULL, N'PIR 23999', GETDATE(), N'PIR 23999', GETDATE(), 0)
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10421)
	INSERT [SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], 
							[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (10421,N'Penalty Header Created Successfully.', 16, N'E', NULL, NULL, N'PIR 23999', GETDATE(), N'PIR 23999', GETDATE(), 0)
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10422)
	INSERT [SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], 
							[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (10422,N'Penalty Header Approved Successfully.', 16, N'E', NULL, NULL, N'PIR 23999', GETDATE(), N'PIR 23999', GETDATE(), 0)
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID = 10423)
	INSERT [SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], 
							[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (10423,N'Penalty Header Ignored Successfully.', 16, N'E', NULL, NULL, N'PIR 23999', GETDATE(), N'PIR 23999', GETDATE(), 0)
GO
/********************************************************************************
************************ New work flow process and activity ****************************
*********************************************************************************/
IF NOT EXISTS (SELECT * FROM SGW_PROCESS WHERE PROCESS_ID = 374)
INSERT [SGW_PROCESS] ([PROCESS_ID], [DESCRIPTION], [NAME], [PRIORITY], [TYPE_ID], [TYPE_VALUE], [STATUS_ID], [STATUS_VALUE], [USE_NEW_MAP_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (374, N'Process Employer Report Penalty', N'nfmProcessEmployerReportPenalty', 0, 1603, N'ORGN', 5003, N'ACT', NULL, 'PIR 23999', GETDATE(), 'PIR 23999', GETDATE(), 0)
GO

IF NOT EXISTS (SELECT * FROM SGW_ACTIVITY WHERE PROCESS_ID = 374 AND ACTIVITY_ID = 341) 
INSERT [SGW_ACTIVITY] ([ACTIVITY_ID], [PROCESS_ID], [NAME], [DISPLAY_NAME], [STANDARD_TIME_IN_MINUTES], [ROLE_ID], [SUPERVISOR_ROLE_ID], [SORT_ORDER], [IS_DELETED_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (341, 374, N'Approve Employer Report Penalty', N'Approve Employer Report Penalty', 300, 140, 148, 1, NULL, 'PIR 23999', GETDATE(), 'PIR 23999', GETDATE(), 0)
GO

/********************************************************************************
************************ New resource for work flow process and activity to approve and cancel Penalty Approve Penalty****************************
*********************************************************************************/

BEGIN
DECLARE @cnt INT
BEGIN TRANSACTION Trans
SELECT @cnt = count(*) FROM SGS_RESOURCES  WHERE RESOURCE_ID=2058 AND RESOURCE_DESCRIPTION='Approve Penalty'; 
   if @cnt = 0   
   Begin    
	   INSERT INTO SGS_RESOURCES ([RESOURCE_ID],[RESOURCE_TYPE_ID],[RESOURCE_TYPE_VALUE],[RESOURCE_DESCRIPTION],[CREATED_BY],[CREATED_DATE]
	   ,[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
  VALUES
           (2058,12,'U','Approve Penalty','PIR 23999',GETDATE(),'PIR 23999',GETDATE(),0)
   END
   ELSE 
   PRINT 'RESOURCE_ID 2058 and RESOURCE_DESCRIPTION Show System Preferences is alredy exist in SGS_RESOURCES table';
 COMMIT TRANSACTION Trans
 END



 --------------------------------------------------------------------------------------------------------------
 /* Insert query to assign New Resources to all ROLES */
 ---------------------------------------------------------------------------------------------------------------
 
 BEGIN TRANSACTION Trans2

INSERT INTO SGS_SECURITY
SELECT ROL.ROLE_ID, RES.RESOURCE_ID, 11, 0, 'PIR 23999', GETDATE(), 'PIR 23999', GETDATE(), 0
  FROM SGS_ROLES ROL, SGS_RESOURCES RES
 WHERE NOT EXISTS (SELECT ROLE_ID 
                     FROM SGS_SECURITY SEC
                    WHERE ROL.ROLE_ID = SEC.ROLE_ID
                      AND RES.RESOURCE_ID = SEC.RESOURCE_ID) AND RES.RESOURCE_ID = 2058

COMMIT TRANSACTION Trans2

/********************************************************************************
************************ New resource for work flow process and activity to approve and cancel Penalty Approve Penalty****************************
*********************************************************************************/

BEGIN
DECLARE @cnt1 INT
BEGIN TRANSACTION Trans
SELECT @cnt1 = count(*) FROM SGS_RESOURCES  WHERE RESOURCE_ID=2059 AND RESOURCE_DESCRIPTION='Cancel Penalty'; 
   if @cnt1 = 0   
   Begin    
	   INSERT INTO SGS_RESOURCES ([RESOURCE_ID],[RESOURCE_TYPE_ID],[RESOURCE_TYPE_VALUE],[RESOURCE_DESCRIPTION],[CREATED_BY],[CREATED_DATE]
	   ,[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
  VALUES
           (2059,12,'U','Cancel Penalty','PIR 23999',GETDATE(),'PIR 23999',GETDATE(),0)
   END
   ELSE 
   PRINT 'RESOURCE_ID 2059 and RESOURCE_DESCRIPTION Show System Preferences is alredy exist in SGS_RESOURCES table';
 COMMIT TRANSACTION Trans
 END



 --------------------------------------------------------------------------------------------------------------
 /* Insert query to assign New Resources to all ROLES */
 ---------------------------------------------------------------------------------------------------------------
 
 BEGIN TRANSACTION Trans2

INSERT INTO SGS_SECURITY
SELECT ROL.ROLE_ID, RES.RESOURCE_ID, 11, 0, 'PIR 23999', GETDATE(), 'PIR 23999', GETDATE(), 0
  FROM SGS_ROLES ROL, SGS_RESOURCES RES
 WHERE NOT EXISTS (SELECT ROLE_ID 
                     FROM SGS_SECURITY SEC
                    WHERE ROL.ROLE_ID = SEC.ROLE_ID
                      AND RES.RESOURCE_ID = SEC.RESOURCE_ID) AND RES.RESOURCE_ID = 2059

COMMIT TRANSACTION Trans2

SET IDENTITY_INSERT [SGT_CHART_OF_ACCOUNT] ON 
GO
IF NOT EXISTS (SELECT 1 FROM [SGT_CHART_OF_ACCOUNT] WHERE GL_ACCOUNT_NUMBER = '463045')
INSERT [SGT_CHART_OF_ACCOUNT] ([CHART_OF_ACCOUNT_ID], [GL_ACCOUNT_NUMBER], [ACCOUNT_TYPE_ID], [ACCOUNT_TYPE_VALUE], [ACCOUNT_NAME], [EFFECTIVE_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) VALUES (255, N'463045', 1306, N'REVE', N'PERS-Penalties', CAST(N'2021-07-01T00:00:00.000' AS DateTime), N'dhohbein', CAST(N'2021-07-27T09:11:55.927' AS DateTime), N'dhohbein', CAST(N'2021-07-27T09:11:55.927' AS DateTime), 0)
GO
SET IDENTITY_INSERT [SGT_CHART_OF_ACCOUNT] OFF
GO

--------------------------APPROVED PENALTY ACCOUNT REFERENCES START--------------------------------
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 1 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'STAT' AND STATUS_TRANSITION_VALUE = 'APVD' 
				AND DEBIT_ACCOUNT_ID = 26 AND CREDIT_ACCOUNT_ID = 255)
INSERT INTO [DBO].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (1,1300,'483',1301,'1001',1302,'CNTR',1302,NULL,1302,NULL,1303,'STAT',1309,'APVD',1304,'EMPR','1',26,255,'JOURNAL DESCRIPTION TEXT','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 1 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'TRAN' AND STATUS_TRANSITION_VALUE = 'APVD' 
				AND DEBIT_ACCOUNT_ID = 10 AND CREDIT_ACCOUNT_ID = 10)
INSERT INTO [dbo].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (1,1300,'483',1301,'1001',1302,'CNTR',1302,null,1302,null,1303,'TRAN',1309,'APVD',1304,'EMPR','1',10,10,'Journal Description Text','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 12 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'STAT' AND STATUS_TRANSITION_VALUE = 'APVD' 
				AND DEBIT_ACCOUNT_ID = 26 AND CREDIT_ACCOUNT_ID = 255)
INSERT INTO [DBO].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (12,1300,'470',1301,'2001',1302,'GHLT',1302,NULL,1302,NULL,1303,'STAT',1309,'APVD',1304,'EMPR','1',26,255,'JOURNAL DESCRIPTION TEXT','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 12 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'TRAN' AND STATUS_TRANSITION_VALUE = 'APVD' 
				AND DEBIT_ACCOUNT_ID = 10 AND CREDIT_ACCOUNT_ID = 10)
INSERT INTO [dbo].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (12,1300,'470',1301,'2001',1302,'GHLT',1302,null,1302,null,1303,'TRAN',1309,'APVD',1304,'EMPR','1',10,10,'Journal Description Text','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO

--------------------------APPROVED PENALTY ACCOUNT REFERENCES END--------------------------------

--------------------------CANCELED PENALTY ACCOUNT REFERENCES START--------------------------------
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 1 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'STAT' AND STATUS_TRANSITION_VALUE = 'CNCL' 
				AND DEBIT_ACCOUNT_ID = 255 AND CREDIT_ACCOUNT_ID = 26)
INSERT INTO [DBO].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (1,1300,'483',1301,'1001',1302,'CNTR',1302,NULL,1302,NULL,1303,'STAT',1309,'CNCL',1304,'EMPR','1',255,26,'JOURNAL DESCRIPTION TEXT','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 1 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'TRAN' AND STATUS_TRANSITION_VALUE = 'CNCL'
				AND DEBIT_ACCOUNT_ID = 10 AND CREDIT_ACCOUNT_ID = 10)
INSERT INTO [dbo].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (1,1300,'483',1301,'1001',1302,'CNTR',1302,null,1302,null,1303,'TRAN',1309,'CNCL',1304,'EMPR','1',10,10,'Journal Description Text','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 12 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'STAT' AND STATUS_TRANSITION_VALUE = 'CNCL' 
				AND DEBIT_ACCOUNT_ID = 255 AND CREDIT_ACCOUNT_ID = 26)
INSERT INTO [DBO].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (12,1300,'470',1301,'2001',1302,'GHLT',1302,NULL,1302,NULL,1303,'STAT',1309,'CNCL',1304,'EMPR','1',255,26,'JOURNAL DESCRIPTION TEXT','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO
IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID = 12 AND SOURCE_TYPE_VALUE = 'EMPR' AND TRANSACTION_TYPE_VALUE = 'TRAN' AND STATUS_TRANSITION_VALUE = 'CNCL'
				AND DEBIT_ACCOUNT_ID = 10 AND CREDIT_ACCOUNT_ID = 10)
INSERT INTO [dbo].[SGT_ACCOUNT_REFERENCE]
           ([PLAN_ID],[FUND_ID],[FUND_VALUE],[DEPT_ID],[DEPT_VALUE],[ITEM_TYPE_ID],[ITEM_TYPE_VALUE],[FROM_ITEM_TYPE_ID],[FROM_ITEM_TYPE_VALUE],[TO_ITEM_TYPE_ID]
           ,[TO_ITEM_TYPE_VALUE],[TRANSACTION_TYPE_ID],[TRANSACTION_TYPE_VALUE],[STATUS_TRANSITION_ID],[STATUS_TRANSITION_VALUE],[SOURCE_TYPE_ID],[SOURCE_TYPE_VALUE]
           ,[GENERATE_GL_FLAG],[DEBIT_ACCOUNT_ID],[CREDIT_ACCOUNT_ID],[JOURNAL_DESCRIPTION],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
           (12,1300,'470',1301,'2001',1302,'GHLT',1302,null,1302,null,1303,'TRAN',1309,'CNCL',1304,'EMPR','1',10,10,'Journal Description Text','PIR_23999',GETDATE()
		   ,'PIR_23999',GETDATE(),0)
GO

--------------------------CANCELED PENALTY ACCOUNT REFERENCES END--------------------------------
