
DECLARE @PLAN_ID INT = 29
-------------------------Mentioned in PIR Document ----------------
IF EXISTS(SELECT 1 FROM SGT_PLAN WHERE PLAN_ID=26 AND PLAN_NAME != 'BCI Law Enforcement')
BEGIN
UPDATE SGT_PLAN SET PLAN_NAME = 'BCI Law Enforcement', ACTUARY_NAME='BCI Law Enforcement', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE PLAN_ID=26
END

IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_PROVISION WHERE [SHORT_DECRIPTION] = 'State Public Safety')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION ( [SHORT_DECRIPTION], [DESCRIPTION])
VALUES( 'State Public Safety', 'Provision for State Public Safety')
END


IF NOT EXISTS(SELECT 1 FROM SGT_PLAN WHERE [PLAN_NAME] = 'State Public Safety')
BEGIN
INSERT INTO SGT_PLAN ( [PLAN_NAME], [BENEFIT_TYPE_ID], [BENEFIT_TYPE_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PLAN_CODE], [ALLOW_NEW_MEMBER_ENROLL_FLAG], [ALLOW_DEPOSIT_FLAG], 
[ALLOW_NEW_EMPLOYER_FLAG], [ALLOW_PROVIDER_FLAG], [BANK_ACCOUNT_TYPE_ID], [BANK_ACCOUNT_TYPE_VALUE], [RETIREMENT_TYPE_ID], [RETIREMENT_TYPE_VALUE], [ALLOW_INTEREST_POSTING], [ALLOW_PEP_CALCULATION], [VSC_THRESHOLD_MONTHS], [SORT_ORDER], [BENEFIT_PROVISION_ID], [APPLY_RHIC_FLAG], [INCLUDE_IN_RETIREE_ANNUAL_STATEMENT_FLAG], [ACTUARY_NAME])
VALUES(	'State Public Safety',250,	'RETR',	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	1,	'STLE',	'Y',	'Y',	'Y',	'N',	1201,	'RETR',	251,	'DB',	1,	1,	36,	5,	13,	'N',	'Y',	'State Law Enforcement')
END


IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_PROVISION_MULTIPLIER WHERE [BENEFIT_PROVISION_ID] = 10 and [EFFECTIVE_DATE]='2023-08-01 00:00:00.000')
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_MULTIPLIER ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], 
[BENEFIT_ACCOUNT_TYPE_VALUE], [SERVICE_FROM], [SERVICE_TO], [MULTIPIER_PERCENTAGE], [TIER_NUMBER], [COMMENTS], [IS_FLAT_PERCENTAGE_FLAG], [ISCONVERSION])
VALUES(10,	'2023-08-01 00:00:00.000',	1904,	'RETR',	0,	20,	3.000000,	1,	'LE with Prior Service 1st 20 Years',	'N',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	'RETR',	20,	999,	1.750000,	2,	'LE with Prior Service for each Year',	'N',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	NULL,	0,	20, 	3.000000,	1,	'LE with Prior Service 1st 20 Years',	'N',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	NULL,	20,	999, 	1.750000,	2,	'LE with Prior Service for each Year',	'N',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	'DISA',	NULL,	NULL, 	0.000000,	1,	'LE with Prior Service 1st 20 Years',	'Y',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	'DETH',	0,	20,	3.000000,	1,	'LE with Prior Service 1st 20 Years',	'N',	'N'),
(10,	'2023-08-01 00:00:00.000',	1904,	'DETH',	20,	999,	1.750000,	2,	'LE with Prior Service for each Year',	'N',	'N')
END

IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_PROVISION_MULTIPLIER WHERE [BENEFIT_PROVISION_ID] = 13)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_MULTIPLIER ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], 
[BENEFIT_ACCOUNT_TYPE_VALUE], [SERVICE_FROM], [SERVICE_TO], [MULTIPIER_PERCENTAGE], [TIER_NUMBER], [COMMENTS], [IS_FLAT_PERCENTAGE_FLAG], [ISCONVERSION])
VALUES(13,	'1900-01-01 00:00:00.000',	1904,	NULL,	0,	999, 	2.000000,	1,	'State Public Safety',	'N',	'N'),
(13,	'1900-01-01 00:00:00.000',	1904,	'DISA',	NULL,	NULL, 	25.000000,	1,	'State Public Safety for each Year',	'Y',	'N'),
(13,	'1900-01-01 00:00:00.000',	1904,	'RETR',	0,	999,	2.000000,	1,	'State Public Safety for each Year',	'N',	'N'),
(13,	'1900-01-01 00:00:00.000',	1904,	'DETH',	0,	999,	2.000000,	1,	'State Public Safety for each Year',	'N',	'N'),
(13,	'2020-01-01 00:00:00.000',	1904,	NULL,	0,	999, 	1.750000,	1,	'State Public Safety',	'N',	'N'),
(13,	'2020-01-01 00:00:00.000',	1904,	'RETR',	0,	999,	1.750000,	1,	'State Public Safety for each Year',	'N',	'N'),
(13,	'2020-01-01 00:00:00.000',	1904,	'DETH',	0,	999,	1.750000,	1,	'State Public Safety for each Year',	'N',	'N')
END


--Creating Org Plan records for Org IDs 6,30,156,165,166,287,293,300,411,423
IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 6 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(6,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 30 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(30,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 156 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(156,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 166 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(166,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 287 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(287,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 293 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(293,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 300 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(300,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 411 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(411,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN WHERE ORG_ID = 423 AND PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_ORG_PLAN ([ORG_ID], [PLAN_ID], [PARTICIPATION_START_DATE], [PARTICIPATION_END_DATE], [REPORT_FREQUENCY_ID], [REPORT_FREQUENCY_VALUE], [COMMENTS], [PLAN_OPTION_ID], [PLAN_OPTION_VALUE], 
[WELLNESS_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [PRE_TAX_PURCHASE], [RESTRICTION], [HEALTH_PARTICIPATION_START_DATE], [ALTERNATE_STRUCTURE_CODE_ID], [ALTERNATE_STRUCTURE_CODE_VALUE], [HSA_PRE_TAX_AGREEMENT], [DAY_OF_MONTH])
VALUES(423,@PLAN_ID,'1966-07-01 00:00:00.000',NULL,405,NULL,NULL,406,NULL,'N','PIR 25729', GETDATE(),'PIR 25729',GETDATE(),0,NULL,'N',NULL,5010,NULL,NULL,NULL)
END


-- Inserting New Member Type 
IF NOT EXISTS (select 1 from SGS_CODE_VALUE where CODE_ID= 320 and CODE_VALUE = 'SPS1')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(320,	'SPS1',	'State Public Safety Regular 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0)
END


-- linking all Mmember Types to plan ID 29 currently linked in plan ID 26 with same effective dates (BCL1 & BCL2 were never used so don't have to create for the new plan)
IF NOT EXISTS (SELECT 1 FROM SGT_PLAN_MEMBER_TYPE_CROSSREF WHERE PLAN_ID = @PLAN_ID)
BEGIN
INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF ([PLAN_ID], [JOB_CLASS_ID], [JOB_CLASS_VALUE], [EMPLOYMENT_TYPE_ID], [EMPLOYMENT_TYPE_VALUE], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE])
SELECT @PLAN_ID, [JOB_CLASS_ID],CASE WHEN [MEMBER_TYPE_VALUE] ='NRG1' THEN 'NGSF' ELSE  'PEAO' END, [EMPLOYMENT_TYPE_ID], [EMPLOYMENT_TYPE_VALUE], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE] FROM SGT_PLAN_MEMBER_TYPE_CROSSREF  WHERE PLAN_ID=26 and MEMBER_TYPE_VALUE IN (SELECT DISTINCT MEMBER_TYPE_VALUE FROM SGT_PLAN_MEMBER_TYPE_CROSSREF  WHERE PLAN_ID=26 AND MEMBER_TYPE_VALUE NOT IN ('BCL1','BCL2'))
END


IF NOT EXISTS (SELECT 1 FROM SGT_PLAN_MEMBER_TYPE_CROSSREF WHERE PLAN_ID=@PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_PLAN_MEMBER_TYPE_CROSSREF ([PLAN_ID], [JOB_CLASS_ID], [JOB_CLASS_VALUE], [EMPLOYMENT_TYPE_ID], [EMPLOYMENT_TYPE_VALUE], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE])
VALUES(@PLAN_ID, 314, 'PEAO', 313, 'PERM', 320, 'SPS1')
END


DECLARE @ORG_PLAN_ID INT; --6,30,156,165,166,287,293,300,411,423
SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 6 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 30 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 156 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 166 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 287 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 293 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 300 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 411 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


SELECT @ORG_PLAN_ID = ORG_PLAN_ID FROM SGT_ORG_PLAN WHERE ORG_ID = 423 AND PLAN_ID = @PLAN_ID

IF NOT EXISTS (SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE WHERE [ORG_PLAN_ID]=@ORG_PLAN_ID AND [MEMBER_TYPE_VALUE] = 'SPS1')
BEGIN
INSERT INTO SGT_ORG_PLAN_MEMBER_TYPE ([ORG_PLAN_ID], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [START_DATE], [END_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(@ORG_PLAN_ID, 320, 'SPS1','08/01/2023', NULL, 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0) 
END


-- INSERTING MEMBER TYPES RATE IN [SGT_PLAN_RETIREMENT_RATE] TABLE
IF NOT EXISTS(SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE [MEMBER_TYPE_VALUE] = 'BCL4' AND [EFFECTIVE_DATE] = '08/01/2023' AND PLAN_ID=26)
BEGIN
INSERT INTO [SGT_PLAN_RETIREMENT_RATE] ([PLAN_ID], [EFFECTIVE_DATE], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [EE_PRE_TAX], [EE_POST_TAX], [EE_EMP_PICKUP], [EE_RHIC], [ER_POST_TAX], [ER_RHIC], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [ADDL_EE_PRE_TAX], [ADDL_EE_POST_TAX], [ADDL_EE_EMP_PICKUP])
VALUES(26, '08/01/2023', 320, 'BCL4',	2.0000,	NULL,	4.0000,	NULL,	20.67,	1.14,	'PIR 25729',	GETDATE(),	'PIR 25729', GETDATE(),	0,	2.0000,	NULL, NULL)
END


IF NOT EXISTS(SELECT 1 FROM [SGT_PLAN_RETIREMENT_RATE] WHERE [MEMBER_TYPE_VALUE] = 'SPS1' AND [EFFECTIVE_DATE] = '08/01/2023' AND PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO [SGT_PLAN_RETIREMENT_RATE] ([PLAN_ID], [EFFECTIVE_DATE], [MEMBER_TYPE_ID], [MEMBER_TYPE_VALUE], [EE_PRE_TAX], [EE_POST_TAX], [EE_EMP_PICKUP], [EE_RHIC], [ER_POST_TAX], [ER_RHIC], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [ADDL_EE_PRE_TAX], [ADDL_EE_POST_TAX], [ADDL_EE_EMP_PICKUP])
VALUES(@PLAN_ID, '08/01/2023',	320, 'SPS1',	2.0000,	NULL,	4.0000,	NULL,	12.75,	1.14, 'PIR 25729',	GETDATE(),	'PIR 25729', GETDATE(),	0,	2.0000,	NULL, NULL)
END

IF NOT EXISTS(SELECT 1 FROM SGT_PLAN_EMP_CATEGORY_CROSSREF WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_PLAN_EMP_CATEGORY_CROSSREF ([PLAN_ID], [EMP_CATEGORY_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [EMP_CATEGORY_VALUE], [REQUIRED_FLAG_OPTION_ID], [REQUIRED_FLAG_OPTION_VALUE])
SELECT @PLAN_ID, [EMP_CATEGORY_ID], 'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0, [EMP_CATEGORY_VALUE], [REQUIRED_FLAG_OPTION_ID], [REQUIRED_FLAG_OPTION_VALUE] FROM SGT_PLAN_EMP_CATEGORY_CROSSREF WHERE PLAN_ID= 26
END

IF NOT EXISTS(SELECT 1 FROM SGT_PLAN_EMP_CATEGORY_CROSSREF WHERE PLAN_ID=@PLAN_ID AND EMP_CATEGORY_VALUE = 'STAT')
BEGIN
INSERT INTO SGT_PLAN_EMP_CATEGORY_CROSSREF ([PLAN_ID], [EMP_CATEGORY_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [EMP_CATEGORY_VALUE], [REQUIRED_FLAG_OPTION_ID], [REQUIRED_FLAG_OPTION_VALUE])
VALUES(@PLAN_ID,	203,	'PIR 25729', GETDATE(),'PIR 25729',GETDATE(), 0,	'STAT',	403, 'MAND')
END

IF NOT EXISTS(SELECT 1 FROM SGT_PLAN_JOB_CLASS_CROSSREF WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_PLAN_JOB_CLASS_CROSSREF ([PLAN_ID], [JOB_TYPE_ID], [JOB_TYPE_VALUE], [JOB_CLASS_ID], [JOB_CLASS_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [DC_TRANSFER_ELIGIBLE])
SELECT @PLAN_ID, [JOB_TYPE_ID], [JOB_TYPE_VALUE], [JOB_CLASS_ID], [JOB_CLASS_VALUE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0, [DC_TRANSFER_ELIGIBLE] FROM SGT_PLAN_JOB_CLASS_CROSSREF WHERE PLAN_ID=26
END

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_PEOPLESOFT_PLAN_CROSS_REF ([PLAN_ID], [DESCRIPTION], [LEVEL_OF_COVERAGE_VALUE], [INSURANCE_TYPE_VALUE], [EMP_TYPE_VALUE], [PLAN_OPTION_VALUE], [WELLNESS_FLAG], [LTC_RELATIONSHIP_VALUE], [MEMBER_TYPE_VALUE], [CHECK_FLEX_COMP_PLAN], [PROVIDER_ORG_CODE], [PLAN_DTL], [FULL_DESCRIPTION], [PLAN_TYPE], [F13], [BENEFIT_PLAN], [COVERAGE_BEGIN_DATE_REQUIRED], [DEDUCTION_BEGIN_DATE_REQUIRED], [COVERAGE_ELECTION_REQUIRED], [ELECTION_DATE_REQUIRED], [BENEFIT_PLAN_REQUIRED], [COVERGAE_CODE_REQUIRED], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [COVERAGE_AMOUNT], [FLAT_AMOUNT_REQUIRED], [PRINT_COVERAGE_AMOUNT_IN_FLAT_AMOUNT], [CALCULATION_ROUTINE_REQUIRED], [RHIC_PLAN_TYPE], [RHIC_BENEFIT_PLAN])
SELECT @PLAN_ID, 'State Public Safety Plan', [LEVEL_OF_COVERAGE_VALUE], [INSURANCE_TYPE_VALUE], [EMP_TYPE_VALUE], [PLAN_OPTION_VALUE], [WELLNESS_FLAG], [LTC_RELATIONSHIP_VALUE], [MEMBER_TYPE_VALUE], [CHECK_FLEX_COMP_PLAN], [PROVIDER_ORG_CODE], 'STLE', [FULL_DESCRIPTION], [PLAN_TYPE], [F13], [BENEFIT_PLAN], [COVERAGE_BEGIN_DATE_REQUIRED], [DEDUCTION_BEGIN_DATE_REQUIRED], [COVERAGE_ELECTION_REQUIRED], [ELECTION_DATE_REQUIRED], [BENEFIT_PLAN_REQUIRED], [COVERGAE_CODE_REQUIRED], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0, [COVERAGE_AMOUNT], [FLAT_AMOUNT_REQUIRED], [PRINT_COVERAGE_AMOUNT_IN_FLAT_AMOUNT], [CALCULATION_ROUTINE_REQUIRED], [RHIC_PLAN_TYPE], [RHIC_BENEFIT_PLAN] FROM [SGT_PEOPLESOFT_PLAN_CROSS_REF] WHERE PLAN_ID=26
END

IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF ([PLAN_ID], [PEOPLE_SOFT_ORG_GROUP_ID], [PEOPLE_SOFT_ORG_GROUP_VALUE], [PEOPLE_SOFT_FILE_DATE_TYPE_ID], [PEOPLE_SOFT_FILE_DATE_TYPE_VALUE], [PEOPLE_SOFT_FILE_DATE_ID], [PEOPLE_SOFT_FILE_DATE_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [ORG_CODE], [PS_FILE_CHANGE_EVENT_ID], [PS_FILE_CHANGE_EVENT_VALUE], [PS_COVERAGE_ELECTION_ID], [PS_COVERAGE_ELECTION_VALUE])
SELECT @PLAN_ID, [PEOPLE_SOFT_ORG_GROUP_ID], [PEOPLE_SOFT_ORG_GROUP_VALUE], [PEOPLE_SOFT_FILE_DATE_TYPE_ID], [PEOPLE_SOFT_FILE_DATE_TYPE_VALUE], [PEOPLE_SOFT_FILE_DATE_ID], [PEOPLE_SOFT_FILE_DATE_VALUE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0, [ORG_CODE], [PS_FILE_CHANGE_EVENT_ID], [PS_FILE_CHANGE_EVENT_VALUE], [PS_COVERAGE_ELECTION_ID], [PS_COVERAGE_ELECTION_VALUE] FROM SGT_PEOPLESOFT_PLAN_ORG_CROSS_REF WHERE PLAN_ID=26
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'USSB')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'USSB',	'State - Univerity System State',	'STAT',	'PEAO',	'022700',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'USSC')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'USSC',	'State - Univerity System State',	'STAT',	'PEAO',	'023000',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'USSD')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'USSD',	'State - Univerity System State',	'STAT',	'PEAO',	'023500',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'USSE')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'USSE',	'State - Univerity System State',	'STAT',	'PEAO',	'023800',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'SPO1')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'SPO1',	'State - Peace Officer',	'STAT',	'PEAO',	'040100',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'SPO2')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'SPO2',	'State - Peace Officer',	'STAT',	'PEAO',	'050200',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'SPO3')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'SPO3',	'State - Peace Officer',	'STAT',	'PEAO',	'072000',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=322 AND CODE_VALUE = 'SPO4')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(322,	'SPO4',	'State - Peace Officer',	'STAT',	'PEAO',	'075000',	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

--The following also need to have plan ID 26 information duplicated for the new plan:  
--SGT_ACCOUNT_REFERENCE
IF NOT EXISTS(SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE [PLAN_ID]=@PLAN_ID)
BEGIN
INSERT INTO SGT_ACCOUNT_REFERENCE ([PLAN_ID], [FUND_ID], [FUND_VALUE], [DEPT_ID], [DEPT_VALUE], [ITEM_TYPE_ID], [ITEM_TYPE_VALUE], [FROM_ITEM_TYPE_ID], [FROM_ITEM_TYPE_VALUE], [TO_ITEM_TYPE_ID], [TO_ITEM_TYPE_VALUE], [TRANSACTION_TYPE_ID], [TRANSACTION_TYPE_VALUE], [STATUS_TRANSITION_ID], [STATUS_TRANSITION_VALUE], [SOURCE_TYPE_ID], [SOURCE_TYPE_VALUE], [GENERATE_GL_FLAG], [DEBIT_ACCOUNT_ID], [CREDIT_ACCOUNT_ID], [JOURNAL_DESCRIPTION], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
SELECT  @PLAN_ID, [FUND_ID], [FUND_VALUE], [DEPT_ID], [DEPT_VALUE], [ITEM_TYPE_ID], [ITEM_TYPE_VALUE], [FROM_ITEM_TYPE_ID], [FROM_ITEM_TYPE_VALUE], [TO_ITEM_TYPE_ID], [TO_ITEM_TYPE_VALUE], [TRANSACTION_TYPE_ID], [TRANSACTION_TYPE_VALUE], [STATUS_TRANSITION_ID], [STATUS_TRANSITION_VALUE], [SOURCE_TYPE_ID], [SOURCE_TYPE_VALUE], [GENERATE_GL_FLAG], [DEBIT_ACCOUNT_ID], [CREDIT_ACCOUNT_ID], [JOURNAL_DESCRIPTION], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0 FROM SGT_ACCOUNT_REFERENCE WHERE PLAN_ID=26
END

--SGT_BENEFIT_PROVISION_BENEFIT_OPTION
IF NOT EXISTS(SELECT 1 FROM [SGT_BENEFIT_PROVISION_BENEFIT_OPTION] WHERE [BENEFIT_PROVISION_ID]=13)
BEGIN
INSERT INTO [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_OPTION] ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE], 
[FACTOR_METHOD_ID], [FACTOR_METHOD_VALUE], [OPTION_FACTOR], [SPOUSE_FACTOR], [SSLI_FLAG], [SSLI_FACTOR_METHOD_ID], [SSLI_FACTOR_METHOD_VALUE], [SSLI_FACTOR], [EXCLUSIVE_CALC_PAYMENT_TYPE_ID],
 [EXCLUSIVE_CALC_PAYMENT_TYPE_VALUE], [POST_RETIREMENT_DEATH_REASON_TYPE_ID], [POST_RETIREMENT_DEATH_REASON_TYPE_VALUE], [SINGLE], [MARRIED]) 
SELECT 13, [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE], [FACTOR_METHOD_ID], [FACTOR_METHOD_VALUE], [OPTION_FACTOR],
 [SPOUSE_FACTOR], [SSLI_FLAG], [SSLI_FACTOR_METHOD_ID], [SSLI_FACTOR_METHOD_VALUE], [SSLI_FACTOR], [EXCLUSIVE_CALC_PAYMENT_TYPE_ID], [EXCLUSIVE_CALC_PAYMENT_TYPE_VALUE], 
 [POST_RETIREMENT_DEATH_REASON_TYPE_ID], [POST_RETIREMENT_DEATH_REASON_TYPE_VALUE], [SINGLE], [MARRIED] FROM [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_OPTION] WHERE BENEFIT_PROVISION_ID=10 --and BENEFIT_ACCOUNT_TYPE_VALUE = 'RETR'
END

--SGT_BENEFIT_PROVISION_BENEFIT_TYPE
IF NOT EXISTS(SELECT 1 FROM [SGT_BENEFIT_PROVISION_BENEFIT_TYPE] WHERE [BENEFIT_PROVISION_ID]=13)
BEGIN
 INSERT INTO [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], 
 [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], 
 [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
 (SELECT 13, [EFFECTIVE_DATE],[BENEFIT_ACCOUNT_TYPE_ID], BPBT.[BENEFIT_ACCOUNT_TYPE_VALUE], [BENEFIT_FORMULA_ID], [BENEFIT_FORMULA_VALUE], 
 [EARLY_REDUCTION_METHOD_ID], [EARLY_REDUCTION_METHOD_VALUE], [EARLY_REDUCTION_FACTOR], [FAS_FORMULA_ID], [FAS_FORMULA_VALUE], [FAS_NO_PERIODS], [FAS_NO_PERIODS_RANGE], [PLSO_FLAG], [PLSO_FACTOR_METHOD_ID], [PLSO_FACTOR_METHOD_VALUE], 
 [PLSO_FACTOR], [DNRO_FLAG], [DNRO_FACTOR_METHOD_ID], [DNRO_FACTOR_METHOD_VALUE], [DNRO_FACTOR], [RHIC_SERVICE_FACTOR], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE]
 FROM [dbo].[SGT_BENEFIT_PROVISION_BENEFIT_TYPE] BPBT WHERE BENEFIT_PROVISION_ID = 10)
END

--SGT_BENEFIT_PROVISION_ELIGIBILITY
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_PROVISION_ELIGIBILITY WHERE [BENEFIT_PROVISION_ID]=13)
BEGIN
INSERT INTO SGT_BENEFIT_PROVISION_ELIGIBILITY ([BENEFIT_PROVISION_ID], [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], 
[COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE])
SELECT 13, [EFFECTIVE_DATE], [BENEFIT_ACCOUNT_TYPE_ID], [BENEFIT_ACCOUNT_TYPE_VALUE], [ELIGIBILITY_TYPE_ID], [ELIGIBILITY_TYPE_VALUE], [AGE], [SERVICE], [AGE_PLUS_SERVICE], 
[COMBINED_SERVICE_FLAG], [CONSECUTIVE_SERVICE_FLAG], [IMMEDIATELY_BEFORE_SERVICE_FLAG], [AGE_WHILE_EMPLOYED_FLAG], [GROUPING_LOGIC], [OTHER_LOGIC_FLAG], [ELIGIBILITY_GROUP_CODE], [MINIMUM_AGE], [BENEFIT_TIER_ID], [BENEFIT_TIER_VALUE]
FROM SGT_BENEFIT_PROVISION_ELIGIBILITY WHERE BENEFIT_PROVISION_ID=10
END

--SGT_BENEFIT_RHIC_REDUCTION_FACTOR
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_RHIC_REDUCTION_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_BENEFIT_RHIC_REDUCTION_FACTOR ([MIN_AGE], [MAX_AGE], [FACTOR], [PLAN_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [EFFECTIVE_DATE])
SELECT [MIN_AGE], [MAX_AGE], [FACTOR], @PLAN_ID, 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0, [EFFECTIVE_DATE] 
FROM SGT_BENEFIT_RHIC_REDUCTION_FACTOR WHERE PLAN_ID=26 
END

--SGT_BENEFIT_OPTION_FACTOR
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_OPTION_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_BENEFIT_OPTION_FACTOR ([MEMBER_AGE], [BEN_AGE], [BENEFIT_TYPE], [PLAN_ID], [FACTOR], [EFFECTIVE_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE])
SELECT [MEMBER_AGE], [BEN_AGE], [BENEFIT_TYPE], @PLAN_ID, [FACTOR], [EFFECTIVE_DATE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0, [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE]
FROM SGT_BENEFIT_OPTION_FACTOR WHERE PLAN_ID=26 AND EFFECTIVE_DATE = '1/1/2023'
END

--SGT_BENEFIT_SSLI_FACTOR 
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_SSLI_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_BENEFIT_SSLI_FACTOR ([MEMBER_AGE], [SSLI_AGE], [SSLI_FACTOR], [PLAN_ID], [EFFECTIVE_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
SELECT [MEMBER_AGE], [SSLI_AGE], [SSLI_FACTOR], @PLAN_ID, [EFFECTIVE_DATE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0
FROM SGT_BENEFIT_SSLI_FACTOR WHERE PLAN_ID=26
END

--SGT_BENEFIT_DNRO_PLSO_EARLY_FACTOR
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_DNRO_PLSO_EARLY_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_BENEFIT_DNRO_PLSO_EARLY_FACTOR ([MEMBER_AGE], [BEN_AGE], [TRAN_TYPE], [SUB_TYPE], [PLAN_ID], [FACTOR], [EFFECTIVE_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
SELECT [MEMBER_AGE], [BEN_AGE], [TRAN_TYPE], [SUB_TYPE], @PLAN_ID, [FACTOR], [EFFECTIVE_DATE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0
FROM SGT_BENEFIT_DNRO_PLSO_EARLY_FACTOR BDEF WHERE BDEF.PLAN_ID=26 AND BDEF.EFFECTIVE_DATE = (SELECT MAX(BDEF1.EFFECTIVE_DATE)
																					FROM SGT_BENEFIT_DNRO_PLSO_EARLY_FACTOR BDEF1
																				    WHERE BDEF1.TRAN_TYPE = BDEF.TRAN_TYPE AND  BDEF1.MEMBER_AGE=BDEF.MEMBER_AGE AND BDEF1.PLAN_ID=BDEF.PLAN_ID
																					AND BDEF1.EFFECTIVE_DATE <= GETDATE()) ORDER BY TRAN_TYPE
END

--SGT_BENEFIT_GRADUATED_BENEFIT_OPTION_FACTOR
IF NOT EXISTS(SELECT 1 FROM SGT_BENEFIT_GRADUATED_BENEFIT_OPTION_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_BENEFIT_GRADUATED_BENEFIT_OPTION_FACTOR ([MEMBER_AGE], [BEN_AGE], [BENEFIT_TYPE], [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE], [GRADUATED_BENEFIT_OPTION_ID], [GRADUATED_BENEFIT_OPTION_VALUE], [PLAN_ID], [FACTOR], [EFFECTIVE_DATE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
SELECT [MEMBER_AGE], [BEN_AGE], [BENEFIT_TYPE], [BENEFIT_OPTION_ID], [BENEFIT_OPTION_VALUE], [GRADUATED_BENEFIT_OPTION_ID], [GRADUATED_BENEFIT_OPTION_VALUE], @PLAN_ID, [FACTOR], [EFFECTIVE_DATE], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0
FROM SGT_BENEFIT_GRADUATED_BENEFIT_OPTION_FACTOR WHERE PLAN_ID=26 AND EFFECTIVE_DATE = '1/1/2023'
END

--SGT_SERVICE_CREDIT_PLAN_FORMULA_REF
IF NOT EXISTS(SELECT 1 FROM SGT_SERVICE_CREDIT_PLAN_FORMULA_REF WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_SERVICE_CREDIT_PLAN_FORMULA_REF ([SERVICE_CREDIT_TYPE_ID], [SERVICE_CREDIT_TYPE_VALUE], [PLAN_ID], [PAYOR_ID], [PAYOR_VALUE], [AGE_FOR_ENRA_CALCULATION], [AGE_CEILING_FOR_ENRA], [ACTUARIAL_TABLE_REFERENCE_ID], [ACTUARIAL_TABLE_REFERENCE_VALUE], [APPLICABLE_TO_PENSION_FLAG], [APPLICABLE_TO_VESTING_FLAG], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
SELECT [SERVICE_CREDIT_TYPE_ID], [SERVICE_CREDIT_TYPE_VALUE], @PLAN_ID, [PAYOR_ID], [PAYOR_VALUE], [AGE_FOR_ENRA_CALCULATION], [AGE_CEILING_FOR_ENRA], [ACTUARIAL_TABLE_REFERENCE_ID], [ACTUARIAL_TABLE_REFERENCE_VALUE], [APPLICABLE_TO_PENSION_FLAG], [APPLICABLE_TO_VESTING_FLAG], 'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0
FROM SGT_SERVICE_CREDIT_PLAN_FORMULA_REF WHERE PLAN_ID=26 
END

--SGT_WSS_AUTO_POSTING_CROSS_REF
DECLARE @MAXID INT
SELECT @MAXID = MAX(AUTO_POSTING_CROSS_REF_ID) FROM SGT_WSS_AUTO_POSTING_CROSS_REF
IF NOT EXISTS(SELECT 1 FROM SGT_WSS_AUTO_POSTING_CROSS_REF WHERE PLAN_ID=29)
BEGIN
INSERT INTO SGT_WSS_AUTO_POSTING_CROSS_REF (AUTO_POSTING_CROSS_REF_ID,[PLAN_ID], [PLAN_ENROLLMENT_OPTION_ID], [PLAN_ENROLLMENT_OPTION_VALUE], [CHANGE_REASON_ID], [CHANGE_REASON_VALUE], [CHANGE_EFFECTIVE_DATE_ID], [CHANGE_EFFECTIVE_DATE_VALUE], [AUTO_POST_FLAG], [WORKFLOW_PROCESS_ID], [PROMPT_USER_TEXT], [DOCUMENT])
SELECT @MAXID + (ROW_NUMBER() OVER (ORDER BY PLAN_ID DESC)), 29, [PLAN_ENROLLMENT_OPTION_ID], [PLAN_ENROLLMENT_OPTION_VALUE], [CHANGE_REASON_ID], [CHANGE_REASON_VALUE], [CHANGE_EFFECTIVE_DATE_ID], [CHANGE_EFFECTIVE_DATE_VALUE], [AUTO_POST_FLAG], [WORKFLOW_PROCESS_ID], [PROMPT_USER_TEXT], [DOCUMENT]
FROM SGT_WSS_AUTO_POSTING_CROSS_REF WHERE PLAN_ID=26
END

--SGT_SERVICE_CREDIT_ACTUARIAL_FACTOR
IF NOT EXISTS(SELECT 1 FROM SGT_SERVICE_CREDIT_ACTUARIAL_FACTOR WHERE PLAN_ID=@PLAN_ID)
BEGIN
INSERT INTO SGT_SERVICE_CREDIT_ACTUARIAL_FACTOR ([ACTUARIAL_TABLE_REFERENCE_ID],[ACTUARIAL_TABLE_REFERENCE_VALUE],[MEMBER_AGE],[RETIREMENT_AGE]
              ,[RETIREMENT_ACTUARIAL_FACTOR],[RHIC_ACTUARIAL_FACTOR],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ],[EFFECTIVE_DATE],[FUTURE_EE_ACTUARIAL_FACTOR]
           ,[MONTHS_OF_SERVICE_FROM],[MONTHS_OF_SERVICE_TO],[PLAN_ID],[EMPLOYER_TYPE])
SELECT [ACTUARIAL_TABLE_REFERENCE_ID],[ACTUARIAL_TABLE_REFERENCE_VALUE],[MEMBER_AGE],[RETIREMENT_AGE]
                     ,[RETIREMENT_ACTUARIAL_FACTOR],[RHIC_ACTUARIAL_FACTOR],'PIR 25729', GETDATE(), 'PIR 25729', GETDATE(), 0,[EFFECTIVE_DATE],[FUTURE_EE_ACTUARIAL_FACTOR]
           ,[MONTHS_OF_SERVICE_FROM],[MONTHS_OF_SERVICE_TO],@PLAN_ID,[EMPLOYER_TYPE]
FROM SGT_SERVICE_CREDIT_ACTUARIAL_FACTOR WHERE PLAN_ID=26 AND EFFECTIVE_DATE = '1/1/2023'
END

-- SGS_CODE_VALUE - CODE_ID=1903
IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS1')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS1', '100% Joint & Survivor', '29',	'DETH',	'J100',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS2')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS2', '50% Lifetime', '29',	'DETH',	'L050',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS3')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS3', 'Auto refund', '29',	'DETH',	'AURD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS4')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS4', 'Refund', '29',	'DETH',	'REFD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS5')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS5', '10 Year Term Certain', '29',	'RETR',	'T10C',	'State Public Safety',	NULL,	NULL,	4,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS6')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS6', '100% Joint & Survivor', '29',	'RETR',	'J100',	'State Public Safety',	NULL,	NULL,	3,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS7')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS7', '20 Year Term Certain', '29',	'RETR',	'T20C',	'State Public Safety',	NULL,	NULL,	5,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS8')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS8', '50% Joint & Survivor', '29',	'RETR',	'J50S',	'State Public Safety',	NULL,	NULL,	2,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS9')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS9', 'Single Life', '29',	'RETR',	'SNGL',	'State Public Safety',	NULL,	NULL,	1,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS10')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS10', '10 Year Term Certain', '29',	'DISA',	'T10C',	'State Public Safety',	NULL,	NULL,	4,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS11')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS11', '100% Joint & Survivor', '29',	'DISA',	'J100',	'State Public Safety',	NULL,	NULL,	3,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS12')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS12', '20 Year Term Certain', '29',	'DISA',	'T20C',	'State Public Safety',	NULL,	NULL,	3,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS13')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS13', '50% Joint & Survivor', '29',	'DISA',	'J50S',	'State Public Safety',	NULL,	NULL,	2,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=1903 AND CODE_VALUE = 'SPS14')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1903, 'SPS14', 'Single Life', '29',	'DISA',	'SNGL',	'State Public Safety',	NULL,	NULL,	1,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

-- CODE_ID=2406
IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M126')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M126', 'State Public Safety', 'SPS4',	'NVMA',	'OTHR',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M127')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M127', 'State Public Safety', 'SPS4',	'NVNM',	'OTHR',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M128')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M128', 'State Public Safety', 'SPS4',	'VEMA',	'OTHR',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M129')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M129', 'State Public Safety', 'SPS4',	'VENM',	'OTHR',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M130')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M130', 'State Public Safety', 'SPS1',	'VEMA',	'SPOU',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M131')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M131', 'State Public Safety', 'SPS2',	'VEMA',	'SPOU',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M132')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M132', 'State Public Safety', 'SPS4',	'NVMA',	'SPOU',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M133')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M133', 'State Public Safety', 'SPS4',	'VEMA',	'SPOU',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M134')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M134', 'State Public Safety', 'SPS4',	'NVMA',	'CHLD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M135')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M135', 'State Public Safety', 'SPS4',	'NVNM',	'CHLD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M136')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M136', 'State Public Safety', 'SPS4',	'VEMA',	'CHLD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2406 AND CODE_VALUE = 'M137')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(2406, 'M137', 'State Public Safety', 'SPS4',	'VENM',	'CHLD',	'State Public Safety',	NULL,	NULL,	NULL,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

--Update scripts to add

--PLAN ID 2,3,4,5,6,7,26,28,29
IF NOT EXISTS(SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE INNER JOIN 
SGT_ORG_PLAN ON SGT_ORG_PLAN_MEMBER_TYPE.ORG_PLAN_ID = SGT_ORG_PLAN.ORG_PLAN_ID
 WHERE BENEFIT_PLAN IS NOT NULL AND PLAN_ID IN (2,3,4,5,6,7,26,28,29))
BEGIN
UPDATE TMP
SET TMP.BENEFIT_PLAN = PPCR.BENEFIT_PLAN ,TMP.RHIC_BENEFIT_PLAN = PPCR.RHIC_BENEFIT_PLAN, TMP.MODIFIED_BY = 'PIR 25729', TMP.MODIFIED_DATE = GETDATE()
FROM SGT_ORG_PLAN_MEMBER_TYPE AS TMP			                  
INNER JOIN SGT_ORG_PLAN OP WITH (NOLOCK) ON OP.ORG_PLAN_ID = TMP.ORG_PLAN_ID 
INNER JOIN SGT_PEOPLESOFT_PLAN_CROSS_REF PPCR WITH (NOLOCK) ON PPCR.PLAN_ID = OP.PLAN_ID
INNER JOIN SGT_ORGANIZATION ORG WITH(NOLOCK) ON ORG.ORG_ID = OP.ORG_ID AND ORG.PEOPLESOFT_ORG_GROUP_VALUE = 'STAT'
WHERE OP.PLAN_ID IN (2,3,4,5,6,7,26,28,29)
AND( END_DATE IS NULL OR END_DATE > GETDATE())
END

-----------------------------------------------------------------------------------------------------------------------------------

--PLAN ID - 1 (REGULAR/TEMP)
IF NOT EXISTS(
SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE INNER JOIN 
SGT_ORG_PLAN ON SGT_ORG_PLAN_MEMBER_TYPE.ORG_PLAN_ID = SGT_ORG_PLAN.ORG_PLAN_ID
WHERE BENEFIT_PLAN IS NOT NULL AND PLAN_ID IN (1) AND MEMBER_TYPE_VALUE = 'MRG8')
BEGIN
UPDATE TMP
SET TMP.BENEFIT_PLAN = PPCR.BENEFIT_PLAN ,TMP.RHIC_BENEFIT_PLAN = PPCR.RHIC_BENEFIT_PLAN, TMP.MODIFIED_BY = 'PIR 25729', TMP.MODIFIED_DATE = GETDATE()
FROM SGT_ORG_PLAN_MEMBER_TYPE AS TMP			                  
INNER JOIN SGT_ORG_PLAN OP WITH (NOLOCK) ON OP.ORG_PLAN_ID = TMP.ORG_PLAN_ID 
INNER JOIN SGT_PEOPLESOFT_PLAN_CROSS_REF PPCR WITH (NOLOCK) ON PPCR.PLAN_ID = OP.PLAN_ID AND SGT_PEOPLESOFT_PLAN_CROSS_REF_ID = 91
INNER JOIN SGT_ORGANIZATION ORG WITH(NOLOCK) ON ORG.ORG_ID = OP.ORG_ID AND ORG.PEOPLESOFT_ORG_GROUP_VALUE = 'STAT'
WHERE OP.PLAN_ID IN (1)
AND( END_DATE IS NULL OR END_DATE > GETDATE())
AND TMP.MEMBER_TYPE_VALUE = 'MRG8'
END

IF NOT EXISTS(
SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE INNER JOIN 
SGT_ORG_PLAN ON SGT_ORG_PLAN_MEMBER_TYPE.ORG_PLAN_ID = SGT_ORG_PLAN.ORG_PLAN_ID
WHERE BENEFIT_PLAN IS NOT NULL AND PLAN_ID IN (1) AND MEMBER_TYPE_VALUE = 'MTP1')
BEGIN
UPDATE TMP
SET TMP.BENEFIT_PLAN = PPCR.BENEFIT_PLAN ,TMP.RHIC_BENEFIT_PLAN = PPCR.RHIC_BENEFIT_PLAN, TMP.MODIFIED_BY = 'PIR 25729', TMP.MODIFIED_DATE = GETDATE()
FROM SGT_ORG_PLAN_MEMBER_TYPE AS TMP			                  
INNER JOIN SGT_ORG_PLAN OP WITH (NOLOCK) ON OP.ORG_PLAN_ID = TMP.ORG_PLAN_ID 
INNER JOIN SGT_PEOPLESOFT_PLAN_CROSS_REF PPCR WITH (NOLOCK) ON PPCR.PLAN_ID = OP.PLAN_ID AND SGT_PEOPLESOFT_PLAN_CROSS_REF_ID = 90
INNER JOIN SGT_ORGANIZATION ORG WITH(NOLOCK) ON ORG.ORG_ID = OP.ORG_ID AND ORG.PEOPLESOFT_ORG_GROUP_VALUE = 'STAT'
WHERE OP.PLAN_ID IN (1)
AND( END_DATE IS NULL OR END_DATE > GETDATE())
AND TMP.MEMBER_TYPE_VALUE = 'MTP1'
END


-----------------------------------------------------------------------------------------------------------------------------------

--PLAN ID - 27 (REGULAR/TEMP)
IF NOT EXISTS(
SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE INNER JOIN 
SGT_ORG_PLAN ON SGT_ORG_PLAN_MEMBER_TYPE.ORG_PLAN_ID = SGT_ORG_PLAN.ORG_PLAN_ID
WHERE BENEFIT_PLAN IS NOT NULL AND PLAN_ID IN (27) AND MEMBER_TYPE_VALUE = 'NM29')
BEGIN
UPDATE TMP
SET TMP.BENEFIT_PLAN = PPCR.BENEFIT_PLAN ,TMP.RHIC_BENEFIT_PLAN = PPCR.RHIC_BENEFIT_PLAN, TMP.MODIFIED_BY = 'PIR 25729', TMP.MODIFIED_DATE = GETDATE()
FROM SGT_ORG_PLAN_MEMBER_TYPE AS TMP			                  
INNER JOIN SGT_ORG_PLAN OP WITH (NOLOCK) ON OP.ORG_PLAN_ID = TMP.ORG_PLAN_ID 
INNER JOIN SGT_PEOPLESOFT_PLAN_CROSS_REF PPCR WITH (NOLOCK) ON PPCR.PLAN_ID = OP.PLAN_ID AND SGT_PEOPLESOFT_PLAN_CROSS_REF_ID = 138
INNER JOIN SGT_ORGANIZATION ORG WITH(NOLOCK) ON ORG.ORG_ID = OP.ORG_ID AND ORG.PEOPLESOFT_ORG_GROUP_VALUE = 'STAT'
WHERE OP.PLAN_ID IN (27)
AND( END_DATE IS NULL OR END_DATE > GETDATE())
AND TMP.MEMBER_TYPE_VALUE = 'NM29'
END

IF NOT EXISTS(SELECT 1 FROM SGT_ORG_PLAN_MEMBER_TYPE INNER JOIN 
SGT_ORG_PLAN ON SGT_ORG_PLAN_MEMBER_TYPE.ORG_PLAN_ID = SGT_ORG_PLAN.ORG_PLAN_ID
WHERE BENEFIT_PLAN IS NOT NULL AND PLAN_ID IN (27) AND MEMBER_TYPE_VALUE = 'NMT1')
BEGIN
UPDATE TMP
SET TMP.BENEFIT_PLAN = PPCR.BENEFIT_PLAN ,TMP.RHIC_BENEFIT_PLAN = PPCR.RHIC_BENEFIT_PLAN, TMP.MODIFIED_BY = 'PIR 25729', TMP.MODIFIED_DATE = GETDATE()
FROM SGT_ORG_PLAN_MEMBER_TYPE AS TMP			                  
INNER JOIN SGT_ORG_PLAN OP WITH (NOLOCK) ON OP.ORG_PLAN_ID = TMP.ORG_PLAN_ID 
INNER JOIN SGT_PEOPLESOFT_PLAN_CROSS_REF PPCR WITH (NOLOCK) ON PPCR.PLAN_ID = OP.PLAN_ID AND SGT_PEOPLESOFT_PLAN_CROSS_REF_ID = 137
INNER JOIN SGT_ORGANIZATION ORG WITH(NOLOCK) ON ORG.ORG_ID = OP.ORG_ID AND ORG.PEOPLESOFT_ORG_GROUP_VALUE = 'STAT'
WHERE OP.PLAN_ID IN (27)
AND( END_DATE IS NULL OR END_DATE > GETDATE())
AND TMP.MEMBER_TYPE_VALUE = 'NMT1'
END

---------------------------------------------------------------------------------------------------------------------------------------

--UPDATE BENEFIT_PLAN AND RHIC_BENEFIT_PLAN TO NULL IN SGT_PEOPLESOFT_PLAN_CROSS_REF
IF NOT EXISTS(SELECT 1 FROM SGT_PEOPLESOFT_PLAN_CROSS_REF WHERE BENEFIT_PLAN IS NULL AND 
SGT_PEOPLESOFT_PLAN_CROSS_REF_ID IN (87,88,89,90,91,94,95,109,112,137,138,139,141))
BEGIN
UPDATE SGT_PEOPLESOFT_PLAN_CROSS_REF SET BENEFIT_PLAN = NULL, RHIC_BENEFIT_PLAN = NULL, MODIFIED_BY = 'PIR 25729', MODIFIED_DATE = GETDATE()
WHERE SGT_PEOPLESOFT_PLAN_CROSS_REF_ID IN (87,88,89,90,91,94,95,109,112,137,138,139,141)
END



--CODE VALUE 2317
IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R177' AND DATA1 = 'SPS11')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (2317, N'R177', N'R177', N'SPS11', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R178' AND DATA1 = 'SPS6')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (2317, N'R178', N'R178', N'SPS6', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R179' AND DATA1 = 'SPS10')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R179', N'R179', N'SPS10', N'R100', N'SPS11', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
 END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R180' AND DATA1 = 'SPS10')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R180', N'R180', N'SPS10', N'RD50', N'SPS13', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R181' AND DATA1 = 'SPS10')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R181', N'R181', N'SPS10', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R182' AND DATA1 = 'SPS6')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R182', N'R182',  N'SPS6', N'R100', N'SPS6', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R183' AND DATA1 = 'SPS6')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R183', N'R183', N'SPS6', N'RD50', N'SPS8', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R184' AND DATA1 = 'SPS6')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R184', N'R184',  N'SPS6', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R185' AND DATA1 = 'SPS12')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R185', N'R185',  N'SPS12', N'R100', N'SPS11', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R186' AND DATA1 = 'SPS12')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R186', N'R186', N'SPS12', N'RD50', N'SPS13', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
 END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R187' AND DATA1 = 'SPS12')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R187', N'R187', N'SPS12', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R188' AND DATA1 = 'SPS7')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R188', N'R188', N'SPS7', N'R100', N'SPS6', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R189' AND DATA1 = 'SPS7')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R189', N'R189', N'SPS7', N'RD50', N'SPS8', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729',GETDATE(), 0)
 END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R190' AND DATA1 = 'SPS7')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R190', N'R190', N'SPS7', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729',GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R191' AND DATA1 = 'SPS13')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R191', N'R191', N'SPS13', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R192' AND DATA1 = 'SPS8')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R192', N'R192', N'SPS8', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R193' AND DATA1 = 'SPS1')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R193', N'R193', N'SPS1', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R194' AND DATA1 = 'SPS14')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R194', N'R194', N'SPS14', N'R100', N'SPS11', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
 END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R195' AND DATA1 = 'SPS14')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R195', N'R195',  N'SPS14', N'RD50', N'SPS13', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R196' AND DATA1 = 'SPS14')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R196', N'R196',  N'SPS14', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R197' AND DATA1 = 'SPS9')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R197', N'R197', N'SPS9', N'R100', N'SPS6', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 3, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
END


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R198' AND DATA1 = 'SPS9')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES ( 2317, N'R198', N'R198',  N'SPS9', N'RD50', N'SPS8', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 2, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
  END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=2317 AND CODE_VALUE = 'R199' AND DATA1 = 'SPS9')
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ( [CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], 
[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES ( 2317, N'R199', N'R199', N'SPS9', N'STRD', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), CAST(N'1900-01-01T00:00:00.000' AS DateTime), 1, N'', N'PIR 25729', GETDATE(), N'PIR 25729', GETDATE(), 0)
 END

 -- UPDATING DATA3
IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17581 AND DATA3 != 'B10D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17581 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17582 AND DATA3 != 'B50D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17582 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17584 AND DATA3 != 'B10D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17584 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17585 AND DATA3 != 'B50D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17585 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17588 AND DATA3 != 'B10D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17588 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17589 AND DATA3 != 'B50D')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50D', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17589 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17592 AND DATA3 != 'B10R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17592 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17593 AND DATA3 != 'B50R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17593 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17595 AND DATA3 != 'B10R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17595 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17596 AND DATA3 != 'B50R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17596 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17599 AND DATA3 != 'B10R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B10R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17599 
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_SERIAL_ID = 17600 AND DATA3 != 'B50R')
BEGIN
UPDATE [SGS_CODE_VALUE] SET DATA3 = 'B50R', MODIFIED_BY='PIR 25729', MODIFIED_DATE=GETDATE() WHERE CODE_SERIAL_ID = 17600 
END



