INSERT INTO SGT_PROVIDER_REPORT_DATA_DC (
SUBSYSTEM_ID,
SUBSYSTEM_VALUE,
SUBSYSTEM_REF_ID,
PERSON_ID,
SSN,
FIRST_NAME,
LAST_NAME,
PROVIDER_ORG_ID,
PLAN_ID,
EFFECTIVE_DATE,
EE_CONTRIBUTION,
EE_PRE_TAX,
EE_EMPLOYER_PICKUP,
ER_CONTRIBUTION,
MEMBER_INTEREST,
EMPLOYER_INTEREST,
BATCH_REQUEST_ID,
CREATED_BY,
CREATED_DATE,
MODIFIED_BY,
MODIFIED_DATE,
UPDATE_SEQ,
EMPLOYER_RHIC_INTEREST)

SELECT 
349 AS SUBSYSTEM_ID,
'PAYR' AS SUBSYSTEM_VALUE,
EMPLOYER_PAYROLL_DETAIL_ID AS SUBSYSTEM_REF_ID,
PERSON_ID,
SSN,
FIRST_NAME,
LAST_NAME,
2413 AS PROVIDER_ORG_ID,
PLAN_ID, 
PAY_PERIOD_DATE AS EFFECTIVE_DATE,
CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN EE_CONTRIBUTION_REPORTED * -1
ELSE EE_CONTRIBUTION_REPORTED END AS EE_CONTRIBUTION,

CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN EE_PRE_TAX_REPORTED * -1
ELSE EE_PRE_TAX_REPORTED END AS EE_PRE_TAX,

CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN EE_EMPLOYER_PICKUP_REPORTED * -1
ELSE EE_EMPLOYER_PICKUP_REPORTED END AS EE_EMPLOYER_PICKUP,

CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN ER_CONTRIBUTION_REPORTED * -1
ELSE ER_CONTRIBUTION_REPORTED END AS ER_CONTRIBUTION,

CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN MEMBER_INTEREST_CALCULATED * -1
ELSE MEMBER_INTEREST_CALCULATED END AS MEMBER_INTEREST,

CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN EMPLOYER_INTEREST_CALCULATED * -1
ELSE EMPLOYER_INTEREST_CALCULATED END AS EMPLOYER_INTEREST,

NULL AS BATCH_REQUEST_ID,
'PIR23782' AS CREATED_BY,
GETDATE() AS CREATED_DATE,
'PIR23782' AS MODIFIED_BY,
GETDATE() AS MODIFIED_DATE,
0 AS UPDATE_SEQ,
CASE WHEN RECORD_TYPE_VALUE IN ('-ADJ', 'NBON') THEN EMPLOYER_RHIC_INTEREST_CALCULATED * -1
ELSE EMPLOYER_RHIC_INTEREST_CALCULATED END AS EMPLOYER_RHIC_INTEREST
FROM SGT_EMPLOYER_PAYROLL_DETAIL
WHERE PLAN_ID = 28 AND STATUS_VALUE = 'PSTD'