/********************Purpose: PIR 26615******************************
*********************Created By: Bharat Reddy********************************
********************Create tables  - SGT_PERSON_TFFR_HEADER and SGT_PERSON_TFFR_DETAIL ********************************************
*/
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('[dbo].[SGT_PERSON_TFFR_HEADER]') AND type in (N'U'))
CREATE TABLE [dbo].[SGT_PERSON_TFFR_HEADER]
(
	[PERSON_TFFR_HEADER_ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[UPLOAD_ID] INT NOT NULL,
	[PERSON_ID] INT NULL,
	[UPLOAD_DATE] DATETIME NULL,
	[NOTES] VARCHAR(2000) NULL
)
GO

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SGT_PERSON_TFFR_DETAIL]') AND type in (N'U'))
CREATE TABLE [dbo].[SGT_PERSON_TFFR_DETAIL](
	[PERSON_TFFR_DETAIL_ID] INT IDENTITY(1,1) NOT NULL,
	[PERSON_TFFR_HEADER_ID] INT NOT NULL,
	[UPLOAD_ID] INT NOT NULL,
	[LINE_NO] INT NULL,
	[TRANSACTION_TYPE_VALUE] INT NOT NULL,
	[MONTH] INT NULL,
	[YEAR] INT NULL,
	[TFFR_WAGE] DECIMAL(13,2) NULL,
	[SERVICE_CREDIT] VARCHAR(100) NULL,
PRIMARY KEY CLUSTERED 
(
	[PERSON_TFFR_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT 1 FROM sys.objects o 
			INNER JOIN sys.foreign_keys fk ON o.object_id = fk.parent_object_id 
			WHERE fk.type = 'F' AND fk.name = 'FK_SGT_PERSON_TFFR_DETAIL_PERSON_TFFR_HEADER_ID_SGT_PERSON_TFFR_HEADER_PERSON_TFFR_HEADER_ID'
				  AND fk.referenced_object_id = OBJECT_ID('SGT_PERSON_TFFR_HEADER')
)
ALTER TABLE [dbo].[SGT_PERSON_TFFR_DETAIL]
ADD CONSTRAINT FK_SGT_PERSON_TFFR_DETAIL_PERSON_TFFR_HEADER_ID_SGT_PERSON_TFFR_HEADER_PERSON_TFFR_HEADER_ID
FOREIGN KEY ([PERSON_TFFR_HEADER_ID]) REFERENCES SGT_PERSON_TFFR_HEADER([PERSON_TFFR_HEADER_ID]) ON DELETE CASCADE
GO

---------------------------------------Created by: Saylee P--------------
---------------------------------------Purpose: PIR 26617----------------
---------------------------------------Added new column to sgt_person----

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_PERSON_BASE'
AND COLUMN_NAME = 'TFFR_REQUEST')
ALTER TABLE SGT_PERSON_BASE
ADD TFFR_REQUEST char(1) null
GO

EXEC sys.sp_refreshview SGT_PERSON	
GO

/********************Purpose: PIR 26260******************************
*********************Created By: Bharat Reddy********************************/

/*********************Comments: SGT_PERSON_CONTACT*****************/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'NOTES' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_CONTACT'))
BEGIN
    ALTER TABLE [DBO].[SGT_PERSON_CONTACT]
	ADD NOTES VARCHAR(2000) NULL 
END
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EXPIRATION_DATE' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_CONTACT'))
BEGIN
    ALTER TABLE [DBO].[SGT_PERSON_CONTACT]
	ADD EXPIRATION_DATE DATETIME NULL 
END
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EXP_ON_DEATH' AND Object_ID = Object_ID(N'dbo.SGT_PERSON_CONTACT'))
BEGIN
    ALTER TABLE [DBO].[SGT_PERSON_CONTACT]
	ADD EXP_ON_DEATH CHAR(1) NULL 
END
GO

/*********************Comments: SGT_PERSON*****************/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'END_OF_LIFE_DOCS' AND Object_ID = Object_ID(N'SGT_PERSON_BASE'))
BEGIN
    ALTER TABLE [DBO].[SGT_PERSON_BASE]
	ADD END_OF_LIFE_DOCS CHAR(1) NULL 
END
GO
--refresh SGT_PERSON view
EXEC sys.sp_refreshview SGT_PERSON	
GO



/*
	PIR 25920 DC 2025 Plan
	HB1040 COMMUNICATION
*/
IF NOT EXISTS(SELECT * FROM sys.OBJECTS
          WHERE [Name] = N'SGT_HB1040_COMMUNICATION' AND [type] = 'U')
BEGIN
	CREATE TABLE SGT_HB1040_COMMUNICATION
	(
		HB1040_COMMUNICATION_ID INT IDENTITY(1,1) PRIMARY KEY,
		PERSON_ID INT,
		PERSON_ACCOUNT_ID INT, 
		NRD DATETIME,
		AGE_AT_NRD DECIMAL(13,2) NULL,
		FAS DECIMAL(13,2),
		ACCRUED_BENEFIT_AMT DECIMAL(13,2),
		DB_ACCOUNT_BALANCE DECIMAL(13,2),
		DB_DC_TRANSFER_AMT DECIMAL(13,2),
		MEMBER_DOB DATETIME,
		JAN_25_DB_ACCT_BAL DECIMAL(13,2),
		LETTER_GENERATED_1 CHAR(1),
		LETTER_GENERATED_DATE_1 DATETIME	
	)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'JAN_25_DB_ACCT_BAL' AND Object_ID = Object_ID(N'SGT_HB1040_COMMUNICATION'))
BEGIN
    ALTER TABLE [DBO].[SGT_HB1040_COMMUNICATION]
	ADD JAN_25_DB_ACCT_BAL DECIMAL(13,2) NULL 
END
GO
/*
	PIR 25920 DC 2025 Plan
	HB1040_LIFE_EXPECTANCY
*/
IF NOT EXISTS(SELECT * FROM sys.OBJECTS
          WHERE [Name] = N'SGT_HB1040_LIFE_EXPECTANCY' AND [type] = 'U')
BEGIN
	CREATE TABLE SGT_HB1040_LIFE_EXPECTANCY
	(
	
		AGE DECIMAL(13,2) NOT NULL,	
		MALE DECIMAL(13,2) NULL,
		FEMALE DECIMAL(13,2) NULL
	)
END
/*
	PIR 25920 DC 2025 Plan
	HB1040_DC_TRANSFER_FACTORS
*/
IF NOT EXISTS(SELECT * FROM sys.OBJECTS
          WHERE [Name] = N'SGT_HB1040_DC_TRANSFER_FACTORS' AND [type] = 'U')
BEGIN
	CREATE TABLE SGT_HB1040_DC_TRANSFER_FACTORS
	(
	
		AGE DECIMAL(13,2) NOT NULL,	
		RETIREMENT_AGE DECIMAL(13,2) NULL,
		FACTOR DECIMAL(13,4) NULL
	)
END
GO
-----------------------------------------------------------------------------------------------------------------------------------


