/********************Purpose: PIR 27038******************************
*********************Created By: Sarvesh ********************************/

/****** Object:  Index [IX_SBC_APPLICATION_ID] ******/

DROP INDEX [IX_SBC_APPLICATION_ID] ON [dbo].[SGT_BENEFIT_CALCULATION]
GO

IF EXISTS(SELECT 1 FROM sys.columns 
	WHERE [Name] = N'EARLY_REDUCTION_FACTOR' AND Object_ID = Object_ID(N'dbo.SGT_BENEFIT_CALCULATION'))
BEGIN
    ALTER TABLE [dbo].[SGT_BENEFIT_CALCULATION]
	ALTER COLUMN [EARLY_REDUCTION_FACTOR] DECIMAL(13,6) NULL 
END
GO 
 
/****** Object:  Index [IX_SBC_APPLICATION_ID] ******/

CREATE NONCLUSTERED INDEX [IX_SBC_APPLICATION_ID] ON [dbo].[SGT_BENEFIT_CALCULATION]
(
	[BENEFIT_APPLICATION_ID] ASC
)
INCLUDE([BENEFIT_CALCULATION_ID],[PERSON_ID],[PLAN_ID],[CALCULATION_TYPE_ID],[CALCULATION_TYPE_VALUE],[BENEFIT_ACCOUNT_TYPE_ID]
,[BENEFIT_ACCOUNT_TYPE_VALUE],[BENEFIT_ACCOUNT_SUB_TYPE_ID],[BENEFIT_ACCOUNT_SUB_TYPE_VALUE],
[PLSO_REQUESTED_FLAG],[BENEFIT_OPTION_ID],[BENEFIT_OPTION_VALUE],[UNIFORM_INCOME_OR_SSLI_FLAG],
[SSLI_OR_UNIFORM_INCOME_COMMENCEMENT_AGE],[ESTIMATED_SSLI_BENEFIT_AMOUNT],[REDUCED_BENEFIT_FLAG],
[REDUCED_BENEFIT_OPTION_AMOUNT],[TERMINATION_DATE],[NORMAL_RETIREMENT_DATE],[RETIREMENT_DATE],[DATE_OF_DEATH],
[COMBINED_DUAL_FAS_FLAG],[RHIC_OPTION_ID],[RHIC_OPTION_VALUE],[UNREDUCED_RHIC_AMOUNT],
[RHIC_EARLY_REDUCTION_FACTOR],[ADJUSTED_PSC],[ADJUSTED_TVSC],[COMMENTS],[JS_RHIC_AMOUNT],
[PAID_UP_ANNUITY_AMOUNT],[COMPUTED_FINAL_AVERAGE_SALARY],[OVERRIDDEN_FINAL_AVERAGE_SALARY],
[UNREDUCED_BENEFIT_AMOUNT],[CREDITED_PSC],[PROJECTED_PSC],[CREDITED_VSC],[PROJECTED_VSC],[INDEXED_FINAL_AVERAGE_SALARY],[PERCENTAGE_SALARY_INCREASE],[SALARY_MONTH_INCREASE],[DNRO_MISSED_MONTHS],
[ADHOC_OR_COLA_AMOUNT],[DNRO_TOTAL_MISSED_AMOUNT],[DNRO_FACTOR],[DNRO_MONTHLY_INCREASE],[EARLY_REDUCED_MONTHS],
[EARLY_REDUCTION_FACTOR],[PLSO_LUMPSUM_AMOUNT],[PLSO_FACTOR],[PLSO_REDUCTION_AMOUNT],[MINIMUM_GUARENTEE_AMOUNT]
,[MINIMUM_GUARENTEE_AMOUNT_TAXABLE_AMOUNT],[MINIMUM_GUARENTEE_AMOUNT_NON_TAXABLE_AMOUNT],[TAXABLE_AMOUNT],[NON_TAXABLE_AMOUNT],[JS_RESIDUAL_MG_AMOUNT],
[STATUS_ID],[STATUS_VALUE],[ACTION_STATUS_ID],[ACTION_STATUS_VALUE],[APPROVED_BY],[SUPPRESS_WARNINGS_FLAG],[SUPPRESS_WARNINGS_BY],[SUPPRESS_WARNINGS_DATE],
[EARLY_MONTHLY_DECREASE],[PLSO_EXCLUSION_RATIO],[SSLI_UNIFORM_INCOME_FACTOR],[QDRO_AMOUNT],[TAXABLE_QDRO_AMOUNT],[NON_TAXABLE_QDRO_AMOUNT],
[DISABILITY_PAYEE_ACCOUNT_ID],[IS_RULE_OR_AGE_CONVERSION],[FINAL_MONTHLY_BENEFIT],[RMD_AMOUNT],[ACTUARIAL_BENEFIT_REDUCTION],[RTW_REFUND_ELECTION_ID],
[RTW_REFUND_ELECTION_VALUE],[IS_RTW_LESS_THAN_2YEARS_FLAG],[PRE_RTW_PAYEE_ACCOUNT_ID],[ACTUARIALLY_ADJUSTED_MONTHLY_SINGLE_LIFE_BENEFIT],[IS_RULE_APPLIED_FLAG],[RHIC_FACTOR_AMOUNT],[ORIGINATING_PAYEE_ACCOUNT_ID]
,[POST_RETIREMENT_DEATH_REASON_TYPE_ID],[POST_RETIREMENT_DEATH_REASON_TYPE_VALUE],[BENEFICIARY_PERSON_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ],
[PARENT_BENEFIT_CALCULATION_ID],[IS_CALCULATION_VISIBLE_FLAG],[RULE_INDICATOR_ID],[RULE_INDICATOR_VALUE],[SSLI_EFFECTIVE_DATE],[RECALCULATED_BY]
,[IS_CREATED_FROM_PORTAL],[NON_TAXABLE_PLSO],[FAS_TERMINATION_DATE],[IS_TENTATIVE_TFFR_TIAA_USED],[GRADUATED_BENEFIT_OPTION_ID],[GRADUATED_BENEFIT_OPTION_VALUE]
,[RTW_GRADUATED_BENEFIT_FACTOR],[OVERRIDDEN_DNRO_MISSED_PAYMENT_AMOUNT],[is_dro_estimate],[TFFR_CALCULATION_METHOD_ID],[TFFR_CALCULATION_METHOD_VALUE],[RHIC_EFFECTIVE_DATE],[FAS_2010],[FAS_2019],[FAS_2020])

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/********************Purpose: PIR 26546 MAS - Active Annual Statements should include Tier for Plan .******************************
*********************Created By: Abhijeet Malwadkar********************************/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'PERSON_ACCOUNT_ID' AND Object_ID = Object_ID(N'dbo.SGT_MAS_PERSON_PLAN'))
BEGIN
    ALTER TABLE SGT_MAS_PERSON_PLAN
	ADD PERSON_ACCOUNT_ID INT NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'PLAN_BENEFIT_TIER_DESCRIPTION' AND Object_ID = Object_ID(N'dbo.SGT_MAS_PERSON_PLAN'))
BEGIN
    ALTER TABLE SGT_MAS_PERSON_PLAN
	ADD PLAN_BENEFIT_TIER_DESCRIPTION VARCHAR(2000) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'PERSON_ACCOUNT_ID' AND Object_ID = Object_ID(N'dbo.SGT_MAS_PAYEE_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_MAS_PAYEE_ACCOUNT
	ADD PERSON_ACCOUNT_ID INT NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'PLAN_BENEFIT_TIER_DESCRIPTION' AND Object_ID = Object_ID(N'dbo.SGT_MAS_PAYEE_ACCOUNT'))
BEGIN
    ALTER TABLE SGT_MAS_PAYEE_ACCOUNT
	ADD PLAN_BENEFIT_TIER_DESCRIPTION VARCHAR(2000) NULL 
END
GO

/********************Purpose: PIR 26652******************************
*********************Created By: Vidya Fulsoundar********************************/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'EMPLOYER_PAYROLL_HEADER_ID' AND Object_ID = Object_ID(N'dbo.SGT_PAYMENT_HISTORY_HEADER'))
BEGIN
ALTER TABLE [dbo].[SGT_PAYMENT_HISTORY_HEADER]
ADD [EMPLOYER_PAYROLL_HEADER_ID] INT NULL;
END

IF EXISTS(SELECT 1 FROM sys.columns 
	WHERE [Name] = N'PAYEE_ACCOUNT_ID' AND Object_ID = Object_ID(N'dbo.SGT_PROVIDER_REPORT_PAYMENT'))
BEGIN
ALTER TABLE [dbo].[SGT_PROVIDER_REPORT_PAYMENT]
ALTER COLUMN [PAYEE_ACCOUNT_ID] INT NULL;
END
