--------------Created By: Sanket Chougale
--------------Purpose   : PIR 25920
--------------Date      : 13/12/2024
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'LETTER_GENERATED_2' AND Object_ID = Object_ID(N'dbo.SGT_HB1040_COMMUNICATION'))
BEGIN
    ALTER TABLE SGT_HB1040_COMMUNICATION
	ADD LETTER_GENERATED_2 char(1) null
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'LETTER_GENERATED_DATE_2' AND Object_ID = Object_ID(N'dbo.SGT_HB1040_COMMUNICATION'))
BEGIN
    ALTER TABLE SGT_HB1040_COMMUNICATION
	ADD LETTER_GENERATED_DATE_2 DATETIME null
END
GO

--------------Created By: Sanket Chougale
--------------Purpose   : PIR 25920
--------------Date      : 13/12/2024
IF NOT EXISTS (SELECT * FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'ENR-5306')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], 
[ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], 
[PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ],
IMAGE_DOC_CATEGORY_ID,IMAGE_DOC_CATEGORY_VALUE,FILENET_DOCUMENT_TYPE_ID,FILENET_DOCUMENT_TYPE_VALUE,DOCUMENT_CODE) 
VALUES ( 'ENR-5306', 'Defined Contribution Retirement Program Election SFN 52170', '19', 'MMBR', 'Y', '601', 'IMG', NULL, NULL, NULL, NULL, 
'515',NULL, 'Y', 'N', 'N', '44', null,  'PIR 25920', getdate(), 'PIR 25920', getdate(), '0',
603,'MEMB',604,'FORM',null)
GO

--------------Created By: Sanket Chougale
--------------Purpose   : PIR 25920
--------------Date      : 13/12/2024

IF NOT EXISTS (SELECT * FROM [dbo].SGS_BATCH_SCHEDULE WHERE BATCH_SCHEDULE_ID = 181)
INSERT INTO [DBO].[SGS_BATCH_SCHEDULE] ([BATCH_SCHEDULE_ID], [STEP_NO], [STEP_NAME], [STEP_DESCRIPTION], [FREQUENCY_IN_DAYS], [FREQUENCY_IN_MONTHS], [NEXT_RUN_DATE], [STEP_PARAMETERS], [ACTIVE_FLAG],[REQUIRES_TRANSACTION_FLAG],[EMAIL_NOTIFICATION],[ORDER_NO],[CUTOFF_START],[CUTOFF_END], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(181, 1031, 'HB 1040 Reminder Letter', NULL,NULL,NULL,'2024-01-10 00:00:00.000',NULL,'Y','N',NULL,NULL,NULL,NULL,	'PIR 25920',	getdate(),	'PIR 25920',	getdate(),	0)
GO

--------------Created By: Sarvesh 
--------------Purpose   : PIR 26843

IF NOT EXISTS (SELECT * FROM [dbo].[SGS_MESSAGES] WHERE [MESSAGE_ID] = 10511)
INSERT INTO [dbo].[SGS_MESSAGES] ([MESSAGE_ID],[DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS],  
[CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES (10511,'Please enter a second acccount for the remainder of your payment.', 16, 'E', null, null,'PIR 26843', getdate(), 'PIR 26843', getdate(), '0')
GO