
--------------Created By: Saylee P
--------------Purpose   : PIR 26372
--------------Date      : 05/15/2024


IF NOT EXISTS (SELECT 1 FROM SGS_FILE WHERE [FILE_ID] = 108 AND [DESCRIPTION] = 'DC File for Empower Positive')
BEGIN
	SET IDENTITY_INSERT[SGS_FILE] ON;
	INSERT INTO SGS_FILE ([FILE_ID], [DESCRIPTION], DELIMITED_BY, TRANSACTION_CODE_POS, TRANSACTION_CODE_LENGTH, TRANSACTION_CODE_VALUE, HEADER_GROUP_POS, HEADER_GROUP_LENGTH, 
	XML_LAYOUT_FILE, INBOUND_MASK, MAILBOX_PATH_CODE, STAGING_PATH_CODE, ERROR_PATH_CODE, PROCESS_PATH_CODE, FILE_STATUS_ID, FILE_STATUS_VALUE, INBOUND_OUTBOUND_FLAG, CREATED_BY,
	 CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, EMAIL_NOTIFICATION, OTHER_PARAMETERS, GROUP_PROCESS_FLAG)
	VALUES(108, 'DC File for Empower Positive', ',', NULL, NULL, 'Detail  Footer', 0, 0, 'fleDCFileforEmpowerPositive','*.*', 'VPOutbox', 'VPStaging', 'VPError', 'VPOutProc', 
	26, 'A', 'O', 'PIR 26372', GETDATE(), 'PIR 26372', GETDATE(), 0, NULL, NULL, 'N')
	SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO

IF NOT EXISTS (SELECT 1 FROM SGS_FILE WHERE [FILE_ID] = 109 AND [DESCRIPTION] = 'DC File for Empower Negative')
BEGIN
	SET IDENTITY_INSERT[SGS_FILE] ON;
	INSERT INTO SGS_FILE ([FILE_ID], [DESCRIPTION], DELIMITED_BY, TRANSACTION_CODE_POS, TRANSACTION_CODE_LENGTH, TRANSACTION_CODE_VALUE, HEADER_GROUP_POS, HEADER_GROUP_LENGTH, 
	XML_LAYOUT_FILE, INBOUND_MASK, MAILBOX_PATH_CODE, STAGING_PATH_CODE, ERROR_PATH_CODE, PROCESS_PATH_CODE, FILE_STATUS_ID, FILE_STATUS_VALUE, INBOUND_OUTBOUND_FLAG, CREATED_BY,
	 CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, EMAIL_NOTIFICATION, OTHER_PARAMETERS, GROUP_PROCESS_FLAG)
	VALUES(109, 'DC File for Empower Negative', ',', NULL, NULL, 'Detail  Footer', 0, 0, 'fleDCFileforEmpowerNegative','*.*', 'VPOutbox', 'VPStaging', 'VPError', 'VPOutProc', 
	26, 'A', 'O', 'PIR 26372', GETDATE(), 'PIR 26372', GETDATE(), 0, NULL, NULL, 'N')
	SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO


IF NOT EXISTS (SELECT 1 FROM SGS_FILE WHERE [FILE_ID] = 110 AND [DESCRIPTION] = 'Def Comp File for Empower Positive')
BEGIN
	SET IDENTITY_INSERT[SGS_FILE] ON;
	INSERT INTO SGS_FILE ([FILE_ID], [DESCRIPTION], DELIMITED_BY, TRANSACTION_CODE_POS, TRANSACTION_CODE_LENGTH, TRANSACTION_CODE_VALUE, HEADER_GROUP_POS, HEADER_GROUP_LENGTH, 
	XML_LAYOUT_FILE, INBOUND_MASK, MAILBOX_PATH_CODE, STAGING_PATH_CODE, ERROR_PATH_CODE, PROCESS_PATH_CODE, FILE_STATUS_ID, FILE_STATUS_VALUE, INBOUND_OUTBOUND_FLAG, CREATED_BY,
	 CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, EMAIL_NOTIFICATION, OTHER_PARAMETERS, GROUP_PROCESS_FLAG)
	VALUES(110, 'Def Comp File for Empower Positive', ',', NULL, NULL, 'Detail  Footer', 0, 0, 'fleDefCompFileforEmpowerPositive','*.*', 'VPOutbox', 'VPStaging', 'VPError', 'VPOutProc', 
	26, 'A', 'O', 'PIR 26372', GETDATE(), 'PIR 26372', GETDATE(), 0, NULL, NULL, 'N')
	SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO


IF NOT EXISTS (SELECT 1 FROM SGS_FILE WHERE [FILE_ID] = 111 AND [DESCRIPTION] = 'Def Comp File for Empower Negative')
BEGIN
	SET IDENTITY_INSERT[SGS_FILE] ON;
	INSERT INTO SGS_FILE ([FILE_ID], [DESCRIPTION], DELIMITED_BY, TRANSACTION_CODE_POS, TRANSACTION_CODE_LENGTH, TRANSACTION_CODE_VALUE, HEADER_GROUP_POS, HEADER_GROUP_LENGTH, 
	XML_LAYOUT_FILE, INBOUND_MASK, MAILBOX_PATH_CODE, STAGING_PATH_CODE, ERROR_PATH_CODE, PROCESS_PATH_CODE, FILE_STATUS_ID, FILE_STATUS_VALUE, INBOUND_OUTBOUND_FLAG, CREATED_BY,
	 CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, EMAIL_NOTIFICATION, OTHER_PARAMETERS, GROUP_PROCESS_FLAG)
	VALUES(111, 'Def Comp File for Empower Negative', ',', NULL, NULL, 'Detail  Footer', 0, 0, 'fleDefCompFileforEmpowerNegative','*.*', 'VPOutbox', 'VPStaging', 'VPError', 'VPOutProc', 
	26, 'A', 'O', 'PIR 26372', GETDATE(), 'PIR 26372', GETDATE(), 0, NULL, NULL, 'N')
	SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO

