/********************Purpose: PIR 18493******************************
*********************Created By: Abhijeet********************************
*********************Comments: New code value for App wizard *****************/
/*
	SGT_WSS_BEN_APP_TAX_WITHHOLDING SCHEMA CHANGES
*/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'REFUND_FED_PERCENT' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD REFUND_FED_PERCENT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'REFUND_STATE_AMT' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD REFUND_STATE_AMT DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TAX_REF' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD TAX_REF VARCHAR(4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_ID' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD FILING_STATUS_ID INT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FILING_STATUS_VALUE' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD FILING_STATUS_VALUE VARCHAR(4) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_i' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD TWO_b_i DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_ii' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD TWO_b_ii DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'TWO_b_iii' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD TWO_b_iii DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_1' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD THREE_1 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_2' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD THREE_2 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_3' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD THREE_3 DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'THREE_TOTAL' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD THREE_TOTAL DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_a' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD FOUR_a DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_b' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD FOUR_b DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'FOUR_c' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD FOUR_c DECIMAL(13,2) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'NO_FED_WITHHOLDING' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD NO_FED_WITHHOLDING CHAR(1) NULL 
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'STATE_FLAT_AMOUNT' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP_TAX_WITHHOLDING'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP_TAX_WITHHOLDING
	ADD STATE_FLAT_AMOUNT DECIMAL(13,2) NULL 
END
GO

/*
	SGT_WSS_BEN_APP SCHEMA CHANGES
*/
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = N'LAST_STEP_WHERE_USER_LEFT' AND Object_ID = Object_ID(N'dbo.SGT_WSS_BEN_APP'))
BEGIN
    ALTER TABLE SGT_WSS_BEN_APP
	ADD LAST_STEP_WHERE_USER_LEFT VARCHAR(25) NULL 
END
GO


/********************Purpose: PIR 25729******************************
*********************Created By: Saylee********************************
*********************Comments: *****************/

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = 'BENEFIT_PLAN' AND Object_ID = Object_ID(N'dbo.SGT_ORG_PLAN_MEMBER_TYPE'))
BEGIN
ALTER TABLE SGT_ORG_PLAN_MEMBER_TYPE
ADD BENEFIT_PLAN VARCHAR(10)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE [Name] = 'RHIC_BENEFIT_PLAN' AND Object_ID = Object_ID(N'dbo.SGT_ORG_PLAN_MEMBER_TYPE'))
BEGIN
ALTER TABLE SGT_ORG_PLAN_MEMBER_TYPE
ADD RHIC_BENEFIT_PLAN VARCHAR(10)
END
GO
