/*Schema_Change_PIR_21230 */
/********************Purpose: PIR 21230 Contact Ticket Maintenance Callback Phone 2, Extn, Entn 2 fields added******************************
*********************Created By: Abhijeet********************************
*********************Comments: *****************/
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET'
                 AND COLUMN_NAME = 'CALLBACK_PHONE_2') 
	ALTER TABLE SGT_CONTACT_TICKET 
	ADD CALLBACK_PHONE_2 VARCHAR(50) NULL
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET'
                 AND COLUMN_NAME = 'EXTN') 
	ALTER TABLE SGT_CONTACT_TICKET 
	ADD EXTN VARCHAR(50) NULL
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET'
                 AND COLUMN_NAME = 'EXTN2') 
	ALTER TABLE SGT_CONTACT_TICKET 
	ADD EXTN2 VARCHAR(50) NULL
GO
-------------------------------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET_HISTORY'
                 AND COLUMN_NAME = 'CALLBACK_PHONE_2') 
	ALTER TABLE SGT_CONTACT_TICKET_HISTORY 
	ADD CALLBACK_PHONE_2 VARCHAR(50) NULL
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET_HISTORY'
                 AND COLUMN_NAME = 'EXTN') 
	ALTER TABLE SGT_CONTACT_TICKET_HISTORY 
	ADD EXTN VARCHAR(50) NULL
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_CONTACT_TICKET_HISTORY'
                 AND COLUMN_NAME = 'EXTN2') 
	ALTER TABLE SGT_CONTACT_TICKET_HISTORY 
	ADD EXTN2 VARCHAR(50) NULL
GO