
/********************Purpose: PIR 18493 App Wizard Round 3 Testing ******************************
*********************Created By: Abhijeet M ********************************
*********************Comments: Added new acknoledgment *****************/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_BEN_APP'
                 AND COLUMN_NAME = 'IS_GBACKNOWLEDGEMENT_CHECKED')
ALTER TABLE SGT_WSS_BEN_APP
	ADD IS_GBACKNOWLEDGEMENT_CHECKED CHAR(1) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_BEN_APP'
                 AND COLUMN_NAME = 'IS_SLCACKNOWLEDGEMENT_CHECKED')
ALTER TABLE SGT_WSS_BEN_APP
	ADD IS_SLCACKNOWLEDGEMENT_CHECKED CHAR(1) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_BEN_APP'
                 AND COLUMN_NAME = 'IS_FPACKNOWLEDGEMENT_CHECKED')
ALTER TABLE SGT_WSS_BEN_APP
	ADD IS_FPACKNOWLEDGEMENT_CHECKED CHAR(1) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_BEN_APP'
                 AND COLUMN_NAME = 'IS_PLSOACKNOWLEDGEMENT_CHECKED')
ALTER TABLE SGT_WSS_BEN_APP
	ADD IS_PLSOACKNOWLEDGEMENT_CHECKED CHAR(1) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGT_WSS_BEN_APP'
                 AND COLUMN_NAME = 'IS_APDBDCACKNOWLEDGEMENT_CHECKED')
ALTER TABLE SGT_WSS_BEN_APP
	ADD IS_APDBDCACKNOWLEDGEMENT_CHECKED CHAR(1) NULL
GO

