DECLARE @NEXTBENEFITPAYMENTDATE DATETIME
DECLARE @LASTDAYOFPREVIOUSMONTHTONEXTBENEFITPAYMENTDATE DATETIME

SELECT @NEXTBENEFITPAYMENTDATE = PAYMENT_DATE FROM SGT_PAYMENT_SCHEDULE WHERE SCHEDULE_TYPE_VALUE = 'MTLY' AND STATUS_VALUE = 'PRCD' AND ACTION_STATUS_VALUE = 'PRCD'
SET @NEXTBENEFITPAYMENTDATE = DATEADD(M, 1, @NEXTBENEFITPAYMENTDATE)
SET @LASTDAYOFPREVIOUSMONTHTONEXTBENEFITPAYMENTDATE = EOMONTH(DATEADD(M, -1, @NEXTBENEFITPAYMENTDATE))

/*
	REFUND, PLSO, ROLLOVER FEDERAL TAX ENTRY
*/
IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_FLAT_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND IS_RMD = 'N')
BEGIN
	INSERT SGT_FED_STATE_FLAT_TAX_RATE VALUES (2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 1904, '', 2201, '', 2225, '', '', 20.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 321, NULL, NULL, 'N', 20.00, 100.00, 'FD22') 
END

/*
	RMD FEDERAL TAX ENTRY
*/
IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_FLAT_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND IS_RMD = 'Y')
BEGIN
	INSERT SGT_FED_STATE_FLAT_TAX_RATE VALUES (2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 1904, '', 2201, '', 2225, '', '', 10.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 321, NULL, NULL, 'Y', 0.00, 100.00, 'FD22') 
END


/*
	REFUND STATE TAX ENTRY
*/
IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_FLAT_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='STAT' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE)
BEGIN
	INSERT SGT_FED_STATE_FLAT_TAX_RATE VALUES (2211, 'STAT', @NEXTBENEFITPAYMENTDATE, 1904, '', 2201, '', 2225, '', '', 3.92, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 321, NULL, NULL, NULL, 0.00, 100.00, 'ST22') 
END


/*
	FILING STATUS CODE GROUP	
*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7033) 
BEGIN
INSERT [dbo].[SGS_CODE] ([CODE_ID], [DESCRIPTION], [DATA1_CAPTION], [DATA1_TYPE], [DATA2_CAPTION], [DATA2_TYPE], [DATA3_CAPTION], [DATA3_TYPE], [FIRST_LOOKUP_ITEM], 
[FIRST_MAINTENANCE_ITEM], [COMMENTS], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (7033, N'Filing Status',NULL, NULL, NULL, NULL, NULL, NULL, N'All', NULL, NULL, NULL, 'PIR_25084', 
GETDATE(), 'PIR_25084', GETDATE(), 1)
END



IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7033 AND CODE_VALUE = 'SGMF') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7033, N'SGMF', N'Single or Married filing Separately', NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, 'PIR_25084', 
 GETDATE(), 'PIR_25084', GETDATE(), 0)
END


IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7033 AND CODE_VALUE = 'MFJQ') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7033, N'MFJQ', N'Married filing jointly or Qualifying widow(er)', NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, 'PIR_25084', 
 GETDATE(), 'PIR_25084', GETDATE(), 0)
END


IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7033 AND CODE_VALUE = 'HOHH') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7033, N'HOHH', N'Head of household (Check only if you are unmarried and pay more than half the costs of keeping up a home for yourself and a qualifying individual.)', NULL, NULL, NULL, NULL, NULL, NULL, '3', NULL, 'PIR_25084', 
 GETDATE(), 'PIR_25084', GETDATE(), 0)
END


/*
	Married filing jointly or Qualifying widow(er)
*/

IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 0.00 AND MAXIMUM_AMOUNT = 13000.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 0.00, 13000.00, 0.00, 0.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 13000.00 AND MAXIMUM_AMOUNT = 33550.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 13000.00, 33550.00, 0.00, 10.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 33550.00 AND MAXIMUM_AMOUNT = 96550.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 33550.00, 96550.00, 2055.00, 12.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 96550.00 AND MAXIMUM_AMOUNT = 191150.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 96550.00, 191150.00, 9615.00, 22.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 191150.00 AND MAXIMUM_AMOUNT = 353100.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 191150.00, 353100.00, 30427.00, 24.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 353100.00 AND MAXIMUM_AMOUNT = 444900.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 353100.00, 444900.00, 69295.00, 32.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 444900.00 AND MAXIMUM_AMOUNT = 660850.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 444900.00, 660850.00, 98671.00, 35.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'MFJQ' AND MINIMUM_AMOUNT = 660850.00 AND MAXIMUM_AMOUNT = 999999999.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 660850.00, 999999999.00, 174253.50, 37.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'MFJQ', 'FD22')
END


/*
	Single or Married filing Separately
*/

IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 0.00 AND MAXIMUM_AMOUNT = 4350.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 0.00, 4350.00, 0.00, 0.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 4350.00 AND MAXIMUM_AMOUNT = 14625.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 4350.00, 14625.00, 0.00, 10.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 14625.00 AND MAXIMUM_AMOUNT = 46125.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 14625.00, 46125.00, 1027.50, 12.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 46125.00 AND MAXIMUM_AMOUNT = 93425.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 46125.00, 93425.00, 4807.50, 22.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 93425.00 AND MAXIMUM_AMOUNT = 174400.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 93425.00, 174400.00, 15213.50, 24.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 174400.00 AND MAXIMUM_AMOUNT = 220300.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 174400.00, 220300.00, 34647.50, 32.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 220300.00 AND MAXIMUM_AMOUNT = 544250.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 220300.00, 544250.00, 49335.50, 35.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'SGMF' AND MINIMUM_AMOUNT = 544250.00 AND MAXIMUM_AMOUNT = 999999999.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 544250.00, 999999999.00, 162718.00, 37.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'SGMF', 'FD22')
END


/*
	Head of household
*/

IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 0.00 AND MAXIMUM_AMOUNT = 10800.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 0.00, 10800.00, 0.00, 0.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 10800.00 AND MAXIMUM_AMOUNT = 25450.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 10800.00, 25450.00, 0.00, 10.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 25450.00 AND MAXIMUM_AMOUNT = 66700.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 25450.00, 66700.00, 1465.00, 12.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 66700.00 AND MAXIMUM_AMOUNT = 99850.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 66700.00, 99850.00, 6415.00, 22.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 99850.00 AND MAXIMUM_AMOUNT = 180850.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 99850.00, 180850.00, 13708.00, 24.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 180850.00 AND MAXIMUM_AMOUNT = 226750.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 180850.00, 226750.00, 33148.00, 32.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 226750.00 AND MAXIMUM_AMOUNT = 550700.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 226750.00, 550700.00, 47836.00, 35.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


IF NOT EXISTS (SELECT 1 FROM SGT_FED_STATE_TAX_RATE WHERE TAX_IDENTIFIER_VALUE ='FDRL' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE AND FILING_STATUS_ID = 7033 AND FILING_STATUS_VALUE = 'HOHH' AND MINIMUM_AMOUNT = 550700.00 AND MAXIMUM_AMOUNT = 999999999.00)
BEGIN
INSERT SGT_FED_STATE_TAX_RATE VALUES(2211, 'FDRL', @NEXTBENEFITPAYMENTDATE, 306, '', 550700.00, 999999999.00, 161218.50, 37.00, 0.00, 'PIR_25084', GETDATE(), 'PIR_25084', GETDATE(), 0, 'Y', 7033, 'HOHH', 'FD22')
END


/*
	Payment - Benefit Destribution Type - New Distribution Types Added.
*/

--IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 2224 AND CODE_VALUE = 'RIRA') 
--BEGIN
--INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
-- [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
-- VALUES (2224, N'RIRA', N'Roth IRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR_25084', 
-- GETDATE(), 'PIR_25084', GETDATE(), 0)
--END
--GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 2224 AND CODE_VALUE = 'RMD') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (2224, N'RMD', N'RMD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR_25084', 
 GETDATE(), 'PIR_25084', GETDATE(), 0)
END


/* 
	RMD Tax PITs
*/

IF NOT EXISTS (SELECT 1 FROM SGT_PAYMENT_ITEM_TYPE WHERE ITEM_TYPE_CODE = 'ITEM81')
BEGIN	
	INSERT SGT_PAYMENT_ITEM_TYPE VALUES ('ITEM81', 'RMD Federal Tax Amount', '81', 2208, 'ONTP', 2207, 'REGL', -1, 
	'Federal Tax', 'N', 'Y', 'Y', 2209, 'DEDT', 2221, 'HDDN', 2212, 'HDDN', 2204, NULL, NULL, 2222, 'NOTX', 2223, 'DONT', NULL, 'N', NULL, 'PIR_25084', GETDATE(), 
	'PIR_25084', GETDATE(), 0, 0, 2511, 'FEDL', 2512, 'FDAN', 2514, 'FDTX', 'N', 'P081', 2519, 'FEDX', 2903, 'CWHR', 2520, NULL, 'N', 3003, 'REGL', 'Y', 'N', 2908, 'REWT')
END


IF NOT EXISTS (SELECT 1 FROM SGT_PAYMENT_ITEM_TYPE WHERE ITEM_TYPE_CODE = 'ITEM82')
BEGIN	
	INSERT SGT_PAYMENT_ITEM_TYPE VALUES ('ITEM82', 'RMD State Tax Amount', '82', 2208, 'ONTP', 2207, 'REGL', -1, 
	'State Tax', 'N', 'Y', 'Y', 2209, 'DEDT', 2221, 'HDDN', 2212, 'HDDN', 2204, NULL, NULL, 2222, 'NOTX', 2223, 'DONT', NULL, 'N', NULL, 'PIR_25084', GETDATE(), 
	'PIR_25084', GETDATE(), 0, 0, 2511, 'STAT', 2512, 'STAN', 2514, 'STTX', 'N', 'P082', 2519, 'STTX', 2903, 'CWHR', 2520, NULL, 'N', 3003, 'REGL', 'Y', 'N', 2908, 'REWT')
END


/*
	TAX REF CONFIG

*/
IF NOT EXISTS (SELECT 1 FROM SGT_TAX_REF_CONFIG WHERE TAX_IDENTIFIER_ID = 2211 AND TAX_IDENTIFIER_VALUE = 'FDRL' AND TAX_REF = 'FD22' AND EFFECTIVE_DATE = @NEXTBENEFITPAYMENTDATE)
INSERT SGT_TAX_REF_CONFIG VALUES (2211, 'FDRL', 'FD22', @NEXTBENEFITPAYMENTDATE, 12, 8600.00, 12900.00, 8600.00, 4300.00,200000.00,400000.00,17,2000.00,500.00, 'If your total income will be ${0} or less (${1} or less if married filing jointly):','Multiply the number of qualifying children under age {0} by ${1}','Multiply the number of other dependents by ${0}')

/*
	
*/
UPDATE SGS_CODE_VALUE SET DESCRIPTION = 'PLSO' WHERE CODE_ID = 2224 AND CODE_VALUE = 'PSLO'

/*  *******NON-ANNUITY PAYMENTS*****************************************
	Existing Withhold Record Conversion - Refund Payee Accounts Federal
	Where Tax_Option_Value = ‘FTWH’ – store 20 in Refund_Fed_Percent
*/
UPDATE WITHHOLDING SET WITHHOLDING.REFUND_FED_PERCENT = 20.00
--SELECT 
--	*
FROM 
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING WITHHOLDING WITH(NOLOCK)
WHERE 
	TAX_IDENTIFIER_VALUE = 'FDRL' AND 
	BENEFIT_DISTRIBUTION_TYPE_VALUE = 'LSDB' AND 
	TAX_OPTION_VALUE = 'FTWH'
/*
	Existing Withhold Record Conversion - Refund Payee Accounts State
	Where Tax_Option_Value = ‘STWH’ – store the amount of the current PAPIT for Item Type 63 and End Date is Null or future in Refund_State_Amt
*/
UPDATE WITHHOLDING SET WITHHOLDING.REFUND_STATE_AMT = PAPIT.AMOUNT
--SELECT 
--PAPIT.PAYEE_ACCOUNT_ID, WITHHOLDING.PAYEE_ACCOUNT_ID, PAPIT.AMOUNT, PAPIT.PAYMENT_ITEM_TYPE_ID, PAPIT.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID, DETAIL.AMOUNT, DETAIL.PAYMENT_ITEM_TYPE_ID, DETAIL.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID
FROM 
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING WITHHOLDING WITH(NOLOCK)
	INNER JOIN SGT_PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE PAPIT WITH(NOLOCK) ON PAPIT.PAYEE_ACCOUNT_ID = WITHHOLDING.PAYEE_ACCOUNT_ID
	INNER JOIN SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING_ITEM_DETAIL DETAIL WITH(NOLOCK) ON DETAIL.PAYEE_ACCOUNT_TAX_WITHHOLDING_ID = WITHHOLDING.PAYEE_ACCOUNT_TAX_WITHHOLDING_ID 
	AND DETAIL.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID = PAPIT.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID AND DETAIL.PAYMENT_ITEM_TYPE_ID = PAPIT.PAYMENT_ITEM_TYPE_ID
WHERE 
	WITHHOLDING.TAX_IDENTIFIER_VALUE = 'STAT' 
	AND WITHHOLDING.BENEFIT_DISTRIBUTION_TYPE_VALUE = 'LSDB' 
	AND WITHHOLDING.TAX_OPTION_VALUE = 'STWH'
	AND PAPIT.PAYMENT_ITEM_TYPE_ID = 12 AND ((PAPIT.END_DATE IS NULL) OR (ISNULL(PAPIT.END_DATE, '99991231') >= @LASTDAYOFPREVIOUSMONTHTONEXTBENEFITPAYMENTDATE))
/*
	Existing Withhold Record Conversion - Refund Payee Accounts State
	Where Tax_Option_Value = ‘NSTW’ – store 0 in Refund_State_Amt
*/
UPDATE WITHHOLDING SET WITHHOLDING.REFUND_STATE_AMT = 0.00
--SELECT 
--*
FROM 
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING WITHHOLDING WITH(NOLOCK)
WHERE 
	WITHHOLDING.TAX_IDENTIFIER_VALUE = 'STAT' 
	AND WITHHOLDING.BENEFIT_DISTRIBUTION_TYPE_VALUE = 'LSDB' 
	AND WITHHOLDING.TAX_OPTION_VALUE = 'NSTW'
/*
	ANNUNITY PAYMENTS EXISTING WITHHOLDING RECORDS CONVERSION - STATE TAX
*/
UPDATE WITHHOLDING SET WITHHOLDING.STATE_FLAT_AMOUNT = PAPIT.AMOUNT
--SELECT 
--*
FROM 
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING WITHHOLDING WITH(NOLOCK)
	INNER JOIN SGT_PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE PAPIT WITH(NOLOCK) ON PAPIT.PAYEE_ACCOUNT_ID = WITHHOLDING.PAYEE_ACCOUNT_ID
	INNER JOIN SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING_ITEM_DETAIL DETAIL WITH(NOLOCK) ON DETAIL.PAYEE_ACCOUNT_TAX_WITHHOLDING_ID = WITHHOLDING.PAYEE_ACCOUNT_TAX_WITHHOLDING_ID 
	AND DETAIL.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID = PAPIT.PAYEE_ACCOUNT_PAYMENT_ITEM_TYPE_ID AND DETAIL.PAYMENT_ITEM_TYPE_ID = PAPIT.PAYMENT_ITEM_TYPE_ID
WHERE 
	WITHHOLDING.TAX_IDENTIFIER_VALUE = 'STAT' 
	AND WITHHOLDING.BENEFIT_DISTRIBUTION_TYPE_VALUE = 'MNBF' 
	AND PAPIT.PAYMENT_ITEM_TYPE_ID = 63 AND ((PAPIT.END_DATE IS NULL) OR (ISNULL(PAPIT.END_DATE, '99991231') >= @LASTDAYOFPREVIOUSMONTHTONEXTBENEFITPAYMENTDATE))	


/*
	ANNUNITY PAYMENTS EXISTING WITHHOLDING RECORDS CONVERSION - FEDERAL TAX
*/
UPDATE SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING SET FILING_STATUS_ID = 7033


UPDATE WITHHOLDING SET FILING_STATUS_VALUE = CASE WHEN WITHHOLDING.MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 'SGMF' WHEN WITHHOLDING.MARITAL_STATUS_VALUE = 'MRID' THEN 'MFJQ' END, 
		WITHHOLDING.FOUR_a = CASE WHEN WITHHOLDING.MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 8600.00 WHEN WITHHOLDING.MARITAL_STATUS_VALUE = 'MRID' THEN 12900.00 ELSE NULL END,
		WITHHOLDING.FOUR_b = CASE WHEN WITHHOLDING.TAX_ALLOWANCE > 0 THEN WITHHOLDING.TAX_ALLOWANCE * 4300 ELSE NULL END,
		WITHHOLDING.FOUR_c = CASE WHEN WITHHOLDING.ADDITIONAL_TAX_AMOUNT != 0 THEN WITHHOLDING.ADDITIONAL_TAX_AMOUNT ELSE NULL END,
		WITHHOLDING.NO_FED_WITHHOLDING = CASE WHEN WITHHOLDING.TAX_OPTION_VALUE = 'NFTX' AND WITHHOLDING.TAX_IDENTIFIER_VALUE = 'FDRL' AND WITHHOLDING.BENEFIT_DISTRIBUTION_TYPE_VALUE = 'MNBF' THEN 'Y' ELSE NULL END
--SELECT 
--		--CASE WHEN WITHHOLDING.MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 'SGMF' WHEN WITHHOLDING.MARITAL_STATUS_VALUE = 'MRID' THEN 'MFJQ' END AS FILING_STATUS_VALUE, 
--		--CASE WHEN WITHHOLDING.MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 8600.00 WHEN WITHHOLDING.MARITAL_STATUS_VALUE = 'MRID' THEN 12900.00 ELSE NULL END AS FOUR_A,
--		--CASE WHEN WITHHOLDING.TAX_ALLOWANCE > 0 THEN WITHHOLDING.TAX_ALLOWANCE * 4300 ELSE NULL END AS FOUR_B,
--		--CASE WHEN WITHHOLDING.ADDITIONAL_TAX_AMOUNT > 0 THEN WITHHOLDING.ADDITIONAL_TAX_AMOUNT ELSE NULL END AS FOUR_C
--		*
FROM 
	SGT_PAYEE_ACCOUNT_TAX_WITHHOLDING WITHHOLDING WITH(NOLOCK)
WHERE 
	WITHHOLDING.TAX_IDENTIFIER_VALUE = 'FDRL' AND (WITHHOLDING.MARITAL_STATUS_VALUE IS NOT NULL AND WITHHOLDING.MARITAL_STATUS_VALUE != '')  
	AND (WITHHOLDING.END_DATE IS NULL OR ISNULL(WITHHOLDING.END_DATE,'99991231') >= @LASTDAYOFPREVIOUSMONTHTONEXTBENEFITPAYMENTDATE)

/*
	WE NEED NOT RUN UPDATE STATE TAX BATCH PIECE
GO
*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 52 AND CODE_VALUE = 'TAXA') 
BEGIN
	INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
	[CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
	VALUES (52, N'TAXA', N'Tax Applicable', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'PIR_25084', 
	GETDATE(), 'PIR_25084', GETDATE(), 0)
END

/*
	MSS Hard Errors
	
*/
IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10470)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10470,'Federal Tax Withholding Percentage Cannot Be Less Than a minimum of 20%.',16,'E',NULL,NULL,'PIR_25084',GETDATE(),'PIR_25084',GETDATE(),0)
GO


UPDATE SGT_PAYMENT_HISTORY_HEADER SET FED_FILING_STATUS_ID = 7033

UPDATE HEADER SET HEADER.FED_FILING_STATUS_VALUE = CASE WHEN HEADER.FED_MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 'SGMF' WHEN HEADER.FED_MARITAL_STATUS_VALUE = 'MRID' THEN 'MFJQ' ELSE NULL END 
--SELECT 
--		CASE WHEN HEADER.FED_MARITAL_STATUS_VALUE IN ('SNGL', 'MRDW') THEN 'SGMF' WHEN HEADER.FED_MARITAL_STATUS_VALUE = 'MRID' THEN 'MFJQ' ELSE NULL END 
FROM 
	SGT_PAYMENT_HISTORY_HEADER HEADER

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10471)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10471,'Filing Status Is Required.',16,'E',NULL,NULL,'PIR_25084',GETDATE(),'PIR_25084',GETDATE(),0)
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10472)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10472,'Federal Tax Withholding Percentage Cannot Be Less Than a minimum of {0}%.',16,'E',NULL,NULL,'PIR_25084',GETDATE(),'PIR_25084',GETDATE(),0)
GO

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10473)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10473,'Please complete Step 1c to update tax filing status.',16,'E',NULL,NULL,'PIR_25084',GETDATE(),'PIR_25084',GETDATE(),0)
GO
