/********************Purpose: PIR 20961 ******************************
*********************Created By: Nikhil Chavan********************************
*********************Comments: PIR 20961 *****************/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_COR_TEMPLATES] WHERE TEMPLATE_NAME = 'PER-0958')
INSERT INTO [dbo].[SGS_COR_TEMPLATES] ([TEMPLATE_NAME], [TEMPLATE_DESC], [TEMPLATE_GROUP_ID], [TEMPLATE_GROUP_VALUE], [ACTIVE_FLAG], [DESTINATION_ID], [DESTINATION_VALUE], [ASSOCIATED_FORMS], [FILTER_OBJECT_ID], [FILTER_OBJECT_FIELD], [FILTER_OBJECT_VALUE], [CONTACT_ROLE_ID], [CONTACT_ROLE_VALUE], [BATCH_FLAG], [ONLINE_FLAG], [AUTO_PRINT_FLAG], [PRINTER_NAME_ID], [PRINTER_NAME_VALUE], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ], IMAGE_DOC_CATEGORY_ID, IMAGE_DOC_CATEGORY_VALUE, FILENET_DOCUMENT_TYPE_ID, FILENET_DOCUMENT_TYPE_VALUE, DOCUMENT_CODE) 
VALUES ('PER-0958', 'Person Envelope', '19', 'MMBR', 'Y', '601', 'PURG', 'wfmPersonMaintenance;', NULL, NULL, NULL, '515',NULL, 'N', 'Y', 'N', '44', NULL, 'PIR 20961', GETDATE(), 'PIR 20961', GETDATE(), '0', 603, NULL, 604, NULL, '1522')
GO