/*Data_Change_PIR 24737 */
/********************Purpose: PIR 24737 – Temp Health enrollment ******************************
*********************Created By: Nurul********************************
*********************Comments: *****************/
------------------------------------------------------------------------------------------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7031) 
BEGIN
INSERT [dbo].[SGS_CODE] ([CODE_ID], [DESCRIPTION], [DATA1_CAPTION], [DATA1_TYPE], [DATA2_CAPTION], [DATA2_TYPE], [DATA3_CAPTION], [DATA3_TYPE], [FIRST_LOOKUP_ITEM], 
[FIRST_MAINTENANCE_ITEM], [COMMENTS], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (7031, N'Method',NULL, NULL, NULL, NULL, NULL, NULL, N'All', NULL, NULL, NULL, 'PIR 24737', 
GETDATE(), 'PIR 24737', GETDATE(), 1)
END
GO


IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7031 AND CODE_VALUE = 'NEWH') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7031, N'NEWH', N'New Hire', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7031 AND CODE_VALUE = 'CPHI') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7031, N'CPHI', N'Change in Position / Increase in Hours', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7031 AND CODE_VALUE = 'LBM') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7031, N'LBM', N'Look-back Measurement',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO
--------------------------------------------------------------------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7032) 
BEGIN
INSERT [dbo].[SGS_CODE] ([CODE_ID], [DESCRIPTION], [DATA1_CAPTION], [DATA1_TYPE], [DATA2_CAPTION], [DATA2_TYPE], [DATA3_CAPTION], [DATA3_TYPE], [FIRST_LOOKUP_ITEM], 
[FIRST_MAINTENANCE_ITEM], [COMMENTS], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
VALUES (7032, N'Lookback Measure ',NULL, NULL, NULL, NULL, NULL, NULL, N'All', NULL, NULL, NULL, 'PIR 24737', 
GETDATE(), 'PIR 24737', GETDATE(), 1)
END
GO


IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7032 AND CODE_VALUE = 'ANNE') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7032, N'ANNE', N'Annual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 7032 AND CODE_VALUE = 'NEWE') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (7032, N'NEWE', N'Newly Eligible', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO
--------------------------------------------------------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10454)
BEGIN
INSERT INTO SGS_MESSAGES ([MESSAGE_ID], [DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(10454, 'Date Of Change In Position Is Required.', 16, 'E', NULL, NULL, 'PIR_24737', GETDATE(), 'PIR_24737', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10455)
BEGIN
INSERT INTO SGS_MESSAGES ([MESSAGE_ID], [DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(10455, 'New Hire Date Is Required.', 16, 'E', NULL, NULL, 'PIR_24737', GETDATE(), 'PIR_24737', GETDATE(), 0)
END
GO
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10456)
BEGIN
INSERT INTO SGS_MESSAGES ([MESSAGE_ID], [DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(10456, 'Type Of Look-back Measurement Is Required.', 16, 'E', NULL, NULL, 'PIR_24737', GETDATE(), 'PIR_24737', GETDATE(), 0)
END
GO



IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 52 AND CODE_VALUE = 'ACAE') 
BEGIN
INSERT [dbo].[SGS_CODE_VALUE] ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE],
 [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ]) 
 VALUES (52, N'ACAE', N'ACA Certification Annual Enrollment Window', '10/01/2022', '10/15/2022', NULL, NULL, NULL, NULL, NULL, NULL, 'PIR 24737', 
 GETDATE(), 'PIR 24737', GETDATE(), 0)
END
GO

IF EXISTS (SELECT 1 FROM [dbo].[SGT_WSS_ACKNOWLEDGEMENT] WHERE ACKNOWLEDGEMENT_ID=48) 
BEGIN
UPDATE SGT_WSS_ACKNOWLEDGEMENT SET ACKNOWLEDGEMENT_TEXT = 'a. I or my Eligible Dependents have other group insurance coverage, and that coverage is either terminated as a result of loss of eligibility (Including loss as a result of legal separation, divorce, death, termination of employment or reduction of hours) or employer contributions toward such coverage was terminated; or'
WHERE ACKNOWLEDGEMENT_ID=48
END
GO

/********************Purpose: PIR 24737 ******************************
*********************Created By: Surendra Reddy********************************
*********************Comments: Derrick Email - *****************/

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID = 10459)
BEGIN
INSERT INTO SGS_MESSAGES ([MESSAGE_ID], [DISPLAY_MESSAGE], [SEVERITY_ID], [SEVERITY_VALUE], [INTERNAL_INSTRUCTIONS], [EMPLOYER_INSTRUCTIONS], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(10459, 'Employer can''t submit the request if the “To” date is greater than today’s date.', 16, 'E', NULL, NULL, 'PIR_24737', GETDATE(), 'PIR_24737', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT 1 FROM SGT_WSS_AUTO_POSTING_CROSS_REF WHERE AUTO_POSTING_CROSS_REF_ID = 153)
BEGIN
INSERT INTO SGT_WSS_AUTO_POSTING_CROSS_REF (AUTO_POSTING_CROSS_REF_ID,PLAN_ID,	PLAN_ENROLLMENT_OPTION_ID,	PLAN_ENROLLMENT_OPTION_VALUE,	CHANGE_REASON_ID,	CHANGE_REASON_VALUE,	CHANGE_EFFECTIVE_DATE_ID,	CHANGE_EFFECTIVE_DATE_VALUE,	AUTO_POST_FLAG,	WORKFLOW_PROCESS_ID,	PROMPT_USER_TEXT,	DOCUMENT)
VALUES(153,12,	6003,	'ENRL',	332,	'ACAA',	6005,	'NOAP',	'Y',	NULL,	NULL,	NULL)
END
GO