
--------------Created By: Sanket Chougale
--------------Purpose   : PIR 25768
--------------Date      : 06/30/2023
IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10491)
INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(10491,'You have reached the maximum number of applications allowed daily. You may complete Life Insurance Enrollment/Change - SFN 53803 or submit a new application through MSS the next day.',16,'E',NULL,NULL,'PIR 25768',GETDATE(),'PIR 25768',GETDATE(),0)
GO

--------------Created By: Vidya Fulsoundar
--------------Purpose   : PIR 25729
--------------Date      : 07/24/2023
IF NOT EXISTS(SELECT 1 FROM SGS_CODE WHERE CODE_ID=7034)
BEGIN
INSERT INTO SGS_CODE ([CODE_ID], [DESCRIPTION], [DATA1_CAPTION], [DATA1_TYPE], [DATA2_CAPTION], [DATA2_TYPE], [DATA3_CAPTION], [DATA3_TYPE], [FIRST_LOOKUP_ITEM], [FIRST_MAINTENANCE_ITEM], [COMMENTS], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7034, 'Benefit Provision Multiplier Type',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL, 'PIR 25729',	GETDATE(),	'PIR 25729', GETDATE(),0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=7034 AND CODE_VALUE = 'FJDT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7034, 'FJDT', 'First Joining Date',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	1,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=7034 AND CODE_VALUE = 'RTDT')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(7034, 'RTDT', 'Retirement Date',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	2,	NULL,	'PIR 25729',	GETDATE(),	'PIR 25729',	GETDATE(),	0)
END

IF EXISTS (SELECT 1 FROM SGT_BENEFIT_PROVISION_MULTIPLIER WHERE BENEFIT_MULTIPLIER_TYPE_ID IS NULL OR BENEFIT_MULTIPLIER_TYPE_VALUE IS NULL)
BEGIN
UPDATE SGT_BENEFIT_PROVISION_MULTIPLIER SET BENEFIT_MULTIPLIER_TYPE_ID = 7034, BENEFIT_MULTIPLIER_TYPE_VALUE = CASE WHEN BENEFIT_PROVISION_ID = 10 AND EFFECTIVE_DATE = '08/01/2023' THEN 'RTDT' ELSE 'FJDT' END
END

--------------Created By: Bharat Reddy	
--------------Purpose   : PIR 25431
--------------Date      : 18 Aug 2023

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10493)
INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(10493,'Member HSA contribution may not start until one month after HDHP effective date.',16,'E',NULL,NULL,'PIR 25431',GETDATE(),'PIR 25431',GETDATE(),0)
GO


--------------Created By: Sanket Chougale
--------------Purpose   : PIR 25808 
--------------Date      : 06/30/2023

IF NOT EXISTS (SELECT * FROM SGS_MESSAGES WHERE MESSAGE_ID=10492)
INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES(10492,'You have reached the maximum number of election allowed daily.',16,'E',NULL,NULL,'PIR 25808',GETDATE(),'PIR 25808',GETDATE(),0)
GO