
IF EXISTS(SELECT 1 FROM [SGT_DOCUMENT] WHERE WSS='MSS' AND DOCUMENT_NAME NOT LIKE 'SFN%')
BEGIN
	UPDATE [SGT_DOCUMENT] SET DOCUMENT_NAME = 'SFN-' + DOCUMENT_CODE + ' ' + dbo.InitialCap(Document_name)
	WHERE WSS='MSS' AND DOCUMENT_NAME NOT LIKE 'SFN%' --AND FILENET_DOCUMENT_TYPE = 'FORM'
END


IF NOT EXISTS (SELECT 1 FROM [SGT_DOCUMENT] WHERE DOCUMENT_NAME = 'SFN-60037 ESRD Physician Statement')
INSERT [SGT_DOCUMENT]
		(DOCUMENT_CODE, DOCUMENT_NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, IGNORE_PROCESS_FLAG, WSS, FILENET_DOCUMENT_TYPE) 
VALUES ('60037', 'SFN-60037 ESRD Physician Statement', 'PIR 18493', GETDATE(), 'PIR 18493', GETDATE(), 0,'N','MSS', 'FORM' )
GO


/********************Purpose: PIR 16890 ******************************
*********************Created By: Ganesh********************************
*********************Comments: *****************/

IF NOT EXISTS (SELECT * FROM SGS_COR_TEMPLATES WHERE TEMPLATE_NAME ='PER-0500')
INSERT INTO [dbo].[SGS_COR_TEMPLATES]
           ([TEMPLATE_NAME]
           ,[TEMPLATE_DESC]
           ,[TEMPLATE_GROUP_ID]
           ,[TEMPLATE_GROUP_VALUE]
           ,[ACTIVE_FLAG]
           ,[DESTINATION_ID]
           ,[DESTINATION_VALUE]
           ,[ASSOCIATED_FORMS]
           ,[FILTER_OBJECT_ID]
           ,[FILTER_OBJECT_FIELD]
           ,[FILTER_OBJECT_VALUE]
           ,[CONTACT_ROLE_ID]
           ,[CONTACT_ROLE_VALUE]
           ,[BATCH_FLAG]
           ,[ONLINE_FLAG]
           ,[AUTO_PRINT_FLAG]
           ,[PRINTER_NAME_ID]
           ,[PRINTER_NAME_VALUE]
           ,[CREATED_BY]
           ,[CREATED_DATE]
           ,[MODIFIED_BY]
           ,[MODIFIED_DATE]
           ,[UPDATE_SEQ]
           ,[IMAGE_DOC_CATEGORY_ID]
           ,[IMAGE_DOC_CATEGORY_VALUE]
           ,[FILENET_DOCUMENT_TYPE_ID]
           ,[FILENET_DOCUMENT_TYPE_VALUE]
           ,[DOCUMENT_CODE])
VALUES
		  ('PER-0500','TFFR Dual Service Verification',19,'MMBR','Y',601,NULL,'wfmPensionContributionDetailMaintenance;',NULL,NULL,NULL,515,NULL,'N','Y','N',44,NULL,'PIR16890',GETDATE(),'PIR16890',GETDATE(),1,603,'MEMB',604,'CORR','1519')
GO

/********************Purpose: PIR 22807 ******************************
*********************Created By: Vidya ********************************
*********************Comments: *****************/

IF EXISTS (SELECT 1 FROM [dbo].[SGS_CODE_VALUE] WHERE CODE_ID = 330) 
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA3=12 WHERE CODE_ID=330
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'SGT_SERVICE_PURCHASE_AMORTIZATION_SCHEDULE' AND [COLUMN_NAME] = 'INTEREST_ACCRUAL_DATE')
BEGIN
ALTER TABLE SGT_SERVICE_PURCHASE_AMORTIZATION_SCHEDULE
ADD INTEREST_ACCRUAL_DATE [DATETIME] NOT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'SGT_SERVICE_PURCHASE_AMORTIZATION_SCHEDULE' AND [COLUMN_NAME] = 'INTEREST_ACCRUAL')
BEGIN
ALTER TABLE SGT_SERVICE_PURCHASE_AMORTIZATION_SCHEDULE
ADD INTEREST_ACCRUAL [DECIMAL](13, 2) NOT NULL
END
GO

/********************Purpose: PIR 14425 ******************************
*********************Created By: Surendra********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT 1 FROM  [dbo].[SGS_MESSAGES] WHERE MESSAGE_ID=10407)
INSERT INTO [dbo].[SGS_MESSAGES]
           ([MESSAGE_ID],[DISPLAY_MESSAGE],[SEVERITY_ID],[SEVERITY_VALUE],[INTERNAL_INSTRUCTIONS],[EMPLOYER_INSTRUCTIONS],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES
          (10407,'Please calculate benefit manually due to prior popup.', 16 ,'E' ,NULL ,NULL ,'PIR_14425', GETDATE(),'PIR_14425' ,GETDATE() ,0)
GO
/********************Purpose: PIR 18493 App Wizard Round 2 Testing ******************************
*********************Created By: Abhijeet M ********************************
*********************Comments: Use DATA2 for Ben Type Text *****************/
IF EXISTS(SELECT 1 FROM SGS_CODE WHERE CODE_ID = 1904 AND DATA2_TYPE IS NULL)
BEGIN
	UPDATE SGS_CODE SET DATA1_CAPTION = 'Used in MSS', DATA1_TYPE = 'str',DATA2_CAPTION = 'Used in App wizard', DATA2_TYPE = 'str' WHERE CODE_ID = 1904
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'DISA' AND DATA2 <> 'Disability')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Disability' WHERE CODE_ID = 1904 AND CODE_VALUE = 'DISA'
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'RETR' AND DATA2 <> 'Retirement')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Retirement' WHERE CODE_ID = 1904 AND CODE_VALUE = 'RETR'
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'RFND' AND DATA2 <> 'Refunds')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Refunds' WHERE CODE_ID = 1904 AND CODE_VALUE = 'RFND'
END


