
/********************Purpose: PIR 23927 ******************************
*********************Created By: Saylee Pujari********************************
*********************Comments:  *****************/


IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10412)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10412,'Invalid or missing Gender.',16,'E',NULL,NULL,'PIR 23927',GETDATE(),'PIR 23927',GETDATE(),0)
GO

IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10413)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10413,'Invalid or missing Marital Status.',16,'E',NULL,NULL,'PIR 23927',GETDATE(),'PIR 23927',GETDATE(),0)
GO

/********************Purpose: PIR 23734 ******************************
*********************Created By: Vidya Fulsoundar********************************
*********************Comments:  *****************/
IF NOT EXISTS (SELECT 1 FROM [SGS_BATCH_SCHEDULE] WHERE BATCH_SCHEDULE_ID = 155)
INSERT INTO [SGS_BATCH_SCHEDULE] (BATCH_SCHEDULE_ID,	STEP_NO,	STEP_NAME,	STEP_DESCRIPTION,	FREQUENCY_IN_DAYS,	FREQUENCY_IN_MONTHS,	NEXT_RUN_DATE,	STEP_PARAMETERS,	ACTIVE_FLAG,	REQUIRES_TRANSACTION_FLAG,	EMAIL_NOTIFICATION,	ORDER_NO,	CUTOFF_START,	CUTOFF_END,	CREATED_BY,	CREATED_DATE,	MODIFIED_BY,	MODIFIED_DATE,	UPDATE_SEQ)
VALUES(155,	1013,'Employment Status Change-COBRA Notice',	NULL,	1,	NULL,	GETDATE(),	NULL,	'Y','N',	NULL,	NULL,	NULL,	NULL,	'PIR 23734',GETDATE(),	'PIR 23734',	GETDATE(),	0)
GO

/********************Purpose: PIR 13155	Add Notes field to Contact Maintenance screen******************************
*********************Created By: Abhijeet Malwadkar********************************
*********************Comments:  *****************/
IF NOT EXISTS (SELECT 1 FROM [dbo].[SGS_CODE] WHERE CODE_ID = 7021)
	INSERT dbo.SGS_CODE ([CODE_ID],[DESCRIPTION],[DATA1_CAPTION],[DATA1_TYPE],[DATA2_CAPTION],[DATA2_TYPE],[DATA3_CAPTION],[DATA3_TYPE],[FIRST_LOOKUP_ITEM],[FIRST_MAINTENANCE_ITEM],[COMMENTS],[LEGACY_CODE_ID],[CREATED_BY],[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
	VALUES
	(7021,'Screens for adding notes','',NULL,'',NULL,'',NULL,NULL,NULL,NULL,NULL,'PIR 13155',GETDATE(),'PIR 13155',GETDATE(),0)
	GO
GO

IF NOT EXISTS (SELECT 1 FROM [SGS_CODE_VALUE] WHERE CODE_ID = 7021 AND CODE_VALUE='CONM')
	INSERT INTO [SGS_CODE_VALUE]([CODE_ID],[CODE_VALUE],[DESCRIPTION],[DATA1],[DATA2],[DATA3]
           ,[COMMENTS],[START_DATE],[END_DATE],[CODE_VALUE_ORDER],[LEGACY_CODE_ID],[CREATED_BY]
           ,[CREATED_DATE],[MODIFIED_BY],[MODIFIED_DATE],[UPDATE_SEQ])
     VALUES(7021,'CONM','Contact Maintenance Screen',null,null,null,null,null,null,1
           ,NULL,'PIR 13155',GETDATE(),'PIR 13155',GETDATE(),0)
GO

/********************Purpose: PIR 11171 ******************************
*********************Created By: Vidya Fulsoundar ********************************
*********************Comments:  *****************/

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE STATUS_TRANSITION_VALUE IS NULL AND SOURCE_TYPE_VALUE = 'PURC' 
AND TRANSACTION_TYPE_VALUE = 'TRAN' AND ITEM_TYPE_VALUE = 'PCEE' AND PLAN_ID = 4)
BEGIN
INSERT INTO SGT_ACCOUNT_REFERENCE ([PLAN_ID], [FUND_ID], [FUND_VALUE], [DEPT_ID], [DEPT_VALUE], [ITEM_TYPE_ID], [ITEM_TYPE_VALUE], [FROM_ITEM_TYPE_ID], [FROM_ITEM_TYPE_VALUE], 
[TO_ITEM_TYPE_ID], [TO_ITEM_TYPE_VALUE], [TRANSACTION_TYPE_ID], [TRANSACTION_TYPE_VALUE], [STATUS_TRANSITION_ID], [STATUS_TRANSITION_VALUE], [SOURCE_TYPE_ID], [SOURCE_TYPE_VALUE], [GENERATE_GL_FLAG], [DEBIT_ACCOUNT_ID], [CREDIT_ACCOUNT_ID], [JOURNAL_DESCRIPTION], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(4,	1300,	482,	1301,	1600,	1302,	'PCEE',	NULL,	NULL,	NULL,	NULL,	1303,	'TRAN',	1309,	NULL,	1304,	'PURC',	1,	39,	25, 'Purchase RHIC allocation to Employee RHIC Share',	'PIR 11171',	GETDATE(),	'PIR 11171',	GETDATE(),	0)
END
GO

IF NOT EXISTS (SELECT 1 FROM SGT_ACCOUNT_REFERENCE WHERE STATUS_TRANSITION_VALUE IS NULL AND SOURCE_TYPE_VALUE = 'REMI' 
AND TRANSACTION_TYPE_VALUE = 'TRAN' AND ITEM_TYPE_VALUE = 'PURC' AND PLAN_ID = 4)
BEGIN
INSERT INTO SGT_ACCOUNT_REFERENCE ([PLAN_ID], [FUND_ID], [FUND_VALUE], [DEPT_ID], [DEPT_VALUE], [ITEM_TYPE_ID], [ITEM_TYPE_VALUE], [FROM_ITEM_TYPE_ID], [FROM_ITEM_TYPE_VALUE], 
[TO_ITEM_TYPE_ID], [TO_ITEM_TYPE_VALUE], [TRANSACTION_TYPE_ID], [TRANSACTION_TYPE_VALUE], [STATUS_TRANSITION_ID], [STATUS_TRANSITION_VALUE], [SOURCE_TYPE_ID], [SOURCE_TYPE_VALUE], [GENERATE_GL_FLAG], [DEBIT_ACCOUNT_ID], [CREDIT_ACCOUNT_ID], [JOURNAL_DESCRIPTION], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(4,	1300,	483,	1301,	1001,	1302,	'PURC',	NULL,	NULL,	NULL,	NULL,	1303,	'TRAN',	1309,	NULL,	1304,	'REMI',	1,	43,	39, 'Purchase RHIC allocation to Employee RHIC Share',	'PIR 11171',	GETDATE(),	'PIR 11171',	GETDATE(),	0)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1302 AND CODE_VALUE = 'PCEE')
BEGIN
INSERT INTO SGS_CODE_VALUE ([CODE_ID], [CODE_VALUE], [DESCRIPTION], [DATA1], [DATA2], [DATA3], [COMMENTS], [START_DATE], [END_DATE], [CODE_VALUE_ORDER], [LEGACY_CODE_ID], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [UPDATE_SEQ])
VALUES(1302,	'PCEE',	'PURCHASE RHIC EE',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 11171',	GETDATE(),	'PIR 11171',	GETDATE(),	0)
END
GO


IF EXISTS (select * from SGS_SYSTEM_MANAGEMENT where REGION_VALUE != 'PROD')
BEGIN
	UPDATE SGS_SYSTEM_SETTINGS SET SETTING_VALUE = 'https://stg-production.shippingapis.com' WHERE SETTING_NAME = 'USPS_WebService_PATH'
END
ELSE IF EXISTS (select 1 from SGS_SYSTEM_MANAGEMENT where REGION_VALUE = 'PROD')
BEGIN 
	UPDATE SGS_SYSTEM_SETTINGS SET SETTING_VALUE = 'https://production.shippingapis.com' WHERE SETTING_NAME = 'USPS_WebService_PATH'
END
GO

