
/********************Purpose: PIR 18493 App Wizard Round 2 Testing ******************************
*********************Created By: Abhijeet M ********************************
*********************Comments: Use DATA2 for Ben Type Text *****************/
IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'DISA' AND ISNULL(DATA2,'') <> 'Disability')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Disability' WHERE CODE_ID = 1904 AND CODE_VALUE = 'DISA'
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'RETR' AND ISNULL(DATA2,'') <> 'Retirement')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Retirement' WHERE CODE_ID = 1904 AND CODE_VALUE = 'RETR'
END

IF EXISTS(SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID = 1904 AND CODE_VALUE = 'RFND' AND ISNULL(DATA2,'') <> 'Refunds')
BEGIN
	UPDATE SGS_CODE_VALUE SET DATA2 = 'Refunds' WHERE CODE_ID = 1904 AND CODE_VALUE = 'RFND'
END

/*Data_Changes_PIR 23178*/
/****Purpose: PIR 23178 A new batch step to run the entPersonAccountFlexComp.fleFlexCompFileToSanford query.  Output as ‘FlexComp_YYYY_MM_DD.csv’.  Batch name ‘Flex File to Sanford’. ****
*********************Created By: Abhijeet********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT 1 FROM [SGS_BATCH_SCHEDULE] WHERE BATCH_SCHEDULE_ID = 153)
INSERT INTO [SGS_BATCH_SCHEDULE] (BATCH_SCHEDULE_ID,	STEP_NO,	STEP_NAME,	STEP_DESCRIPTION,	FREQUENCY_IN_DAYS,	FREQUENCY_IN_MONTHS,	NEXT_RUN_DATE,	STEP_PARAMETERS,	ACTIVE_FLAG,	REQUIRES_TRANSACTION_FLAG,	EMAIL_NOTIFICATION,	ORDER_NO,	CUTOFF_START,	CUTOFF_END,	CREATED_BY,	CREATED_DATE,	MODIFIED_BY,	MODIFIED_DATE,	UPDATE_SEQ)
VALUES(153,	1011,'Flex File to Sanford','Create out put Flex Comp File that send to Sanford',	NULL,	1,	GETDATE(),	NULL,	'Y','N',	NULL,	NULL,	NULL,	NULL,	'PIR 23178 ',GETDATE(),	'PIR 23178 ',	GETDATE(),	0)
GO


IF NOT EXISTS (SELECT 1 FROM SGS_FILE WHERE [FILE_ID] = 104)
BEGIN
	SET IDENTITY_INSERT[SGS_FILE] ON;
	INSERT INTO SGS_FILE ([FILE_ID], [DESCRIPTION], DELIMITED_BY, TRANSACTION_CODE_POS, TRANSACTION_CODE_LENGTH, TRANSACTION_CODE_VALUE, HEADER_GROUP_POS, HEADER_GROUP_LENGTH, XML_LAYOUT_FILE, INBOUND_MASK, MAILBOX_PATH_CODE, STAGING_PATH_CODE, ERROR_PATH_CODE, PROCESS_PATH_CODE, FILE_STATUS_ID, FILE_STATUS_VALUE, INBOUND_OUTBOUND_FLAG, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ, EMAIL_NOTIFICATION, OTHER_PARAMETERS, GROUP_PROCESS_FLAG)
	VALUES(104, 'Flex Comp To Sanford File Out', ',', NULL, NULL, 'Header Detail', 0, 0, 'fleFlexCompToSanfordFileOut',	'*.*', 'PAOut', 'PAStaging', 'PAError', 'PAOutProc', 26, 'A', 'O', 'PIR 23178 ', GETDATE(), 'PIR 23178', GETDATE(), 1, NULL, NULL, 'N')
	SET IDENTITY_INSERT[SGS_FILE] OFF;
END
GO

/*Data_Change_PIR_23480 */
/********************Purpose: Validation message for bonus/Retro pay check for Pay period end date with date of termination PIR 23480******************************
*********************Created By: Abhijeet********************************
*********************Comments: *****************/
IF NOT EXISTS (SELECT 1 FROM SGS_MESSAGES WHERE MESSAGE_ID=10409)
	INSERT INTO SGS_MESSAGES (MESSAGE_ID,DISPLAY_MESSAGE,SEVERITY_ID,SEVERITY_VALUE,INTERNAL_INSTRUCTIONS,EMPLOYER_INSTRUCTIONS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(10409,'End Date may not exceed Termination Date.',16,'E',NULL,'End Date may not exceed Termination Date.','PIR 23480',GETDATE(),'PIR 23480',GETDATE(),0)
GO

/*Data_Change_PIR_23651 */
/********************Purpose: PIR 23651 Implement a new bookmark to read SFN logo and address images******************************
*********************Created By: Abhijeet********************************
*********************Comments: *****************/
DECLARE @PHYSICAL_PATH VARCHAR(100) = ''
SELECT @PHYSICAL_PATH = BASE_DIRECTORY FROM SGS_SYSTEM_MANAGEMENT 

IF NOT EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=52 AND CODE_VALUE='SFNL')
BEGIN
	INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(52,'SFNL','Corrospondence SFN Logo Image URL',	@PHYSICAL_PATH + 'Correspondence\Templates\SFNLogo.jpg',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 23651',	GETDATE(),	'PIR 23651',	GETDATE(),	0)
END

/*Data_Changes_PIR_23651*/
IF NOT EXISTS (SELECT 1 FROM SGS_CODE_VALUE WHERE CODE_ID=52 AND CODE_VALUE='SFNA')
BEGIN
	INSERT INTO SGS_CODE_VALUE (CODE_ID,CODE_VALUE,DESCRIPTION,DATA1,DATA2,DATA3,COMMENTS,START_DATE,END_DATE,CODE_VALUE_ORDER,LEGACY_CODE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
    VALUES(52,'SFNA','Corrospondence SFN Address Image URL',	@PHYSICAL_PATH + 'Correspondence\Templates\SFNAddress.jpg',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'PIR 23651',	GETDATE(),	'PIR 23651',	GETDATE(),	0)
END
GO