CREATE TABLE [dbo].[SGW_BPM_CASE] (
    [CASE_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [CASE_FILE]     VARCHAR (MAX) NULL,
    [DESCRIPTION]   VARCHAR (MAX) NULL,
    [NAME]          VARCHAR (MAX) NULL,
    [CREATED_BY]    VARCHAR (50)  NOT NULL,
    [CREATED_DATE]  DATETIME      NOT NULL,
    [MODIFIED_BY]   VARCHAR (50)  NOT NULL,
    [MODIFIED_DATE] DATETIME      NOT NULL,
    [UPDATE_SEQ]    INT           NULL,
    [VERSION]       INT           NULL,
    [BPMMAP]        VARCHAR (MAX) NULL,
	[BBPMMAP]		IMAGE		  NULL,
    [STATUS_ID]     INT           NOT NULL,
    [STATUS_VALUE]  VARCHAR (4)   NULL,
	[EFFECTIVE_DATE] DATE		  NOT NULL DEFAULT GETDATE(),
	[RESOURCE_ID]    INT          NULL,
    CONSTRAINT [PK_SGW_BPM_CASE_CASE_ID] PRIMARY KEY CLUSTERED ([CASE_ID] ASC)
);

