CREATE TABLE [dbo].[SGW_BPM_CASE_DETAILS] (
    [CASE_DETAILS_ID] INT             IDENTITY (1, 1) NOT NULL,
    [CASE_ID]         INT             NOT NULL,
    [CASE_DETAILS]    VARBINARY (MAX) NOT NULL,
    CONSTRAINT [PK_SGW_BPM_CASE_DETAILS] PRIMARY KEY CLUSTERED ([CASE_DETAILS_ID] ASC)
);

