IF EXISTS (SELECT TOP 1 (1)  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SGS_ACT_LOG_APP' AND COLUMN_NAME = 'USERS_WAIT_TIME')
BEGIN
	PRINT 'DROPPING COLUMN';
	ALTER TABLE SGS_ACT_LOG_APP DROP COLUMN USERS_WAIT_TIME;
	PRINT 'COLUMN DROPPED SUCCESSFULLY !';
END
GO