GO

/****** Object:  StoredProcedure [dbo].[GetActivityRuleFromSessionStore]    Script Date: 3/17/2021 5:25:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[GetActivityRuleFromSessionStore]
	@SESSION_STORE_SERIAL_ID INT
AS
BEGIN
 SELECT ACTIVITY_INSTANCE_ID, RULE_RESULT, 
     CASE WHEN BUS_OBJECT IS NULL THEN 'FALSE' ELSE 'TRUE' END as BUS_OBJECT,
	 UPDATE_SEQ FROM dbo.SGS_SESSION_STORE  WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID 
END
GO


