

ALTER TABLE [dbo].[SGW_BPM_PROCESS_INSTANCE]
ADD [PROCESS_OWNER_ROLE] [int] NULL;

ALTER TABLE [dbo].[SGW_BPM_ESCALATION]
ADD [NOTIFY_PROCESS_OWNER] [varchar](1) NULL;

ALTER TABLE [dbo].[SGW_BPM_PROCESS_ESCALATION]
ADD [NOTIFY_PROCESS_OWNER] [varchar](1) NULL;
Go
SET IDENTITY_INSERT SGW_BPM_CASE ON;
INSERT INTO SGW_BPM_CASE(CASE_ID,CASE_FILE,NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ,
STATUS_ID,STATUS_VALUE,VERSION,EFFECTIVE_DATE)
VALUES(0,'GlobalCase','GlobalCase','GlobalCase','System',getdate(),'System',GETDATE(),0,'2002','ACTV',1,getdate())
SET IDENTITY_INSERT SGW_BPM_CASE OFF;

SET IDENTITY_INSERT SGW_BPM_PROCESS ON;
INSERT INTO SGW_BPM_PROCESS(PROCESS_ID,BPM_PROCESS_ID,CASE_ID,NAME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ
,PRIORITY,TYPE_ID,TYPE_VALUE,STATUS_ID,STATUS_VALUE)
VALUES(0,'',0,'GlobalProcess','System',getdate(),'System',GETDATE(),0,'','','','','');
SET IDENTITY_INSERT SGW_BPM_PROCESS OFF;

SET IDENTITY_INSERT SGW_BPM_ACTIVITY ON;
INSERT INTO SGW_BPM_ACTIVITY(ACTIVITY_ID,PROCESS_ID,NAME,BPM_ACTIVITY_ID,ACTIVITY_TYPE_ID,ACTIVITY_TYPE_VALUE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ)
VALUES
(0,0,'GlobalActivity','',2031,'USTK','System',getdate(),'System',GETDATE(),0);
SET IDENTITY_INSERT SGW_BPM_ACTIVITY OFF;


GO
/****** Object:  Table [dbo].[SGW_BPM_EXCEPTION_DETAILS]    Script Date: 5/12/2021 6:14:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_INSTANCE_ID] [int] NOT NULL,
	[EXCEPTION_INSTANCE_ID] [uniqueidentifier] NOT NULL,
	[EXCEPTION_TYPE] [nvarchar](100) NOT NULL,
	[EXCEPTION_MESSAGE] [nvarchar](1000) NOT NULL,
	[ROLES] [nvarchar](max) NULL,
	[RETRY_COUNT] [int] NOT NULL,
	[RETRY_FREQUENCY] [int] NOT NULL,
	[NEXT_RETRY] [datetime] NULL,
	[STATUS_ID] [int] NOT NULL,
	[STATUS_VALUE] [varchar](4) NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
	[MACHINE_NAME] [varchar](100) NULL,
 CONSTRAINT [PK_SGW_BPM_EXCEPTION_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS] ADD  DEFAULT ('BPM Service') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS] ADD  DEFAULT ('BPM Service') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[SGW_BPM_EXCEPTION_DETAILS] ADD  DEFAULT ((0)) FOR [UPDATE_SEQ]
GO


