CREATE TABLE [dbo].[SGS_SERVER_CONFIGURATION]
(
	[SERVER_CONFIGURATION_ID]	int					  IDENTITY(1,1) NOT NULL,
	[SERVER_ID]					int					  NOT NULL,	
	[ENGINE_ID]					int					  NOT NULL,
	[ENGINE_VALUE]				varchar(4)			  NOT NULL,
	[CREATED_BY]				varchar(50)			  NOT NULL,
	[CREATED_DATE]				datetime			  NOT NULL,
	[MODIFIED_BY]				varchar(50)			  NOT NULL,
	[MODIFIED_DATE]				datetime			  NOT NULL,
	[UPDATE_SEQ]				int					  NOT NULL,
	CONSTRAINT [PK_SGS_SERVER_CONFIGURATION] PRIMARY KEY CLUSTERED ([SERVER_CONFIGURATION_ID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
