

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2021 AND CODE_VALUE = 'BTCH')
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2021,'BTCH','Batch',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
END


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2021 AND CODE_VALUE = 'INDX')
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2021,'INDX','Scanning & Indexing',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
END
 


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2021 AND CODE_VALUE = 'MSGF')
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2021,'MSGF','Message Flow',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',getdate(),'system',getdate(),0);
END
 

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2021 AND CODE_VALUE = 'ONLI')
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2021,'ONLI','Online',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
END
 