IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'APPLICATION_DATE'  AND OBJECT_ID = OBJECT_ID(N'SGS_SYSTEM_MANAGEMENT'))
BEGIN
ALTER TABLE SGS_SYSTEM_MANAGEMENT ADD APPLICATION_DATE UDT_DATETIME NULL
END

ELSE
BEGIN
  PRINT 'COLUMN NAME: APPLICATION_DATE ALREADY EXISTS IN THE TABLE SGS_SYSTEM_MANAGEMENT'
END
GO