IF NOT EXISTS(SELECT 1 FROM SGS_CODE WITH(NOLOCK) WHERE CODE_ID = 3013) 
BEGIN
	 INSERT INTO DBO.SGS_CODE (CODE_ID, DESCRIPTION, DATA1_CAPTION, DATA1_TYPE, DATA2_CAPTION, DATA2_TYPE, DATA3_CAPTION, DATA3_TYPE, FIRST_LOOKUP_ITEM, FIRST_MAINTENANCE_ITEM, COMMENTS, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (3013, 'Reason Id', NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3013 AND CODE_VALUE = 'UNDL') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (3013,'UNDL','Undelivered',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',getdate(),'system',getdate(),0);
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3013 AND CODE_VALUE = 'TRNA') 
BEGIN
	INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (3013,'TRNA','Turn Around',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',getdate(),'system',getdate(),0);
END
GO