CREATE TABLE [SGW_BPM_CASE_EXCPT_NTFC_ROLE](
    [CASE_EXCPT_NTFC_ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CASE_EXCPT_NOTIFICATION_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL
 CONSTRAINT [PK_SGW_BPM_CASE_EXCPT_NTFC_ROLE_CASE_EXCPT_NTFC_ROLE_ID] PRIMARY KEY CLUSTERED 
(
	[CASE_EXCPT_NTFC_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];