IF COL_LENGTH('dbo.SGW_BPM_PRCS_INST_ATTACHMENTS', 'ADDITIONAL_INFO') IS NULL
BEGIN
ALTER TABLE SGW_BPM_PRCS_INST_ATTACHMENTS
ADD ADDITIONAL_INFO VARCHAR(8000) NULL
END
GO

IF COL_LENGTH('dbo.SGW_BPM_REQUEST', 'ADDITIONAL_INFO') IS NULL
BEGIN
ALTER TABLE SGW_BPM_REQUEST
ADD ADDITIONAL_INFO VARCHAR(8000) NULL
END
GO

IF COL_LENGTH('dbo.SGW_BPM_ACTY_INST_CHECKLIST', 'RECEIVED_DATE') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ACTY_INST_CHECKLIST
ADD RECEIVED_DATE DATETIME NULL
END
GO