CREATE TABLE [dbo].[SGW_BPM_CASE_MESSAGE_FLOW] (
    [BPM_CASE_MESSAGE_FLOW_ID] INT          IDENTITY (1, 1) NOT NULL,
    [CASE_ID]                  INT          NOT NULL,
    [BPM_MESSAGE_FLOW_ID]      VARCHAR (50) NOT NULL,
    [NAME]                     VARCHAR (50) NOT NULL,
    [SOURCE_BPM_ACTIVITY_ID]   VARCHAR (50) NOT NULL,
    [TARGET_BPM_ACTIVITY_ID]   VARCHAR (50) NOT NULL,
    [INITIATING_FLAG]          VARCHAR (1)  NULL,
    [SOURCE_BPM_PROCESS_ID]    VARCHAR (50) NULL,
    [TARGET_BPM_PROCESS_ID]    VARCHAR (50) NULL,
    [CREATED_BY]               VARCHAR (50) NOT NULL,
    [CREATED_DATE]             DATETIME     NOT NULL,
    [MODIFIED_BY]              VARCHAR (50) NOT NULL,
    [MODIFIED_DATE]            DATETIME     NOT NULL,
    [UPDATE_SEQ]               INT          NOT NULL,
    CONSTRAINT [PK_SGW_BPM_CASE_MESSAGE_BPM_CASE_MESSAGE_FLOW_ID] PRIMARY KEY CLUSTERED ([BPM_CASE_MESSAGE_FLOW_ID] ASC)
);

