CREATE TABLE [dbo].[SGW_BPM_ESC_ADDTL_RECIPIENT] (
    [ESC_ADDTL_RECIPIENT_ID] INT IDENTITY (1, 1) NOT NULL,
    [ESCALATION_ID]                      INT NOT NULL,
    [USER_SERIAL_ID]                     INT NOT NULL,
    CONSTRAINT [PK_SGW_BPM_ESC_ADDTL_RECIPIENT_ESC_ADDTL_RECIPIENT_ID] PRIMARY KEY CLUSTERED ([ESC_ADDTL_RECIPIENT_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_ESC_ADDTL_RECIPIENT_ESCALATION_ID_SGW_BPM_ESCALATION_ESCALATION_ID] FOREIGN KEY ([ESCALATION_ID]) REFERENCES [dbo].[SGW_BPM_ESCALATION] ([ESCALATION_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_SGW_BPM_ESC_ADDTL_RECIPIENT_USER_SERIAL_ID_SGS_USER_USER_SERIAL_ID] FOREIGN KEY ([USER_SERIAL_ID]) REFERENCES [dbo].[SGS_USER] ([USER_SERIAL_ID]) ON DELETE CASCADE
);

