CREATE TABLE [dbo].[SGW_BPM_ESC_RECIPIENT_ROLE](
	[ESCALATION_RECIPIENT_ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ESCALATION_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SGW_BPM_ESC_RECIPIENT_ROLE] PRIMARY KEY CLUSTERED 
(
	[ESCALATION_RECIPIENT_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

