CREATE TABLE [dbo].[SGW_BPM_ACTY_INST_CHECKLIST](
	[ACTIVITY_INST_CHECKLIST_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_INSTANCE_ID] [dbo].[UDT_ID] NOT NULL,
	[ACTIVITY_CHECKLIST_ID] [dbo].[UDT_ID] NOT NULL,
	[REQUIRED_FLAG] [dbo].[UDT_FLAG] NOT NULL,
	[COMPLETED_IND] [dbo].[UDT_IND] NULL,
	[COMPLETED_DATE] [dbo].[UDT_DATE] NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NULL,
 CONSTRAINT [PK_SGW_BPM_ACTIVITY_INSTANCE_CHECKLIST_ACTIVITY_INSTANCE_CHECKLIST_ID] PRIMARY KEY CLUSTERED 
(
	[ACTIVITY_INST_CHECKLIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SGW_BPM_ACTY_INST_CHECKLIST]  WITH CHECK ADD  CONSTRAINT [FK_SGW_BPM_ACTY_INST_CHECKLIST_ACTY_INST_CHECKLIST_ID_SGW_ACTIVITY_CHECKLIST_ACTIVITY_CHECKLIST_ID] FOREIGN KEY([ACTIVITY_CHECKLIST_ID])
REFERENCES [dbo].[SGW_BPM_ACTIVITY_CHECKLIST] ([ACTIVITY_CHECKLIST_ID])
GO
ALTER TABLE [dbo].[SGW_BPM_ACTY_INST_CHECKLIST]  WITH CHECK ADD  CONSTRAINT [FK_ACTY_INST_CHECKLIST_ACTIVITY_INSTANCE_ID_SGW_BPM_ACTIVITY_INSTANCE_ACTIVITY_INSTANCE_ID] FOREIGN KEY([ACTIVITY_INSTANCE_ID])
REFERENCES [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID])
GO

ALTER TABLE [dbo].[SGW_BPM_ACTY_INST_CHECKLIST] CHECK CONSTRAINT [FK_ACTY_INST_CHECKLIST_ACTIVITY_INSTANCE_ID_SGW_BPM_ACTIVITY_INSTANCE_ACTIVITY_INSTANCE_ID]