CREATE TABLE [dbo].[SGW_BPM_PRCS_ESC_RECPNT_ROLE] (
    [PRCS_ESC_RECPNT_ROLE_ID] INT IDENTITY (1, 1) NOT NULL,
    [PROCESS_ESCALATION_ID]                INT NOT NULL,
    [ROLE_ID]                              INT NOT NULL,
    CONSTRAINT [PK_SGW_BPM_PRCS_ESC_RECPNT_ROLE] PRIMARY KEY CLUSTERED ([PRCS_ESC_RECPNT_ROLE_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_PRCS_ESC_RECPNT_ROLE_PROCESS_ESCALATION_ID_SGW_BPM_PROCESS_ESCALATION_PROCESS_ESCALATION_ID] FOREIGN KEY ([PROCESS_ESCALATION_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS_ESCALATION] ([PROCESS_ESCALATION_ID])
);

