CREATE TABLE [SGW_BPM_PRCS_INST_RSRT_NOTY_XR](
    [PRCS_INST_RESTRICT_NOTIFY_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARENT_PROCESS_INSTANCE_ID] [int] NOT NULL,
	[DEPENDENT_PROCESS_INSTANCE_ID] [int] NULL,
	[RESTRICT_NOTIFY_CODE_ID] [int] NOT NULL,
	[RESTRICT_NOTIFY_CODE_VALUE] [varchar](4) NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NULL   
 CONSTRAINT [SGW_BPM_PRCS_INST_RSRT_NOTY_XR_S_INST_RESTRICT_NOTIFY_ID] PRIMARY KEY CLUSTERED 
(
	[PRCS_INST_RESTRICT_NOTIFY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];