CREATE TABLE [dbo].[SGW_BPM_CASE_INST_PARAMETER] (
    [CASE_INSTANCE_PARAMETER_ID] INT            IDENTITY (1, 1) NOT NULL,
    [CASE_INSTANCE_ID]           INT            NOT NULL,
    [PARAMETER_NAME]             VARCHAR (50)   NOT NULL,
    [PARAMETER_VALUE]            VARCHAR (1000) NULL,
    [OBJECT_VALUE]               VARBINARY(MAX)          NULL,
    [CREATED_BY]                 VARCHAR (50)   NOT NULL,
    [CREATED_DATE]               DATETIME       NOT NULL,
    [MODIFIED_BY]                VARCHAR (50)   NOT NULL,
    [MODIFIED_DATE]              DATETIME       NOT NULL,
    [UPDATE_SEQ]                 INT            NULL,
    CONSTRAINT [PK_SGW_BPM_CASE_INST_PARAMETER_CASE_INSTANCE_PARAMETER_ID] PRIMARY KEY CLUSTERED ([CASE_INSTANCE_PARAMETER_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_CASE_INST_PARAMETER_SGW_BPM_CASE_INSTANCE_CASE_INSTANCE_ID] FOREIGN KEY ([CASE_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_CASE_INSTANCE] ([CASE_INSTANCE_ID])
);

