CREATE TABLE [dbo].[SGW_BPM_TMER_ACTY_INST_DETAILS] (
    [TIMER_ID]             INT            IDENTITY (1, 1) NOT NULL,
    [ACTIVITY_INSTANCE_ID] INT            NOT NULL,
    [START_DATE_TIME]      DATETIME       NOT NULL,
    [END_DATE_TIME]        DATETIME       NOT NULL,
    [MACHINE_NAME]         NVARCHAR (MAX) NULL,
    [PROCESSING_FLAG]      VARCHAR (1)    DEFAULT ('N') NULL,
    CONSTRAINT [PK_SGW_BPM_TMER_ACTY_INST_DETAILS] PRIMARY KEY CLUSTERED ([TIMER_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_TMER_ACTY_INST_DETAILS_ACTIVITY_INSTANCE_ID_SGW_BPM_ACTIVITY_INSTANCE_ACTIVITY_INSTANCE_ID] FOREIGN KEY ([ACTIVITY_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID])
);





