
CREATE TABLE SGW_BPM_TRACE_INSTANCE(
	[TRACE_INSTANCE_ID] [INT] IDENTITY(1,1) NOT NULL,	
	[ENGINE_NAME] [VARCHAR](100) NULL,
	[START_TIME] [DATETIME] NOT NULL,
	[END_TIME] [DATETIME] NULL,
	[MACHINE_NAME] [VARCHAR](50) NULL,
	[USER_ID] [VARCHAR] (100) NULL,
	[PARAMETER_DETAILS][VARCHAR](8000) NULL,
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT] NULL,
 CONSTRAINT [PK_SGW_BPM_TRACE_INSTANCE] PRIMARY KEY CLUSTERED 
(
	[TRACE_INSTANCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
