CREATE TABLE [dbo].[SGW_BPM_TRACE_THRESHOLD_QUERY](
	[TRACE_THRESHOLD_QUERY_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_INSTANCE_ID] [int] NOT NULL,	
	[QUERY_ID] [varchar](100)  NULL,
	[QUERY_TEXT] [varchar](8000) NULL,
	[QUERY_RESULT] [varchar](100) NULL,	
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NULL,
	[PARAMETER_DETAILS] [varchar](8000) NULL,
	[TRANSACTION_ID] [uniqueidentifier] null,
	[SUB_TRANSACTION_ID] int,
	[TOTAL_TIME_IN_MS] [int] NOT NULL,		
 CONSTRAINT [PK_SGW_BPM_TRACE_THRESHOLD_QUERY] PRIMARY KEY CLUSTERED 
(
	[TRACE_THRESHOLD_QUERY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]  
