CREATE TABLE [dbo].[SGW_USER_TIMEOFF](
	[USER_TIMEOFF_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[USER_SERIAL_ID] [dbo].[UDT_IDENTITY] NOT NULL,
	[START_DATE] [dbo].[UDT_DATE] NOT NULL,
	[END_DATE] [dbo].[UDT_DATE] NOT NULL,
	[STATUS_ID] [dbo].[UDT_CODE_ID] NOT NULL,
	[STATUS_VALUE] [dbo].[UDT_CODE_VALUE] NOT NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NOT NULL,
 CONSTRAINT [PK_SGW_USER_TIMEOFF] PRIMARY KEY CLUSTERED 
(
	[USER_TIMEOFF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGW_USER_TIMEOFF]  WITH NOCHECK ADD  CONSTRAINT [FK_SGW_USER_TIMEOFF_SGS_USER] FOREIGN KEY([USER_SERIAL_ID])
REFERENCES [dbo].[SGS_USER] ([USER_SERIAL_ID])
GO

ALTER TABLE [dbo].[SGW_USER_TIMEOFF] CHECK CONSTRAINT [FK_SGW_USER_TIMEOFF_SGS_USER]
GO