IF NOT EXISTS (SELECT 1 FROM [dbo].SGS_SYSTEM_SETTINGS WHERE SETTING_NAME = 'AvoidDuplicateEntriesInHistory')
BEGIN
INSERT [dbo].[SGS_SYSTEM_SETTINGS] ([SETTING_NAME], [SETTING_TYPE], [SETTING_VALUE], [ENCRYPTED_FLAG],[REFRESHABLE]) 
VALUES (N'AvoidDuplicateEntriesInHistory', N'bool', N'true ', NULL,NULL);
 END
GO