------------------------------------------------------------------------------------------------------------------------ 
--Created By	:	Siddharth Sabara
--Created On	:	30th June 2020
--Description	:	Adding audit columns in  SGW_BPM_ESCALATION_INSTANCE
------------------------------------------------------------------------------------------------------------------------ 

IF COL_LENGTH('dbo.SGW_BPM_ESCALATION_INSTANCE', 'CREATED_BY') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ESCALATION_INSTANCE
ADD CREATED_BY varchar(50) NOT NULL DEFAULT 'BPM Service'
END
GO

IF COL_LENGTH('dbo.SGW_BPM_ESCALATION_INSTANCE', 'CREATED_DATE') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ESCALATION_INSTANCE
ADD CREATED_DATE datetime NOT NULL DEFAULT getdate()
END
GO

IF COL_LENGTH('dbo.SGW_BPM_ESCALATION_INSTANCE', 'MODIFIED_BY') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ESCALATION_INSTANCE
ADD MODIFIED_BY varchar(50) NOT NULL DEFAULT 'BPM Service'
END
GO

IF COL_LENGTH('dbo.SGW_BPM_ESCALATION_INSTANCE', 'MODIFIED_DATE') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ESCALATION_INSTANCE
ADD MODIFIED_DATE datetime NOT NULL DEFAULT getdate()
END
GO

IF COL_LENGTH('dbo.SGW_BPM_ESCALATION_INSTANCE', 'UPDATE_SEQ') IS NULL
BEGIN
ALTER TABLE SGW_BPM_ESCALATION_INSTANCE
ADD UPDATE_SEQ int NOT NULL DEFAULT 0
END
GO