-----------------------------------------
--Created By	:	Siddharth Sabadra
--Created On	:	10nd July 2020
--Description	:	Adding table SGW_BPM_DOCUMENT_UPLOAD 
------------------------------------------------------------------------------------------------------------------------

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME = 'SGW_BPM_DOCUMENT_UPLOAD'))
BEGIN
CREATE TABLE [dbo].[SGW_BPM_DOCUMENT_UPLOAD](
	[BPM_DOCUMENT_UPLOAD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BPM_PROCESS_INSTANCE_ID] [int] NOT NULL,
	[BPM_DOCUMENT_NAME] [varchar](100) NOT NULL,
	[CREATED_BY] [UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [UDT_MODIFIEDBY] NOT NULL,
	[MODIFIED_DATE] [UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [UDT_UPDSEQ] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BPM_DOCUMENT_UPLOAD_ID] ASC
))

ALTER TABLE [SGW_BPM_DOCUMENT_UPLOAD]  WITH NOCHECK ADD  CONSTRAINT [FK_SGW_BPM_DOCUMENT_UPLOAD_SGW_BPM_PROCESS_INSTANCE] FOREIGN KEY([BPM_PROCESS_INSTANCE_ID])
REFERENCES [SGW_BPM_PROCESS_INSTANCE] ([PROCESS_INSTANCE_ID])

ALTER TABLE [dbo].[SGW_BPM_DOCUMENT_UPLOAD] CHECK CONSTRAINT [FK_SGW_BPM_DOCUMENT_UPLOAD_SGW_BPM_PROCESS_INSTANCE]

END
GO

