-- DROP PROCEDURES--
IF OBJECT_ID('dbo.CheckObjectInSQL', 'P') IS NOT NULL 
	DROP PROCEDURE [dbo].[CheckObjectInSQL];
GO

IF OBJECT_ID('dbo.GetActivityRuleFromSessionStore', 'P') IS NOT NULL 
	DROP PROCEDURE [dbo].[GetActivityRuleFromSessionStore];
GO

IF OBJECT_ID('dbo.GetBusObjectFromSessionStore', 'P') IS NOT NULL 
	DROP PROCEDURE [dbo].[GetBusObjectFromSessionStore];
GO

IF OBJECT_ID('dbo.GetDetailsFromSessionStore', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.GetDetailsFromSessionStore;
GO

IF OBJECT_ID('dbo.GetSessionDetails', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.GetSessionDetails;
GO

IF OBJECT_ID('dbo.InsertSessionStore', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.InsertSessionStore;
GO

IF OBJECT_ID('dbo.UpdateSessionStore', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.UpdateSessionStore;
GO

IF OBJECT_ID('dbo.SelectRuleResultFromSessionStoreForCaptcha', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.SelectRuleResultFromSessionStoreForCaptcha;
GO

IF OBJECT_ID('dbo.UpdateRuleResultInSessionStoreForCaptcha', 'P') IS NOT NULL 
  DROP PROCEDURE dbo.UpdateRuleResultInSessionStoreForCaptcha;
GO

-- DROP TABLE--
IF OBJECT_ID('dbo.SGS_SESSION_STORE', 'U') IS NOT NULL 
  DROP TABLE dbo.SGS_SESSION_STORE;
GO

-- CREATE TABLE 
CREATE TABLE [dbo].[SGS_SESSION_STORE]
(
	[SESSION_STORE_SERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[SESSION_USER_KEY] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SESSION_ID] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORM_ID] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_KEY] [int] NULL,
	[BUS_OBJECT] [varbinary](max) NULL,
	[DATE_CREATED] [datetime] NOT NULL,
	[WINDOW_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RULE_RESULT] [varbinary](max) NULL,
	[ACTIVITY_INSTANCE_ID] [int] NULL,
	[GRID_HASH] [varbinary](max) NULL,
	[UPDATE_SEQ] [int] NULL DEFAULT 0,

INDEX [NCIX_SGS_SESSION_STORE_SESSION_ID] NONCLUSTERED 
(
	[SESSION_ID] ASC
),
INDEX [NCIX_SGS_SESSION_STORE_SESSION_USER_KEY] NONCLUSTERED 
(
	[SESSION_USER_KEY] ASC
),
 CONSTRAINT [PK_SGS_SESSION_STORE]  PRIMARY KEY NONCLUSTERED 
(
	[SESSION_STORE_SERIAL_ID]
))
GO

-- CREATE STORED PROCEDURES --
CREATE PROCEDURE [dbo].[CheckObjectInSQL]
	@SESSION_USER_KEY varchar(200) 
AS
BEGIN
 SELECT session_store_serial_id,update_seq FROM dbo.SGS_SESSION_STORE  WHERE SESSION_USER_KEY = @SESSION_USER_KEY 
END
GO

CREATE PROCEDURE [dbo].[GetActivityRuleFromSessionStore]
	@SESSION_STORE_SERIAL_ID INT
AS
BEGIN
 SELECT ACTIVITY_INSTANCE_ID, RULE_RESULT,UPDATE_SEQ FROM dbo.SGS_SESSION_STORE  WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID 
END
GO

CREATE PROCEDURE [dbo].[GetBusObjectFromSessionStore]
	@SESSION_USER_KEY VARCHAR(200)
AS
BEGIN
 SELECT BUS_OBJECT FROM DBO.SGS_SESSION_STORE  where SESSION_USER_KEY=@SESSION_USER_KEY
END
GO


CREATE PROCEDURE [dbo].[GetDetailsFromSessionStore]
	@SESSION_STORE_SERIAL_ID INT

AS
BEGIN
 SELECT PRIMARY_KEY,SESSION_ID,FORM_ID,GRID_HASH, UPDATE_SEQ FROM DBO.SGS_SESSION_STORE  WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID
END
GO

CREATE PROCEDURE [dbo].[GetSessionDetails]
	-- Add the parameters for the stored procedure here
	@SESSION_STORE_SERIAL_ID INT

AS
BEGIN
   --Insert statements for the stored procedure here
 SELECT SESSION_ID,FORM_ID,BUS_OBJECT FROM DBO.SGS_SESSION_STORE  where SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID
END
GO

CREATE PROCEDURE [dbo].[InsertSessionStore]
	-- Add the parameters for the stored procedure here
	@SESSION_USER_KEY varchar(200) ,
	@SESSION_ID  VARCHAR (50) ,
	@WINDOW_NAME VARCHAR(40),
	@FORM_ID VARCHAR(100) ,
	@PRIMARY_KEY INT ,
	@DATE_CREATED DATETIME ,
	@RULE_RESULT VARBINARY ,
	@ACTIVITY_INSTANCE_ID INT ,
	@GRID_HASH VARBINARY (MAX),
	@UPDATE_SEQ INT = 0

AS
BEGIN
	
   --Insert statements for the stored procedure here
   DECLARE @SESSION_STORE_SERIAL_ID INT ; 
 INSERT INTO DBO.SGS_SESSION_STORE (SESSION_USER_KEY, SESSION_ID, WINDOW_NAME, FORM_ID, PRIMARY_KEY, DATE_CREATED, RULE_RESULT, ACTIVITY_INSTANCE_ID, GRID_HASH, UPDATE_SEQ)
                           VALUES (@SESSION_USER_KEY, @SESSION_ID, @WINDOW_NAME, @FORM_ID, @PRIMARY_KEY, @DATE_CREATED, @RULE_RESULT, @ACTIVITY_INSTANCE_ID, @GRID_HASH, ISNULL(@UPDATE_SEQ,0)) 
  SET @SESSION_STORE_SERIAL_ID = SCOPE_IDENTITY()  ;

  return @SESSION_STORE_SERIAL_ID ; 
END
GO

CREATE PROCEDURE [dbo].[UpdateSessionStore]
	-- Add the parameters for the stored procedure here
	@ACTIVITY_INSTANCE_ID INT ,
	@GRID_HASH VARBINARY (MAX) ,
	@RULE_RESULT VARBINARY (MAX),
	@DATE_CREATED DATETIME ,
	@BUS_OBJECT VARBINARY (MAX),
	@SESSION_STORE_SERIAL_ID INT,
	@UPDATE_SEQ INT = 0

AS
BEGIN
   --Insert statements for the stored procedure here
 UPDATE DBO.SGS_SESSION_STORE SET ACTIVITY_INSTANCE_ID = @ACTIVITY_INSTANCE_ID, GRID_HASH = @GRID_HASH, RULE_RESULT = @RULE_RESULT, DATE_CREATED = @DATE_CREATED, BUS_OBJECT= @BUS_OBJECT, UPDATE_SEQ= ISNULL(@UPDATE_SEQ,0) WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID
END
GO

CREATE PROCEDURE [dbo].[SelectRuleResultFromSessionStoreForCaptcha]
	-- Add the parameters for the stored procedure here
	@SESSION_STORE_SERIAL_ID INT
AS BEGIN 
	
   --Insert statements for the stored procedure here
 SELECT RULE_RESULT FROM DBO.SGS_SESSION_STORE WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID
END
GO

CREATE PROCEDURE [dbo].[UpdateRuleResultInSessionStoreForCaptcha]
	-- Add the parameters for the stored procedure here
	@RULE_RESULT VARBINARY (MAX),
	@SESSION_STORE_SERIAL_ID INT
AS BEGIN 
   --Insert statements for the stored procedure here
 UPDATE DBO.SGS_SESSION_STORE SET RULE_RESULT = @RULE_RESULT WHERE SESSION_STORE_SERIAL_ID = @SESSION_STORE_SERIAL_ID
END
GO