USE [SWSNew]
GO

/****** Object:  Table [dbo].[SWS_DOMAIN]    Script Date: 6/1/2018 12:14:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SWS_DOMAIN](
	[DOMAIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOMAIN_NAME] [varchar](50) NOT NULL,
	[LDAP_PATH] [varchar](500) NOT NULL,
 CONSTRAINT [PK_SWS_DOMAIN] PRIMARY KEY CLUSTERED 
(
	[DOMAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[SWS_DOMAIN_CLIENT]    Script Date: 6/1/2018 12:14:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SWS_DOMAIN_CLIENT](
	[DOMAIN_CLIENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOMAIN_ID] [int] NOT NULL,
	[CLIENT_ID] [int] NOT NULL,
 CONSTRAINT [PK_SWS_DOMAIN_CLIENT] PRIMARY KEY CLUSTERED 
(
	[DOMAIN_CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SWS_DOMAIN_CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_SWS_DOMAIN_CLIENT_SWS_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[SWS_CLIENT] ([CLIENT_ID])
GO

ALTER TABLE [dbo].[SWS_DOMAIN_CLIENT] CHECK CONSTRAINT [FK_SWS_DOMAIN_CLIENT_SWS_CLIENT]
GO

ALTER TABLE [dbo].[SWS_DOMAIN_CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_SWS_DOMAIN_CLIENT_SWS_DOMAIN] FOREIGN KEY([DOMAIN_ID])
REFERENCES [dbo].[SWS_DOMAIN] ([DOMAIN_ID])
GO

ALTER TABLE [dbo].[SWS_DOMAIN_CLIENT] CHECK CONSTRAINT [FK_SWS_DOMAIN_CLIENT_SWS_DOMAIN]
GO

DECLARE @DOMAIN_ID AS INT;
INSERT INTO SWS_DOMAIN (DOMAIN_NAME,LDAP_PATH) VALUES('SAGITEC','LDAP://DC=CORP,DC=SAGITEC,DC=COM');
SET @DOMAIN_ID = SCOPE_IDENTITY();
INSERT INTO SWS_DOMAIN_CLIENT (DOMAIN_ID,CLIENT_ID) SELECT @DOMAIN_ID, CLIENT_ID  FROM SWS_CLIENT;