
/****** Object:  Table [dbo].[SGS_SESSION_STORE]    Script Date: 11/20/2017 12:54:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_SESSION_STORE](
	[SESSION_STORE_SERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[SESSION_USER_KEY] [varchar](200) NULL,
	[SESSION_ID] [varchar](50) NULL,
	[FORM_ID] [varchar](50) NULL,
	[PRIMARY_KEY] [int] NULL,
	[BUS_OBJECT] [image] NULL,
	[DATE_CREATED] [datetime] NOT NULL,
	[WINDOW_NAME] [varchar](50) NULL,
	[RULE_RESULT] [image] NULL,
	[ACTIVITY_INSTANCE_ID] [int] NULL,
	[GRID_HASH] [image] NULL,
 CONSTRAINT [SGS_SESSION_STORE_PK] PRIMARY KEY CLUSTERED 
(
	[SESSION_STORE_SERIAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


