
/****** Object:  Table [dbo].[SGS_ACT_LOG_THRESHOLD_QUERY]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_THRESHOLD_QUERY', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_THRESHOLD_QUERY]
END 
GO 

/****** Object:  Table [dbo].[SGS_ACT_LOG_THRESHOLD_ACTN]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_THRESHOLD_ACTN', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_THRESHOLD_ACTN]
END 
GO 


/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_RULE]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_INST_RULE', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_INST_RULE]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_QUERY]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_INST_QUERY', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_INST_QUERY]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_ACTN_STEP]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_INST_ACTN_STEP', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_INST_ACTN_STEP]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_ACTN]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_INST_ACTN', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_INST_ACTN]
END 
GO


/****** Object:  Table [dbo].[SGS_ACT_LOG_INST]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_INST', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_INST]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_APP_ACTOR]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_APP_ACTOR', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_APP_ACTOR]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_APP]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG_APP', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG_APP]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG]    Script Date: 10/11/2017 1:33:38 PM ******/
IF OBJECT_ID(N'dbo.SGS_ACT_LOG', N'U') IS NOT NULL
BEGIN
 DROP TABLE [dbo].[SGS_ACT_LOG]
END 
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG](
	[ACT_LOG_ID] [int] NOT NULL,
	[APP_MONITORING_FLAG] [varchar](1) NOT NULL,
	[TRANSACTION_LIMIT] [int] NOT NULL,
	[TRANSACTION_LIMIT_ALERT] [varchar](100) NOT NULL,
	[TRANSACTION_HIGH_LIMIT] [int] NOT NULL,
	[TRANSACTION_HIGH_LIMIT_ALERT] [varchar](100) NOT NULL,
	[QUERY_LIMIT] [int] NOT NULL,
	[QUERY_LIMIT_ALERT] [varchar](100) NOT NULL,
	[QUERY_HIGH_LIMIT] [int] NOT NULL,
	[QUERY_HIGH_LIMIT_ALERT] [varchar](100) NOT NULL,
	[APPSERVER_LIMIT] [int] NOT NULL,
	[APPSERVER_LIMIT_ALERT] [varchar](100) NOT NULL,
	[APPSERVER_HIGH_LIMIT] [int] NOT NULL,
	[APPSERVER_HIGH_LIMIT_ALERT] [varchar](100) NOT NULL,
	[RULE_LIMIT] [int] NOT NULL,
	[RULE_LIMIT_ALERT] [varchar](100) NOT NULL,
	[RULE_HIGH_LIMIT] [int] NOT NULL,
	[RULE_HIGH_LIMIT_ALERT] [varchar](100) NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
 CONSTRAINT [PK_SGS_ACT_LOG] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_APP]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_APP](
	[ACT_LOG_APP_ID] [int] IDENTITY(1,1) NOT NULL,
	[APP_NAME] [varchar](50) NOT NULL,
	[ACTION_FLAG] [varchar](1) NOT NULL,
	[ACTION_STEP_FLAG] [varchar](1) NOT NULL,
	[QUERY_FLAG] [varchar](1) NOT NULL,
	[RULE_FLAG] [varchar](1) NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
	[BROWSER_TIME_FLAG] [varchar](1) NOT NULL,
	[ACTION_STEP_SIZE_FLAG] [varchar](1) NOT NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_APP] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_APP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

ALTER TABLE [dbo].[SGS_ACT_LOG_APP] ADD  CONSTRAINT [DF_SGS_ACT_LOG_APP_TRACK_BROWSER_TIME_FLAG]  DEFAULT ('N') FOR [BROWSER_TIME_FLAG]
GO

ALTER TABLE [dbo].[SGS_ACT_LOG_APP] ADD  CONSTRAINT [DF_SGS_ACT_LOG_APP_ACTION_STEP_SIZE_FLAG]  DEFAULT ('N') FOR [ACTION_STEP_SIZE_FLAG]
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_APP_ACTOR]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_APP_ACTOR](
	[ACT_LOG_APP_ACTOR_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACT_LOG_APP_ID] [int] NOT NULL,
	[ACTOR_NAME] [varchar](100) NOT NULL,
	[ACTION_FLAG] [varchar](1) NOT NULL,
	[ACTION_STEP_FLAG] [varchar](1) NOT NULL,
	[QUERY_FLAG] [varchar](1) NOT NULL,
	[RULE_FLAG] [varchar](1) NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_APP_INSTANCE] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_APP_ACTOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_INST](
	[ACT_LOG_INST_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACT_LOG_APP_ID] [int] NOT NULL,
	[ACTOR_NAME] [varchar](100) NOT NULL,
	[MACHINE_NAME] [varchar](100) NOT NULL,
	[ACT_LOG_INITIAL_UID] [varchar](100) NULL,
	[ACT_LOG_UID] [varchar](100) NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NULL,
	[WINDOW_NAME] [varchar](50) NULL,
	[INVALID_LOGIN_FLAG] [varchar](1) NULL,
	[IP_ADDRESS] [varchar](100) NOT NULL,
	[MAC_ADDRESS] [varchar](100) NOT NULL,
	[OS_NAME] [varchar](50) NULL,
	[BROWSER_NAME] [varchar](50) NULL,
	[IS_MOBILE_DEVICE] [varchar](1) NULL,
	[EXTRA_DETAILS] [varchar](max) NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_INST] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_INST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_ACTN]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_INST_ACTN](
	[ACT_LOG_INST_ACTN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACT_LOG_INST_ID] [int] NOT NULL,
	[REQUEST_FROM] [varchar](500) NULL,
	[ACTION_NAME] [varchar](100) NOT NULL,
	[ACTION_SOURCE] [varchar](100) NULL,
	[ACTION_TARGET] [varchar](100) NULL,
	[ACTION_RESULT] [varchar](max) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[ADDITONAL_INFO] [varchar](max) NULL,
	[TIME_IN_MS] [int] NULL,
	[BROWSER_START_TIME] [datetime] NULL,
	[BROWSER_TIME_IN_MS] [int] NULL,
	[ERROR_FLAG] [varchar](1) NULL,
	[WEB_SERVER_NAME] [varchar](50) NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_INST_ACTN] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_INST_ACTN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_ACTN_STEP]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_INST_ACTN_STEP](
	[ACT_LOG_INST_ACTN_STEP_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACT_LOG_INST_ACTN_ID] [int] NOT NULL,
	[STEP_NAME] [varchar](100) NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[SUB_TRANSACTION_ID] [varchar](20) NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[RETURN_SIZE] [int] NULL,
	[ERROR_MESSAGE] [varchar](max) NULL,
	[TIME_IN_MS] [int] NULL,
	[APPSERVER_NAME] [varchar](100) NULL,
	[TOTAL_QUERIES_EXECUTED] [int] NULL,
	[TOTAL_QUERIES_TIME_IN_MS] [int] NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_INST_ACTN_STEP] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_INST_ACTN_STEP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_QUERY]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_INST_QUERY](
	[ACT_LOG_INST_QUERY_ID] [int] IDENTITY(1,1) NOT NULL,
	[QUERY_ID] [varchar](100) NULL,
	[QUERY] [varchar](max) NOT NULL,
	[RESULT] [varchar](500) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[STEP_NAME] [varchar](100) NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[SUB_TRANSACTION_ID] [varchar](10) NULL,
	[TIME_IN_MS] [int] NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_INST_QUERY] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_INST_QUERY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_INST_RULE]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_INST_RULE](
	[ACT_LOG_INST_RULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[RULE_NAME] [varchar](500) NULL,
	[RESULT] [varchar](500) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[STEP_NAME] [varchar](100) NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[SUB_TRANSACTION_ID] [varchar](10) NULL,
	[TIME_IN_MS] [int] NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_INST_RULE] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_INST_RULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_THRESHOLD_ACTN]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_THRESHOLD_ACTN](
	[ACT_LOG_THRESHOLD_ACTN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACT_LOG_INST_ID] [int] NOT NULL,
	[REQUEST_FROM] [varchar](500) NULL,
	[ACTION_NAME] [varchar](100) NOT NULL,
	[ACTION_SOURCE] [varchar](100) NULL,
	[ACTION_TARGET] [varchar](100) NULL,
	[ACTION_RESULT] [varchar](max) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[ADDITONAL_INFO] [varchar](max) NULL,
	[TIME_IN_MS] [int] NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_THRESHOLD_ACTN] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_THRESHOLD_ACTN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

/****** Object:  Table [dbo].[SGS_ACT_LOG_THRESHOLD_QUERY]    Script Date: 10/11/2017 1:33:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_ACT_LOG_THRESHOLD_QUERY](
	[ACT_LOG_THRESHOLD_QUERY_ID] [int] IDENTITY(1,1) NOT NULL,
	[QUERY_ID] [varchar](100) NULL,
	[QUERY] [varchar](max) NOT NULL,
	[RESULT] [varchar](500) NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[STEP_NAME] [varchar](100) NULL,
	[PARAMETER_DETAILS] [varchar](max) NULL,
	[ACT_LOG_APP_ID] [int] NULL,
	[EXECUTABLE_NAME] [varchar](100) NULL,
	[ACT_LOG_INST_ID] [int] NOT NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[SUB_TRANSACTION_ID] [varchar](10) NULL,
	[CALLER_DETAILS] [varchar](max) NULL,
	[TIME_IN_MS] [int] NULL,
 CONSTRAINT [PK_SGS_ACT_LOG_THRESHOLD_QUERY] PRIMARY KEY CLUSTERED 
(
	[ACT_LOG_THRESHOLD_QUERY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


IF Not EXISTS (SELECT SO.NAME, SC.NAME FROM SYSOBJECTS SO JOIN SYSCOLUMNS SC ON SO.ID = SC.ID WHERE SO.NAME = 'SGS_ACT_LOG_INST_ACTN_STEP' AND SC.NAME = 'APPSERVER_NAME' AND SO.XTYPE = 'U')
BEGIN 
	ALTER TABLE SGS_ACT_LOG_INST_ACTN_STEP ADD APPSERVER_NAME VARCHAR(100)	 
END 
GO
