CREATE TABLE [dbo].[SGW_BPM_ACTIVITY_INST_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ACTIVITY_INSTANCE_ID] [int] NOT NULL,
	[PARENT_ACTV_INST_ID] [int] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[UPDATE_SEQ] [int] NOT NULL,
 CONSTRAINT [PK_SGW_BPM_ACTIVITY_INST_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
