CREATE TABLE [dbo].[SGW_BPM_CASE_CONFIGURATION]
(
	[CASE_CONFIGURATION_ID]  int				IDENTITY(1,1) NOT NULL,
	[CASE_FILE]				 varchar(4000)		NULL,
	[ENGINE_ID]				 int				NULL,
	[ENGINE_VALUE]			 varchar(4)			NOT NULL,
	[SOURCE_ID]              int                NOT NULL DEFAULT 2021,
	[SOURCE_VALUE]           VARCHAR(4)         NULL,
	[PRIORITY_ID]            int                NOT NULL DEFAULT 3008,
	[PRIORITY_VALUE]         VARCHAR(4)         NULL,
	[CREATED_BY]			 varchar(50)		NOT NULL,
	[CREATED_DATE]			 datetime			NOT NULL,
	[MODIFIED_BY]			 varchar(50)		NOT NULL,
	[MODIFIED_DATE]			 datetime			NOT NULL,
	[UPDATE_SEQ]			 int				NOT NULL
	CONSTRAINT [PK_SGW_BPM_CASE_CONFIGURATION] PRIMARY KEY CLUSTERED ([CASE_CONFIGURATION_ID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

