IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'USE_APPLICATION_DATE'  AND OBJECT_ID = OBJECT_ID(N'SGS_SYSTEM_MANAGEMENT'))
BEGIN
ALTER TABLE SGS_SYSTEM_MANAGEMENT ADD USE_APPLICATION_DATE VARCHAR(1) DEFAULT ('N') NOT NULL 
END

ELSE
BEGIN
  PRINT 'COLUMN NAME: USE_APPLICATION_DATE ALREADY EXISTS IN THE TABLE SGS_SYSTEM_MANAGEMENT'
END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'SYSTEM_FLAG'  AND OBJECT_ID = OBJECT_ID(N'SGS_SYSTEM_MANAGEMENT'))
BEGIN
ALTER TABLE SGS_SYSTEM_MANAGEMENT ADD SYSTEM_FLAG VARCHAR(50) NULL
END

ELSE
BEGIN
  PRINT 'COLUMN NAME: SYSTEM_FLAG ALREADY EXISTS IN THE TABLE SGS_SYSTEM_MANAGEMENT'
END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'DATA1'  AND OBJECT_ID = OBJECT_ID(N'SGS_SYSTEM_MANAGEMENT'))
BEGIN
ALTER TABLE SGS_SYSTEM_MANAGEMENT ADD DATA1 VARCHAR(50) NULL
END

ELSE
BEGIN
  PRINT 'COLUMN NAME: DATA1 ALREADY EXISTS IN THE TABLE SGS_SYSTEM_MANAGEMENT'
END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME =N'DATA2'  AND OBJECT_ID = OBJECT_ID(N'SGS_SYSTEM_MANAGEMENT'))
BEGIN
ALTER TABLE SGS_SYSTEM_MANAGEMENT ADD DATA2 VARCHAR(50) NULL
END

ELSE
BEGIN
  PRINT 'COLUMN NAME: SYSTEM_FLAG ALREADY EXISTS IN THE TABLE SGS_SYSTEM_MANAGEMENT'
END
GO
