CREATE TABLE [dbo].[SGS_TIME_TRAVEL] (
    [TIME_TRAVEL_ID]         [dbo].[UDT_IDENTITY]   IDENTITY (1, 1) NOT NULL,
    [MACHINE_NAME]			 [dbo].[UDT_NAME]		NOT NULL UNIQUE,
    [APPLICATION_DATE]       [dbo].[UDT_DATETIME]   NOT NULL,   
	[CREATED_BY]             [dbo].[UDT_CREATEDBY]  NOT NULL,
    [CREATED_DATE]           [dbo].[UDT_DATETIME]   NOT NULL,
    [MODIFIED_BY]            [dbo].[UDT_MODIFIEDBY] NOT NULL,
    [MODIFIED_DATE]          [dbo].[UDT_DATETIME]   NOT NULL,
    [UPDATE_SEQ]             [dbo].[UDT_UPDSEQ]     NOT NULL, 
    CONSTRAINT [PK_SGS_TIME_TRAVEL_ID] PRIMARY KEY CLUSTERED ([TIME_TRAVEL_ID] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);
