IF NOT EXISTS(SELECT 1 FROM SGS_CODE WITH(NOLOCK) WHERE CODE_ID = 2007) 
BEGIN
	 INSERT INTO DBO.SGS_CODE (CODE_ID, DESCRIPTION, DATA1_CAPTION, DATA1_TYPE, DATA2_CAPTION, DATA2_TYPE, DATA3_CAPTION, DATA3_TYPE, FIRST_LOOKUP_ITEM, FIRST_MAINTENANCE_ITEM, COMMENTS, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007, 'Workflow - Activity Instance - Status', NULL,NULL,NULL,NULL,NULL,NULL,'All',NULL,NULL,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2007 AND CODE_VALUE = 'INPC') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007,'INPC','In Progress',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2007 AND CODE_VALUE = 'PROC') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007,'PROC','Completed',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2007 AND CODE_VALUE = 'RESU') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007,'RESU','Resumed',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO


IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2007 AND CODE_VALUE = 'SUSP') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007,'SUSP','Suspended',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2007 AND CODE_VALUE = 'UNPC') 
BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2007,'UNPC','Initiated',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'Conversion',GETDATE(),'Conversion',GETDATE(),0)
END
GO

	 
   
	  
 
  
  