IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3003 AND CODE_VALUE = 'ACTV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3003,'ACTV','Active',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3003 AND CODE_VALUE = 'INTV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3003,'INTV','In Active',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO