IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BACA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BACA','Calling Activity',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BAEV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BAEV','Base Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BAGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BAGW','Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BATK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BATK','Base Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BATV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BATV','Base Activity',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'BRCA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'BRCA','Calling Global Business Rule Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'COGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'COGW','Complex Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'EBGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'EBGW','Event Based Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'EDEV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'EDEV','End Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'EXGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'EXGW','Exclusive Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'GTCA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'GTCA','Calling Global Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'IMCE')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'IMCE','Intermediate Message Catch Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'INCE')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'INCE','Intermediate Catch Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'INGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'INGW','Inclusive Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'INTE')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'INTE','Intermediate Throw Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'ITCE')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'ITCE','Intermediate Timer Catch Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'MACA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'MACA','Calling Global Manual Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'MATK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'MATK','Manual Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'PAGW')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'PAGW','Parallel Gateway',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'PRCA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'PRCA','Calling Process',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'RMTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'RMTK','Receive Message Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'RUTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'RUTK','Business Rule Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'SCCA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'SCCA','Calling Global Script Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'SCTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'SCTK','Script Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'SMTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'SMTK','Send Message Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'SPTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'SPTK','Sub Process',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'SRTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'SRTK','Service Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'STEV')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'STEV','Start Event',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'USCA')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'USCA','Calling Global User Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO



IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 2031 AND CODE_VALUE = 'USTK')
BEGIN
INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (2031,'USTK','User Task',NULL,NULL, NULL,NULL,NULL, NULL,0,NULL, 'system',GETDATE(),'system',GETDATE(),0)
END
GO