IF NOT EXISTS (SELECT *	FROM SGS_CODE WHERE CODE_ID = 3006)
BEGIN
INSERT INTO dbo.SGS_CODE (CODE_ID, DESCRIPTION, DATA1_CAPTION, DATA1_TYPE, DATA2_CAPTION, DATA2_TYPE, DATA3_CAPTION, DATA3_TYPE, FIRST_LOOKUP_ITEM, FIRST_MAINTENANCE_ITEM, COMMENTS, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3006, 'Process Escalation Lapse Type', NULL, NULL, NULL, NULL, NULL, NULL, 'All', NULL, NULL, NULL, 'rahul.mane', GETDATE(), 'tanaji.biradar', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT  1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3006 AND CODE_VALUE = 'LTAE')
BEGIN
INSERT INTO dbo.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3006, 'LTAE', 'After Expiration', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'rahul.mane', GETDATE(), 'tanaji.biradar', GETDATE(), 0)
END
GO


IF NOT EXISTS (SELECT  1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3006 AND CODE_VALUE = 'LTBE')
BEGIN
INSERT INTO dbo.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3006, 'LTBE', 'Before Expiration', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'rahul.mane', GETDATE(), 'tanaji.biradar', GETDATE(), 0)
END
GO

IF NOT EXISTS (SELECT  1 FROM SGS_CODE_VALUE WITH(NOLOCK) WHERE CODE_ID = 3006 AND CODE_VALUE = 'LTOE')
BEGIN
INSERT INTO dbo.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
VALUES (3006, 'LTOE', 'On Expiration', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'rahul.mane', GETDATE(), 'tanaji.biradar', GETDATE(), 0)
END
GO