IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2005 AND CODE_VALUE = 'ALIN') 
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2005,'ALIN','Initiate New',NULL,NULL, NULL,NULL,NULL, NULL,1,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
PRINT 'Initiate New INSERTED SUCCESSFULLY.'
END
ELSE
BEGIN
PRINT 'Initiate New already EXISTS'
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2005 AND CODE_VALUE = 'INRE') 
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2005,'INRE','Initiate Or Resume',NULL,NULL, NULL,NULL,NULL, NULL,2,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
PRINT 'Initiate Or Resume INSERTED SUCCESSFULLY.'
END
ELSE
BEGIN
PRINT 'Initiate Or Resume already EXISTS'
END
GO

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2005 AND CODE_VALUE = 'REEX') 
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2005,'REEX','Resume or Exception',NULL,NULL, NULL,NULL,NULL, NULL,4,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
PRINT 'Resume or Exception INSERTED SUCCESSFULLY.'
END
ELSE
BEGIN
PRINT 'Resume or Exception already EXISTS'
END
GO
 

IF NOT EXISTS(SELECT 1 FROM SGS_CODE_VALUE   WHERE CODE_ID = 2005 AND CODE_VALUE = 'RENE') 
 BEGIN
	 INSERT INTO DBO.SGS_CODE_VALUE (CODE_ID, CODE_VALUE, DESCRIPTION, DATA1, DATA2, DATA3, COMMENTS, START_DATE, END_DATE, CODE_VALUE_ORDER, LEGACY_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, UPDATE_SEQ)
	 VALUES (2005,'RENE','Never Initiate only Resume',NULL,NULL, NULL,NULL,NULL, NULL,3,NULL, 'Conversion',getdate(),'Conversion',getdate(),0);
PRINT 'Never Initiate only Resume INSERTED SUCCESSFULLY.'
END
ELSE
BEGIN
PRINT 'Never Initiate only Resume already EXISTS'
END
GO
