CREATE TABLE [dbo].[SGW_BPM_PROCESS_SEQUENCE_FLOW] (
    [BPM_PROCESS_SEQUENCE_FLOW_ID] INT           IDENTITY (1, 1) NOT NULL,
    [PROCESS_ID]                   INT           NOT NULL,
    [BPM_SEQUENCE_FLOW_ID]         VARCHAR (50)  NOT NULL,
    [NAME]                         VARCHAR (50)  NOT NULL,
    [SOURCE_BPM_ACTIVITY_ID]       VARCHAR (50)  NOT NULL,
    [TARGET_BPM_ACTIVITY_ID]       VARCHAR (50)  NOT NULL,
    [FLOW_EXPRESSION]              VARCHAR (100) NULL,
    [CREATED_BY]                   VARCHAR (50)  NOT NULL,
    [CREATED_DATE]                 DATETIME      NOT NULL,
    [MODIFIED_BY]                  VARCHAR (50)  NOT NULL,
    [MODIFIED_DATE]                DATETIME      NOT NULL,
    [UPDATE_SEQ]                   INT           NOT NULL,
    CONSTRAINT [PK_SGW_BPM_PROCESS_SEQUENCE_FLOW_BPM_PROCESS_SEQUENCE_ID] PRIMARY KEY CLUSTERED ([BPM_PROCESS_SEQUENCE_FLOW_ID] ASC)
);

