
CREATE TABLE SGW_BPM_PROCESSING_ERROR(
	[PROCESSING_ERROR_ID] [int] IDENTITY(1,1) NOT NULL,
	[TRANSACTION_ID] [UNIQUEIDENTIFIER] NOT NULL,
	[TRACE_INSTANCE_ID] [int] NOT NULL,
	[SUB_TRANSACTION_ID] [int] NOT NULL,
	[ACTION_TYPE] VARCHAR(200) NULL,
	[METHOD_NAME] VARCHAR(200) NULL,
	[EXCEPTION_MESSAGE] VARCHAR(4000) NOT NULL,	
	[EXCEPTION_DATE] [DATETIME] NOT NULL,	
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT]  NULL,
	[MACHINE_NAME] [VARCHAR] (500) NULL,
 CONSTRAINT [PK_SGW_BPM_PROCESSING_ERROR] PRIMARY KEY CLUSTERED 
(
	[PROCESSING_ERROR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

