CREATE TABLE [dbo].[SGW_BPM_ACTIVITY_CHECKLIST](
	[ACTIVITY_CHECKLIST_ID] [dbo].[UDT_IDENTITY] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [dbo].[UDT_DESC] NULL,
	[ACTIVITY_ID] [dbo].[UDT_ID] NULL,
	[BPM_EVENT_ID] [dbo].[UDT_ID] NULL,
	[REQUIRED_FLAG] [dbo].[UDT_FLAG] NOT NULL,
	[CREATED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[CREATED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[MODIFIED_BY] [dbo].[UDT_CREATEDBY] NOT NULL,
	[MODIFIED_DATE] [dbo].[UDT_DATETIME] NOT NULL,
	[UPDATE_SEQ] [dbo].[UDT_UPDSEQ] NULL,
	[DELETED_IND] [dbo].[UDT_IND] NULL,
	[GROUP_ID]    INT NULL,
 CONSTRAINT [PK_SGW_ACTIVITY_CHECKLIST_ACTIVITY_CHECKLIST_ID] PRIMARY KEY CLUSTERED 
(
	[ACTIVITY_CHECKLIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SGW_BPM_ACTIVITY_CHECKLIST]  WITH CHECK ADD  CONSTRAINT [FK_SGW_BPM_ACTIVITY_CHECKLIST_ACTIVITY_ID_SGW_ACTIVITY_ACTIVITY_ID] FOREIGN KEY([ACTIVITY_ID])
REFERENCES [dbo].[SGW_BPM_ACTIVITY] ([ACTIVITY_ID])
