CREATE TABLE [dbo].[SGW_BPM_ESCALATION_INSTANCE] (
    [ESCALATION_INSTANCE_ID] INT         IDENTITY (1, 1) NOT NULL,
    [ESCALATION_ID]          INT         NOT NULL,
    [ACTIVITY_INSTANCE_ID]   INT         NOT NULL,
    [ESCLATION_DATE_TIME]    DATETIME    NOT NULL,
    [STATUS_ID]              INT         NOT NULL,
    [STATUS_VALUE]           VARCHAR (4) NOT NULL,
    [PROCESSING_FLAG]        VARCHAR (1) DEFAULT ('N') NULL,
    CONSTRAINT [PK_SGW_BPM_ESCALATION_INSTANCE_ESCALATION_INSTANCE_ID] PRIMARY KEY CLUSTERED ([ESCALATION_INSTANCE_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_ESCALATION_INSTANCE_ACTIVITY_INSTANCE_ID_SGW_BPM_ACTIVITY_INSTANCE_ACTIVITY_INSTANCE_ID] FOREIGN KEY ([ACTIVITY_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_SGW_BPM_ESCALATION_INSTANCE_ESCALATION_ID_SGW_BPM_ESCALATION_ESCALATION_ID] FOREIGN KEY ([ESCALATION_ID]) REFERENCES [dbo].[SGW_BPM_ESCALATION] ([ESCALATION_ID]) ON DELETE CASCADE
);



