CREATE TABLE [dbo].[SGW_BPM_PRCS_INST_ATTACHMENTS] (
    [PROCESS_INST_ATTCHMNT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [BPM_PROCESS_INSTANCE_ID]  INT           NULL,
    [ECM_GUID]                 VARCHAR (MAX) NULL,
    [CREATED_BY]               VARCHAR (50)  NOT NULL,
    [CREATED_DATE]             DATETIME      NOT NULL,
    [MODIFIED_BY]              VARCHAR (50)  NOT NULL,
    [MODIFIED_DATE]            DATETIME      NOT NULL,
    [UPDATE_SEQ]               INT           NULL,
    [DOC_TYPE]                 VARCHAR (50)  NULL,
    [DOC_CLASS]                VARCHAR (100) NULL,
    [ACTIVITY_INSTANCE_ID]     INT           NULL,
    CONSTRAINT [PK_SGW_BPM_PRCS_INST_ATTACHMENTS_PROCESS_INST_ATTCHMNT_ID] PRIMARY KEY CLUSTERED ([PROCESS_INST_ATTCHMNT_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_PRCS_INST_ATTACHMENTS_BPM_PROCESS_INSTANCE_ID_SGW_BPM_PROCESS_INSTANCE_PROCESS_INSTANCE_ID] FOREIGN KEY ([BPM_PROCESS_INSTANCE_ID]) REFERENCES [dbo].[SGW_BPM_PROCESS_INSTANCE] ([PROCESS_INSTANCE_ID])
);





