CREATE TABLE [dbo].[SGW_BPM_DOCUMENT_UPLOAD](
	[BPM_DOCUMENT_UPLOAD_ID]		[int]	IDENTITY (1, 1)	NOT NULL,
	[BPM_PROCESS_INSTANCE_ID]		[int]					NOT NULL,
	[BPM_DOCUMENT_NAME]				[varchar](100)			NOT NULL,
	[CREATED_BY]					[dbo].[UDT_CREATEDBY]	NOT NULL,
	[CREATED_DATE]					[dbo].[UDT_DATETIME]	NOT NULL,
	[MODIFIED_BY]					[dbo].[UDT_MODIFIEDBY]	NOT NULL,
	[MODIFIED_DATE]					[dbo].[UDT_DATETIME]	NOT NULL,
	[UPDATE_SEQ]					[dbo].[UDT_UPDSEQ]		NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BPM_DOCUMENT_UPLOAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SGW_BPM_DOCUMENT_UPLOAD]  WITH CHECK ADD  CONSTRAINT [FK_SGW_BPM_DOCUMENT_UPLOAD_SGW_BPM_PROCESS_INSTANCE] FOREIGN KEY([BPM_PROCESS_INSTANCE_ID])
REFERENCES [dbo].[SGW_BPM_PROCESS_INSTANCE] ([PROCESS_INSTANCE_ID])
GO

ALTER TABLE [dbo].[SGW_BPM_DOCUMENT_UPLOAD] CHECK CONSTRAINT [FK_SGW_BPM_DOCUMENT_UPLOAD_SGW_BPM_PROCESS_INSTANCE]
GO


