CREATE TABLE [dbo].[SGW_BPM_QUEUE] (
	[QUEUE_ITEM_ID]       INT             IDENTITY (1, 1) NOT NULL,
	[MACHINE_NAME]        NVARCHAR (MAX)  NULL,
	[PRIORITY_CODE_ID]    INT             NULL,
	[PRIORITY_CODE_VALUE] VARCHAR (4)     NULL,
	[ENGINE_VALUE]		  VARCHAR (4)	  NULL,
	[SRC_PRCS_INST_ID]			INT NULL,
	[ACTV_INST_ID_TO_EXEC]		INT NULL,
	[TRG_PRCS_INST_ID]			INT NULL,
	[TRG_ACTV_ID_TO_INST]		INT NULL,
	[STATUS_ID]					[UDT_CODE_ID] NULL,
	[STATUS_VALUE]				[UDT_CODE_VALUE] NULL,
	[QUEUE_REQUEST_TYPE_ID]		[UDT_CODE_ID] NULL,
	[QUEUE_REQUEST_TYPE_VALUE]	[UDT_CODE_VALUE] NULL,
	[CREATED_BY]				[UDT_CREATEDBY]	NOT NULL default user,
	[CREATED_DATE]			    [UDT_DATETIME]	NOT NULL,
	[MODIFIED_BY]				[UDT_MODIFIEDBY]	NOT NULL default user,
	[MODIFIED_DATE]				[UDT_DATETIME]	NOT NULL,
	[UPDATE_SEQ]				[UDT_UPDSEQ]		NOT NULL
	CONSTRAINT [PK_SGW_BPM_QUEUE] PRIMARY KEY CLUSTERED ([QUEUE_ITEM_ID] ASC)
);