CREATE TABLE [dbo].[SGW_BPM_REQUEST_PARAMETER] (
    [REQUEST_PARAMETER_ID] INT            IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID]           INT            NULL,
    [PARAMETER_NAME]       VARCHAR (50)   NULL,
    [PARAMETER_VALUE]      VARCHAR (1000) NULL,
    [CREATED_BY]           VARCHAR (50)   NOT NULL,
    [CREATED_DATE]         DATETIME       NOT NULL,
    [MODIFIED_BY]          VARCHAR (50)   NOT NULL,
    [MODIFIED_DATE]        DATETIME       NOT NULL,
    [UPDATE_SEQ]           INT            NULL,
    CONSTRAINT [PK_SGW_BPM_REQUEST_PARAMETER_REQUEST_PARAMETER_ID] PRIMARY KEY CLUSTERED ([REQUEST_PARAMETER_ID] ASC),
    CONSTRAINT [FK_SGW_BPM_REQUEST_PARAMETER_REQUEST_ID_SGW_BPM_REQUEST_REQUEST_ID] FOREIGN KEY ([REQUEST_ID]) REFERENCES [dbo].[SGW_BPM_REQUEST] ([REQUEST_ID])
);

