CREATE TABLE [dbo].[SGW_BPM_SERVICE_TIMER](
	[SERVICE_TIMER_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACTION_METHOD] [varchar](200) NOT NULL,
	[INTERVAL] [int] NOT NULL,
	[ENABLED] [varchar](1) NOT NULL CONSTRAINT [DF_SGW_BPM_SERVICE_TIMERS_ENABLED]  DEFAULT ('Y'),
	[BPM_TRACING_FLAG]						VARCHAR(1)			NULL,
	[BPM_QUERY_TRACING_FLAG]				VARCHAR(50)			NULL,
	[BPM_QUERY_LIMIT]						INT					NULL,
	[BPM_QUERY_LIMIT_ALERT]					VARCHAR(100)		NULL,
	[BPM_QUERY_HIGH_LIMIT]					INT					NULL,
	[BPM_QUERY_HIGH_LIMIT_ALERT]			VARCHAR(100)		NULL,
 CONSTRAINT [PK_SGW_BPM_SERVICE_TIMERS] PRIMARY KEY CLUSTERED 
(
	[SERVICE_TIMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

