
CREATE TABLE SGW_BPM_TRACE_INST_ACTN(
	[TRACE_INST_ACTN_ID] [INT] IDENTITY(1,1) NOT NULL,	
	[TRACE_INSTANCE_ID] [INT] NOT NULL,
	[START_TIME] [DATETIME] NOT NULL,
	[ACTION_TYPE] [VARCHAR](200) NOT NULL,
	[PARAMETER_DETAILS] [varchar](8000) NULL,
	[QUERY_ID] [VARCHAR](100) NOT NULL,
	[QUERY_TEXT] [VARCHAR](8000) NOT NULL,
	[RECORD_COUNT] [INT] NULL,
	[TRANSACTION_ID] [uniqueidentifier] NULL,
	[END_TIME] [DATETIME] NULL,
	[CREATED_BY] [VARCHAR](50) NOT NULL,
	[CREATED_DATE] [DATETIME] NOT NULL,
	[MODIFIED_BY] [VARCHAR](50) NOT NULL,
	[MODIFIED_DATE] [DATETIME] NOT NULL,
	[UPDATE_SEQ] [INT] NULL,
 CONSTRAINT [PK_SGW_BPM_TRACE_INST_ACTN] PRIMARY KEY CLUSTERED 
(
	[TRACE_INST_ACTN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


