CREATE TABLE [dbo].[SGW_BPM_SERVER_SETTINGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERVER_ID] [int] NOT NULL,
	[SERVICE_TIMER_ID] [int] NOT NULL,
	[INTERVAL] [int] NOT NULL,
	[ENABLED] [varchar](1) NOT NULL,
	[BPM_TRACING_FLAG]			varchar(1) NULL,
	[BPM_QUERY_TRACING_FLAG]	varchar(50) NULL,
	[BPM_QUERY_LIMIT]			INT			NULL,
	[BPM_QUERY_LIMIT_ALERT]		varchar(100) NULL,
	[BPM_QUERY_HIGH_LIMIT]		INT			NULL,
	[BPM_QUERY_HIGH_LIMIT_ALERT] varchar(100) NULL
 CONSTRAINT [PK_SGW_BPM_SERVER_SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SGW_BPM_SERVER_SETTINGS]  WITH NOCHECK ADD  CONSTRAINT [FK_SGW_BPM_SERVER_SETTINGS_SGS_SERVER_SERVER_ID] FOREIGN KEY([SERVER_ID])
REFERENCES [dbo].[SGS_SERVERS] ([SERVER_ID])
GO

ALTER TABLE [dbo].[SGW_BPM_SERVER_SETTINGS] CHECK CONSTRAINT [FK_SGW_BPM_SERVER_SETTINGS_SGS_SERVER_SERVER_ID]
GO

ALTER TABLE [dbo].[SGW_BPM_SERVER_SETTINGS]  WITH NOCHECK ADD  CONSTRAINT [FK_SGW_BPM_SERVER_SETTINGS_SGW_BPM_SERVICE_TIMERS_SERVICE_TIMER_ID] FOREIGN KEY([SERVICE_TIMER_ID])
REFERENCES [dbo].[SGW_BPM_SERVICE_TIMER] ([SERVICE_TIMER_ID])
GO

ALTER TABLE [dbo].[SGW_BPM_SERVER_SETTINGS] CHECK CONSTRAINT [FK_SGW_BPM_SERVER_SETTINGS_SGW_BPM_SERVICE_TIMERS_SERVICE_TIMER_ID]
GO