-----------------------------------------
--Created By	:	Mansi Shah
--Created On	:	21st January 2020
--Description	:	Adding RELE,APPR,REJT to SGS_CODE_VALUE table
------------------------------------------------------------------------------------------------------------------------ 
IF NOT EXISTS(SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 2007 AND CODE_VALUE = 'RELE') 
 INSERT INTO SGS_CODE_VALUE(CODE_ID,CODE_VALUE,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ) VALUES (2007,'RELE','Released','system',GETDATE(),'system',GETDATE(),0);  

IF NOT EXISTS(SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 2007 AND CODE_VALUE = 'APPR') 
 INSERT INTO SGS_CODE_VALUE(CODE_ID,CODE_VALUE,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ) VALUES (2007,'APPR','Approved','system',GETDATE(),'system',GETDATE(),0);  

IF NOT EXISTS(SELECT * FROM SGS_CODE_VALUE WHERE CODE_ID = 2007 AND CODE_VALUE = 'REJT') 
 INSERT INTO SGS_CODE_VALUE(CODE_ID,CODE_VALUE,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,UPDATE_SEQ) VALUES (2007,'REJT','Rejected','system',GETDATE(),'system',GETDATE(),0);  