name: .NET Framework 4.5 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show working directory
      run: |
        Write-Host "Current working directory:" -ForegroundColor Cyan
        pwd
        Write-Host "Repository contents:" -ForegroundColor Cyan
        ls
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: |
        Write-Host "Restoring NuGet packages..." -ForegroundColor Cyan
        nuget restore './slnNeoSpin/slnNeoSpin.sln'
      shell: powershell

    - name: Build Solution (Release)
      run: |
        Write-Host "Building solution..." -ForegroundColor Cyan
        msbuild './slnNeoSpin/slnNeoSpin.sln' /p:Configuration=Release /p:OutDir='./slnNeoSpin/bin/Release/' /clp:ErrorsOnly;Summary
      shell: powershell

    - name: Scan for Warnings
      run: |
        Write-Host "Checking for warnings in build output..." -ForegroundColor Cyan
        $logFiles = Get-ChildItem -Path './slnNeoSpin/bin/Release/' -Filter '*.log' -Recurse
        foreach ($log in $logFiles) {
            $warnings = Select-String -Path $log.FullName -Pattern "warning"
            if ($warnings) {
                Write-Host "Warnings found in $($log.FullName):" -ForegroundColor Yellow
                $warnings | ForEach-Object { Write-Host $_.Line -ForegroundColor Yellow }
            } else {
                Write-Host "No warnings in $($log.FullName)" -ForegroundColor Green
            }
        }
      shell: powershell

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NeoSpin_Build_Output
        path: './slnNeoSpin/bin/Release/'
