name: .NET Framework 4.5 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild path
        shell: pwsh
        run: |
          Write-Host "MSBuild is assumed to be on PATH on windows-latest runners."
          msbuild /version

      - name: Build solution
        shell: pwsh
        run: |
          Write-Host "Building solution..." -ForegroundColor Cyan
          msbuild ".\slnNeoSpin\slnNeoSpin.sln" /p:Configuration=Release /clp:ErrorsOnly
