name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and SonarQube Analysis
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore "slnNeoSpin/slnNeoSpin.sln"

      - name: Install .NET Framework 4.8 targeting pack
        run: |
          choco install netfx-4.8-devpack -y
        continue-on-error: true

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add SonarScanner to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Test SonarQube connection
        run: curl http://localhost:9000/api/system/status

      - name: Begin SonarQube analysis
        run: |
          dotnet-sonarscanner begin `
            /k:"slnNeoSpin" `
            /d:sonar.host.url="http://localhost:9000" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.verbose=true

      - name: Build Solution
        run: msbuild "slnNeoSpin/slnNeoSpin.sln" /p:Configuration=Release /p:Platform="Any CPU"

      - name: End SonarQube analysis
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
