
/****** Object:  Table [dbo].[SGS_SYSTEM_SETTINGS]    Script Date: 11/20/2017 12:59:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SGS_SYSTEM_SETTINGS](
	[SYSTEM_SETTING_ID] [int] IDENTITY(1,1) NOT NULL,
	[SETTING_NAME] [varchar](100) NOT NULL,
	[SETTING_TYPE] [varchar](50) NOT NULL,
	[SETTING_VALUE] [varchar](500) NULL,
	[ENCRYPTED_FLAG] [char](1) NULL,
 CONSTRAINT [PK_SGS_SYSTEM_SETTINGS] PRIMARY KEY CLUSTERED 
(
	[SYSTEM_SETTING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


