----------------------------------------------------------------------------------------------------------------------------------
-- Name - Pathan Vasim
-- Date - 05/10/2018
-- Purpose - SGS_SYSTEM_SETTINGS
-- PLEASE CHANGES SCRIPTS BASED ON YOUR ENVIRONMENT
----------------------------------------------------------------------------------------------------------------------------------

/****** Object:  Table dbo.SGS_SYSTEM_SETTINGS  ********/
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('InterfaceToLegacy','bool','false',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('ValidateAdsFlag','bool','false',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('AdsPath','string','',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('Sagiserver','string','Sagiserv',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('Sagiserver2','string','N',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('BaseMetaDataPath','string','C:\PERSLinkSource\PERSLink\QA\Xml\',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('MetaDataPath','string','C:\PERSLinkSource\PERSLink\QA\Xml\',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('BusinessTierUrl','string','net.tcp://localhost:9350/{0}',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('DBCacheUrl','string','tcp://localhost:9350/NeoSpinDBCache',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('MetaDataCacheUrl','string','tcp://localhost:9350/NeoSpinMetaDataCache',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('ReportBuilderUrl','string','tcp://localhost:9355/srvReportBuilder',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('BusinessObjectNamespace','string','NeoSpin.BusinessObjects',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('BusinessObjectAssembly','string','NeoSpinBusinessObjects',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('BusinessTierAssembly','string','NeoSpinBusinessTier',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('NEOFLOW_SERVICE_TIER_URL','string','tcp://localhost:9353/NeoFlowService',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('SmtpServer','string','mail.sagitec.com',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('USPS_WebService_USERID','string','oVMTfR5a6AcudeyC8j/k2A==',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('USPS_WebService_PATH','string','http://testing.shippingapis.com/ShippingAPITest.dll',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('OBJECT_STORE','string','Public Employees Retirement System',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('FILENET_CONTENT_ENGINE_WS_API_URL','string','https://itdfncmtst.nd.gov/wsi/FNCEWS40MTOM/',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('NDPERS_USERNAME','string','!PERSLinkAdminTest',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('NDPERS_PASSWORD','string','qNFKNt3tErTdsoPv58UIkQ==',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('IsolationLevel','string','ReadUncommitted',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('NeoFlowActivityNameSpace','string','clr-namespace:NeoFlow.Activities;assembly=NeoFlowActivities',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('NeoFlowMapPath','string','C:\PERSLinkSource\PERSLink\QA\slnNeoSpin\NeoFlowMaps\',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('ProjectAndRegion','string','NeoSpinDevelopment',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('GetMaxSearch','bool','true',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('WorkFlowTypeId','int','1603',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('WorkFlowStatusId','int','5003',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('WSSMailFrom','string','vinovin.pt@sagitec.com',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('WSSMailSubject','string','NDPERS Correspondence',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('WSSRetrieveMailFrom','string','vinovin.pt@sagitec.com',NULL)
INSERT dbo.SGS_SYSTEM_SETTINGS ([SETTING_NAME],[SETTING_TYPE],[SETTING_VALUE],[ENCRYPTED_FLAG])VALUES('AllowedCharsRegex','string','.',NULL)
